### PR TITLE
fix deprecated getAllNetworks call (issue #12181)

### LINKED ISSUE #12181: [android] Fix deprecated getAllNetworks call
```
./gradlew assembleGoogleDebug -Parm64

> Task :sdk:compileDebugJavaWithJavac
/Users/alex/Developer/omim/omim/android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java:262: warning: [deprecation] getAllNetworks() in ConnectivityManager has been deprecated
      for (Network network : manager.getAllNetworks())
                                    ^
1 warning
```

### PR DESCRIPTION
**Pull request by HossamSaberr**
Replaces the deprecated `getAllNetworks()` call with `getActiveNetwork()` for API 23+, falling back to `getActiveNetworkInfo()` for older API versions to prevent crashes. This resolves the deprecation warning while maintaining correct debug logging of the active network state.

Fixes #12181

### CODE REVIEW

File: android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java [hunk 1]
```diff
@@ -257,10 +257,33 @@ String getSystemInformation()
...
+        }
+        else
+        {
+           sb.append("\n\tNo active network.");
+        }
+      }
+      else
+      {
+        // Fallback for older Android versions (API < 23)
+        @SuppressWarnings("deprecation")
```
Comment (AndrewShkrob) [inline android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java]: Fixing deprecation by silencing it? 😄

Comment (HossamSaberr) [reply android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java]: to clarify, the main fix isn't just silencing the warning. The actual fix is replacing getAllNetworks() with the modern getActiveNetwork() for API 23+.

The @SuppressWarnings("deprecation") is strictly applied to the else block for legacy devices (API < 23). Since getActiveNetwork() doesn't exist on those older versions, we are forced to fall back to getActiveNetworkInfo(), which is also technically deprecated in newer Android versions.

Since Organic Maps supports older Android versions, I added the suppression there to prevent breaking the build while keeping the fallback safe.

If there is a preferred, non-deprecated alternative specifically for API < 23 you could recommend, I would be more than happy to update the PR! What do you suggest?

Comment (AndrewShkrob) [reply android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java]: You can check how it can implemented without `@SuppressWarnings` f.e. here: https://github.com/organicmaps/organicmaps/blob/c94edbbbcf7153f097deb02af32458e78973ba58/android/sdk/src/main/java/app/organicmaps/sdk/sound/AudioFocusManager.java#L83-L84

Comment (HossamSaberr) [reply android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java]: thank you for pointing me.
I've just pushed a new commit that removes the suppression and implements the ImplApi23. Let me know if it looks good to go

File: android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java [hunk 2]
```diff
@@ -257,10 +258,21 @@ String getSystemInformation()
...
+      {
+        final android.net.NetworkInfo activeNetworkInfo = manager.getActiveNetworkInfo();
+        if (activeNetworkInfo != null)
+        {
+          sb.append("\n\tActive Network: ").append(activeNetworkInfo.toString());
+        }
+        else
+        {
+          sb.append("\n\tNo active network.");
+        }
```
Comment (biodranik) [inline android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java]: Move this code to a similar ImplApi21?

**Comment by HossamSaberr** [comment]
@biodranik Thanks for the review! I've implemented`ImplApi21` class as suggested.

Regarding the log outputs:

**Android 6+ (API 23+):** Tested locally on Android 13. `getActiveNetwork()` outputs just the network ID (`id=183`). However, because `LogsManager` already appends `NetworkCapabilities` right after, no diagnostic data is lost:
`Networks: id=183`
`[ Transports: WIFI Capabilities: NOT_METERED... TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:... SignalStrength: -65 ]`

**Android 5 (API 21-22):** I don't have a legacy device to pull logs from, but based on the `NetworkInfo` [source code in AOSP (Android 5.0.0_r1)](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-5.0.0_r1/core/java/android/net/NetworkInfo.java), the `toString()` method dynamically builds the legacy state string to look exactly like this:
`Active Network: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]`

Let me know if this looks good to merge!

**Comment by biodranik** [comment]
@HossamSaberr did you try Android 5 emulator?

File: android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java [hunk 3]
```diff
@@ -259,10 +258,13 @@ String getSystemInformation()
...
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
       {
-        final NetworkCapabilities cap = manager.getNetworkCapabilities(network);
-        sb.append("\n\tid=").append(network.toString()).append("\n").append(cap != null ? cap.toString() : "null");
+        ImplApi23.appendActiveNetworkInfo(sb, manager);
+      }
+      else 
+      {
+        ImplApi21.appendActiveNetworkInfo(sb, manager);
       }
```
Comment (biodranik) [inline android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java]:
```suggestion
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
        ImplApi23.appendActiveNetworkInfo(sb, manager);
      else 
        ImplApi21.appendActiveNetworkInfo(sb, manager);
```

File: android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java [hunk 4]
```diff
@@ -322,5 +324,41 @@ public static String getMemoryInfo(@NonNull Context context)
...
+    {
+      final android.net.NetworkInfo activeNetworkInfo = manager.getActiveNetworkInfo();
+      if (activeNetworkInfo != null)
+      {
+        sb.append("\n\tActive Network: ").append(activeNetworkInfo.toString());
+      }
+      else
+      {
+        sb.append("\n\tNo active network.");
+      }
```
Comment (biodranik) [inline android/sdk/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java]:
```suggestion
      if (activeNetworkInfo != null)
        sb.append("\n\tActive Network: ").append(activeNetworkInfo.toString());
      else
        sb.append("\n\tNo active network.");
```

**Comment by biodranik** [comment]
Ah, and there's some missing symbol on the CI.

**Comment by HossamSaberr** [comment]
@biodranik I couldn't use the Android 5 emulator because it froze my device, but I checked the implementation in the source code I linked in my previous comment.

I also applied your suggestions and pushed a commit to fix the CI failure.

**Comment by HossamSaberr** [comment]
that should fix the code style failure

**Comment by biodranik** [comment]
Did you set up/run clang-format as described in https://github.com/organicmaps/organicmaps/blob/master/docs/CODE_STYLE_GUIDE.md#clangformat ?

**Review by biodranik — APPROVED** [review]
Okay, LGTM! Thanks for the patience and the contribution!
