### PR TITLE
UTM coordinates format fix

### LINKED ISSUE #8593: UTM coordinates are wrong in Germany
The location information in UTM format shows 32N and 33N anywhere in German. Germany is located in 32U or 33U respectively.

image

@strump can you please take a look?

### PR DESCRIPTION
**Pull request by strump**
Closes #8593

Old-new-UTM-format

In old UTM format zone letter could be either `N` for Northern Hemisphere or `S` for Southern. This information is enough to convert UTM format back to latitude and longitude.

But most geospatial applications use full zone letter instead. Updated UTM format to generate valid zone letter (the same way as we generate it for MGRS format).

TODO: Implement Universal Polar Stereographic (UPS) coordinate system for areas with lat < 80 and lat >= 84. See [code](https://github.com/mrJean1/PyGeodesy/blob/master/pygeodesy/ups.py) for reference.

### CODE REVIEW

File: platform/utm_mgrs_utils.cpp [hunk 1]
```diff
@@ -110,7 +110,15 @@ UTMPoint LatLonToUtm(double lat, double lon)
   double const latTan4 = latTan2 * latTan2;
 
   int const zoneNumber = LatLonToZoneNumber(lat, lon);
-  char const zoneLetter = (lat >= 0.0) ? 'N' : 'S';
+  auto const maybeZoneLetter = LatitudeToZoneLetter(lat);
+  if (!maybeZoneLetter.has_value())
```
Comment (vng) [inline platform/utm_mgrs_utils.cpp:114]: nit: if (!maybeZoneLetter)

File: platform/utm_mgrs_utils.cpp [hunk 2]
```diff
@@ -110,7 +110,15 @@ UTMPoint LatLonToUtm(double lat, double lon)
...
+  {
+    // Invalid latitude should be excluded by FormatUTM and FormatMGRS functions.
+    ASSERT(false, ("Invalid latitude ",lat,". Can't calculate UTM zone letter"));
+    return {};
```
Comment (vng) [inline platform/utm_mgrs_utils.cpp:118]: So we return just _anything_ that is not even initialized?
Probably, there is no problem here because I see:
```
  if (lat <= -80 || lat > 84)
    return {}; // Latitude limit exceeded.
```
everywhere in code.

I don't know if it is ok to have an invalid UTM for say (-88, 0), but this link gives a correct value (Z) for lat=-88
https://www.latlong.net/lat-long-utm.html

**Comment by vng** [comment]
Probably, it is a bug, but I see some airport lat < -80.
https://www.openstreetmap.org/node/1042062606/history#map=13/-80.32075/-81.29831

Also, China station below -80:
https://www.openstreetmap.org/?mlat=-80.417&mlon=77.117

File: platform/utm_mgrs_utils.cpp (hunk 2 above)
Comment (strump) [reply platform/utm_mgrs_utils.cpp:118]: UTM coordinates near the North and South poles are calculated with completely different formulas. For that purpose `Z` zone letter was introduced. We doesn’t support it for the moment, because those areas are not very popular. Let me update the code to cover latitude values outside of `[-80, 84)` range

Comment (vng) [reply platform/utm_mgrs_utils.cpp:118]: Ah, ok, no problem then, we can merge this PR now.
Then put ```ASSERT(maybeZoneLetter, (lat));``` here without ifs. Caller side makes needed checks.

Comment (strump) [reply platform/utm_mgrs_utils.cpp]: Done! Simplified UTM zone letter check.

**Review by vng — APPROVED** [review]
