### PR TITLE
[editor] Removed superfluous name=* restrictions

### LINKED ISSUE #1481: [Android] Editor ignores name in russian if it's the same as default name
Android 9
OrganicMaps: 2021.10.15-15-google
Android default locale: Russian

**Steps to reproduce:**

1. Select a POI which has `'name'` and `'name:ru'` tags same value. E.g. https://osm.org/node/8235467349

    | Key | Value |
    | ---------- | ---------- |
    | name | Паштет |
    | name:en | Pashtet |
    | name:ru | Паштет |

    `'name'` tag is treated as ukrainian lang.

2. Open editor
3. Don't change anything and press save button (upper right corner)
4. Open editor again

**Actual result:** Russian name becomes empty.
**Expected result:** Russian name should be present.

This happenes only when `name` and `name:ru` tags have the same value on the map of Ukraine.

pashtet

### PR DESCRIPTION
**Pull request by map-per**
closes #1481

- Removed code that prevents users from adding a multilingual name in case it is the same as `name=*`. In uni lingual countries the OSM convention is that e.g. `name:de` should be the same as `name`. (see: #1481)

- ~~Allowed users to remove names / submit an empty name. This is e.g. helpful when the name of a POI (e.g. restaurant) changes. OM users can then update the multilingual names in languages they know and remove the wrong names in languages they don't know (no multilingual name is better than a wrong one) (see: #6292)~~

### CODE REVIEW

**Comment by map-per** [comment]
Tested it here: https://pewu.github.io/osm-history/#/node/11073340805
- Deleting names results in a blank name instead of deleting the `name` tag

**Comment by biodranik** [comment]
@map-per that's a bug, there is no need to push an empty tag. It should be cleared properly in the core, ideally even before upload/merging with osm starts, right at the moment of saving it.

@kirylkaveryn You've recently touched this code in #8032 , it would be great if you cooperate to finish these changes.

File: indexer/editable_map_object.cpp [hunk 1]
```diff
@@ -352,27 +352,6 @@ void EditableMapObject::SetCuisines(std::vector<std::string> const & cuisines)
...
-    if (!name.empty() && !duplicate)
-      editedName.AddString(langCode, name);
-  });
-
-  m_name = editedName;
-}
-
-void EditableMapObject::RemoveNeedlessNames()
-{
-  RemoveBlankAndDuplicationsForDefault();
```
Comment (biodranik) [inline indexer/editable_map_object.cpp:373]: Removing blank names is still needed, right? So the code above with !name.empty() should stay? Or can it be done more efficiently in another way? 
CC @kirylkaveryn

Comment (kirylkaveryn) [reply indexer/editable_map_object.cpp:373]: This method is used to clean up empty names. And used in ios.

Maybe it would be better to set `nil` to the names that shouldn't be added to the list of changes (when a user adds a name but decides to skip this change later and delete translation from the list) and `empty string` when a user cleans up names manually?

Comment (biodranik) [reply indexer/editable_map_object.cpp:373]: This is a good question: how tag removal is encoded now in the OM editor core? Is it supported at all? If not, should empty values signal that these keys should be removed from the OSM at the tag merging stage, when there are local tags, and remote tags?

**Comment by map-per** [comment]
I limited the PR to only fix the identical names problem.

Test: :heavy_check_mark: Works as intended (https://pewu.github.io/osm-history/#/node/5433124122)

**Review by biodranik — APPROVED** [review]
Thanks! @kirylkaveryn can you please confirm that the behavior on iOS is exactly the same?

**Comment by biodranik** [comment]
@map-per Strange, I was sure that I had invited you to our closed chat for active contributors... Ping me (biodranik) if you are interested and have a Telegram or Matrix account.

**Comment by map-per** [comment]
You did ask, I'm just slow, but I created a Matrix account now (and wrote you).

**Comment by biodranik** [comment]
@map-per for some reason, I don't see any messages in Elements matrix client (it s%cks btw...), can you please ping me again, so I can re-invite you?

**Comment by map-per** [comment]
I tried again, but both times the request was instantly rejected. Maybe it works the other way round, my account is: @map-per:matrix.org
