### PR TITLE
[Android] Fix insets handling

### LINKED ISSUE #9423: [Android] Maps download UI is covered by bottom navigation bar
**Description**
Some UI elements on map download UI are covered with Android navigation bar. Probably caused by #9251.

**Steps to reproduce**
1. Go to Menu / Download Maps / Ukraine
2. Try to tap "Download All" button

**Expected behaviour**
"Download All" button is accessible.

**Screenshots**
 

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: master at commit https://github.com/organicmaps/organicmaps/commit/aa436f3cf7351ccca84c733368d140953fa027ef

### PR DESCRIPTION
**Pull request by strekha**
In case when action button is hidden, we should update margins of FAB. Otherwise keep the original value

Closes #9423

### CODE REVIEW

File: android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java [hunk 1]
```diff
@@ -75,10 +75,20 @@ public WindowInsetsCompat onApplyWindowInsets(@NonNull View v, @NonNull WindowIn
...
 
         fabParams.rightMargin = safeInsets.right + baseMargin;
+        if (isButtonVisible)
+        {
+          fabParams.bottomMargin = baseMargin;
+        }
+        else
+        {
+          fabParams.bottomMargin = safeInsets.bottom + baseMargin;
+        }
```
Comment (strump) [inline android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java:91]: Don't need curly braces here

**Review by strump — APPROVED** [review]

**Review by vng — APPROVED** [review]
