### PR TITLE
Remove navigation mode priority exceptions

### LINKED ISSUE #5725: Set relative priorities of road pathtexts vs road shields
_Originally posted by @pastk in https://github.com/organicmaps/organicmaps/issues/4645#issuecomment-1657104821_

There are still priority exceptions hardcoded in the drape for the navigation mode to make pathtexts and shields higher than any other overlays.

This affects **all** pathtexts incl. e.g. rivers :) so they displace everything around.
Also all highways pathtexts are treated the same, so e.g. residential road name can displace trunk road one (actually a longer text will have a priority).

All road shield are treated the same also, but put just below pathtexts.

The plan is to make pathtexts orderable via prio.txt files, then we can order by highway type (i.e. motorways first, service last), lower rivers priorities, etc.

The question is - how do we want to prioritize road shields vs road pathtexts?
Keep the current logic (all pathtexts are higher than all shields), or e.g.
```
hw-motoway pathtext
hw-motorway shield
hw-primary pathtext
hw-primary shield
...
```
or somehow else?

### PR DESCRIPTION
**Pull request by pastk**
Removes hardcoded priorities of speedcams, pathtexts and shields and makes them configurable via priority files.

Closes #5725

### CODE REVIEW

**Comment by pastk** [comment]
The main change is illustrated by the screenshots here: https://github.com/organicmaps/organicmaps/issues/5725#issuecomment-1684456733

**Comment by biodranik** [comment]
Cool, thanks!

1. Can someone help test it with normal and vehicle styles in navigation?
2. Please rebase
3. DCO is missing

**Comment by pastk** [comment]
First we need to decide on road shields vs road names priorities.

ATM its quite strange:
- in the main style shields are higher priority than road names of the same type, e.g.
    ```
    hw-motorway shield
    hw-motorway pathtext
    hw-primary shield
    hw-primary pathtext
    ```	
- in the vehicle style road names are higher than *any* shields, i.e.
    ```
    hw-motorway pathtext
    hw-primary pathtext
    hw-motorway shield
    hw-primary shield
    ```	

One middle option is to make road names higher priority than shields of the same type, e.g.
    ```
    hw-motorway pathtext
    hw-motorway shield
    hw-primary pathtext
    hw-primary shield
    ```	

Here is comparison of a current "road names above all shields" vs "road names are higher priority than shields of the same type" approaches:

Zurich-veh-z13
(on the left: tertiary road name becomes displaced by secondary shield)

Zurich-veh-z14
(center-top: primary road name becomes displaced by motorway shield)

Overall its not much difference, except for cases like Tallinn where there are too many shields (the "current" approach leads to less shields), but the Tallinn case should be solved differently by filtering road refs IMO.


And here is a comparison of main style current "shields are higher priority than road names of the same type" vs "road names are higher priority than shields of the same type":

Zurich-main-z13


I'm more inclined to use the same logic for both styles, but we can use different approaches if needed.
WDYT?

**Comment by vng** [comment]
Test help needed: make sure that speed cams are visible in Navigation mode and are not displaced (especially speed cams with maxspeed limit). Sample is here https://www.openstreetmap.org/node/10014146924
Navigation mode can be emulated on desktop also.
Screenshot 2023-09-02 at 07 44 48
Screenshot 2023-09-02 at 07 44 54


Don't know if we can make something here or not, but the current master behaves strangely with street name vs sheld. Looks like they are drawn on the same points and a shield always displaces a name.
I checked on this example: https://www.openstreetmap.org/way/631075078
I was not able to see the street's name at all on Android and was able to see on Desktop only on the last zoom level (>19). Good to test it on this PR. Actually, we should draw a name and a shield if there is enough place to fit them both -> they should draw on different _origin_ points.

**Comment by vng** [comment]
In general I think that path-text should be higher than shield on the same type roads.
Even more here (IMO):
- motorway/trunk shields are higher than _any_ road type path-text
- primary/secondary/... path-text is higher than _any_ road type shield, except motorway/trunk (above)

File: drape_frontend/apply_feature_functors.cpp [hunk 1]
```diff
@@ -1052,15 +1003,6 @@ void ApplyLineFeatureAdditional::GetRoadShieldsViewParams(ref_ptr<dp::TextureMan
...
   }
-
-  // Special priority for road shields in navigation style.
-  if (GetStyleReader().IsCarNavigationStyle())
-  {
-    textParams.m_specialDisplacement = poiParams.m_specialDisplacement
-      = symbolParams.m_specialDisplacement = SpecialDisplacement::SpecialMode;
-    textParams.m_specialPriority = poiParams.m_specialPriority
-      = symbolParams.m_specialPriority = CalculateNavigationRoadShieldPriority();
-  }
```
Comment (vng) [inline drape_frontend/apply_feature_functors.cpp:1063]: We can raise the shield's priority in Navigation mode by editing the correspondent style, right?
In case we want to not displace shields at all for example ..

**Review by vng — COMMENTED** [review]
I like the approach to tune shields priorities like all other POIs without hacks like _hardcoded depths_ or _special modes_.

File: drape_frontend/apply_feature_functors.cpp (hunk 1 above)
Comment (pastk) [reply drape_frontend/apply_feature_functors.cpp:1063]: Yeap!

**Comment by pastk** [comment]
Ok I'll make it the most flexible way i.e. shields priorities set independently from corresponding pathtexts. And then we'll finalize their relative positions..

**Comment by pastk** [comment]
And probably in future we should operate not by e.g. motorway shields, secondary shields etc. but national routes shields, regional routes shields etc. I.e. national route shields should be high priority regardless of whether the route goes by motorway or tertiary. But for now shields styles are bound to feature types.

**Comment by pastk** [comment]
> Don't know if we can make something here or not, but the current master behaves strangely with street name vs sheld. Looks like they are drawn on the same points and a shield always displaces a name.

The current logic is more complex:
- shields are placed inbetween road names if >1 names fit into a segment (usually its a metaline, not just a line)
- if there is space for just one name then a shield is placed into the same spot (the middle)

Perhaps this logic could be improved. And overall road names placement could be made smarter by choosing "spare" places without displacement conflicts. These are ideas for future, I'd prefer to keep this PR small.

**Comment by biodranik** [comment]
@pastk what are the shields vs names priorities in Google and Apple maps?

**Comment by vng** [comment]
Of course not in this PR. I am just worried if we broke something sensitive with the refactoring. Or ensure that behaviour is not getting worse at the moment.

**Comment by pastk** [comment]
> @pastk what are the shields vs names priorities in Google and Apple maps?

In Gmaps only shields are displayed at lower zooms, sometimes one needs to zoom in almost all the way to see road name.

**Comment by pastk** [comment]
Depends on https://github.com/organicmaps/kothic/pull/21

So I made it like this:
**main style**
```
motorway/trunk pathtext
motorway/trunk shield

primary pathtext
...
residential pathtext

primary shield
...
residential shield
```

**vehicle style**
```
motorway/trunk shield
motorway/trunk pathtext

primary pathtext
primary shield

secondary pathtext
...
residential pathtext

secondary shield
...
residential shield
```

See the full picture in [main prios](https://github.com/organicmaps/organicmaps/blob/pastk-drape-remove-navigation-priority-exceptions/data/styles/clear/include/priorities_4_overlays.prio.txt) and [vehicle prios](https://github.com/organicmaps/organicmaps/blob/pastk-drape-remove-navigation-priority-exceptions/data/styles/vehicle/include/priorities_4_overlays.prio.txt).
Also there are some important POIs for drivers mixed in between road names priorities, e.g. highway-services, highway-ford.. Does it make sense?

Also fixed a bug with primary_link having a lone pathtext without a line on z10 (its supposed to start at z11).

**Review by vng — APPROVED** [review]
