### PR TITLE
[android] Map fragments improvements

### LINKED ISSUE #4680: Disable zoom settings not working
**Steps to reproduce**
1. Start OM
2. Open settings and disable zoom settings
3. Go to map -> buttons zoom is not disabled

**Expected behavior**
Zoom settings can able to enable or disable buttons zoom on map

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.02-1-Google-beta
 - Device Model: Pixel 6

### LINKED ISSUE #4729: [android] A crash in PlacePageView.refreshDistanceToObject()
```
Exception java.lang.NullPointerException:
  at app.organicmaps.widget.placepage.PlacePageView.refreshDistanceToObject (PlacePageView.java)
  at app.organicmaps.widget.placepage.PlacePageView.onLocationUpdated (PlacePageView.java)
  at app.organicmaps.location.LocationHelper.notifyLocationUpdated (LocationHelper.java)
  at app.organicmaps.location.LocationHelper.onLocationChanged (LocationHelper.java)
  at app.organicmaps.location.GoogleFusedLocationProvider$GoogleLocationCallback.onLocationResult (GoogleFusedLocationProvider.java)
  at com.google.android.gms.internal.location.zzct.notifyListener (zzct.java)
  at com.google.android.gms.common.api.internal.ListenerHolder.zaa (ListenerHolder.java)
  at com.google.android.gms.common.api.internal.zacb.run (zacb.java)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

https://play.google.com/console/u/0/developers/8084273541548442467/app/4972992444534608608/vitals/crashes/cd98cf52578f8195c5eda8b43f9b341b/details?days=28&versionCode=23030505%2C23030203

https://github.com/organicmaps/organicmaps/blob/b1269be1a4ab5451b6a04c27f46f3b39a950ef46/android/src/app/organicmaps/widget/placepage/PlacePageView.java#L567-L578

Either mTvDistance or mMapObject is null.

### LINKED ISSUE #4903: Action bar under bottomsheet is locked
Requirements:
- Location disabled
- Google Play Services enabled on OM settings

**Steps to reproduce**
1. Start OM
2. Select POI
3.  Use button route to -> pop-up to search location with Google Play Services is shown
4. Deny pop-up ->wrong action bar stay at the bottom (we need to select other POI and leave place page to remove action bar)

**Screenshots**
In normally case (with Google Play Services disabled, OM show clickable bottom bar to add start point)

In my case, OM keep at the bottom action bar used with place page

Logs:
```
2023-04-01 21:27:19.611  5297-5297  PlacePageController app.organicmaps E  onStateChanged(): Called in the wrong activity state=STARTED
2023-04-01 21:27:19.616  5297-5297  PlacePageController app.organicmaps E  onSlide(): Called in the wrong activity state=STARTED
```

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.05-5-Google (reproduced on 2023.03.31-4-Google-beta)
 - Device Model: Pixel 6

CC @arnaudvergnet

### PR DESCRIPTION
**Pull request by arnaudvergnet**
Further improve place page and map buttons fragment abstraction by trying to follow [Android's best practices](https://developer.android.com/topic/architecture/ui-layer?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-architecture%23article-https%3A%2F%2Fdeveloper.android.com%2Ftopic%2Farchitecture%2Fui-layer#udf).

With these changes, the main activity does not call fragment functions directly, but instead updates their state using view models. Fragments send data back to the activity using event callbacks.

Saving the UI state between configuration changes is a lot easier as view models handle this natively, it is easier to sync multiple UI components to a single state and we better understand when the data is modified.

The menu bottom sheets would also benefit from this change, but I will keep that for another PR.

This is not ready yet, I still need to find and fix possible regressions, but this will make the code easier to maintain and will also help with implementing https://github.com/organicmaps/organicmaps/pull/4613.

@Jean-BaptisteC you don't need to test yet, I already know of some bugs, but I would greatly appreciate your help when I feel the PR is close enough to being finished :). The PR is only published to let people know I'm working on this.

Fixes #4729 
Fixes #4903 
Fixes #4680

### CODE REVIEW

**Comment by arnaudvergnet** [comment]
We'll need to do more testing but it should fix https://github.com/organicmaps/organicmaps/pull/4689#issuecomment-1474418909

**Comment by arnaudvergnet** [comment]
I fixed all the issues I could find and the PR is now ready for testing

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13

I have see weird bugs in first launch, but i'm not able to reproduce

- Open OM
- Select POI -> open place page
- Open editor
- Leave editor without save -> place page is closed

Others problem (buttons zoom is disabled)
- select POI -> expand place page
- Rotate device ->informations on place page disappear

**Comment by arnaudvergnet** [comment]
Thanks for the tests I'll fix those issues

**Comment by arnaudvergnet** [comment]
I haven't been able to reproduce both bugs. I updated the pr, please check and if you can still reproduce the issues, can you send a video demonstrating it please?

**Comment by Jean-BaptisteC** [comment]
I'm not able to reproduce bugs
Did you have remove ability to download map from place page ?

**Comment by arnaudvergnet** [comment]
Managed to reproduce both issues thanks! For the empty place page and going back from edit issues, it seems to only happen when you enable a layer first. Even if it is not currently active, having enabled one makes those issues appear.

For the missing download button, it seems to be an initialization issue as it only happens when selecting a non-downloaded map region while the place page is hidden.

**Comment by arnaudvergnet** [comment]
The bugs you found should be fixed, can you please try again?

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13
Bugs about layer ✅
Bugs about download button on place page ✅

Find another bug :)

- Select town or airport outside of downloaded map (with link to website)
- Start download map
- Open website on browser
- Go back to OM -> button about download is not present on place page

**Comment by arnaudvergnet** [comment]
Should be fixed as well

**Comment by arnaudvergnet** [comment]
Fixed :+1:

**Comment by Jean-BaptisteC** [comment]
Another crash
```
03-22 18:16:42.383 17483 17483 E AndroidRuntime: FATAL EXCEPTION: main
03-22 18:16:42.383 17483 17483 E AndroidRuntime: Process: app.organicmaps.debug, PID: 17483
03-22 18:16:42.383 17483 17483 E AndroidRuntime: java.lang.IllegalStateException: Fragment PlacePageController{af11f03} (9d12476a-1331-4d8a-a608-9f61b1da68e7) not attached to an activity.
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at androidx.fragment.app.Fragment.requireActivity(Fragment.java:995)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at app.organicmaps.widget.placepage.PlacePageController$DefaultBottomSheetCallback.onStateChanged(PlacePageController.java:82)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1388)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetBehavior.startSettling(BottomSheetBehavior.java:1673)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetBehavior.access$100(BottomSheetBehavior.java:87)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetBehavior$1.run(BottomSheetBehavior.java:1309)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetBehavior.runAfterLayout(BottomSheetBehavior.java:1319)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetBehavior.setState(BottomSheetBehavior.java:1304)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at app.organicmaps.widget.placepage.PlacePageController.lambda$onPlacePageContentChanged$3$app-organicmaps-widget-placepage-PlacePageController(PlacePageController.java:325)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at app.organicmaps.widget.placepage.PlacePageController$$ExternalSyntheticLambda3.run(Unknown Source:2)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7884)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-22 18:16:42.383 17483 17483 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-22 18:16:42.384  1478  1560 E WindowManager: Performed 6 layouts in a row. Skipping
03-22 18:16:42.516  1478 12356 I ActivityManager: Process app.organicmaps.debug (pid 17483) has died: prcp TOP
```
- Open OM
- Select POI -> place page is open
- Select layer -> place page is closed
- Re-select same POI -> place page is open
- Rotate screen and after use splitscreen -> app crash

**Comment by arnaudvergnet** [comment]
This one I can't reproduce, did you properly update your branch to the latest changes?

**Comment by Jean-BaptisteC** [comment]
I used debug build generate by workflow to save time

https://user-images.githubusercontent.com/87148630/227005791-8c6ff8e9-53d1-4ebe-9c62-85f964f97aa9.mp4

**Comment by arnaudvergnet** [comment]
@Jean-BaptisteC I managed to reproduce the issue only by shaking my phone all over the place while activating split screen :smile:, your simple case was working fine on my end.

I think the issue is now fixed, but it was not easy to reproduce for me in the first place, so could you confirm it now works for you please?

**Comment by Jean-BaptisteC** [comment]
Crash in split screen is fixed ✅
Split screen is good feature but each manufacturer doing different version of split screen and potientially doesn't have same behavior with views
Others bugs with top bar and place page

https://user-images.githubusercontent.com/87148630/227037925-0aac55d0-f804-4f43-86cc-38f807e781e0.mp4

I have tested around place page, have you others ideas ?

**Comment by arnaudvergnet** [comment]
The position chooser hides the map buttons, but the refactoring logic was that if map buttons are hidden, then we are in fullscreen so the status/navigation bars are hidden as well.

I changed it so fullscreen is only active if the map buttons are hidden and we are not using the place page picker so this should fix the issue.

**Comment by arnaudvergnet** [comment]
Have you tried routing/navigation modes? Navigation mode has a fancy animated search button which could cause issues, and switching between the different modes loads different map buttons layouts.

**Comment by rtsisyk** [comment]
This patch looks good to me, but let's hold it for a week until the next release is branched out to have more time for testing and bugfixing.

**Comment by arnaudvergnet** [comment]
Rebased on master to fix conflicts

File: android/src/app/organicmaps/widget/placepage/sections/PlacePageOpeningHoursFragment.java [hunk 1]
```diff
@@ -192,8 +192,11 @@ public void onPause()
...
 
   @Override
-  public void onChanged(MapObject mapObject)
+  public void onChanged(@Nullable MapObject mapObject)
   {
-    refreshOpeningHours();
+    if (mapObject != null)
+    {
+      refreshOpeningHours(mapObject);
+    }
```
Comment (biodranik) [inline android/src/app/organicmaps/widget/placepage/sections/PlacePageOpeningHoursFragment.java:200]:
```suggestion
    if (mapObject != null)
      refreshOpeningHours(mapObject);
```

File: android/src/app/organicmaps/widget/placepage/sections/PlacePagePhoneFragment.java [hunk 2]
```diff
@@ -53,8 +54,11 @@ public void onPause()
...
 
   @Override
-  public void onChanged(MapObject mapObject)
+  public void onChanged(@Nullable MapObject mapObject)
   {
-    mPhoneAdapter.refreshPhones(mapObject.getMetadata(Metadata.MetadataType.FMD_PHONE_NUMBER));
+    if (mapObject != null)
+    {
+      mPhoneAdapter.refreshPhones(mapObject.getMetadata(Metadata.MetadataType.FMD_PHONE_NUMBER));
+    }
```
Comment (biodranik) [inline android/src/app/organicmaps/widget/placepage/sections/PlacePagePhoneFragment.java:62]:
```suggestion
    if (mapObject != null)
      mPhoneAdapter.refreshPhones(mapObject.getMetadata(Metadata.MetadataType.FMD_PHONE_NUMBER));
```

**Review by biodranik — COMMENTED** [review]
@rtsisyk let's proceed with this refactoring to unblock AA and avoid many merge conflicts caused by delayed merging.

**Comment by arnaudvergnet** [comment]
Updated the PR to fix https://github.com/organicmaps/organicmaps/issues/4903. Unsubscription from events is now done is `onStop` instead of `onPause`. `onPause` may be called when system popups such as the google location services or the share bottom sheet show up. In those cases the app is still visible under the popups and should still respond to events to update the UI.

We started unsubscribing from events in `onPause` to fix issues with the location listener, but in the end it was not enough. So now we stop listening in `onStop` and check if the map object is not null when receiving events from the location listener.

**Comment by biodranik** [comment]
@arnaudvergnet wait, how _paused_ activity/fragment can respond and be updated?

**Comment by arnaudvergnet** [comment]
[From the android documentation](https://developer.android.com/guide/components/activities/activity-lifecycle#onpause):

```
The system calls this method as the first indication that the user is leaving your activity, though it does not always mean the activity is being destroyed. It indicates that the activity is no longer in the foreground, but it is still visible if the user is in multi-window mode. There are several reasons why an activity might enter this state:

    An event that interrupts app execution, as described in the section about the [onResume()](https://developer.android.com/guide/components/activities/activity-lifecycle#onresume) callback, pauses the current activity. This is the most common case.
    In multi-window mode, only one app has focus at any time, and the system pauses all the other apps.
    The opening of a new, semi-transparent activity, such as a dialog, pauses the activity it covers. As long as the activity is partially visible but not in focus, it remains paused. 

When an activity moves to the Paused state, any lifecycle-aware component tied to the activity's lifecycle receives the [ON_PAUSE](https://developer.android.com/reference/androidx/lifecycle/Lifecycle.Event#ON_PAUSE) event. This is where the lifecycle components can stop any functionality that does not need to run while the component is not in the foreground, such as stopping a camera preview.
```

So a better name for `onPause` would be `onLeaveForeground`.

File: android/src/app/organicmaps/maplayer/MapButtonsController.java [hunk 3]
```diff
@@ -75,44 +85,51 @@ else if (mLayoutMode == LayoutMode.planning)
...
     }
     if (helpButton != null)
-      helpButton.setOnClickListener((v) -> mMapButtonClickListener.onClick(MapButtons.help));
+      helpButton.setOnClickListener((v) -> mMapButtonClickListener.onMapButtonClick(MapButtons.help));
 
-    mSearchWheel = new SearchWheel(mFrame, (v) -> mMapButtonClickListener.onClick(MapButtons.search), mOnSearchCanceledListener);
+    mSearchWheel = new SearchWheel(mFrame,
+                                   (v) ->
+                                       mMapButtonClickListener.onMapButtonClick(MapButtons.search)
+        , (v) -> mMapButtonClickListener.onSearchCanceled(), mMapButtonsViewModel);
```
Comment (biodranik) [inline android/src/app/organicmaps/maplayer/MapButtonsController.java:132]: Something is very wrong with formatting here.

File: android/src/app/organicmaps/maplayer/MapButtonsController.java [hunk 4]
```diff
@@ -301,26 +308,32 @@ private int getViewTopOffset(float translation, View v)
...
+    mMapButtonsViewModel.getSearchOption().removeObserver(mSearchOptionObserver);
+  }
   public void onResume()
   {
     super.onResume();
+    mPlacePageViewModel.getPlacePageDistanceToTop().observe(requireActivity(), mPlacePageDistanceToTopObserver);
+    mMapButtonsViewModel.getButtonsHidden().observe(requireActivity(), mButtonHiddenObserver);
+    mMapButtonsViewModel.getMyPositionMode().observe(requireActivity(), mMyPositionModeObserver);
+    mMapButtonsViewModel.getMapLayerMode().observe(requireActivity(), mMapLayerModeObserver);
+    mMapButtonsViewModel.getSearchOption().observe(requireActivity(), mSearchOptionObserver);
```
Comment (biodranik) [inline android/src/app/organicmaps/maplayer/MapButtonsController.java:328]: 1. What are these different observers, and what is their role/usefulness for the user, especially when some dialogs are displayed on top of the paused activity?
2. What is the full list of dialogs that may pause the activity? E.g. the "location is disabled" dialog (it means that subscribing to location updates doesn't make sense yet, right?), what else?

Comment (arnaudvergnet) [reply android/src/app/organicmaps/maplayer/MapButtonsController.java:328]: The observers related to `mMapButtonsViewModel` allow the buttons to react to changes in the app state, such as when the position mode or the layers change, etc.

The observer on `mPlacePageViewModel.getPlacePageDistanceToTop` allows the buttons to follow/avoid the place page when it slides. This observer cannot be removed in `onPause` otherwise the buttons will not follow the place page if it is sliding while there is a popup over the screen (eg you click share and swipe down the place page at the same time, the place page will slide while the share popup pauses the activity). 

To make the code easier to understand, I chose to remove every observer in `onStop`.

**Comment by Jean-BaptisteC** [comment]
Problem about #4903 is fixed ✅
Thanks

**Comment by arnaudvergnet** [comment]
Anything else blocking this PR?

File: android/src/app/organicmaps/maplayer/MapButtonsController.java (hunk 4 above)
Comment (biodranik) [reply android/src/app/organicmaps/maplayer/MapButtonsController.java:328]: l. That's a leak. Resume may be called many times.
2. It would be safer to leave the old behavior, and only subscribe/unsubscribe in onStop the one needed observer. It will also save users batteries in many cases.

Comment (arnaudvergnet) [reply android/src/app/organicmaps/maplayer/MapButtonsController.java:328]: For example `onResume` may be called right after `onPause` without triggering `onStop`. That makes handling lifecycle more complex.

Comment (biodranik) [reply android/src/app/organicmaps/maplayer/MapButtonsController.java:328]: It is an inconsistent pattern to start something in onResume but stop it onStop.

A more general question: the ViewModel approach doesn't make the code easier, it's more connected now than before the refactoring. Are there any better ways? Maybe not following official "pattern recommendations", but something simpler, with fewer dependencies and fewer lines of code?

Comment (arnaudvergnet) [reply android/src/app/organicmaps/maplayer/MapButtonsController.java:328]: I don't see why it is inconsistent as onResume is called both on activity start and on activity resume, but I don't have that much android experience.

After reading the docs a bit more, I think we may be able to simplify this and only observe/remove in onCreate/onDestroy because the viewmodels are linked to the activity lifecycle and thus will never fire when the app goes into background.

Regarding your question, it does make the code simpler. You now have a clear dependency on only the viewmodels, while before you had a mess of callbacks from different classes interacting with each other. Fragments should not depend on any other class than viewmodels. It makes it a lot easier to handle lifecycle as you don't have to worry about using omSaveState, the viewmodel does it for you.

**Comment by biodranik** [comment]
Thanks for the feedback. 

onCreate/onDestroy are definitely no-go. 

If you think that we’ll have issues when subscribe/unsubscribe in onResume/onPause, then let’s do it in onStart/onStop. 

Android lifecycle is crazy sometimes, it’s important to do everything in sync.

**Comment by arnaudvergnet** [comment]
I moved all observers from onResume to onStart and removed them in onStop so everything is clearer/safer.

**Review by rtsisyk — APPROVED** [review]

**Review by biodranik — COMMENTED** [review]
It become too big for a detailed review. We can hope for good testing from @Jean-BaptisteC

It would be great to do similar refactoring in steps or to extract independent parts of them into separate PRs/commits.

**Comment by arnaudvergnet** [comment]
This PR is already split into commits as small as possible. I can try to make PRs for each individual commit if you think it will be easier to review.

**Comment by biodranik** [comment]
No need to split commits. @vng can you please double-check it? Statistically, we have non-zero chances of regressions after similar refactorings, it would be great to reduce their amount by reviewing the code.

File: android/src/app/organicmaps/MwmActivity.java [hunk 5]
```diff
@@ -1233,8 +1213,8 @@ public void updateBottomWidgetsOffset(int offsetX)
       return;
 
     int offsetY = mNavBarHeight;
-    if (mMapButtonsController != null)
-      offsetY = Math.max(offsetY, (int) mMapButtonsController.getBottomButtonsHeight() + mNavBarHeight);
+    if (mMapButtonsViewModel.getBottomButtonsHeight().getValue() != null)
+      offsetY = Math.max(offsetY, mMapButtonsViewModel.getBottomButtonsHeight().getValue().intValue() + mNavBarHeight);
```
Comment (vng) [inline android/src/app/organicmaps/MwmActivity.java:1217]: nit: I prefer avoiding code like this with additional var:
```final ? val = mMapButtonsViewModel.getBottomButtonsHeight().getValue();```

File: android/src/app/organicmaps/maplayer/MapButtonsController.java (hunk 4 above)
Comment (vng) [reply android/src/app/organicmaps/maplayer/MapButtonsController.java:319]: nit: I'd prefer additional var: ```final Activity activity = requireActivity();```

File: android/src/app/organicmaps/widget/placepage/PlacePageViewModel.java [hunk 6]
```diff
@@ -11,6 +11,8 @@ public class PlacePageViewModel extends ViewModel
 {
   private final MutableLiveData<List<PlacePageButtons.ButtonType>> mCurrentButtons = new MutableLiveData<>();
   private final MutableLiveData<MapObject> mMapObject = new MutableLiveData<>();
+  private final MutableLiveData<Integer> mPlacePageWidth = new MutableLiveData<>();
+  private final MutableLiveData<Integer> mPlacePageDistanceToTop = new MutableLiveData<>();
```
Comment (vng) [inline android/src/app/organicmaps/widget/placepage/PlacePageViewModel.java:15]: Same here, why MutableLiveData ?

File: android/src/app/organicmaps/widget/placepage/PlacePageController.java [hunk 7]
```diff
@@ -104,51 +90,48 @@ public void onStateChanged(@NonNull View bottomSheet, int newState)
...
-      final Lifecycle.State state = mMwmActivity.getLifecycle().getCurrentState();
-      if (!state.isAtLeast(Lifecycle.State.RESUMED))
-      {
-        Logger.e(TAG, "Called in the wrong activity state=" + state);
-        return;
-      }
       stopCustomPeekHeightAnimation();
       mDistanceToTop = bottomSheet.getTop();
-      mSlideListener.onPlacePageSlide(mDistanceToTop);
+      mViewModel.setPlacePageDistanceToTop(mDistanceToTop);
```
Comment (vng) [inline android/src/app/organicmaps/widget/placepage/PlacePageController.java:95]: Do we need to call here?
 ```PlacePageUtils.updateMapViewport(mCoordinator, mDistanceToTop, mViewportMinHeight);```
mDistanceToTop was changed

File: android/src/app/organicmaps/maplayer/MapButtonsViewModel.java [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+import androidx.lifecycle.ViewModel;
+
+public class MapButtonsViewModel extends ViewModel
+{
+  private final MutableLiveData<Boolean> mButtonsHidden = new MutableLiveData<>(false);
+  private final MutableLiveData<Float> mBottomButtonsHeight = new MutableLiveData<>(0f);
+  private final MutableLiveData<MapButtonsController.LayoutMode> mLayoutMode = new MutableLiveData<>(MapButtonsController.LayoutMode.regular);
+  private final MutableLiveData<Integer> mMyPositionMode = new MutableLiveData<>();
+  private final MutableLiveData<Mode> mMapLayerMode = new MutableLiveData<>();
+  private final MutableLiveData<SearchWheel.SearchOption> mSearchOption = new MutableLiveData<>();
```
[the remark this answers is not in the document]
Comment (arnaudvergnet) [reply android/src/app/organicmaps/maplayer/MapButtonsViewModel.java:14]: Here is the documentation: https://developer.android.com/topic/libraries/architecture/livedata#java.

**This is a lifecycle aware observable value**. When you create the view model, you tie it to an activity. Then the live data inside that view model follows the activity life cycle, so it does not trigger callbacks when the activity is stopped and automatically removes listeners when it is destroyed.

In our case, when we use the viewmodels in fragments we still have to remove the listeners because they have a shorter life cycle than the parent activity (to prevent the listeners from trying to update a destroyed UI).

Tying the view model to the parent activity allows us the reuse the value across different fragments. So the viewmodels store the UI state, and fragments can simply observe the live data to update their UI. No more `onSavedInstanceState`, no more dependency injection all over the place and we are sure all the fragments use the same state.

This makes debugging a lot easier and makes the codebase more robust. But then again I am no Android expert.

File: android/src/app/organicmaps/widget/placepage/PlacePageController.java (hunk 7 above)
Comment (arnaudvergnet) [reply android/src/app/organicmaps/widget/placepage/PlacePageController.java:95]: To improve performance we only update the viewport when the place page is settled, which happens after the place page finished sliding.

If we call `PlacePageUtils.updateMapViewport(mCoordinator, mDistanceToTop, mViewportMinHeight);` here then the viewport will update as the place page moves.

**Review by vng — APPROVED** [review]
Gonna test this PR myself for updateMapViewport.

**Review by biodranik — COMMENTED** [review]
Thanks! Two more issues I found:

1. In the navigation mode in landscape, when you select some POI, it jumps too much up, and sometimes becomes hidden (on the narrow device). Likely because of the perspective.
2. When I build a route in landscape, with the finish point at the top, it always becomes hidden by the top bar with routing mode icons. Not sure if it's related to this PR, but it should be fixed anyway. Maybe in a separate PR.

**Comment by biodranik** [comment]
Note: For some reason, sometimes there is a (significant) several seconds delay in the debug version when the PP is closed for some objects:
1. Tap some objects at the bottom of the map.
2. PP opens and then the viewport jumps up so the selected POI is visible on the screen.
1. You close pp.
3. Several seconds pass.
4. The POI blue selection circle disappears and viewport "jumps" back.

In the release it works ok.

File: android/src/app/organicmaps/widget/placepage/PlacePageUtils.java [hunk 9]
```diff
@@ -15,20 +13,14 @@
 
 import java.util.List;
 
-class PlacePageUtils
+public class PlacePageUtils
 {
-  static void moveViewportUp(@NonNull View placePageView, int viewportMinHeight)
+  static void updateMapViewport(@NonNull View parent, int placePageDistanceToTop, int viewportMinHeight)
```
[the remark this answers is not in the document]
Comment (vng) [reply android/src/app/organicmaps/widget/placepage/PlacePageUtils.java:18]: I did testing on my device and it works ok. @rtsisyk Please, check your Huawei.

**Comment by biodranik** [comment]
@arnaudvergnet thank you for your work, and sorry for the delay. Statistically, these refactorings were always leading to some regressions, so we tried to double-check it as much as we can :)

**Comment by arnaudvergnet** [comment]
Thanks for the merge! Hopefully if there are any regressions they will be easier to fix and won't break something else in the process.
