### PR TITLE
[android] Fix a crash in processNavigation() called after onDestroy()

### LINKED ISSUE #6190: [android] androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
samsung starlte (Galaxy S9)
Android 10 (SDK 29)
Version: 23092227 (2023.09.22-27-Google)

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
  at app.organicmaps.SplashActivity.processNavigation (SplashActivity.java)
  at app.organicmaps.MwmApplication.nativeProcessTask (MwmApplication.java)
  at app.organicmaps.MwmApplication.lambda$forwardToMainThread$0 (MwmApplication.java)
  at android.os.Handler.handleCallback (Handler.java:809)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7555)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)
```

https://play.google.com/console/u/0/developers/8084273541548442467/app/4972992444534608608/vitals/crashes/5dec41631f7653ed8948dea26a696376/details?days=28&versionCode=23092227

processNavigation is called from NDK when SplashActivity is not in the right state

### PR DESCRIPTION
**Pull request by rtsisyk**
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
  at app.organicmaps.SplashActivity.processNavigation (SplashActivity.java)
  at app.organicmaps.MwmApplication.nativeProcessTask (MwmApplication.java)
  at app.organicmaps.MwmApplication.lambda$forwardToMainThread$0 (MwmApplication.java)
  at android.os.Handler.handleCallback (Handler.java:809)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7555)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)
```

Fixes #6190

### CODE REVIEW

File: android/app/src/main/java/app/organicmaps/SplashActivity.java [hunk 1]
```diff
@@ -172,6 +172,12 @@ private void init()
   @SuppressWarnings({"unused", "unchecked"})
   public void processNavigation()
   {
+    if (isDestroyed())
```
Comment (rtsisyk) [inline android/app/src/main/java/app/organicmaps/SplashActivity.java:175]: This should be added to almost every JNI to Java call...

Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/SplashActivity.java:175]: Why? That doesn't look like a reliable solution.

Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/SplashActivity.java:175]: > Why? That doesn't look like a reliable solution.

What is not clear in this situation? JNI can call Java callbacks at any point in the lifecycle. Some JNI callbacks are removed from onDestroy(), but there are lot of callbacks are static. Especially funny are callback called via event loop.

> What causes it to be called in the first place? Should the destruction start properly and deactivate all native subscribers first?

The callback is called after the end of async map initialization. This is a regression from the previous release.

**Comment by vng** [comment]
So if this situation is possible then we never register maps? So the app becomes useless :).
There is no JNI static callbacks here, a just regular one.
Initial code https://github.com/organicmaps/organicmaps/commit/9aedde5b2a1a5aaba8c3792d0898fa49ede065e5 was:
```
rf = jni::make_global_ref(listener)
```
so SplashActivity was always alive.

Then we rewrite it on _completition handler_. 
this::processNavigation -> Runnable onComplete
and this Runnable is *not* holding SplashActivity, so there is no guarantee that it will be alive when running. Or not?

Return back holding activity ref or make Runnable holding SplashActivity ref.

**Comment by vng** [comment]
Ok, then what exact NullPointerException is here?

**Comment by vng** [comment]
Seems like mApiRequest is null. Anyway, the fix should be another here ..

**Comment by rtsisyk** [comment]
> So if this situation is possible then we never register maps? So the app becomes useless :). There is no JNI static callbacks here, a just regular one. Initial code [9aedde5](https://github.com/organicmaps/organicmaps/commit/9aedde5b2a1a5aaba8c3792d0898fa49ede065e5) was:
> 
> ```
> rf = jni::make_global_ref(listener)
> ```
> 
> so SplashActivity was always alive.

Java object was alive != Activity was in the right state. There is no issue that Java object is collected by GC. The issue is that the method is called when activity is already not in the right state.

**Review by vng — APPROVED** [review]
