### PR TITLE
[android] Hide plus fab if all maps are downloaded or updatable

### LINKED ISSUE #8271: [android] Not functional map download button
**Describe the issue**
Hello. I noticed a button that does not perform its function. When all the maps of the country are loaded, clicking on the plus button does not open the list of available maps (because there are none), but only the letter at the top appears. As a user, it would be logical for me not to show the button

**Steps to reproduce**
1. Open Download Maps
2. Download all maps of the country
3. Click on '+' 

**Screenshots**
Screenshot_2024-05-24-12-10-58-961_app organicmaps beta

Screenshot_2024-05-24-12-11-03-934_app organicmaps beta

**System information:**
 - Operating system and its version: [Android 13, HyperOS 1.0.2.0]
 - Organic Maps version: [2024.05.19-30-Google-beta]
 - Device Model: [Redmi Note 12 Pro]

### PR DESCRIPTION
**Pull request by strider-dunadan**
- Hide the floating action button (FAB) in the downloader when there are no maps available to download
- FAB is hidden when status is `STATUS_DONE` (all downloaded) or `STATUS_UPDATABLE` (all present, just updates available)
- FAB remains visible when there are downloadable regions (`STATUS_PARTLY`, `STATUS_PROGRESS`, etc.)

image
image

Fixes #8271

### CODE REVIEW

File: android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java [hunk 1]
```diff
@@ -107,12 +106,15 @@ public void update()
     boolean search = adapter.isSearchResultsMode();
 
     boolean show = !search;
-    UiUtils.showIf(show && adapter.isMyMapsMode(), mFab);
+    String root = adapter.getCurrentRootId();
+    int status = MapManager.nativeGetStatus(root);
+
+    // Hide FAB when all maps are already downloaded or updatable - nothing new to download
+    boolean hideFab = (status == STATUS_DONE || status == STATUS_UPDATABLE);
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java]: **Bug: `STATUS_UPDATABLE` does not mean "nothing new to download".**

Group node status is computed as the **minimum** `NodeStatus` enum value across all leaf descendants (`storage.cpp:1611`):

```cpp
if (static_cast<size_t>(statusAndError.status) < static_cast<size_t>(result))
    result = statusAndError.status;
```

The `NodeStatus` enum ordering (`storage_defines.hpp:56-67`):
```
OnDiskOutOfDate = 5  →  Java STATUS_UPDATABLE
OnDisk          = 6  →  Java STATUS_DONE
NotDownloaded   = 7  →  Java STATUS_DOWNLOADABLE
```

Since `OnDiskOutOfDate (5) < NotDownloaded (7)`, any subtree containing **at least one updatable map AND any not-yet-downloaded maps** reports `STATUS_UPDATABLE` as its aggregate status — even though there are still maps available to download.

**Example:** Country with leaves `[OnDisk, OnDiskOutOfDate, NotDownloaded, NotDownloaded]`:
- `min(6, 5, 7, 7) = 5` → `OnDiskOutOfDate` → Java `STATUS_UPDATABLE`
- `hideFab = true` → FAB hidden, but 2 regions are still downloadable

**Worst case at root level:** With just 1 out-of-date map among hundreds of not-downloaded countries, the root reports `STATUS_UPDATABLE`, the FAB disappears globally, and the user **loses the only UI path into available maps**.

**Suggested fix:** Only hide on `STATUS_DONE`:
```java
boolean hideFab = (status == STATUS_DONE);
```

`STATUS_DONE` (backed by `allOnDisk == true` in `GetNodeStatusInfo`) is the only status that guarantees every leaf descendant is downloaded and up-to-date — safe to hide the FAB.

**Comment by biodranik** [comment]
## Review: `STATUS_UPDATABLE` check causes a regression

The idea is right — hiding the FAB when there's nothing to download — but `STATUS_UPDATABLE` doesn't guarantee that. I traced through the native code to verify:

### How group status works

`Storage::GetNodeStatusInfo` (in `libs/storage/storage.cpp:1591-1622`) computes group status as the **minimum `NodeStatus` enum value** across all leaf descendants. The enum order is: `OnDiskOutOfDate(5) < OnDisk(6) < NotDownloaded(7)`.

So a subtree with 1 updatable map + N not-downloaded maps → group status = `OnDiskOutOfDate` → Java `STATUS_UPDATABLE`. The only status that reliably means "every leaf is downloaded" is `STATUS_DONE`, which is returned only when `allOnDisk == true`.

### Impact

At the downloader **root level**, a single out-of-date map among hundreds of not-downloaded countries will hide the FAB, removing the only UI path to browse and download new maps.

### Suggested alternatives

1. **Minimal safe fix** — hide only on `STATUS_DONE`:
   ```java
   boolean hideFab = (status == STATUS_DONE);
   ```
   This leaves the FAB visible when all maps are downloaded but some are updatable. Tapping it in that case would show all regions (because `keepAvailableChildren=true` in `nativeListItems`), which is slightly redundant but not broken.

2. **More robust** — if you also want to hide when everything is downloaded-but-updatable, you could check whether there are actual `NotDownloaded` descendants. The native layer already exposes child counts via `NodeAttrs.m_mwmCounter` / `m_downloadingMwmCounter` (`storage.cpp:1675`), or a dedicated `hasDownloadableDescendants(root)` native helper could be added.

Option 1 is the simplest path to a correct fix.

File: android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java (hunk 1 above)
Comment (strider-dunadan) [reply android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java]: Right, thanks, fixed!
