### PR TITLE
Modified startForeground() method call to adapt for android 14+

### LINKED ISSUE #9395: [android] Crash in routing.NavigationService.onStartCommand -> Service.startForeground
2024.09.19-2-Google, 48 users, 128 crashes.

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:5286)
  at android.app.ActivityThread.-$$Nest$mhandleServiceArgs
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2531)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at android.app.ActivityThread.main (ActivityThread.java:8919)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:578)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
Caused by java.lang.SecurityException:
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3069)
  at android.os.Parcel.createException (Parcel.java:3053)
  at android.os.Parcel.readException (Parcel.java:3036)
  at android.os.Parcel.readException (Parcel.java:2978)
  at android.app.IActivityManager$Stub$Proxy.setServiceForeground (IActivityManager.java:7234)
  at android.app.Service.startForeground (Service.java:775)
  at app.organicmaps.routing.NavigationService.onStartCommand (NavigationService.java:231)
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:5268)
Caused by android.os.RemoteException: Remote stack trace:
  at com.android.server.am.ActiveServices.validateForegroundServiceType (ActiveServices.java:2741)
  at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked (ActiveServices.java:2452)
  at com.android.server.am.ActiveServices.setServiceForegroundLocked (ActiveServices.java:1797)
  at com.android.server.am.ActivityManagerService.setServiceForeground (ActivityManagerService.java:15948)
  at android.app.IActivityManager$Stub.onTransact$setServiceForeground$ (IActivityManager.java:11974)
```

### PR DESCRIPTION
**Pull request by kavikhalique**
Fixes #9395

Its not sure it fixes the crash or not but this could be the cause of crash since in android api 34 and above we need to specify the foreground service type while calling the startForegound method for track recording and navigation.

Reference android documentation - https://developer.android.com/develop/background-work/services/foreground-services#start

Please test and provide feedback if its solves the crash or not

### CODE REVIEW

File: android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java [hunk 1]
```diff
@@ -163,7 +165,7 @@ public int onStartCommand(@NonNull Intent intent, int flags, int startId)
     {
       try
       {
-        startForeground(TrackRecordingService.TRACK_REC_NOTIFICATION_ID, getNotificationBuilder(this).build());
+        ServiceCompat.startForeground(this, TrackRecordingService.TRACK_REC_NOTIFICATION_ID, getNotificationBuilder(this).build(), ServiceInfo.FOREGROUND_SERVICE_TYPE_LOCATION);
```
Comment (AndrewShkrob) [inline android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java:168]: What is the point of specifying the service type that was defined in the manifest and already has a service type specified?
```xml
<service android:name=".location.TrackRecordingService"
      android:foregroundServiceType="location"
      android:exported="false"
      android:enabled="true"
      android:stopWithTask="false"
      />
````

If this is a legitimate change then I'd prefer to set this value: [FOREGROUND_SERVICE_TYPE_MANIFEST](https://developer.android.com/reference/android/content/pm/ServiceInfo.html#FOREGROUND_SERVICE_TYPE_MANIFEST). It should automatically use all values from manifest and no need to define them in two places.

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java:168]: I am also not very sure that it gonna solve the issue correctly or not but i read that from android 14 above we need to provide the type of foreground service. Since i was unable to regenerate the issue i cannot say it will resolve it since everything else seems fine.

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java:168]: https://developer.android.com/about/versions/14/changes/fgs-types-required#location

In this doc it states the steps while starting foreground service which requires location service

Kindly have a look @AndrewShkrob , i think this will probably solve the issue

**Comment by zeac** [comment]
> @zeac Could you please take a look here and write your opinion?

According to the documentation explicit FOREGROUND_SERVICE_TYPE_ is not required and all Android 15 devices I have work fine. But it's possible that some versions of Android had issues with that.

Is that crash still present in Google Play Console?

**Comment by kavikhalique** [comment]
Is the crash still there? If not we can close this PR.

**Comment by biodranik** [comment]
@kavikhalique can you please also update other usages of startForeground in the code? I see 6 of them.

**Comment by kavikhalique** [comment]
> @kavikhalique can you please also update other usages of startForeground in the code? I see 6 of them.

Done

File: android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java (hunk 1 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java]: PTAL @AndrewShkrob

File: android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java [hunk 2]
```diff
@@ -40,18 +41,17 @@ public int onStartCommand(Intent intent, int flags, int startId)
...
-      try
-      {
-        startForeground(DownloaderNotifier.NOTIFICATION_ID, notification);
-      } catch (ForegroundServiceStartNotAllowedException e)
-      {
-        Logger.e(TAG, "Oops! ForegroundService is not allowed", e);
-      }
-    } else
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
+        ServiceCompat.startForeground(this, DownloaderNotifier.NOTIFICATION_ID, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_MANIFEST);
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java]: @AndrewShkrob would it be safer (including google reviewers and their automated tools) to explicitly define the necessary permission type for each service, as they can be different? E.g downloader and Edits Upload services don't need location permission, and if it expires (or user disables it explicitly) these services will still work.

File: android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java [hunk 3]
```diff
@@ -158,20 +159,18 @@ public int onStartCommand(@NonNull Intent intent, int flags, int startId)
...
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
+        ServiceCompat.startForeground(this, TrackRecordingService.TRACK_REC_NOTIFICATION_ID, getNotificationBuilder(this).build(), ServiceInfo.FOREGROUND_SERVICE_TYPE_MANIFEST);
+      else
+        ServiceCompat.startForeground(this, TrackRecordingService.TRACK_REC_NOTIFICATION_ID, getNotificationBuilder(this).build(), 0);
     }
-    else
+    catch (Exception e)
     {
-      startForeground(TrackRecordingService.TRACK_REC_NOTIFICATION_ID, getNotificationBuilder(this).build());
+      Logger.e(TAG, "Unable to start Track Recording Foreground Service", e);
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java]: I don't like silent failure approach, it would be hard to debug later. If permissions are checked properly before launching the service, then there should be no any exceptions. And if there will be any exception, it would be important for us to know about it ASAP to fix properly instead of leaving a user with a non-working service.

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java]: Foreground service is prone to throw errors as documentation says (In our case this ([exception](https://developer.android.com/develop/background-work/services/fgs/troubleshooting#startForeground-too-slow)) may occur with many users because we have lots of check between these two methods (startForegroundService and serviceCompat.startForeground()) whereas documentation says it should not have more than 5-6 seconds gap or it may throw error.

We can do two things-

1. Remove try catch and see if it causes crashes in user devices or not. (Risky)

2. Keep the try catch and if due to any reasons crash occurs stop all the native works corresponding to that service and inform user to retry (eg. for track recording if any exception occurs, Log it and close the native track recorder and show user some error occurred as hint) (It can be done in separate PR)

Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java]: I see, thanks for the details! Google uses try catch too in their example that also tries to separately handle/log `ForegroundServiceStartNotAllowedException`:
https://developer.android.com/develop/background-work/services/fgs/launch#promote-service
… so it should be ok to do the same approach as in their example and print error log now (we can't show a toast from this part of the service code, right?).

File: android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java (hunk 2 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java]: Google says:
> For example, suppose a fitness app runs a running-tracker service that always needs location information, but might or might not need to play media. You would need to declare both location and mediaPlayback in the manifest. If a user starts a run and just wants their location tracked, your app should call startForeground() and pass just the ACCESS_FINE_LOCATION permission. Then, if the user wants to start playing audio, call startForeground() again and pass the bitwise combination of all the foreground service types (in this case, ACCESS_FINE_LOCATION|FOREGROUND_SERVICE_MEDIA_PLAYBACK).

So it would be safer to follow [their recommendations](https://developer.android.com/develop/background-work/services/fgs/launch#promote-service).

File: android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java (hunk 3 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java]: Yes we cannot show toast from here since we need context.

**Comment by biodranik** [comment]
Isn't [this crash](https://github.com/organicmaps/organicmaps/issues/10128#issuecomment-2698741248) related?

```
03-04 18:43:30.688 30066 30066 E AndroidRuntime: FATAL EXCEPTION: main
03-04 18:43:30.688 30066 30066 E AndroidRuntime: Process: app.organicmaps, PID: 30066
03-04 18:43:30.688 30066 30066 E AndroidRuntime: java.lang.RuntimeException: Unable to start service app.organicmaps.routing.NavigationService@34424d9 with Intent { cmp=app.organicmaps/.routing.NavigationService }: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{b0e0021 30066:app.organicmaps/u0a207} targetSDK=35 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5280)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2555)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:109)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8826)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: Caused by: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{b0e0021 30066:app.organicmaps/u0a207} targetSDK=35 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3240)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3224)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3200)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3142)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7231)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:778)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at app.organicmaps.routing.NavigationService.onStartCommand(NavigationService.java:231)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5262)
03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	... 11 more
```

**Comment by kavikhalique** [comment]
> Isn't [this crash](https://github.com/organicmaps/organicmaps/issues/10128#issuecomment-2698741248) related?
> 
> 
> 
> ```
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: FATAL EXCEPTION: main
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: Process: app.organicmaps, PID: 30066
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: java.lang.RuntimeException: Unable to start service app.organicmaps.routing.NavigationService@34424d9 with Intent { cmp=app.organicmaps/.routing.NavigationService }: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{b0e0021 30066:app.organicmaps/u0a207} targetSDK=35 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5280)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2555)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:109)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8826)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: Caused by: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{b0e0021 30066:app.organicmaps/u0a207} targetSDK=35 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3240)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3224)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3200)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3142)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7231)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:778)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at app.organicmaps.routing.NavigationService.onStartCommand(NavigationService.java:231)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5262)
> 
> 03-04 18:43:30.688 30066 30066 E AndroidRuntime: 	... 11 more
> 
> ```

This issue is occuring because of security exceptions. Possible cause would be any of these.

1. Location permissions (both coarse and precise) are not allowed 

[less possible since we dont let users start navigation without that] 

2. Starting foreground service when app is in background 

[also not possible because we start FG services when app is in foreground.]

3. Foreground service permission. 

[this could be the reason, since permission is already present in manifest, only left is passing the same through method call]

**Review by vng — APPROVED** [review]
Consider extracting some ServiceUtils class to avoid copy-paste.

File: android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java (hunk 2 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java]: @kavikhalique please change FOREGROUND_SERVICE_TYPE_MANIFEST to the explicitly used type, and clean up unnecessary changes, and also remove unnecessary try/catch (as it was used before instead of an explicit if(SDK version check))

**Comment by kavikhalique** [comment]
> Consider extracting some ServiceUtils class to avoid copy-paste.

Should I create a utility method start foreground to start all services from there?

In that case, we need proper refactoring and need to move few more methods like create notification builder and notification channel etc. Can be done in separate PR may be?

File: android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java (hunk 2 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java]: Done!!
PTAL - @biodranik

**Review by biodranik — APPROVED** [review]
Thanks, LGTM, and can be merged after a smoke-test in the emulator/real device with different API versions.
