### PR TITLE
[routing] Highway factor fixes.

### LINKED ISSUE #8541: Should use the shortest unpaved bad road.
Likely caused by smoothness values: https://www.openstreetmap.org/way/1118727419

Foot/cycling paths are correct according to a user report:

car|foot|bicycle
--|--|--
выява|выява|выява

CC @vng

### LINKED ISSUE #8729: ETA/time estimates on some dirt and small residential roads are about 2-5x too slow
**Describe the issue**

I live on the end of a dirt road.  Organic Maps seems to assume dirt roads have a speed limit somewhere around 5mph.  This results in trip estimates being 10 to 30 minutes too long, and causes some strange routing, like if I'm traveling mostly on dirt roads, trying to take me miles out of my way to a paved road and back around "the long way" instead of creating a route that's a fraction of a mile and goes straight to my destination.

**Steps to reproduce**
1. Pick a destination and starting point both on a dirt road near each other (this is happening in rural Montana, USA but likely other places too)
2. ETA is insane and route is likely to be as well

**Expected behaviour**
It performs in a normal manner when navigating on dirt roads.

**Screenshots**

Wants me to deviate to a highway and then come around the long way, despite this being several miles longer:
Screenshot_20240709-164659

Wants me to turn around at the next interstate exit (the one I actually had to get off at) so I can backtrack towards and through an entire city and back up into the hills on a slightly more paved route. Following these instructions would have required an extra half hour of driving and dozens more miles.  It kept prompting me to turn around after I left the interstate, even when I was almost to my destination.
Screenshot_20240618-140103

Seems to assume a 9mph speed limit for no apparent reason, nobody drives that slowly (half the road involved is paved too):
Screenshot_20240719-005301

**System information:**
 - Operating system and its version: Android 14 (CalyxOS)
 - Organic Maps version: 2024.06.19-3-FDroid
 - Device Model: Fairphone 5

### LINKED ISSUE #8823: App takes longer trunk detour instead of shorter primary.
4.737768, -74.077599 to 4.684999, -74.046393

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=4.7378%2C-74.0776%3B4.6859%2C-74.0457#map=14/4.7113/-74.0623

telegram-cloud-photo-size-1-4999374553276853534-y

CC @vng

### PR DESCRIPTION
**Pull request by vng**
Will merge after integration tests update.

Closes #8823
Closes #8729
Closes #8541

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
LGTM. The current algo looks like a black magic of tuning constants.

**Comment by biodranik** [comment]
Routing tests are failing on mac.

File: routing/routing_integration_tests/route_test.cpp [hunk 1]
```diff
@@ -246,16 +246,16 @@ UNIT_TEST(CanadaBridgeCrossToEdwardIsland)
...
       FromLatLon(49.85015, 2.24296), {0., 0.},
-      FromLatLon(48.85458, 2.36291), 132897);
+      FromLatLon(48.85458, 2.36291), 128749);
 
   // Backward.
   // OM makes the same as GraphHopper and Valhalla. OSRM makes a bit shorter route.
   CalculateRouteAndTestRouteLength(GetVehicleComponents(VehicleType::Car),
       FromLatLon(48.85458, 2.36291), {0., 0.},
-      FromLatLon(49.85027, 2.24283), 136652);
+      FromLatLon(49.85027, 2.24283), 136653);
```
Comment (biodranik) [inline routing/routing_integration_tests/route_test.cpp:258]: +1 meter? :)

**Review by biodranik — APPROVED** [review]
LGTM
