### PR TITLE
Fixed selection of a POI with bookmark when bookmark is not selected

### LINKED ISSUE #4141: Touch bookmarks icon or title POI on map doesn't open same place page
How reproduce:
- Open OM
- Select POI --> add to bookmarks
- Touch bookmarks icon on POI --> POI is attached to bookmarks and star is yellow on place page
- Touch title of POI --> POI is not attached to bookmarks and star is grey on place page (we can re-add POI on bookmarks)

User has touched bookmarks icon

User has touched title of POI

Pixel 6 - Android 13
v2022.12.18-12-Google

### PR DESCRIPTION
**Pull request by strump**
Closes #4141

poi-with-bookmark

When user taps on the map we do next steps:

1. Search for a bookmark at the tap position
2. Search for a POI at the tap position
3. Search for a building at the tap position.
4. Search for any feature at the tap position

I added additional bookmark search after POI is selected.

### CODE REVIEW

File: map/framework.cpp [hunk 1]
```diff
@@ -2178,6 +2178,14 @@ place_page::Info Framework::BuildPlacePageInfo(place_page::BuildInfo const & bui
     // Selection circle should match feature
     FillFeatureInfo(selectedFeature, outInfo);
 
+    if (!outInfo.IsBookmark() && !isBuildingSelected)
+    {
+      // Search for a bookmark at POI position instead of tap position
```
Comment (strump) [inline map/framework.cpp:2183]: We actually search for a bookmark two times during tap handling. Should we check that POI position (`outInfo.GetMercator()`) is far from tap position (`buildInfo.m_mercator`) before performing the second search?

**Comment by biodranik** [comment]
> I added an additional bookmark search after POI is selected.

Why (1) "Search for a bookmark at the tap position" not select the nearest bookmark again, in the same way it was selected on the first tap?

**Comment by strump** [comment]
> > I added an additional bookmark search after POI is selected.
> 
> Why (1) "Search for a bookmark at the tap position" not select the nearest bookmark again, in the same way it was selected on the first tap?

Bookmark is not selected because it's far from the tap position. But POI is selected because we tap on the label.

File: map/framework.cpp [hunk 2]
```diff
@@ -2178,6 +2178,14 @@ place_page::Info Framework::BuildPlacePageInfo(place_page::BuildInfo const & bui
     // Selection circle should match feature
     FillFeatureInfo(selectedFeature, outInfo);
 
+    if (!outInfo.IsBookmark() && !isBuildingSelected)
```
Comment (biodranik) [inline map/framework.cpp:2181]: Does a bookmark on a building work with this check?

File: map/framework.cpp [hunk 3]
```diff
@@ -2178,6 +2178,14 @@ place_page::Info Framework::BuildPlacePageInfo(place_page::BuildInfo const & bui
...
+    {
+      // Search for a bookmark at POI position instead of tap position
+      auto mark = FindBookMarkInPosition(outInfo.GetMercator());
```
Comment (biodranik) [inline map/framework.cpp:2184]: Searching _all_ bookmarks in _all_ lists twice on each tap looks like an overhead. @vng do you have any better ideas on the implementation? The tap's radius doesn't find a bookmark near it but selects a POI at a distance with a large text which was tapped.

File: map/framework.cpp (hunk 2 above)
Comment (strump) [reply map/framework.cpp:2181]: Building centroid works as POI. If you tap on centroid or on a building label then `isBuildingSelected==false` and bookmark is found correctly.

If you tap inside a building then PlacePage shows building properties but with no bookmark.

You can install and try 😉

Comment (biodranik) [reply map/framework.cpp:2181]: Thanks for the details.

> You can install and try 😉

Building, installing, and trying every PR takes a lot of time, and is not possible from iPhone. I'm doing it, of course, when there's some time.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14

**Review by biodranik — APPROVED** [review]
@vng how to avoid double search of all bookmarks in such cases? Should text POI coordinate be detected first, and bookmark search check for two coordinates (POI + tapped place) if the distance between them is greater than the tap radius?

**Comment by vng** [comment]
Honestly, I still don't understand why it is a bug :)

If we select some map feature (even by tapping on the very edge of a caption) and we have a bookmark placed on that feature, it should also be selected. Why is it a problem?

**Review by vng — APPROVED** [review]
We already have _a lot of_ bookmark list searches, and I doubt that this fix can make it worth.

Recommend merging it and investigating bookmark lists in separate tasks. I have a lot of questions there.

**Comment by biodranik** [comment]
@strump @kirylkaveryn the proper search should be implemented using a tree container, not a linear vector-like one. A good internal refactoring may improve the situation and make the search of tapped bookmarks instant/consuming less battery. Any volunteers are welcome )

**Comment by strump** [comment]
@biodranik  the problem is that we have no index for boomarks. When you search in a bookmark folder fulltext index is built in-memory and cleaned after you exit search dialog.

If we have two bookmark indexes (full-text and geospatial) when those should be updated? On every modification? Should indexing made async? Refactoring is needed.

**Comment by biodranik** [comment]
@strump we are already using geospatial index to quickly find which map features should be displayed in the viewport. A similar approach should apply to bookmarks too. @vng which container would you use for bookmarks?

**Comment by vng** [comment]
First of all should investigate how it works starting from rendering.

**Comment by strump** [comment]
@biodranik I found that OM builds index for Bookmarks in `DrapeEngine::UpdateUserMarks(...)` method. Which actually posts `UpdateUserMarkGroupMessage` to update geo index with `UserMarkGenerator::UpdateIndex()`. Maybe we can consume `UserMarkGenerator` to get nearest bookmark. I lack knowledge in drape_engine.
