### PR TITLE
[android] Fix ArrayIndexOutOfBoundsException in Logger

### LINKED ISSUE #6558: [android] Exception when using HttpClient
Reproduces on map downloads (at least for links with 404) and for OSM uploads. Likely is caused by recently merged R8. Note that printed exception can happen earlier when calling Java from JNI, but only printed when explicit `HandleJavaException` is called.

```
11-14 15:52:25.546 (Thread-3) E/OMcore: core/jni_helper.cpp:206 HandleJavaException(): java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
	at app.organicmaps.util.log.Logger.log(SourceFile:52)
	at app.organicmaps.util.log.Logger.d(SourceFile:2)
	at app.organicmaps.util.HttpClient.run(SourceFile:33)
```

### PR DESCRIPTION
**Pull request by rtsisyk**
Fixes #6558

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Does it fix the OSM upload? Why it started to fail only in upload cases?

**Comment by rtsisyk** [comment]
> Does it fix the OSM upload? Why it started to fail only in upload cases?

It always failed during OSM upload, not during OSM login. The code assumed that the stack trace always have 4 frames at least. R8 optimized some unnecessary calls, which reduced the stack trace size to 3.

**Review by vng — APPROVED** [review]

File: android/app/src/main/java/app/organicmaps/util/log/Logger.java [hunk 1]
```diff
@@ -88,16 +88,17 @@ public static void e(String tag, String msg, Throwable tr)
...
   private static String getSourcePoint()
   {
     final StackTraceElement[] stackTrace = new Throwable().getStackTrace();
-    assert stackTrace.length > CALL_STACK_INDEX : "Synthetic stacktrace doesn't have enough elements";
-
-    final StackTraceElement st = stackTrace[CALL_STACK_INDEX];
+    // Skip the chain of Logger.x() -> Logger.log() calls.
+    int f = 0;
+    for (; f < stackTrace.length && stackTrace[f].getClassName().equals(Logger.class.getName()); f++);
+    // The stack trace should have at least one non-logger frame, but who wants to crash here if it doesn't?
```
Comment (pastk) [inline android/app/src/main/java/app/organicmaps/util/log/Logger.java:98]: what about logging from the Logger?
maybe better to locate the specific call that should always precede log's caller? is it `Logger.log()`?

another approach might be to disable r8 / add @keep to log methods to guarantee a stable stacktrace "prefix"
