### PR TITLE
[android] Improve the changing of location refresh intervals and fix NavigationService

### LINKED ISSUE #6091: [android] SIGSEGV in  Framework::GetMyPositionMode() const
```
null pointer dereference: SIGSEGV  0x00000000000004b0
#00 pc 0x8537d8 liborganicmaps.so (Framework::GetMyPositionMode() const [memory:2667]) (BuildId: c3665fbc180e405013711318687388d052fc9bc2)
#01 pc 0x7ed354 liborganicmaps.so (Java_app_organicmaps_location_LocationState_nativeGetMode [Framework.cpp:659]) (BuildId: c3665fbc180e405013711318687388d052fc9bc2)
#02 pc 0x461d54 libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#03 pc 0x20008c libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#04 pc 0x461cbc libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#05 pc 0x7c5544c462
#06 pc 0x20087c libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#07 pc 0x209398 libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#08 pc 0x803654 libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#09 pc 0x7c5544c462
#10 pc 0x7c5544ca86null pointer dereference: SIGSEGV  0x00000000000004b0
#00 pc 0x8537d8 liborganicmaps.so (Framework::GetMyPositionMode() const [memory:2667]) (BuildId: c3665fbc180e405013711318687388d052fc9bc2)
#01 pc 0x7ed354 liborganicmaps.so (Java_app_organicmaps_location_LocationState_nativeGetMode [Framework.cpp:659]) (BuildId: c3665fbc180e405013711318687388d052fc9bc2)
#02 pc 0x461d54 libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#03 pc 0x20008c libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#04 pc 0x461cbc libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#05 pc 0x7c5544c462
#06 pc 0x20087c libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#07 pc 0x209398 libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#08 pc 0x803654 libart.so (BuildId: 4c9b59b74ca9272f710a71137164c349)
#09 pc 0x7c5544c462
#10 pc 0x7c5544ca86
```

Device
Brand:Samsung
Model:Galaxy S20 FE
Orientation:Unknown
RAM free: 236.22 MB
Disk free: 62.08 GB
Operating system
Version:Android 13
Orientation:Unknown
Rooted:No
Crash
Date:19 Sept 2023, 10:12:48
App version:2023.09.18-8-Google-beta (23091808)

Device
Brand:Xiaomi
Model:Redmi Note 9
Orientation:Unknown
RAM free: 80.58 MB
Disk free: 70.18 GB
Operating system
Version:Android 12
Orientation:Unknown
Rooted:No
Crash
Date:19 Sept 2023, 07:20:28
App version:2023.09.10-23-Google-beta (23091023)

Device
Brand:Oppo
Model:Realme 7
Orientation:Unknown
RAM free: 433.4 MB
Disk free: 1.92 GB
Operating system
Version:Android 12
Orientation:Unknown
Rooted:No
Crash
Date:16 Sept 2023, 22:06:30
App version:2023.09.10-23-Google-beta (23091023)

### PR DESCRIPTION
**Pull request by rtsisyk**
For all location modes other than NOT_FOLLOW location should be updated as soon as possible. Also, keep in mind that Android updates GPS data only once every second.

Add a comment why NavigationService cannot be STICKY. Remove LocationHelper::restart() from NavigationService::onDestroy() as asked by @vng.

Fixes #6091

### CODE REVIEW

**Comment by rtsisyk** [comment]
Perfect:

```
09-26 10:35:36.054  9302  9302 E AndroidRuntime: Process: app.organicmaps.debug, PID: 9302
09-26 10:35:36.054  9302  9302 E AndroidRuntime: java.lang.RuntimeException: Unable to create service app.organicmaps.routing.NavigationService: java.lang.IllegalStateExcep
tion: Application is not initialized
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4499)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)                                                                      09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7924)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-26 10:35:36.054  9302  9302 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Application is not initialized
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at app.organicmaps.routing.NavigationService.onCreate(NavigationService.java:117)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4486)
09-26 10:35:36.054  9302  9302 E AndroidRuntime:        ... 9 more
```

See instructions in https://github.com/organicmaps/organicmaps/issues/6091#issuecomment-1734988513

File: android/app/src/main/java/app/organicmaps/routing/NavigationService.java [hunk 1]
```diff
@@ -191,7 +198,11 @@ public int onStartCommand(Intent intent, int flags, int startId)
     // re-subscribe for more frequent GPS updates for navigation.
     LocationHelper.from(this).restart();
 
-    return START_STICKY;
+    // Tell the system that this service should not be restarted automatically
```
[the remark this answers is not in the document]
Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/routing/NavigationService.java:201]:
```
Constant to return from [onStartCommand(Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)): if this service's process is killed while it is started (after returning from [onStartCommand(Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int))), and there are no new start intents to deliver to it, then take the service out of the started state and don't recreate until a future explicit call to [Context.startService(Intent)](https://developer.android.com/reference/android/content/Context#startService(android.content.Intent)). The service will not receive a [onStartCommand(android.content.Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)) call with a null Intent because it will not be restarted if there are no pending Intents to deliver.
```

We use the primary app process. It doesn't make sense to restart the primary app process without properly initialized framework to start the service.

[the remark this answers is not in the document]
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/routing/NavigationService.java:201]: 1. "It does not any sense like it's done now, because framework is not initialized" sounds unclear. Does it make sense to enable sticky _and initialize framework properly_ ? What are pros and cons?
2. Does enabled background service permission change the behavior in our favor?

[the remark this answers is not in the document]
Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/routing/NavigationService.java:201]: > 1. "It does not any sense like it's done now, because framework is not initialized" sounds unclear. Does it make sense to enable sticky _and initialize framework properly_ ? What are pros and cons?
> 
>     2. Does enabled background service permission change the behavior in our favor?

> and initialize framework properly 

Oh, please not. Not in the hotfix.

**Comment by rtsisyk** [comment]
> I'd suggest replacing these lines
> 
> https://github.com/organicmaps/organicmaps/blob/a18f40343c6a815a5117f2319d1e861b725bf88a/android/app/src/main/java/app/organicmaps/routing/NavigationService.java#L152-L153
> 
> with
> 
> ```java
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N)
>     stopForeground(STOP_FOREGROUND_REMOVE);
> else
>     stopForeground(true);
> ```
> 
> Or just
> 
> ```java
> stopForeground(true);
> ```

Is it possible that Android calls onDestroy() before stopping the service?

File: android/app/src/main/java/app/organicmaps/routing/NavigationService.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/routing/NavigationService.java]: Added comments.

**Comment by rtsisyk** [comment]
> > I'd suggest replacing these lines
> > https://github.com/organicmaps/organicmaps/blob/a18f40343c6a815a5117f2319d1e861b725bf88a/android/app/src/main/java/app/organicmaps/routing/NavigationService.java#L152-L153
> > 
> > with
> > ```java
> > if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N)
> >     stopForeground(STOP_FOREGROUND_REMOVE);
> > else
> >     stopForeground(true);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or just
> > ```java
> > stopForeground(true);
> > ```
> 
> Is it possible that Android calls onDestroy() before stopping the service?

These calls are not needed at all. Notification is cancelled automatically.

**Comment by rtsisyk** [comment]
Reworked this PR significatlly. Please review.

File: android/app/src/main/java/app/organicmaps/location/LocationHelper.java [hunk 2]
```diff
@@ -232,71 +231,44 @@ public void removeListener(@NonNull LocationListener listener)
...
-        mInterval = INTERVAL_FOLLOW_MS;
-        break;
+        return INTERVAL_FOLLOW_MS;
       case LocationState.FOLLOW_AND_ROTATE:
-        mInterval = INTERVAL_FOLLOW_AND_ROTATE_MS;
-        break;
+        return INTERVAL_FOLLOW_AND_ROTATE_MS;
       case LocationState.NOT_FOLLOW:
       case LocationState.NOT_FOLLOW_NO_POSITION:
       case LocationState.PENDING_POSITION:
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/location/LocationHelper.java:248]: Won't user receive location later when the delay is set to 3 seconds in case when location was not available?

Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/location/LocationHelper.java:248]: This is not an artificial delay, like sleep(3). We subscribe to location services with a given refresh interval. Implementation can take these 3 seconds into consideration to optimize battery usage.

Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/location/LocationHelper.java:248]: My question is about this situation:
1. A user wants to see his direction ASAP and presses the location button.
2. The system can return the location ASAP, but instead, it returns it ASAP + 3 seconds (or ASAP + 2 seconds).

Is it possible? If yes, then it's a bad UX because a user needs to wait for more time than in case of a 0 or 1-second delay.

Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/location/LocationHelper.java:248]: When the user presses the location button, the mode switches between FOLLOW and FOLLOW_AND_ROTATE modes, both of which use the fastest available refresh interval in this patch. NOT_FOLLOW mode is enabled then the user scrolls the map. In this case, precise location is not really important because the arrow is not in the center of the screen.

Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/location/LocationHelper.java:248]: For `PENDING_POSITION`  this PR changes `mInterval = INTERVAL_NOT_FOLLOW_MS;` to `return INTERVAL_NOT_FOLLOW_MS;`. That is it. What problem do you see here?

Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/location/LocationHelper.java:248]: INTERVAL_NOT_FOLLOW_MS = 3000;

I'm trying to understand if with interval = 0; the initial position will be reported to the user faster by 2 or 3 seconds or not.

In short: why not change interval for PENDING_POSITION to zero?

File: android/app/src/main/java/app/organicmaps/routing/NavigationService.java [hunk 3]
```diff
@@ -207,11 +220,13 @@ public int onStartCommand(@NonNull Intent intent, int flags, int startId)
...
-    // requested AFTER starting the foreground service. Restarting the location is also necessary to
-    // re-subscribe for more frequent GPS updates for navigation.
-    LocationHelper.from(this).restart();
+    // Subscribe to location updates. This call is idempotent.
+    LocationHelper.from(this).addListener(this);
+
+    // Restart the location with more frequent refresh interval for navigation.
+    LocationHelper.from(this).restartWithNewMode();
 
+    // Please make this service START_STICKY after fixing the issues at the beginning of the function.
```
Comment (vng) [inline android/app/src/main/java/app/organicmaps/routing/NavigationService.java:229]: nit:
final LocationHelper lh = LocationHelper.from(this);
lh.addListener(this);
lh.restartWithNewMode();

Put todo here?

**Review by vng — APPROVED** [review]

File: android/app/src/main/java/app/organicmaps/location/LocationHelper.java (hunk 2 above)
Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/location/LocationHelper.java:248]: > In short: why not change the interval for PENDING_POSITION to zero?

It is unclear to me why it was 3 seconds. I can change it to zero.

File: android/app/src/main/java/app/organicmaps/routing/NavigationService.java (hunk 3 above)
Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/routing/NavigationService.java:232]: Filed a ticket https://github.com/organicmaps/organicmaps/issues/6233 and added a link to the code.

File: android/app/src/main/java/app/organicmaps/location/LocationHelper.java (hunk 2 above)
Comment (rtsisyk) [reply android/app/src/main/java/app/organicmaps/location/LocationHelper.java]: I updated the code to have 0 refresh interval for PENDING_POSITION. Practical tests show that the first location is returned as soon as the device has it. In case of fused location, it almost instant. GPS can take a while to start up.
