### PR TITLE
[android] Fix inconsistent ChoosePositionMode

### LINKED ISSUE #6575: [android] Crash with point chooser on device rotation
I'm able to reproduce on latest beta and debug version from master :)
- Open bottom menu
- Add new place on map
- Rotate device-> crash

mPointChooserMode is reset when we rotate the device?

_Originally posted by @Jean-BaptisteC in https://github.com/organicmaps/organicmaps/issues/6437#issuecomment-1809135987_

### PR DESCRIPTION
**Pull request by rtsisyk**
Keep this state only on C++ side without duplicating in Java.

**Test cases:**

1. Open the Editor and choose a point and try to rotate the screen.
2. https://github.com/organicmaps/api-android/tree/master/sample-pick-point - click "Pick Point" and try to rotate the screen.

See #3945
See #6437
Closes #6575

### CODE REVIEW

**Review by pastk — APPROVED** [review]
It has fixed the crash on my android 9 device!

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 1]
```diff
@@ -1037,15 +1024,10 @@ protected void onResume()
...
     refreshSearchToolbar();
     setFullscreen(isFullscreen());
-    if (Framework.nativeIsInChoosePositionMode())
+    if (Framework.nativeGetChoosePositionMode() != Framework.ChoosePositionMode.NONE)
     {
       UiUtils.show(mPointChooser);
       mMapButtonsViewModel.setButtonsHidden(true);
-      if (mPointChooserMode == PointChooserMode.NONE)
-      {
-        // BUG: https://github.com/organicmaps/organicmaps/issues/3945
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java:1046]: Rotating the device should be the documented test case for everything, including API calls.
