### PR TITLE
[ios] Fix the layout of the toast message

### LINKED ISSUE #2556: "Zoom in to explore isolines" label covers the bottom bar
on iOS the label that says "Zoom in to explore isolines" is covering the bottom bar, should be moved upwards

File 14-05-22, 14 04 42

### LINKED ISSUE #6726: [UI] Annoying bug
Little but super annoying. Can you please make it not overlap buttons?

IMG_1310

### PR DESCRIPTION
**Pull request by kirylkaveryn**
Closes #6726 
Closes #2556

In this PR:
1. the toast layout changed from `visualFormat` to `anchors` constraints (because using string literals for layout is bad practice, hard to read and debug)
2. adjust toast position (63pt constraint is used because the tabbar buttons height is 48 so spacing will be 15 on devices with rounded edges and 5 on SE-like devices (that have additional 10pt spacing from bottom))

image

### CODE REVIEW

**Comment by vng** [comment]
Also closes https://github.com/organicmaps/organicmaps/issues/2556, right?

File: iphone/Maps/Classes/CustomAlert/Toast/Toast.swift [hunk 1]
```diff
@@ -47,26 +44,29 @@ final class Toast: NSObject {
...
+    let trailingConstraint = blurView.trailingAnchor.constraint(lessThanOrEqualTo: view.trailingAnchor, constant: -16)
+    
+    NSLayoutConstraint.activate([
+      leadingConstraint,
+      trailingConstraint
+    ])
+    
+    let topConstraint: NSLayoutConstraint
+    if alignment == .bottom {
+      topConstraint = blurView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -63)
```
Comment (biodranik) [inline iphone/Maps/Classes/CustomAlert/Toast/Toast.swift:61]: nit: it would be great to have some comments about how these constants were calculated in the future. If comments are short, they can be converted to a named constant.

**Review by biodranik — APPROVED** [review]
Thank you!
