### PR TITLE
Fix crash on Android 5 and 6 when PP type field (subtitle) has unicode > 0xFFFF

### LINKED ISSUE #9624: Android 5 crash on complex Place Page.
Crash when selecting some POI with a complex PP.
Moto G 1st Gen (XT1032) running on Android 5.1

```
11-08 23:28:22.727 E/AndroidRuntime(21900): FATAL EXCEPTION: main
11-08 23:28:22.727 E/AndroidRuntime(21900): Process: app.organicmaps, PID: 21900
11-08 23:28:22.727 E/AndroidRuntime(21900): android.view.InflateException: Binary XML file line #25: Error inflating class TextView
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at app.organicmaps.widget.placepage.sections.PlacePhoneAdapter.onCreateViewHolder(PlacePhoneAdapter.java:47)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at app.organicmaps.widget.placepage.sections.PlacePhoneAdapter.onCreateViewHolder(PlacePhoneAdapter.java:19)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7788)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4022)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1941)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:650)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at com.google.android.material.bottomsheet.BottomSheetBehavior.onMeasureChild(BottomSheetBehavior.java:515)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.vie
```

### PR DESCRIPTION
**Pull request by biodranik**
Fixes #9624 thanks to @batterydotac

Now it doesn't crash, but WiFi emoji is missing in the font, so it can be fixed separately. Note that other emoji (atm, toilet, accessibility) are displayed properly.

What I don't understand is: why the title without this conversion works, but only subtitle where types are displayed crashes? CC @hb0nd 

grafik

CC @hemanggs

### CODE REVIEW

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp [hunk 1]
```diff
@@ -28,6 +28,21 @@ jclass g_elevationInfoClazz;
...
+  char value[92] = { 0 };
+  if (__system_property_get("ro.build.version.sdk", value) < 1)
+    return false;
+  const int apiLevel = atoi(value);
+  if (apiLevel > 0 && apiLevel < 24)
+    return true;
+  return false;
+}
+
+static bool const g_isAndroidLowerThan7 = IsAndroidLowerThan7();
```
Comment (vng) [inline android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:44]:
```
bool IsAndroidLowerThan7()
{
  static bool res = IsAndroidLowerThan7Impl();
  return res;
}
```

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp [hunk 2]
```diff
@@ -28,6 +28,21 @@ jclass g_elevationInfoClazz;
 
 extern "C"
 {
+int __system_property_get(char const * name, char * value);
+
+static bool IsAndroidLowerThan7()
+{
+  char value[92] = { 0 };
+  if (__system_property_get("ro.build.version.sdk", value) < 1)
```
Comment (vng) [inline android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:36]: Hm, Google says that ```__system_property_get``` is removed on Android NDK API > 21 ..

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp (hunk 1 above)
Comment (biodranik) [reply android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:44]: Static vars in functions have way more overhead for thread safety than using a global variable. That is one of reasons why we use "normal" global variables in many places :)

```C++
#include <cstdlib>

static bool IsSet() {
  static const bool res = std::rand() < 42;
  return res;
}

int main(int argc, char**) {
  return IsSet();
}
```
produces
```
IsSet():
        push    rbp
        mov     rbp, rsp
        movzx   eax, BYTE PTR guard variable for IsSet()::res[rip]
        test    al, al
        sete    al
        test    al, al
        je      .L2
        mov     edi, OFFSET FLAT:guard variable for IsSet()::res
        call    __cxa_guard_acquire
        test    eax, eax
        setne   al
        test    al, al
        je      .L2
        call    rand
        cmp     eax, 41
        setle   al
        mov     BYTE PTR IsSet()::res[rip], al
        mov     edi, OFFSET FLAT:guard variable for IsSet()::res
        call    __cxa_guard_release
.L2:
        movzx   eax, BYTE PTR IsSet()::res[rip]
        pop     rbp
        ret
main:
        push    rbp
        mov     rbp, rsp
        sub     rsp, 16
        mov     DWORD PTR [rbp-4], edi
        mov     QWORD PTR [rbp-16], rsi
        call    IsSet()
        movzx   eax, al
        leave
        ret
```


while

```
#include <cstdlib>

static const bool res = std::rand() < 42;

int main(int argc, char**) {
  return res;
}
```

produces

```
main:
        movzx   eax, BYTE PTR res[rip]
        ret
_GLOBAL__sub_I_main:
        sub     rsp, 8
        call    rand
        cmp     eax, 41
        setle   BYTE PTR res[rip]
        add     rsp, 8
        ret
```

Comment (biodranik) [reply android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:44]: A similar code is generated for arm64 (47 asm lines vs 17): https://godbolt.org/z/cKrM3Ga9z

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp (hunk 2 above)
Comment (biodranik) [reply android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:36]: Nope, it is [there](https://android.googlesource.com/platform/bionic/+/master/libc/include/sys/system_properties.h), and is actively used in NDK:

```
$ cat /Users/alex/Developer/android-sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/get_device_api_level_inlines.h
#pragma once

#if defined(__BIONIC_GET_DEVICE_API_LEVEL_INLINE)

#include <sys/cdefs.h>

__BEGIN_DECLS

// Avoid circular dependencies since this is exposed from <sys/cdefs.h>.
int __system_property_get(const char* _Nonnull __name, char*  _Nonnull __value);
int atoi(const char* _Nonnull __s) __attribute_pure__;

__BIONIC_GET_DEVICE_API_LEVEL_INLINE int android_get_device_api_level() {
  char value[92] = { 0 };
  if (__system_property_get("ro.build.version.sdk", value) < 1) return -1;
  int api_level = atoi(value);
  return (api_level > 0) ? api_level : -1;
}

__END_DECLS

#endif  // __BIONIC_GET_DEVICE_API_LEVEL_INLINE
```

Comment (biodranik) [reply android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:36]: And `android_get_device_api_level()` is available only from API 24:
https://developer.android.com/ndk/reference/group/apilevels#group__apilevels_1ga79b134cadc2dfed84268e67fd9e2dfd6

**Comment by biodranik** [comment]
@batterydotac can you please also try to download fdroid or web debug builds from this link (at the bottom), unzip, install and see if they work on your devices? https://github.com/organicmaps/organicmaps/actions/runs/15219869465

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp (hunk 1 above)
Comment (vng) [reply android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:44]: - Actually, my comment is about you added a useless var and didn't use it g_isAndroidLowerThan7
- Global vars are bad for the app startup
- Your example with a simple return is not honest :) Especially, when the logic becomes more complex with several global vars initialization and order.

**Comment by batterydotac** [comment]
> What build error do you see? Are you building the code with `cd android; ./gradlew runFdroidDebug -Parm32` ? This command should build and run the debug version on the attached Android device.

Well at first I was referring to the other code at that link - I had included the necessary files and everything just got junked up and I couldn't debug it and I therefore wrote what I provided out of impatience and frustration.

Your patch compiles and seems to work fine on Android 5.0.2.  I tried both putting in the code myself, via Android Studio complied to fdroidRelease which is how I like to do it (weak tablet USB port...), as well as your fdroidDebug link.  I don't see any problems with Charlie's Cafe and it looks just like my other screenshot.  I also checked numerous local places which were initially problematic.  Would you mind trying my function on your emulator/device just out of curiosity?  Those null-squares are concerning at the beginning of the title and almost seem to indicate memory corruption.  We need to be careful assuming that they're simply missing fonts, as they aren't always.  I don't have an easy way to test Android 6 without further debugging (my emulator on API 36 seemed to crash).

Not that it's important nor relevant now, but using `./gradlew runFdroidDebug -Parm32` doesn't work, and gives:

```
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to calculate the value of task ':app:compileGoogleDebugJavaWithJavac' property 'javaCompiler'.
   > Toolchain installation '/usr/lib/jvm/java-21-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]
```

**Comment by biodranik** [comment]
> Those null-squares are concerning at the beginning of the title

It's me inserting icons of wifi into the bookmark's title. Default emulator image doesn't render this icon.

> using ./gradlew runFdroidDebug -Parm32 doesn't work, and gives

You need to install JDK in the system, and set JAVA_HOME to it. Usually Android Studio already contains one, so you can fix it with something like
```
export JAVA_HOME=/Applications/Android Studio.app/Contents/jbr/Contents/Home
```

> Is there any particular reason why the fdroidDebug build won't install

You need to uninstall your fdroidDebug build first, as it is signed with a different key.

@vng PTAL

**Comment by batterydotac** [comment]
> It's me inserting icons of wifi into the bookmark's title. Default emulator image doesn't render this icon.

Oh I see.  Makes sense.

> You need to install JDK in the system, and set JAVA_HOME to it. Usually Android Studio already contains one, so you can fix it with something like
> 
> ```
> export JAVA_HOME=/Applications/Android Studio.app/Contents/jbr/Contents/Home
> ```

Alright, thanks.

> > Is there any particular reason why the fdroidDebug build won't install
> 
> You need to uninstall your fdroidDebug build first, as it is signed with a different key.

Doesn't help and I already tried - it gives a different message about it conflicting, anyhow.  I removed all instances of OM, even the fdroidRelease one, and it still says this.

**Comment by batterydotac** [comment]
It's probably just an ABI mismatch as it says "INSTALL_FAILED_NO_MATCHING_ABIS" over logcat.  So hopefully fine to ignore as long as it's not needed for testing.  Again, I was using "arm64-v8a" which worked well.  (I also tried downloading another copy to rule out file corruption, and same result.)

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp [hunk 3]
```diff
@@ -154,6 +169,24 @@ jstring ToJavaString(JNIEnv * env, char const * s)
...
 
+jstring ToJavaStringWithSupplementalCharsFix(JNIEnv * env, std::string const & s)
+{
+  // Android 5 and 6 do not support unicode characters greater than 0xFFFF encoded in UTF-8.
+  if (g_isAndroidLowerThan7)
+  {
+    // Detect 4-byte sequence start marker to avoid unnecessary allocation + copy.
+    for (const auto c : s)
+    {
+      if (0b11110000 == (c & 0b11111000))
```
Comment (zloidemon) [inline android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:180]: Defining 0b11110000 as a named constant elsewhere, rather than leaving it exposed here. This not only lends clarity but also aligns with the elegance of abstraction. Don’t you agree?

**Comment by biodranik** [comment]
INSTALL_FAILED_NO_MATCHING_ABIS means that you need to build it for arm64 instead if arm32, or build for all abis (default if -P is not specified for gradle).

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp [hunk 4]
```diff
@@ -28,6 +28,21 @@ jclass g_elevationInfoClazz;
...
 {
+int __system_property_get(char const * name, char * value);
+
+static bool IsAndroidLowerThan7()
+{
+  char value[92] = { 0 };
+  if (__system_property_get("ro.build.version.sdk", value) < 1)
+    return false;
+  const int apiLevel = atoi(value);
+  if (apiLevel > 0 && apiLevel < 24)
```
Comment (zloidemon) [inline android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:39]: Upon careful consideration, the current version check appears somewhat ambiguous. Might You suggest employing other constructs for greater clarity moving forward?

File: android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp (hunk 3 above)
Comment (zloidemon) [reply android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp:180]: Might I request clarification? While these appear to be foundational programming principles, their clarification could unveil deeper insights into the your logic.

**Comment by batterydotac** [comment]
> INSTALL_FAILED_NO_MATCHING_ABIS means that you need to build it for arm64 instead if arm32, or build for all abis (default if -P is not specified for gradle).

I'm in fact seeing the following lines in the "Workflow file" in the "Android Check" section for those artifacts:

```
          - flavor: WebDebug
            arch: arm64
          - flavor: FdroidDebug
            arch: arm32
```

So this is probably why I wasn't able to install that test package.  I didn't figure I should use "WebDebug" instead?

**Comment by biodranik** [comment]
@batterydotac right! Please let me know if it works for you )

**Comment by batterydotac** [comment]
> @batterydotac right! Please let me know if it works for you )

Okay, that version installs fine.  I thought it was something completely different and would've expected an "fDroidDebug" version similar to what Android Studio makes that works on both architectures.  I now see the "Web" flavor described in "INSTALL.md".

Anyway, I've tested it with Charlie's Cafe and all of my usual spots, plus some more, and everything seems to render/run properly.  So I don't see any reason to hold off any further and the changes should all be a go.
