### PR TITLE
[android] Fix the title after editing the name of a boomark.

### LINKED ISSUE #10005: App Bar Title Doesn't Update Immediately When Switching Bookmark Lists
⚠ **Have you searched for similar, already existing issues?**  
Yes, no similar issues were found.

**Describe the issue**  
When we open the **"Bookmarks and Tracks"** page in the app, it displays a list of bookmarks.  
For example, I have a list named **"List 1"**. When I click on it, the app navigates to another page showing all the bookmarks of **"List 1"**.  

However, if I change the list (e.g., from **"List 1"** to **"List 2"**), the change is **not reflected in the App Bar title**. Instead:  
1. The updated name (**"List 2"**) is displayed in the **Notes** section.  
2. When I navigate back to the **"Bookmarks and Tracks"** page, the updated name is reflected.  
3. Upon navigating back to the **"List 2"** page, the App Bar title now correctly shows the updated name.

**Steps to reproduce**  
1. Open the **"Bookmarks and Tracks"** page in the app.  
2. Select a list (e.g., **"List 1"**) and navigate to its details page.  
3. Switch to another list (e.g., **"List 2"**).  
4. Observe the App Bar title—it still shows the old list name (**"List 1"**).  
5. Navigate back to the **"Bookmarks and Tracks"** page and then return to the list page.  
6. The App Bar title now reflects the updated list name (**"List 2"**).  

**Expected behaviour**  
The App Bar title should update immediately when the list is changed (e.g., from **"List 1"** to **"List 2"**) without requiring navigation back and forth.

**System information**  
- Operating system and its version: Android 14  
- Organic Maps version: 2024.11.27-12-Google  
- Device Model: Motorola G64 5G  

**Additional context**  
Below is a video demonstrating the issue for clarity.  

https://github.com/user-attachments/assets/daf01340-1625-4817-9710-865b7f365b98

**Screenshots**  
If applicable, please add screenshots or screen recordings to illustrate the problem.

2555c232-bed3-4479-859d-e00ebd6fcd6c
4d5ab787-611f-4cd1-ab02-b83885e2fa2f
d86397f6-b2bc-43c9-8be5-74967e921837

a19e02a5-249f-46a2-8d19-1f99c23250da

4d6f27c2-a0bd-48cc-bbfe-4116bdb76f7d

d0a873d1-d4a8-49d4-a05d-67e38a5afec2

### PR DESCRIPTION
**Pull request by zeac**
CategoryDataSource is connected to that one.

Resolves #10005

### CODE REVIEW

**Review by vng — APPROVED** [review]

File: android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java [hunk 1]
```diff
@@ -810,7 +810,7 @@ public void onPreparedFileForSharing(@NonNull BookmarkSharingResult result)
   public void onActivityResult(int requestCode, int resultCode, Intent data)
   {
     super.onActivityResult(requestCode, resultCode, data);
-    getAdapter().notifyDataSetChanged();
+    getBookmarkListAdapter().notifyDataSetChanged();
```
Comment (rtsisyk) [inline android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java:813]: This looks misleader, but I can see that the same approach is used across the code.

**Review by rtsisyk — APPROVED** [review]

**Comment by rtsisyk** [comment]
@DeshDeepakKant @map-per could you please test the PR quickly?

**Comment by map-per** [comment]
> could you please test the PR quickly?

Works as intended on Android 14

**Comment by DeshDeepakKant** [comment]
@rtsisyk Sorry for being late! I tested the PR, and it is working fine.

File: android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java (hunk 1 above)
Comment (zeac) [reply android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java:813]: Yeah, I didn't want to change the pattern to fix the bug.
