### PR TITLE
[android] Add missing PendingIntent.FLAG_IMMUTABLE flag

### LINKED ISSUE #2372: Android 12 intent mutability crash
There are many crashes in the play console like this one. Here are more details about it: https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a

```
exception.class.missing._Unknown_: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at android.app.PendingIntent.checkFlags (PendingIntent.java:375)
  at android.app.PendingIntent.getActivityAsUser (PendingIntent.java:458)
  at android.app.PendingIntent.getActivity (PendingIntent.java:444)
  at android.app.PendingIntent.getActivity (PendingIntent.java:408)
  at com.mapswithme.maps.background.Notifier.notifyDownloadFailed (Notifier.java:53)
  at com.mapswithme.maps.MwmApplication$StorageCallbackImpl.onStatusChanged (MwmApplication.java:328)
  at com.mapswithme.maps.downloader.ChunkTask.nativeOnFinish (Native Method)
  at com.mapswithme.maps.downloader.ChunkTask.onPostExecute (ChunkTask.java:80)
  at com.mapswithme.maps.downloader.ChunkTask.onPostExecute (ChunkTask.java:24)
  at android.os.AsyncTask.finish (AsyncTask.java:771)
  at android.os.AsyncTask.access$900 (AsyncTask.java:199)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:788)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:334)
  at android.app.ActivityThread.main (ActivityThread.java:8333)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:582)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1065)
```

### PR DESCRIPTION
**Pull request by rtsisyk**
Closes #2372

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

### CODE REVIEW

File: android/src/com/mapswithme/maps/background/Notifier.java [hunk 1]
```diff
@@ -50,8 +51,9 @@ public void notifyDownloadFailed(@Nullable String id, @Nullable String name)
 
     Intent intent = MwmActivity.createShowMapIntent(mContext, id)
                                .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
-    PendingIntent pi = PendingIntent.getActivity(mContext, 0, intent,
-                                                 PendingIntent.FLAG_UPDATE_CURRENT);
+    int flags = (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
+        ? PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE : PendingIntent.FLAG_UPDATE_CURRENT;
+    PendingIntent pi = PendingIntent.getActivity(mContext, 0, intent, flag);
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/background/Notifier.java:56]:
```suggestion
    final int flags = (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
        ? PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE : PendingIntent.FLAG_UPDATE_CURRENT;
    PendingIntent pi = PendingIntent.getActivity(mContext, 0, intent, flags);
```

**Review by biodranik — APPROVED** [review]
