### PR TITLE
Fix/add vehicle mode hatching fills 

### LINKED ISSUE #6311: [android-auto] Crash in `apply_feature_functors`
**Describe the issue**
Some asserts in `apply_feature_functors` fail in AA.

**Steps to reproduce**
1. Build route
2. Start navigation
3. Crash

First failed assert:
https://github.com/organicmaps/organicmaps/blob/458cdfa6cffb373f01ca1af7539e23d5d6117761/drape_frontend/apply_feature_functors.cpp#L409

Log:
```
2023-10-14 10:14:36.227 13147-13243 OMcore                  app.organicmaps.debug                E  drape_frontend/apply_feature_functors.cpp:409 PriorityToDepth(): CHECK(areaDepth >= drule::kBaseDepthBgBySize) -11001 -11000 { MwmId [Poland_Lesser Poland Voivodeship, 230920], 19058 }
2023-10-14 10:14:36.228 13147-13243 libc                    app.organicmaps.debug                A  organicmaps/drape_frontend/apply_feature_functors.cpp:409: double df::BaseApplyFeature::PriorityToDepth(int, drule::rule_type_t, double) const: assertion "false" failed
2023-10-14 10:14:36.228 13147-13243 libc                    app.organicmaps.debug                A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13243 (Thread-22), pid 13147 (ganicmaps.debug)
2023-10-14 10:14:36.411 13248-13248 DEBUG                   pid-13248                            A  pid: 13147, tid: 13243, name: Thread-22  >>> app.organicmaps.debug <<<
2023-10-14 10:14:36.452 13248-13248 DEBUG                   pid-13248                            A        #02 pc 0000000002950a68  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::BaseApplyFeature::PriorityToDepth(int, drule::rule_type_t, double) const+1072) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.452 13248-13248 DEBUG                   pid-13248                            A        #03 pc 0000000002953f00  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::ApplyAreaFeature::ProcessRule(AreaRuleProto const&, double, bool)+116) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.452 13248-13248 DEBUG                   pid-13248                            A        #04 pc 0000000002953dd4  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::ApplyAreaFeature::ProcessAreaRules(AreaRuleProto const*, AreaRuleProto const*)+656) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.452 13248-13248 DEBUG                   pid-13248                            A        #05 pc 00000000027be7c0  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::RuleDrawer::ProcessAreaAndPointStyle(FeatureType&, df::Stylist const&, std::__ndk1::function<void (std::__ndk1::unique_ptr<df::MapShape, std::__ndk1::default_delete<df::MapShape> >&&)> const&)+1180) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.452 13248-13248 DEBUG                   pid-13248                            A        #06 pc 00000000027c12d4  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::RuleDrawer::operator()(FeatureType&)+1572) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.452 13248-13248 DEBUG                   pid-13248                            A        #07 pc 00000000028e6520  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #08 pc 00000000028e64f4  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (std::__ndk1::__invoke_of<df::RuleDrawer&, FeatureType&>::type std::__ndk1::reference_wrapper<df::RuleDrawer>::operator()[abi:v170000]<FeatureType&>(FeatureType&) const+32) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #09 pc 00000000028e6474  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #10 pc 00000000028e640c  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #11 pc 00000000028e63a4  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (std::__ndk1::__bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&>, __is_valid_bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&> >::value>::type std::__ndk1::__bind<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>::operator()[abi:v170000]<FeatureType&>(FeatureType&)+84) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #12 pc 00000000028e6340  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #13 pc 00000000028e6314  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (void std::__ndk1::__invoke_void_return_wrapper<void, true>::__call<std::__ndk1::__bind<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&>(std::__ndk1::__bind<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&)+28) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #14 pc 00000000028e62e8  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (std::__ndk1::enable_if<(is_convertible<std::__ndk1::__bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&>, __is_valid_bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&> >::value>::type, void>::value) || (std::__ndk1::integral_constant<bool, true>::value), void>::type std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>::operator()[abi:v170000]<FeatureType&>(FeatureType&)+28) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #15 pc 00000000028e62bc  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #16 pc 00000000028e626c  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (void std::__ndk1::__invoke_void_return_wrapper<void, true>::__call<std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&>(std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&)+28) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #17 pc 00000000028e6240  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #18 pc 00000000028e52e0  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (std::__ndk1::__function::__func<std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>, std::__ndk1::allocator<std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&> >, void (FeatureType&)>::operator()(FeatureType&)+32) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #19 pc 0000000002e9ce50  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #20 pc 0000000002dbd638  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void (FeatureType&)>::operator()(FeatureType&) const+28) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.453 13248-13248 DEBUG                   pid-13248                            A        #21 pc 0000000002dbd48c  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (DataSource::ReadFeatures(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+1512) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #22 pc 00000000021c2964  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (void FeaturesFetcher::ReadFeatures<std::__ndk1::function<void (FeatureType&)> const>(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+40) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #23 pc 00000000023b3588  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #24 pc 00000000023b354c  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #25 pc 00000000023b34f4  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #26 pc 00000000023b34c0  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #27 pc 00000000023b2564  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #28 pc 000000000249cd3c  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #29 pc 00000000022045b0  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void (std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&)>::operator()(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+36) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #30 pc 00000000029cd7c8  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::MapDataProvider::ReadFeatures(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+40) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #31 pc 00000000027a9918  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::TileInfo::ReadFeatures(df::MapDataProvider const&)+596) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #32 pc 00000000027a95f8  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (df::ReadMWMTask::Do()+384) (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #33 pc 0000000003788d10  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #34 pc 00000000037770d0  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #35 pc 000000000379e02c  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #36 pc 000000000379dfd8  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
2023-10-14 10:14:36.454 13248-13248 DEBUG                   pid-13248                            A        #37 pc 000000000379dce0  /data/app/~~3qXY2eTfaH_yLyNUf30oJA==/app.organicmaps.debug-v2oqv8a2z2DBPu05oBLpdQ==/lib/arm64/liborganicmaps.so (BuildId: fa4e7b11150b78e80cc933082c07450d74459a65)
```

Second failed assert:
https://github.com/organicmaps/organicmaps/blob/458cdfa6cffb373f01ca1af7539e23d5d6117761/drape_frontend/apply_feature_functors.cpp#L733

Log:
```
2023-10-14 10:17:19.129 14045-14140 OMcore                  app.organicmaps.debug                E  drape_frontend/apply_feature_functors.cpp:733 ProcessAreaRules(): CHECK(hatchingRule->priority() >= drule::kBasePriorityFg) -1860 0 
2023-10-14 10:17:19.129 14045-14140 libc                    app.organicmaps.debug                A  organicmaps/drape_frontend/apply_feature_functors.cpp:733: void df::ApplyAreaFeature::ProcessAreaRules(const AreaRuleProto *, const AreaRuleProto *): assertion "false" failed
2023-10-14 10:17:19.129 14045-14140 libc                    app.organicmaps.debug                A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14140 (Thread-21), pid 14045 (ganicmaps.debug)
2023-10-14 10:17:19.219 14144-14144 DEBUG                   pid-14144                            A  pid: 14045, tid: 14140, name: Thread-21  >>> app.organicmaps.debug <<<
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #02 pc 0000000002953d68  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (df::ApplyAreaFeature::ProcessAreaRules(AreaRuleProto const*, AreaRuleProto const*)+908) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #03 pc 00000000027be7d0  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (df::RuleDrawer::ProcessAreaAndPointStyle(FeatureType&, df::Stylist const&, std::__ndk1::function<void (std::__ndk1::unique_ptr<df::MapShape, std::__ndk1::default_delete<df::MapShape> >&&)> const&)+1180) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #04 pc 00000000027c12e4  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (df::RuleDrawer::operator()(FeatureType&)+1572) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #05 pc 00000000028e6530  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #06 pc 00000000028e6504  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (std::__ndk1::__invoke_of<df::RuleDrawer&, FeatureType&>::type std::__ndk1::reference_wrapper<df::RuleDrawer>::operator()[abi:v170000]<FeatureType&>(FeatureType&) const+32) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #07 pc 00000000028e6484  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #08 pc 00000000028e641c  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #09 pc 00000000028e63b4  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (std::__ndk1::__bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&>, __is_valid_bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&> >::value>::type std::__ndk1::__bind<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>::operator()[abi:v170000]<FeatureType&>(FeatureType&)+84) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #10 pc 00000000028e6350  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #11 pc 00000000028e6324  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (void std::__ndk1::__invoke_void_return_wrapper<void, true>::__call<std::__ndk1::__bind<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&>(std::__ndk1::__bind<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&)+28) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #12 pc 00000000028e62f8  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (std::__ndk1::enable_if<(is_convertible<std::__ndk1::__bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&>, __is_valid_bind_return<std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::tuple<std::__ndk1::placeholders::__ph<1> >, std::__ndk1::tuple<FeatureType&> >::value>::type, void>::value) || (std::__ndk1::integral_constant<bool, true>::value), void>::type std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>::operator()[abi:v170000]<FeatureType&>(FeatureType&)+28) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #13 pc 00000000028e62cc  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #14 pc 00000000028e627c  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (void std::__ndk1::__invoke_void_return_wrapper<void, true>::__call<std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&>(std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>&, FeatureType&)+28) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #15 pc 00000000028e6250  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #16 pc 00000000028e52f0  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (std::__ndk1::__function::__func<std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&>, std::__ndk1::allocator<std::__ndk1::__bind_r<void, std::__ndk1::reference_wrapper<df::RuleDrawer>, std::__ndk1::placeholders::__ph<1> const&> >, void (FeatureType&)>::operator()(FeatureType&)+32) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #17 pc 0000000002e9ce50  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #18 pc 0000000002dbd638  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void (FeatureType&)>::operator()(FeatureType&) const+28) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #19 pc 0000000002dbd48c  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (DataSource::ReadFeatures(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+1512) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #20 pc 00000000021c2974  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (void FeaturesFetcher::ReadFeatures<std::__ndk1::function<void (FeatureType&)> const>(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+40) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #21 pc 00000000023b3598  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #22 pc 00000000023b355c  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #23 pc 00000000023b3504  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #24 pc 00000000023b34d0  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #25 pc 00000000023b2574  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #26 pc 000000000249cd4c  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #27 pc 00000000022045c0  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void (std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&)>::operator()(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+36) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #28 pc 00000000029cd7c8  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (df::MapDataProvider::ReadFeatures(std::__ndk1::function<void (FeatureType&)> const&, std::__ndk1::vector<FeatureID, std::__ndk1::allocator<FeatureID> > const&) const+40) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #29 pc 00000000027a9928  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (df::TileInfo::ReadFeatures(df::MapDataProvider const&)+596) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #30 pc 00000000027a9608  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (df::ReadMWMTask::Do()+384) (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #31 pc 0000000003788d10  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #32 pc 00000000037770d0  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #33 pc 000000000379e02c  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #34 pc 000000000379dfd8  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
2023-10-14 10:17:19.242 14144-14144 DEBUG                   pid-14144                            A        #35 pc 000000000379dce0  /data/app/~~LWPczWu_rPQOT_ngM87Ksg==/app.organicmaps.debug-yzR-7Plq7as9zWzMMJflvQ==/lib/arm64/liborganicmaps.so (BuildId: 6be9182c0bc84a4955965053a2a860cfbb95de9b)
```

### PR DESCRIPTION
**Pull request by pastk**
veh-hatching

Fixes #6311

### CODE REVIEW

**Review by vng — APPROVED** [review]

File: drape_frontend/apply_feature_functors.cpp [hunk 1]
```diff
@@ -403,10 +403,10 @@ double BaseApplyFeature::PriorityToDepth(int priority, drule::rule_type_t ruleTy
   {
     if (depth < drule::kBasePriorityBgTop)
     {
-      ASSERT(ruleType == drule::area, (m_f.GetID()));
-      ASSERT_GREATER_OR_EQUAL(depth, drule::kBasePriorityBgBySize, (m_f.GetID()));
+      ASSERT(ruleType == drule::area, (m_f.DebugString()));
+      ASSERT_GREATER_OR_EQUAL(depth, drule::kBasePriorityBgBySize, (m_f.DebugString()));
```
Comment (biodranik) [inline drape_frontend/apply_feature_functors.cpp:407]: Do you really need to explicitly specify `.DebugString()`? Won't it work with just `m_f`?

File: indexer/feature.hpp [hunk 2]
```diff
@@ -142,7 +142,7 @@ class FeatureType
   }
   //@}
 
-  std::string DebugString(int scale, bool includeKeyPoint = true);
+  std::string DebugString(int scale = FeatureType::BEST_GEOMETRY, bool includeKeyPoint = true);
```
Comment (biodranik) [inline indexer/feature.hpp:145]: Is this default parameter really necessary? Isn't it clearer with the explicit syntax?

Comment (pastk) [reply indexer/feature.hpp:145]: Its almost never needed, because usually geometry is loaded already.
And if its not loaded then doesn't matter much which one to load as its used solely to display coords so that its easier to locate the feature.

In some specific cases it could make a difference (e.g. we want to just log and then continue working with the feature), so I didn't remove it completely.

Comment (biodranik) [reply indexer/feature.hpp:145]: Isn't loading the best geometry slower? I would prefer an explicit specialization in the place where it is used. It makes the author's intention and needs clearer.

File: drape_frontend/apply_feature_functors.cpp (hunk 1 above)
Comment (pastk) [reply drape_frontend/apply_feature_functors.cpp:407]: No, this magic works with `.DebugPrint()` only.
But `.DebugPrint()` requires its arg to be `const` whereas FeatureType is lazy loaded.
I'll add a comment to make it clear.

File: indexer/feature.hpp (hunk 2 above)
Comment (pastk) [reply indexer/feature.hpp:145]: I could change to WORST_GEOMETRY of course, but it doesn't really matter for firing an assert.
And where it matters an explicit zoom param could be passed still.

**Comment by pastk** [comment]
I've removed the `includeKeyPoint` param completely as its never had been used anyway.

File: indexer/feature.hpp (hunk 2 above)
Comment (biodranik) [reply indexer/feature.hpp]: I'm against any default parameter here. So the function's user will always be forced to explicitly specify what is needed.

Comment (vng) [reply indexer/feature.hpp]: Default value is ok here. A developer just wants to print a Feature for debug purpose. Why we do force him to think about scales ..

Comment (biodranik) [reply indexer/feature.hpp]: Then let's remove this parameter from the function's signature.

Comment (pastk) [reply indexer/feature.hpp]: @biodranik do you mean your preferred approach would be overloading? e.g.
```
std::string DebugString();
std::string DebugString(int scale);
```
If so, why is it better?

**Comment by pastk** [comment]
@vng do you remember what does it check exactly? consistency of what?
https://github.com/organicmaps/organicmaps/blob/f8f46216e660327b7b3b98b8f26bf699acbe3fc6/map/mwm_tests/mwm_foreach_test.cpp#L56-L62

**Comment by vng** [comment]
Since we have complicated (delayed-lazy) logic of Features loading, check that consequence calls produce the same results.

File: indexer/feature.hpp (hunk 2 above)
Comment (vng) [reply indexer/feature.hpp]: I don't see a problem why having scale and its default is bad. For regular and advanced experience.

**Comment by pastk** [comment]
Ok, but its very strange to use `DebugString()` to check that consistency :)
E.g. it couldn't be used to check geometry consistency reliably because it compares the first point only (a more reliable way would be to check points/triangles counts, but still not 100%).

Anyway I think we can remove the scale parameter there and add an explicit `ParseGeometryAndTriangles(m_scale)` before `DebugString()` calls (they will call `ParseGeometryAndTriangles()` again internally) - with the same effect. WDYT?

**Comment by vng** [comment]
Well, maybe is is better. Actually, we can make DebugString() without scale and it prints geometry as-is (which is currently loaded or not). And rewrite the test as you described.

**Comment by vng** [comment]
ParseGeometry is private. Let's remove the last commit and keep it as before with DebugString(scale).

**Comment by pastk** [comment]
Thanks, I missed it :)
Strange that `ParseGeometryAndTriangles()` is private while both `ParseGeometry()` and `ParseTriangles()` which it calls are public :)

**Review by vng — APPROVED** [review]
