### PR TITLE
[Android][iOS] Social pages editor fix

### LINKED ISSUE #2787: Automatically shortened facebook links won't allow you to save changes.
When adding the facebook link of a poi and saving the change, it will shorten the link to the reference after the / (so https:/www.facebook is removed). This is fine, but if you want to re-edit the poit, it won't allow you to save your changes until you r-add the first part of the url or delete the field. 
Can anyone confirm this issue on their device?

### LINKED ISSUE #3089: Editor breaks some Facebook links
When the Facebook URL is in the format `facebook.com/pages/PLACENAME`, the editor removes the host part so the text shown in the text field is `pages/PLACENAME`. As there is a `/` the input is considered invalid.

| Full URL | URL in editor |
|-|-|
| Screenshot_20220804-134316_Organic_Maps | Screenshot_20220804-134328_Organic_Maps |

Tested on Android with version 2022.07.27-3-FDroid, but my guess is that it will also happen on iOS as it seems to be handled by the CPP.

### PR DESCRIPTION
**Pull request by strump**
Closes #2787, closes #3089

The problem is some URLs after normalization are not valid because domain name is removed. I fixed the issue by adding domain name to native code called from UI. Also domain name is added to OSM changeset now.

* **Facebook**:
  * **OSM data or User input**:  `https://facebook.com/pages/Daikichi-Japans-Restaurant/118163444928138`
  * **After normalization**: `pages/Daikichi-Japans-Restaurant/118163444928138`
  * **On PlacePage UI**:
    * Old:&nbsp;`https://facebook.com/pages/Daikichi-Japans-Restaurant/118163444928138`
    * New:&nbsp;`pages/Daikichi-Japans-Restaurant/118163444928138`
  * **On upload to OSM**:
    * Old:&nbsp;`pages/Daikichi-Japans-Restaurant/118163444928138`
    * New:&nbsp;`https://facebook.com/pages/Daikichi-Japans-Restaurant/118163444928138`

* **Instagram**:
  * **OSM data or User input**:  `https://www.instagram.com/p/BvkgKZNDbqN/?ghid=UwPchX7B`
  * **After normalization**: `p/BvkgKZNDbqN`
  * **On PlacePage UI**:
    * Old:&nbsp;`https://instagram.com/p/BvkgKZNDbqN`
    * New:&nbsp;`p/BvkgKZNDbqN`
  * **On upload to OSM**:
    * Old:&nbsp;`p/BvkgKZNDbqN`
    * New:&nbsp;`https://instagram.com/p/BvkgKZNDbqN`

* **Facebook 2**:
  * **OSM data or User input**:  `www.facebook.com/OpenStreetMap`
  * **After normalization**: `OpenStreetMap`
  * **On PlacePage UI**:
    * Old:&nbsp;`@OpenStreetMap`
    * New:&nbsp;`OpenStreetMap`
  * **On upload to OSM**: `OpenStreetMap`

Also fixed iPhone UI. **This is my first commit to Swift and Objective-C code.** Please verify!!!
| Before | After |
| --------------- | --------------- |
| iphone-url-old | iphone-url-new |

Doesn't require map data change (in contrast to PR #3212).

## Update 2023-01-23

* Simplified social contacts URLs on PlacePage. Only part of URL is shown.
* Don't generate mobile URLs for social networks. Only default URLs.
* [iOS] Added Line social network to iPhone PlacePage and Editor.
* Formatting and comments updates.

social-contacts-editor-fix

## Update 2023-01-31
* Social contacts on PlacePage doesn't have `@` symbol now
* Introduced `constexpr` variables in C++ code
* Tests improvements

social-contacts-editor-fix-2

### CODE REVIEW

File: indexer/validate_and_format_contacts.cpp [hunk 1]
```diff
@@ -406,4 +406,30 @@ bool ValidateLinePage(string const & page)
...
 
+bool isSocialContactTag(string_view const tag)
+{
+  return (tag == "contact:instagram" || tag == "contact:facebook" || tag == "contact:twitter"
+          || tag == "contact:vk" || tag == "contact:line");
+}
+
+// Functions ValidateAndFormat_{facebook,instagram,twitter,vk}(...) by default strip domain name
+// from OSM data and user input. This function prepends domain name if it's needed.
+string denormalizeSocialContact(string_view tag, string_view value)
```
Comment (strump) [inline indexer/validate_and_format_contacts.cpp:417]: This function converts `string_view value` to `string` even if no changes are made. Don't know how to improve it.

**Comment by biodranik** [comment]
Actually, I have a better idea. To avoid duplicating the code in both iOS and Android, let's do normalization in the core before features are uploaded to OSM. WDYT?

**Comment by strump** [comment]
@biodranik let me answer you [comment](https://github.com/organicmaps/organicmaps/pull/3212#issuecomment-1257014842) here.
Here're analytics of `contact:facebook` data for the whole planet:

* count - `141 882` - total object in OSM database;
* source_length - `5 949 920` - Total length of `contact:facebook` values;
* normalized_length - `2 498 146` - Total length of normalized values;
* url_count - `8 302` - number of normalized values with '/' symbol (e.g. `pg/LiveGalleryHairDesign`); it's 5.8% of all objects;
* denormalized_length - `2 672 488` - Total length of normalized values with `https://facebook.com` domain (if it's needed); nicknames are not affected.

So if we add `https://facebook.com/` explicitly to all URLs (not nicknames) it will increase map size by `2 672 488 - 2 498 146 = 174 342` bytes.

For all social contacts:

| tag | count | source_length | normalized_length | url_count | denormalized_length |
| --------------- | --------------: | --------------: | --------------: | --------------: | --------------: |
| `contact:facebook` | `141 882` | `5 949 920` | `2 498 146` | `8302`&nbsp;(5.8%) | `2 672 488` |
| `contact:instagram` | `69 168` | `2 590 348` | `895 059` | `255` (0.3%) | `900 669` |
| `contact:twitter` | `34 020` | `996 019` | `353 032` | `142` (0.4%) | `355 872` |
| `contact:vk` | `53 760` | `1 361 593` | `568 377` | `15` (0.03%) | `568 602` |

**Comment by biodranik** [comment]
Thanks for the stats. There is no need to increase entropy by copypasting thousands of lines of code into the OSM DB and our maps. When tens of millions of users start using OM, the number of these strings will grow quickly. Also, don't forget about the general rule: the more compact map data, the faster the rendering.

**Comment by biodranik** [comment]
Can we solve that issue even easier? For example:

1. Make a list of prefixes to strip by checking values on taginfo or even better by getting them from the dump and find common patterns, e.g.
   - https://www.facebook.com/
   - https:https://www.facebook.com/
   - https://facebook.com/
   - https://es-es.facebook.com/
   - @page
   - page
   - https://www.facebook.com/pages/category/Restaurant/Au-poincaré-182381015649241
   Here we see that we can strip anything, including @ symbol, and then restore the full link by adding https://www.facebook,com/ without breaking it (the link will remain valid).
2. Strip all these prefixes at the map generation stage (and save space!)
3. Where do we need the full prefix? Only when the user clicks on the link or copies it. For simplicity, it can be hard-coded in each platform, or a full link can be retrieved via some C++ getter.
4. If a user adds social link, we can show `https://facebook.com/` label before the input, so the user should type only the normalized part of the URL. But if someone inserts a full URL - no problem! Our code will send it to OSM as is, either a short form of the link, or a full one. 
5. If a user edits an existing address, here the previous value in OSM (possibly with a full prefix) may be replaced by a shorter version without the prefix. But it is allowed by OSM!

What do you think about this approach?

**Comment by strump** [comment]
@biodranik your description looks rational. It mostly works in such way on master branch.
95% of cases social contact field has only username or pagename. OM works fine with such values
1. `@username` is shown on PlacePage ✅
2. Full URL is visible only when user copies contact ✅
3. In Editor user can change contact username ✅
4. Username is uploaded to OSM without domain name (which is correct) ✅

But there are 5% of cases when social contact field has no username but full URL. We strip domain name leaving short part 
`https://www.facebook.com/pages/category/Restaurant/Au-poincaré-182381015649241` -> `pages/category/Restaurant/Au-poincaré-182381015649241`

1. Full URL is shown on PlacePage (UI code prepends domain) ✅
2. Full URL is visible when user copies contact (UI code prepends domain) ✅ 
3. In Editor user can change full URL 🚫 (domain name is stripper and user needs to add it manually [#2787](https://github.com/organicmaps/organicmaps/issues/2787) [#3089](https://github.com/organicmaps/organicmaps/issues/3089))
4. Full URL is uploaded to OSM 🚫 (domain name is stripped)

With this PR I'm fixing cases 3. and 4.

And I'm thinking that short URL to full URL conversion could be moved to Native code to simplify UI code.

**Comment by biodranik** [comment]
1. What stops us from always showing a full url in the editor by always appending it?
2. What stops us by always stripping full url when uploading it to the OpenStreetMap.org? Or, alternatively, always upload full urls if they were edited/changed by the user? (No need to rewrite the same unmodified url, of course, by comparing a stripped part only, for example).

**Comment by strump** [comment]
@biodranik 
1. We can show full URL on editor UI. But for user it could look odd.
2. We can upload full URL to OSM API.

But from code perspective it's not hard to keep short pagename and full URL in parallel. See my [code](https://github.com/organicmaps/organicmaps/pull/3248/files#diff-1875d95de404ef18d91166583b07278ec0468b31f6da4603e3e69e41b394e7ceR429) for a simple check.

In this PR social contacts work in such way:
1. Map data stores nickname/pagename or short URL (no domain name). No updates here.
2. When PlacePage UI calls native method to get POI details it gets either nickname/pagename or full URL (with domain name)
3. When Editor UI calls native method to get social contacts it gets either nickname/pagename or full URL (with domain name)
4. OSM Changeset contains either nickname/pagename or full URL (with domain name).

I need to look iOS code if it needs modifications. Will install xCode and learn Swift.

File: iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm [hunk 2]
```diff
@@ -50,10 +58,10 @@ - (instancetype)initWithRawData:(Info const &)rawData ohLocalization:(id<IOpenin
           _email = ToNSString(value);
           _emailUrl = [NSURL URLWithString:[NSString stringWithFormat:@"mailto:%@", _email]];
           break;
-        case MetadataID::FMD_CONTACT_FACEBOOK: _facebook = ToNSString(value); break;
-        case MetadataID::FMD_CONTACT_INSTAGRAM: _instagram = ToNSString(value); break;
-        case MetadataID::FMD_CONTACT_TWITTER: _twitter = ToNSString(value); break;
-        case MetadataID::FMD_CONTACT_VK: _vk = ToNSString(value); break;
+        case MetadataID::FMD_CONTACT_FACEBOOK: _facebook = denormalizaSocialContact(value, @"https://facebook.com/"); break;
```
Comment (biodranik) [inline iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm:61]: It would be great to avoid hardcoding these URL parts several times everywhere in the code.

File: indexer/validate_and_format_contacts.cpp [hunk 3]
```diff
@@ -406,4 +406,57 @@ bool ValidateLinePage(string const & page)
...
+  // 'contact:line' value doesn't need to add domain name. See ValidateAndFormat_contactLine() for details.
+  return "https://" + string(value);
+}
+
+string denormalizeSocialContact(MapObject::MetadataID metaID, string_view value)
+{
+  if (value.find('/') == string::npos)
+    return string(value); // 'value' is not an URL but username. Don't do add domain name.
+
+  if (metaID == MapObject::MetadataID::FMD_CONTACT_INSTAGRAM)
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:449]: switch is more appropriate here.

File: indexer/validate_and_format_contacts.hpp [hunk 4]
```diff
@@ -17,4 +18,9 @@ bool ValidateInstagramPage(std::string const & v);
 bool ValidateTwitterPage(std::string const & v);
 bool ValidateVkPage(std::string const & v);
 bool ValidateLinePage(std::string const & v);
+
+bool isSocialContactTag(std::string_view const tag);
+bool isSocialContactTag(osm::MapObject::MetadataID const metaID);
+std::string denormalizeSocialContact(std::string_view tag, std::string_view value);
+std::string denormalizeSocialContact(osm::MapObject::MetadataID metaID, std::string_view value);
 }
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.hpp:26]:
```suggestion
}  // namespace osm
```

File: indexer/validate_and_format_contacts.hpp [hunk 5]
```diff
@@ -17,4 +18,9 @@ bool ValidateInstagramPage(std::string const & v);
 bool ValidateTwitterPage(std::string const & v);
 bool ValidateVkPage(std::string const & v);
 bool ValidateLinePage(std::string const & v);
+
+bool isSocialContactTag(std::string_view const tag);
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.hpp:22]:
```suggestion
bool isSocialContactTag(std::string_view tag);
```

File: editor/editor_tests/xml_feature_test.cpp [hunk 6]
```diff
@@ -459,3 +459,38 @@ UNIT_TEST(XMLFeature_AmenityRecyclingFromAndToXml)
   }
   */
 }
+
+UNIT_TEST(XMLFeature_SocialContactsProcessing)
+{
+  {
```
Comment (biodranik) [inline editor/editor_tests/xml_feature_test.cpp:465]: Why do you need it?

File: android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java [hunk 7]
```diff
@@ -1376,27 +1358,29 @@ public void onClick(View v)
         Utils.openUrl(getContext(), mMapObject.getMetadata(Metadata.MetadataType.FMD_WIKIMEDIA_COMMONS));
         break;
       case R.id.ll__place_facebook:
-        final String facebookPage = mMapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_FACEBOOK);
-        Utils.openUrl(getContext(), "https://m.facebook.com/"+facebookPage);
+        String facebookPage = mMapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_FACEBOOK);
+        if (facebookPage.indexOf('/') == -1) facebookPage = "https://m.facebook.com/" + facebookPage;
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java:1362]: Can we optimize and implement these similar checks only once, in the C++?

**Review by biodranik — CHANGES_REQUESTED** [review]
Thanks for your efforts! I'm worrying that our code complexity grows with all these copy-pasted approaches, and it increases the time to support it. Can it be optimized?

File: indexer/validate_and_format_contacts.cpp [hunk 8]
```diff
@@ -406,4 +406,57 @@ bool ValidateLinePage(string const & page)
   return (domain == "line.me" || strings::EndsWith(domain, ".line.me"));
 }
 
+bool isSocialContactTag(string_view const tag)
```
[the remark this answers is not in the document]
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Removed `const`.

File: indexer/validate_and_format_contacts.cpp [hunk 9]
```diff
@@ -406,4 +406,57 @@ bool ValidateLinePage(string const & page)
...
+{
+  return (tag == "contact:instagram" || tag == "contact:facebook" || tag == "contact:twitter"
+          || tag == "contact:vk" || tag == "contact:line");
```
[the remark this answers is not in the document]
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Removed parentheses

File: indexer/validate_and_format_contacts.cpp (hunk 3 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Replaced with `switch`

File: indexer/validate_and_format_contacts.hpp (hunk 4 above)
Comment (strump) [reply indexer/validate_and_format_contacts.hpp]: Done

File: indexer/validate_and_format_contacts.cpp [hunk 10]
```diff
@@ -406,4 +406,57 @@ bool ValidateLinePage(string const & page)
...
+          metaID == MapObject::MetadataID::FMD_CONTACT_VK ||
+          metaID == MapObject::MetadataID::FMD_CONTACT_LINE);
+}
+
+// Functions ValidateAndFormat_{facebook,instagram,twitter,vk}(...) by default strip domain name
+// from OSM data and user input. This function prepends domain name if it's needed.
+string denormalizeSocialContact(string_view tag, string_view value)
+{
+  if (value.find('/') == string::npos)
+    return string(value); // 'value' is not an URL but username. Don't do add domain name.
```
[the remark this answers is not in the document]
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: `return {value};` doesn't work. Fails with
`chosen constructor is explicit in copy-initialization`

**Comment by strump** [comment]
@biodranik sorry for being offline with this PR. So this is another version of my fix:

1. Implemented `socialContactToURL(...)` function to convert any social contant to full URL. See `validate_and_format_contacts.cpp` for details. All string constants with domain names are hardcoded there.
2. On UI every time we need to show full URI we use `socialContactToURL(...)`:
2.1. On Place page if social contact is not pagename/username but a link
2.2. On Place page when user taps social contant and we build URL to open in browser/app
2.3. On Place page when user long tap on social contact
2.4. On Editor UI if social contact is not pagename/username but a link
2.5. When we build changeset to upload to OSM and social contact is a link
3. On iOS Place page we don't add `@` symbol if social contact is an URL

**N.B.** Every call to `socialContactToURL(...)` isn't cheap because of string convertions and native call:

`jstring -> std::string -> socialContactToURL(...) -> std::string -> jstring`

or

`NSString -> std::string -> socialContactToURL(...) -> std::string -> NSString`

But UI calls this method only once per social network and only on user interaction: open Place Page view, tap, long tap, open Editor.

**Comment by biodranik** [comment]
Is there a way to get a properly formatted URL for UI without the overhead? E.g. to query it by id, and receive the final, properly formatted one?

**Comment by strump** [comment]
> Is there a way to get a properly formatted URL for UI without the overhead? E.g. to query it by id, and receive the final, properly formatted one?

Is there any way I can read selected `mapObject` from native code? Fro editor there's `g_editableMapObject` variable in native code but not for PlacePage.

**Comment by strump** [comment]
I rebased this PR to the latest 'master'. And fixed case of `contact:facebook=facebook.com/profile.php?id=34496388`.

**Comment by strump** [comment]
I rebased this PR to the latest 'master'. And fixed case of `contact:facebook=facebook.com/profile.php?id=34496388`.

File: editor/xml_feature.cpp [hunk 11]
```diff
@@ -532,7 +533,10 @@ XMLFeature ToXML(osm::EditableMapObject const & object, bool serializeType)
 
   object.ForEachMetadataItem([&toFeature](string_view tag, string_view value)
   {
-    toFeature.SetTagValue(tag, value);
+    if (osm::isSocialContactTag(tag) && value.find('/') != std::string::npos)
+      toFeature.SetTagValue(tag, osm::socialContactToURL(tag, value));
```
Comment (biodranik) [inline editor/xml_feature.cpp:537]: Would it be easier to avoid any logic here, and store it as-is? But apply the stripping logic (in C++ core) when a user presses "Save" in the editor window?

File: indexer/indexer_tests/validate_and_format_contacts_test.cpp [hunk 12]
```diff
@@ -14,6 +14,8 @@ UNIT_TEST(EditableMapObject_ValidateAndFormat_facebook)
   TEST_EQUAL(osm::ValidateAndFormat_facebook("http://www.facebook.com/OpenStreetMap"), "OpenStreetMap", ());
   TEST_EQUAL(osm::ValidateAndFormat_facebook("https://www.facebook.com/OpenStreetMap"), "OpenStreetMap", ());
   TEST_EQUAL(osm::ValidateAndFormat_facebook("https://en-us.facebook.com/OpenStreetMap"), "OpenStreetMap", ());
+  TEST_EQUAL(osm::ValidateAndFormat_facebook("https://de-de.facebook.com/profile.php?id=100085707580841"), "100085707580841", ());
+  TEST_EQUAL(osm::ValidateAndFormat_facebook("http://facebook.com/profile.php?share=app&id=809415707510008#m"), "809415707510008", ());
```
Comment (biodranik) [inline indexer/indexer_tests/validate_and_format_contacts_test.cpp:18]: This link is not valid anymore.

File: indexer/validate_and_format_contacts.cpp [hunk 13]
```diff
@@ -92,6 +92,16 @@ string ValidateAndFormat_facebook(string const & facebookPage)
...
   {
     auto webPath = url.GetPath();
+    // In case of https://www.facebook.com/profile.php?id=100085707580841 extract only ID
+    if (strings::StartsWith(webPath, "profile.php"))
+    {
+      auto valuePtr = url.GetParamValue("id");
+      if (valuePtr == nullptr)
+        return {};
+      else
+        return *valuePtr;
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:102]:
```suggestion
      return *valuePtr;
```

File: indexer/validate_and_format_contacts.cpp [hunk 14]
```diff
@@ -92,6 +92,16 @@ string ValidateAndFormat_facebook(string const & facebookPage)
       || strings::EndsWith(domain, "facebook.fr"))
   {
     auto webPath = url.GetPath();
+    // In case of https://www.facebook.com/profile.php?id=100085707580841 extract only ID
+    if (strings::StartsWith(webPath, "profile.php"))
+    {
+      auto valuePtr = url.GetParamValue("id");
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:98]:
```suggestion
      auto const valuePtr = url.GetParamValue("id");
```

File: indexer/validate_and_format_contacts.cpp [hunk 15]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
   return (domain == "line.me" || strings::EndsWith(domain, ".line.me"));
 }
 
+bool isSocialContactTag(string_view tag)
+{
+  return tag == "contact:instagram" || tag == "contact:facebook" || tag == "contact:twitter"
+         || tag == "contact:vk" || tag == "contact:line";
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:422]: A faster version of this code is possible, but if we don't use it at all, it would be even better (see my other comment).

File: indexer/validate_and_format_contacts.cpp [hunk 16]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+}
+
+bool isSocialContactTag(MapObject::MetadataID const metaID)
+{
+  return metaID == MapObject::MetadataID::FMD_CONTACT_INSTAGRAM ||
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:427]: nit: would the `switch` be better/faster?

File: indexer/validate_and_format_contacts.cpp [hunk 17]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+         metaID == MapObject::MetadataID::FMD_CONTACT_TWITTER ||
+         metaID == MapObject::MetadataID::FMD_CONTACT_VK ||
+         metaID == MapObject::MetadataID::FMD_CONTACT_LINE;
+}
+
+// Functions ValidateAndFormat_{facebook,instagram,twitter,vk}(...) by default strip domain name
+// from OSM data and user input. This function prepends domain name to generate full URL.
+string socialContactToURL(string_view tag, string_view value)
+{
+  if(value.empty())
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:438]:
```suggestion
  if (value.empty())
```

Is it a normal case? Maybe `ASSERT(!value.empty(), ());` could be more helpful?

File: indexer/validate_and_format_contacts.cpp [hunk 18]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+    return {};
+
+  if (tag == "contact:instagram")
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:441]: string_view objects are faster to compare than raw C strings. It makes sense to use local constexpr constants like this:

constexpr std::string_view kInstagram{"contact:instagram"};

if (tag == kInstagram) ...

File: indexer/validate_and_format_contacts.cpp [hunk 19]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+
+  if (tag == "contact:line")
+  {
+    if (value.find('/') == string::npos) // 'value' is a username.
+      return "https://line.me/R/ti/p/@" + string(value);
+    else // 'value' is an URL.
+      return "https://" + string(value);
+  }
+
+  return string(value);
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:458]: {} is a safer constructor version than () here and above.
```suggestion
  return string{value};
```

File: indexer/validate_and_format_contacts.cpp [hunk 20]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+}
+
+string socialContactToURL(MapObject::MetadataID metaID, string_view value)
+{
+  if(value.empty())
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:463]:
```suggestion
  if (value.empty())
```

File: indexer/validate_and_format_contacts.cpp [hunk 21]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+    return {};
+
+  switch (metaID)
+  {
+    case MapObject::MetadataID::FMD_CONTACT_INSTAGRAM:
+      return "https://instagram.com/" + string(value);
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:469]: As hostnames are copy-pasted here, they can be stored as global static constexpr constants and reused in different methods.

File: indexer/validate_and_format_contacts.cpp [hunk 22]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+    case MapObject::MetadataID::FMD_CONTACT_FACEBOOK:
+      return "https://facebook.com/" + string(value);
+    case MapObject::MetadataID::FMD_CONTACT_TWITTER:
+      return "https://twitter.com/" + string(value);
+    case MapObject::MetadataID::FMD_CONTACT_VK:
+      return "https://vk.com/" + string(value);
+    case MapObject::MetadataID::FMD_CONTACT_LINE:
+      if (value.find('/') == string::npos) // 'value' is a username.
+        return "https://line.me/R/ti/p/@" + string(value);
+      else // 'value' is an URL.
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:479]: Isn't Line normalized? Why do we store URLs for it?

Actually, it can be safe to assume that all URLs are normalized in the new release (after adding force-normalization into the generator) because now we don't allow users to edit the map if a new maps data update is available.

File: indexer/validate_and_format_contacts.cpp [hunk 23]
```diff
@@ -406,4 +416,97 @@ bool ValidateLinePage(string const & page)
...
+        return "https://" + string(value);
+    default:
+      return string(value);
+  }
+}
+
+// Same as socialContactToURL(...) but prepends mobile domains
+string socialContactToMobileURL(MapObject::MetadataID metaID, string_view value)
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:487]: Do we really need a mobile url version?

File: iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm [hunk 24]
```diff
@@ -52,10 +54,36 @@ - (instancetype)initWithRawData:(Info const &)rawData ohLocalization:(id<IOpenin
           _email = ToNSString(value);
           _emailUrl = [NSURL URLWithString:[NSString stringWithFormat:@"mailto:%@", _email]];
           break;
-        case MetadataID::FMD_CONTACT_FACEBOOK: _facebook = ToNSString(value); break;
-        case MetadataID::FMD_CONTACT_INSTAGRAM: _instagram = ToNSString(value); break;
-        case MetadataID::FMD_CONTACT_TWITTER: _twitter = ToNSString(value); break;
-        case MetadataID::FMD_CONTACT_VK: _vk = ToNSString(value); break;
+        case MetadataID::FMD_CONTACT_FACEBOOK:
+          if (value.find("/") != std::string::npos)
+            _facebook = ToNSString(osm::socialContactToURL(osm::MapObject::MetadataID::FMD_CONTACT_FACEBOOK, value));
```
Comment (biodranik) [inline iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm:59]: Can we avoid using full urls here?

**Review by biodranik — COMMENTED** [review]
Thank you very much for your work! I know that it already took a lot of time and energy for everyone, so there is even bigger motivation to finish it in the best way possible :)

Let's focus on how we can simplify everything.

File: android/jni/app/organicmaps/editor/Editor.cpp [hunk 25]
```diff
@@ -100,7 +100,15 @@ Java_app_organicmaps_editor_Editor_nativeGetMetadata(JNIEnv * env, jclass, jint
 {
   auto const metaID = static_cast<osm::MapObject::MetadataID>(id);
   ASSERT_LESS(metaID, osm::MapObject::MetadataID::FMD_COUNT, ());
-  return jni::ToJavaString(env, g_editableMapObject.GetMetadata(metaID));
+  if (osm::isSocialContactTag(metaID)) {
+    auto const value = g_editableMapObject.GetMetadata(metaID);
+    if (value.find('/') == std::string::npos) // `value` contains pagename
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/editor/Editor.cpp:105]: If I understand you correctly, you propose to get rid of social network domain on PlacePage UI. This is how it will look (Android). I added one more options with leading `'/'` symbol.

social-contacts-no-domain

Which of the three options do you prefer?

[the remark this answers is not in the document]
Comment (biodranik) [reply android/jni/app/organicmaps/editor/Editor.cpp:105]: Without a slash is ok. It is not critical at all, because a better solution will be to show icons without the text. It will be obvious, and won't take much space, thus easier to use.

[the remark this answers is not in the document]
Comment (biodranik) [reply android/jni/app/organicmaps/editor/Editor.cpp:105]: We can finish with this PR, create an issue about redesigning icons in Place Page, and do it later separately.

File: android/jni/app/organicmaps/editor/Editor.cpp [hunk 26]
```diff
@@ -100,7 +100,15 @@ Java_app_organicmaps_editor_Editor_nativeGetMetadata(JNIEnv * env, jclass, jint
 {
   auto const metaID = static_cast<osm::MapObject::MetadataID>(id);
   ASSERT_LESS(metaID, osm::MapObject::MetadataID::FMD_COUNT, ());
-  return jni::ToJavaString(env, g_editableMapObject.GetMetadata(metaID));
+  if (osm::isSocialContactTag(metaID)) {
+    auto const value = g_editableMapObject.GetMetadata(metaID);
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/editor/Editor.cpp]: Fixed formatting.

File: android/jni/app/organicmaps/editor/Editor.cpp (hunk 25 above)
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/editor/Editor.cpp]: Ok, I did as we agreed. Place page shows only part of URL. See screenshots in PR description.

File: android/jni/app/organicmaps/editor/Editor.cpp [hunk 27]
```diff
@@ -100,7 +100,15 @@ Java_app_organicmaps_editor_Editor_nativeGetMetadata(JNIEnv * env, jclass, jint
...
+    if (value.find('/') == std::string::npos) // `value` contains pagename
+      return jni::ToJavaString(env, value);
+    else // `value` contains URL
+      return jni::ToJavaString(env, osm::socialContactToURL(metaID, value));
+  }
+  else
+    return jni::ToJavaString(env, g_editableMapObject.GetMetadata(metaID));
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/editor/Editor.cpp]: Removed `else`.

File: android/jni/app/organicmaps/editor/Editor.cpp [hunk 28]
```diff
@@ -119,6 +127,28 @@ Java_app_organicmaps_editor_Editor_nativeSetMetadata(JNIEnv * env, jclass, jint
...
 
+JNIEXPORT jstring JNICALL
+Java_app_organicmaps_editor_Editor_nativeGetFullUrl(JNIEnv * env, jclass, jint id, jstring value)
+{
+  auto const metaID = static_cast<osm::MapObject::MetadataID>(id);
+  if (osm::isSocialContactTag(metaID)) {
+    return jni::ToJavaString(env, osm::socialContactToURL(metaID, jni::ToNativeString(env, value)));
+  }
+  else
+    return value;
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/editor/Editor.cpp]: Fixed formatting.

File: android/jni/app/organicmaps/editor/Editor.cpp [hunk 29]
```diff
@@ -119,6 +127,28 @@ Java_app_organicmaps_editor_Editor_nativeSetMetadata(JNIEnv * env, jclass, jint
...
+}
+
+JNIEXPORT jstring JNICALL
+Java_app_organicmaps_editor_Editor_nativeGetFullMobileUrl(JNIEnv * env, jclass, jint id, jstring value)
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/editor/Editor.cpp]: Removed mobile URL generation all over the code. Only full URL is used.

File: android/jni/app/organicmaps/editor/Editor.cpp [hunk 30]
```diff
@@ -119,6 +127,28 @@ Java_app_organicmaps_editor_Editor_nativeSetMetadata(JNIEnv * env, jclass, jint
...
+{
+  auto const metaID = static_cast<osm::MapObject::MetadataID>(id);
+  if (osm::isSocialContactTag(metaID)) {
+    return jni::ToJavaString(env, osm::socialContactToMobileURL(metaID, jni::ToNativeString(env, value)));
+  }
+  else
+    return value;
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/editor/Editor.cpp]: Fixed formatting.

File: android/src/app/organicmaps/widget/placepage/PlacePageView.java [hunk 31]
```diff
@@ -1038,18 +1038,18 @@ private void refreshWiFi(@NonNull MapObject mapObject)
...
     final String vkPageLink = mapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_VK);
-    refreshSocialPageLink(mVkPage, mTvVkPage, vkPageLink, "vk.com");
+    refreshSocialPageLink(mVkPage, mTvVkPage, vkPageLink, Metadata.MetadataType.FMD_CONTACT_VK);
     final String linePageLink = mapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_LINE);
-    refreshLinePageLink(mLinePage, mTvLinePage, linePageLink);
+    refreshSocialPageLink(mLinePage, mTvLinePage, linePageLink, Metadata.MetadataType.FMD_CONTACT_LINE);
   }
 
-  private void refreshSocialPageLink(View view, TextView tvSocialPage, String socialPage, String webDomain)
+  private void refreshSocialPageLink(View view, TextView tvSocialPage, String socialPage, Metadata.MetadataType metaType)
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/widget/placepage/PlacePageView.java]: Simplified `PlacePageView.refreshSocialLinks(...)` method. Do not show full URL on PlacePage.

File: android/src/app/organicmaps/widget/placepage/PlacePageView.java [hunk 32]
```diff
@@ -1058,26 +1058,8 @@ private void refreshSocialPageLink(View view, TextView tvSocialPage, String soci
...
-    if (TextUtils.isEmpty(socialPage))
-    {
-      view.setVisibility(GONE);
-    }
-    else
-    {
-      view.setVisibility(VISIBLE);
-      if (socialPage.indexOf('/') >= 0)
-        tvSocialPage.setText("https://" + socialPage);
+      if (socialPage.indexOf('/') >= 0) // `socialPage` contains URL. Convert it to full URL
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/widget/placepage/PlacePageView.java]: Done!

File: android/src/app/organicmaps/widget/placepage/PlacePageView.java [hunk 33]
```diff
@@ -1384,31 +1366,33 @@ else if (id == R.id.ll__place_wikimedia)
       Utils.openUrl(getContext(), mMapObject.getMetadata(Metadata.MetadataType.FMD_WIKIMEDIA_COMMONS));
     else if (id == R.id.ll__place_facebook)
     {
-      final String facebookPage = mMapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_FACEBOOK);
-      Utils.openUrl(getContext(), "https://m.facebook.com/" + facebookPage);
+       final String facebookPage = mMapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_FACEBOOK);
+       final String fullUrl = Editor.nativeGetFullMobileUrl(Metadata.MetadataType.FMD_CONTACT_FACEBOOK.toInt(), facebookPage);
+       Utils.openUrl(getContext(), fullUrl);
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/widget/placepage/PlacePageView.java]: Added method `MapObject.getFullUrl(Metadata.MetadataType)` to simplify the code.
Storing simplified link is better. We show it on UI and can restore full URL any time (on click or in Editor).

File: android/src/app/organicmaps/widget/placepage/PlacePageView.java [hunk 34]
```diff
@@ -1473,40 +1457,36 @@ else if (id == R.id.ll__place_facebook)
...
     {
       final String linePage = mMapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_LINE);
-      if (linePage.indexOf('/') >= 0)
-        items.add("https://" + linePage);
-      else
-      {
-        items.add(linePage); // Show username along with URL.
-        items.add("https://line.me/R/ti/p/@" + linePage);
-      }
+      if (linePage.indexOf('/') == -1)
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/widget/placepage/PlacePageView.java:1461]: Yes. PlacePage now shows social contacts with no modification. Only `@` symbol is added is needed.

File: editor/xml_feature.cpp (hunk 11 above)
Comment (strump) [reply editor/xml_feature.cpp:537]: We do strip full URL in Editor. We can't send to OSM partial URLs like 'contact:instagram=p/BvkgKZNDbqN'. [Wiki](https://wiki.openstreetmap.org/wiki/Key:contact:*) says that either username of full URL is expected. This part of code converts all shortened URLs to full URLs before sending to OSM API.

File: indexer/validate_and_format_contacts.cpp (hunk 14 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Fixed.

File: indexer/validate_and_format_contacts.cpp (hunk 15 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: This code is used from `editor/xml_feature.cpp` to convert short URLs to full URLs for OSM API. I simplified it with `constexpr` as you proposed.

File: indexer/validate_and_format_contacts.cpp (hunk 16 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp:431]: You mean replace:

```
  return metaID == MapObject::MetadataID::FMD_CONTACT_INSTAGRAM ||
         metaID == MapObject::MetadataID::FMD_CONTACT_FACEBOOK ||
         metaID == MapObject::MetadataID::FMD_CONTACT_TWITTER ||
         metaID == MapObject::MetadataID::FMD_CONTACT_VK ||
         metaID == MapObject::MetadataID::FMD_CONTACT_LINE;
```

with 

```
switch (metaID)
{
  case MapObject::MetadataID::FMD_CONTACT_INSTAGRAM:
  case MapObject::MetadataID::FMD_CONTACT_FACEBOOK:
  case MapObject::MetadataID::FMD_CONTACT_TWITTER:
  case MapObject::MetadataID::FMD_CONTACT_VK:
  case MapObject::MetadataID::FMD_CONTACT_LINE:
   return true;
  default:
    return false;
}
```
? I don't know how it would affect performance. We can try and use `switch`.

File: indexer/validate_and_format_contacts.cpp (hunk 18 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Added `constexpr` for all `"contact:*"` strings in `validate_and_format_contacts.cpp`.

File: indexer/validate_and_format_contacts.cpp (hunk 19 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Fixed.

File: indexer/validate_and_format_contacts.cpp (hunk 20 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Fixed.

File: indexer/validate_and_format_contacts.cpp (hunk 22 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp:480]: Line normalization is tricky. You can find some examples in `validate_and_format_contacts_test.cpp` file. E.g.

* `https://line.me/R/ti/p/gdltt7s380` → can extract username `gdltt7s380`
* `https://line.me/R/home/public/profile?id=r90ck7n1rq` → can extract username `r90ck7n1rq`
* `https://liff.line.me/1645278921-kWRPP32q/?accountId=673watcr` → no username and different domain
* `https://page.line.me/?accountId=673watcr` → different domain and `accountId` is not the same thing as username.

So we store domain (no HTTP(S) protocol) for `contact:line`.

File: indexer/validate_and_format_contacts.cpp (hunk 23 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Removed mobile URL code

File: indexer/validate_and_format_contacts.hpp [hunk 35]
```diff
@@ -1,6 +1,7 @@
 #pragma once
 
 #include <string>
+#include "map_object.hpp"
```
[the remark this answers is not in the document]
Comment (strump) [reply indexer/validate_and_format_contacts.hpp]: Fixed formatting.

File: iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm (hunk 24 above)
Comment (strump) [reply iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm]: Reverted this code. Copy raw data here.

File: iphone/Maps/UI/Editor/MWMEditorViewController.mm [hunk 36]
```diff
@@ -417,10 +418,15 @@ - (void)configTextViewCell:(UITableViewCell * _Nonnull)cell
                       icon:(NSString * _Nonnull)icon
                placeholder:(NSString * _Nonnull)name
 {
+  MetadataID metaId = static_cast<MetadataID>(cellID);
+  NSString* value = ToNSString(m_mapObject.GetMetadata(metaId));
+  if (osm::isSocialContactTag(metaId) && [value containsString:@"/"])
+    value = ToNSString(osm::socialContactToURL(metaId, [value UTF8String]));
```
[the remark this answers is not in the document]
Comment (strump) [reply iphone/Maps/UI/Editor/MWMEditorViewController.mm:424]: As we do with Android, short URLs should be converted to full URLs on editor. This is what issue #2787 is about.

Editor validates those values and stores short URLs.

File: android/src/app/organicmaps/editor/Editor.java [hunk 37]
```diff
@@ -72,6 +72,8 @@ public static void uploadChanges(@NonNull Context context)
   public static native String nativeGetMetadata(int id);
   public static native boolean nativeIsMetadataValid(int id, String value);
   public static native void nativeSetMetadata(int id, String value);
+  public static native String nativeGetFullUrl(int id, String value); // Convert normalized contact value to full URL
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/editor/Editor.java]: Fixed

File: indexer/validate_and_format_contacts.cpp (hunk 13 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Fixed

File: indexer/validate_and_format_contacts.cpp (hunk 16 above)
Comment (biodranik) [reply indexer/validate_and_format_contacts.cpp:429]: That's not important. It's nit )

File: indexer/validate_and_format_contacts.cpp (hunk 21 above)
Comment (biodranik) [reply indexer/validate_and_format_contacts.cpp:468]: Let's avoid the copy-paste by using constexpr string_view for hosts.

Comment (strump) [reply indexer/validate_and_format_contacts.cpp:468]: What's the best way to concat two `string_view` values?

```
constexpr string_view urlInstagram{"https://instagram.com/"};
string socialContactToURL(string_view tag, string_view value)
{
    return urlInstagram + value;
}
```

gives error: `invalid operands to binary expression ('const std::string_view' (aka 'const basic_string_view<char>') and 'std::string_view' (aka 'basic_string_view<char>'))`

File: indexer/validate_and_format_contacts.cpp [hunk 38]
```diff
@@ -92,7 +98,14 @@ string ValidateAndFormat_facebook(string const & facebookPage)
       || strings::EndsWith(domain, "facebook.fr"))
   {
     auto webPath = url.GetPath();
-    // Strip last '/' symbol
+    // In case of https://www.facebook.com/profile.php?id=100085707580841 extract only ID.
+    if (strings::StartsWith(webPath, "profile.php"))
```
[the remark this answers is not in the document]
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Introduced `constexpr` variables for "profile.php", domain names, URLs etc.

File: android/src/app/organicmaps/widget/placepage/PlacePageView.java [hunk 39]
```diff
@@ -1383,33 +1359,15 @@ else if (id == R.id.ll__place_website)
     else if (id == R.id.ll__place_wikimedia)
       Utils.openUrl(getContext(), mMapObject.getMetadata(Metadata.MetadataType.FMD_WIKIMEDIA_COMMONS));
     else if (id == R.id.ll__place_facebook)
-    {
-      final String facebookPage = mMapObject.getMetadata(Metadata.MetadataType.FMD_CONTACT_FACEBOOK);
-      Utils.openUrl(getContext(), "https://m.facebook.com/" + facebookPage);
-    }
+       Utils.openUrl(getContext(), mMapObject.getContactUrl(Metadata.MetadataType.FMD_CONTACT_FACEBOOK));
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/widget/placepage/PlacePageView.java]: Removed `mMapObject.getContactUrl()` method. Introduced `Framework.nativeGetPoiContactUrl(id)` to simplify code.

File: android/src/app/organicmaps/bookmarks/data/MapObject.java [hunk 40]
```diff
@@ -268,6 +269,14 @@ public boolean hasMetadata()
     return !mMetadata.isEmpty();
   }
 
+  public String getContactUrl(Metadata.MetadataType type)
+  {
+    final String res = mMetadata.getMetadata(type);
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/bookmarks/data/MapObject.java]: Introduced `Framework.nativeGetPoiContactUrl()` function instead

File: android/jni/app/organicmaps/DownloadResourcesLegacyActivity.cpp [hunk 41]
```diff
@@ -7,7 +7,7 @@
 
 #include "platform/downloader_defines.hpp"
 #include "platform/http_request.hpp"
-#include "platform/platform.hpp"
+#include "platform/Platform.hpp"
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/DownloadResourcesLegacyActivity.cpp]: I saw compiler warnings and changed include statement.
Reverting it back.

File: android/jni/app/organicmaps/Framework.cpp [hunk 42]
```diff
@@ -40,7 +40,7 @@
 #include "platform/location.hpp"
 #include "platform/measurement_utils.hpp"
 #include "platform/network_policy.hpp"
-#include "platform/platform.hpp"
+#include "platform/Platform.hpp"
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/Framework.cpp]: Ok, reverting

File: android/src/app/organicmaps/widget/placepage/PlacePageView.java [hunk 43]
```diff
@@ -1037,47 +1037,23 @@ private void refreshWiFi(@NonNull MapObject mapObject)
...
-    }
-    else
-    {
-      view.setVisibility(VISIBLE);
-      if (socialPage.indexOf('/') >= 0)
-        tvSocialPage.setText("https://" + socialPage);
+      if (socialPage.indexOf('/') >= 0) // `socialPage` contains URL.
+        tvSocialPage.setText(socialPage);
       else
         tvSocialPage.setText("@" + socialPage);
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/widget/placepage/PlacePageView.java]: Removed `@` symbol from Android and iOS place page UI

File: indexer/validate_and_format_contacts.cpp [hunk 44]
```diff
@@ -403,7 +444,70 @@ bool ValidateLinePage(string const & page)
...
+}
+
+// Functions ValidateAndFormat_{facebook,instagram,twitter,vk}(...) by default strip domain name
+// from OSM data and user input. This function prepends domain name to generate full URL.
+string socialContactToURL(string_view tag, string_view value)
+{
+  ASSERT(!value.empty(), ());
+
+  if (tag == kInstagram)
+    return string{urlInstagram} + string{value};
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:471]: It is not critical, but it is better to avoid unnecessary memory allocation for a temporary string object. The optimal way to do it (here and in other places):
```suggestion
    return string{urlInstagram}.append(value);
```

File: indexer/validate_and_format_contacts.cpp [hunk 45]
```diff
@@ -14,22 +14,50 @@ static auto const s_badVkRegex = regex(R"(^\d\d\d.+$)");
...
 
-char const * const kWebsiteProtocols[] = {"http://", "https://"};
-size_t const kWebsiteProtocolDefaultIndex = 0;
+constexpr string_view kFacebook{"contact:facebook"};
+constexpr string_view kInstagram{"contact:instagram"};
+constexpr string_view kTwitter{"contact:twitter"};
+constexpr string_view kVk{"contact:vk"};
+constexpr string_view kLine{"contact:line"};
+
+constexpr string_view fbProfilePhp{"profile.php"};
```
Comment (biodranik) [inline indexer/validate_and_format_contacts.cpp:23]: According to our docs/CPP_STYLE.md:
> - Compile-time constants must be named in camelCase, starting with a lower-case `k`, e.g. `kCompileTimeConstant` and marked as `constexpr` when possible.

So all constants should be named like kConstant.

File: base/string_utils.cpp [hunk 46]
```diff
@@ -337,6 +337,15 @@ bool EndsWith(std::string const & s1, char const * s2)
   return (s1.compare(n - m, m, s2) == 0);
 }
 
+bool EndsWith(std::string const & s1, std::string_view s2)
```
Comment (biodranik) [inline base/string_utils.cpp:340]: Is there a unit-test for this method?

**Review by biodranik — COMMENTED** [review]
Almost done!

@Jean-BaptisteC can you please test this PR?

File: indexer/validate_and_format_contacts.cpp (hunk 44 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Replaced `+` with `.append(...)` in the file.

File: indexer/validate_and_format_contacts.cpp (hunk 45 above)
Comment (strump) [reply indexer/validate_and_format_contacts.cpp]: Ok, didn't see style guide file.
Renamed constants in the file.

File: base/string_utils.cpp (hunk 46 above)
Comment (strump) [reply base/string_utils.cpp:340]: Added tests for EndsWith(string, string_view)

**Comment by Jean-BaptisteC** [comment]
> @Jean-BaptisteC can you please test this PR?

Yes :)
Do you want i test upload changes on OSM or automated tests is enough ?
To test on https://master.apis.dev.openstreetmap.org, did i have need a new OSM account ?

**Comment by biodranik** [comment]
> Do you want i test upload changes on OSM or automated tests is enough ?

It would be great to test OSM upload for some real business )

> To test on https://master.apis.dev.openstreetmap.org/, did i have need a new OSM account ?

You need a new account there. But you may also need to import OSM data there (as far as I remember, their database was empty, not mirroring the original OSM data that is used in production).

**Review by biodranik — APPROVED** [review]
You've made it!

File: android/jni/app/organicmaps/Framework.cpp [hunk 47]
```diff
@@ -1650,6 +1650,16 @@ Java_app_organicmaps_Framework_nativeDeleteBookmarkFromMapObject(JNIEnv * env, j
   return usermark_helper::CreateMapObject(env, g_framework->GetPlacePageInfo());
 }
 
+JNIEXPORT jstring JNICALL
+Java_app_organicmaps_Framework_nativeGetPoiContactUrl(JNIEnv *env, jclass, jint id)
+{
+  auto const metaID = static_cast<osm::MapObject::MetadataID>(id);
+  string_view value = g_framework->GetPlacePageInfo().GetMetadata(metaID);
```
[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/Framework.cpp:1657]: `string_view const` or `const string_view` ? I'm confused with C++ const semantics 😊

[the remark this answers is not in the document]
Comment (biodranik) [reply android/jni/app/organicmaps/Framework.cpp:1657]: It is the same :) But we use the right-to-left notation (check our CPP_STYLE.md for details).

[the remark this answers is not in the document]
Comment (biodranik) [reply android/jni/app/organicmaps/Framework.cpp:1657]: For example: `string_view const * const` reads as const pointer to a const string_view.

[the remark this answers is not in the document]
Comment (strump) [reply android/jni/app/organicmaps/Framework.cpp]: Done!

**Review by Jean-BaptisteC — APPROVED** [review]
Pixel 6 - Android 13 ✅
Facebook:
- ID + Full URL
Tested with https://www.openstreetmap.org/node/2864998473

Instagram:
- ID + Full URL
Tested with https://www.openstreetmap.org/node/2864998473

Twitter:
- ID + Full URL
https://www.openstreetmap.org/node/9722726898

VK:
- ID + Full URL
https://www.openstreetmap.org/node/3199685169

LINE:
- ID + Full URL
https://www.openstreetmap.org/node/4007245809

Long press on Place page works (Copy just ID and copy full URL) ✅
We can't add instagram link in Facebook field (Tested on all socials fields) ✅

I have create account on master dev osm and add in OM debug, but changes are not upload

**Comment by Jean-BaptisteC** [comment]
> > We can't instagram link in Facebook field (Tested on all socials fields) ✅
> 
> What is it about? :)
We can't add instagram link in Facebook field (Tested on all socials fields) ✅

I have try to update instagram links -> ID is just send not a full url, same for Facebook ❌
Example: https://www.openstreetmap.org/node/2864998473

**Comment by biodranik** [comment]
@Jean-BaptisteC sorry, I'm a bit confused. Above you wrote that FB and Instagram links are uploaded as a full URL, now you're saying that they are not uploaded as a full URL, right?

@strump all uploaded links should be complete URLs, correct?

**Comment by Jean-BaptisteC** [comment]
Yes, i didn't have give enough details on my tests.
In first, i have doing tests on editor without upload.
I have check, if i add just ID, i can save POI
If i add full URL in editor, OM remove start of URL and just keep ID
I have check on place page, if social links can be opened.

I have doing 1 test about upload with this POI https://www.openstreetmap.org/node/2864998473

**Comment by strump** [comment]
@biodranik @Jean-BaptisteC
If Organic Maps UI shows nickname then only nickname is uploaded to OSM (for all social networks).
If OrganicMaps shows part of URL on UI, then full URL is uploaded to OSM.

This is how I implemented it (we have unit-tests to check it).

OSM wiki tells that full URL and nickname are both valid values.

**Comment by biodranik** [comment]
@Jean-BaptisteC what did you type for the FB for [this feature](https://www.openstreetmap.org/node/2864998473)?
1. It looks like a page link, not a nickname.
2. It is invalid (there is no such nickname and no such page).
3. Did you insert a full link into the editor? Or a short nickname?

**Comment by Jean-BaptisteC** [comment]
On this POI, i have update instagram link (full link) and OM have upload nickname to OSM
And OM have re-upload Facebook (I don't have update FB link in editor, OM have send nickname, and i know nickname is invalid)

On OM, if i add nickname or full link in editor, automatically, OM send nickname

**Comment by biodranik** [comment]
@Jean-BaptisteC a full URL that points to a nickname is shortened to a nickname. A full URL that is NOT pointing to a nickname should NOT be shortened.

**Comment by Jean-BaptisteC** [comment]
I think Facebook have changed, how is build their URLS, because for my example, this is the new URL https://www.facebook.com/Eltheatris, same for others pages
https://www.facebook.com/latourdargent
https://www.facebook.com/thilchocolatier

**Comment by biodranik** [comment]
@strump can you please rebase it?

@Jean-BaptisteC it should be good to merge, right? Or are there any issues?

**Comment by strump** [comment]
@biodranik should I squash commits after rebase?

**Comment by biodranik** [comment]
@strump ideally, contributors can squash necessary changes into one or more logically independent commits. We can also squash during the merge if it's just one big change.

**Comment by biodranik** [comment]
Please double-check that this is fixed: https://github.com/organicmaps/organicmaps/issues/3089#issuecomment-1435770527

**Comment by Jean-BaptisteC** [comment]
Yes, it's OK for me, i didn't have find any others issues :)

File: base/string_utils.cpp [hunk 48]
```diff
@@ -337,6 +337,15 @@ bool EndsWith(std::string const & s1, char const * s2)
   return (s1.compare(n - m, m, s2) == 0);
```
Comment (vng) [inline base/string_utils.cpp:337]: Now you can simply call EndsWith(s1, std::string_view(s2)) here

File: editor/editor_tests/xml_feature_test.cpp [hunk 49]
```diff
@@ -480,3 +480,89 @@ UNIT_TEST(XMLFeature_Diet)
...
+    </node>
+    )";
+
+    editor::XMLFeature xmlFeature(nightclubStr);
+
+    osm::EditableMapObject emo;
+    editor::FromXML(xmlFeature, emo);
+
+    // Read and write "contact:facebook" to apply normalization.
+    std::string contactFacebook = std::string(emo.GetMetadata(feature::Metadata::FMD_CONTACT_FACEBOOK));
```
Comment (vng) [inline editor/editor_tests/xml_feature_test.cpp:503]: Here is the shorter way to construct string from view:
std::string contactFacebook(view);

File: indexer/indexer_tests/validate_and_format_contacts_test.cpp [hunk 50]
```diff
@@ -248,3 +261,17 @@ UNIT_TEST(EditableMapObject_ValidateLinePage)
   TEST(!osm::ValidateLinePage("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), ());
   TEST(!osm::ValidateLinePage("https://line.com/ti/p/invalid-domain"), ());
 }
+
+UNIT_TEST(EditableMapObject_socialContactToURL) {
```
Comment (vng) [inline indexer/indexer_tests/validate_and_format_contacts_test.cpp:265]: { from new line

**Review by vng — CHANGES_REQUESTED** [review]
I suspect that updating kothic submodule is not needed in this PR.
Don't commit it, just make git submodule update ...

**Review by strump — COMMENTED** [review]
Looks like this PR updates submodules kothic and twine. It’s by accident probably after rebase. Need to revert submodule changes…
Update: Done!

File: base/string_utils.cpp (hunk 48 above)
Comment (strump) [reply base/string_utils.cpp]: Fixed

File: indexer/indexer_tests/validate_and_format_contacts_test.cpp (hunk 50 above)
Comment (strump) [reply indexer/indexer_tests/validate_and_format_contacts_test.cpp]: Fixed formatting

**Review by vng — APPROVED** [review]

File: base/string_utils.cpp [hunk 51]
```diff
@@ -334,7 +334,7 @@ bool EndsWith(std::string const & s1, char const * s2)
   size_t const m = strlen(s2);
   if (n < m)
     return false;
-  return (s1.compare(n - m, m, s2) == 0);
+  return EndsWith(s1, std::string_view(s2));
```
Comment (vng) [inline base/string_utils.cpp:337]: Replace all the function's body here :)
```
bool EndsWith(std::string const & s1, char const * s2)
{
  return EndsWith(s1, std::string_view(s2));
}
```

Comment (strump) [reply base/string_utils.cpp:333]: Replaced body 😊
