### PR TITLE
[Android] Fix settings crashes

### LINKED ISSUE #4748: [android] Can't get preference by key: EmulateBadExternalStorage
Robo test, Pixel 6a, API level 32

```
java.lang.RuntimeException: Can't get preference by key: EmulateBadExternalStorage

     FATAL EXCEPTION: Thread-4
Process: app.organicmaps.debug, PID: 3478
java.lang.RuntimeException: Can't get preference by key: EmulateBadExternalStorage
	at app.organicmaps.settings.BaseXmlSettingsFragment.getPreference(BaseXmlSettingsFragment.java:27)
	at app.organicmaps.settings.SettingsPrefsFragment.getPreference(SettingsPrefsFragment.java:47)
	at app.organicmaps.settings.SettingsPrefsFragment.initEmulationBadStorage(SettingsPrefsFragment.java:467)
	at app.organicmaps.settings.SettingsPrefsFragment.onViewCreated(SettingsPrefsFragment.java:262)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:871)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:778)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:699)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:429)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:255)
	at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:673)
	at app.organicmaps.base.BaseMwmFragmentActivity.onBackPressed(BaseMwmFragmentActivity.java:252)
	at app.organicmaps.base.BaseToolbarActivity.onBackPressed(BaseToolbarActivity.java:107)
	at app.organicmaps.base.BaseMwmFragmentActivity.onHomeOptionItemSelected(BaseMwmFragmentActivity.java:194)
	at app.organicmaps.base.BaseMwmFragmentActivity.onOptionsItemSelected(BaseMwmFragmentActivity.java:186)
	at android.app.Activity.onMenuItemSelected(Activity.java:4324)
	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:529)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:265)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
	at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30250)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:23)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

https://console.firebase.google.com/u/0/project/omapsapp/testlab/histories/bh.7a38003b1edbc7b5/matrices/8747814439743634446/executions/bs.f5259f28ee0493b/issues

### PR DESCRIPTION
**Pull request by strump**
Closes #4748

In some cases preferences could be removed at runtime. And `findPreference()` method returns `null` even if key is present in `prefs_main.xml`.

## Update 2023.03.13

Added ↗ arrow symbol at the end. And the link changed color to blue (accent color).

### CODE REVIEW

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 1]
```diff
@@ -241,11 +241,11 @@ public void onViewCreated(View view, @Nullable Bundle savedInstanceState)
   {
     super.onViewCreated(view, savedInstanceState);
     mPreferenceScreen = getPreferenceScreen();
-    mStoragePref = getPreference(getString(R.string.pref_storage));
+    mStoragePref = findPreference(getString(R.string.pref_storage));
```
Comment (strump) [inline android/src/app/organicmaps/settings/SettingsPrefsFragment.java:244]: I couldn't reproduce case when `findPreference(getString(R.string.pref_storage))` returns null. This setting is never removed at runtime.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 2]
```diff
@@ -95,8 +93,6 @@ public boolean onPreferenceChange(Preference preference, Object newValue)
       root.setSummary(R.string.on);
       if (mPrefEnabled != null)
         mPrefEnabled.setTitle(R.string.on);
-      if (mLangInfoLink != null)
-        removePreference(getString(R.string.pref_navigation), mLangInfoLink);
```
Comment (strump) [inline android/src/app/organicmaps/settings/SettingsPrefsFragment.java:99]: Behaviour of `mLangInfoLink` is little bit strange. It's not in "Navigation" preferences, so this remove does nothing.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 3]
```diff
@@ -80,8 +80,6 @@ public boolean onPreferenceChange(Preference preference, Object newValue)
           mPrefLanguages.setEnabled(false);
         if (mLangInfo != null)
           mLangInfo.setSummary(R.string.prefs_languages_information_off);
-        if (mLangInfoLink != null && isOnTtsScreen())
-          getPreferenceScreen().addPreference(mLangInfoLink);
```
Comment (strump) [inline android/src/app/organicmaps/settings/SettingsPrefsFragment.java:84]: Behaviour of `mLangInfoLink` is little bit strange. It's already on TTS Settings screen so don't need to add it at a runtime.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 4]
```diff
@@ -151,9 +147,6 @@ private void setLanguage(@NonNull LanguageData lang)
 
   private void updateTts()
   {
-    if (mPrefEnabled == null || mPrefLanguages == null || mLangInfo == null || mLangInfoLink == null)
-      return;
-
```
Comment (strump) [inline android/src/app/organicmaps/settings/SettingsPrefsFragment.java:156]: `updateTts()` should be called only when we initialize TTS settings. We expect no nulls here.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java (hunk 3 above)
Comment (biodranik) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:84]: Does it make sense to cleanup mLangInfoLink related code now, to make it easier in the future? E.g. initLangInfoLink can be removed, all null checks can be removed too. Maybe storing mLangInfoLink as a variable would not be needed at all.

Comment (biodranik) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:84]: Renaming would be great. Simplifying the code and removing unnecessary vars and functions would be also great )

Comment (strump) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:84]: Replaced field `mLangInfoLink` with local variable.
Renamed fields, method and local variable by adding `Tts`.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 5]
```diff
@@ -52,13 +52,12 @@ public class SettingsPrefsFragment extends BaseXmlSettingsFragment
   private Preference mStoragePref;
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:52]: I submitted PR #4779
But I think this PR fixes settings in `master`. We can close this one and merge new #4779

[the remark this answers is not in the document]
Comment (biodranik) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:52]: Let's create a separate refactoring issue for the future if it is really necessary.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java (hunk 4 above)
Comment (biodranik) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:156]: Maybe add a comment about it to the code?

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 6]
```diff
@@ -344,24 +346,24 @@ else if (preference.getKey() != null && preference.getKey().equals(getString(R.s
...
-        final Intent intent = new Intent(Intent.ACTION_VIEW);
-        intent.setData(Uri.parse(TTS_INFO_LINK));
-        requireContext().startActivity(intent);
-        return false;
-      });
-      removePreference(getString(R.string.pref_navigation), mLangInfoLink);
-    }
+    Preference ttsLangInfoLink = getPreference(getString(R.string.pref_tts_info_link));
+    final String ttsLinkText = getString(R.string.prefs_languages_information_off_link);
+    Spannable link = new SpannableString(ttsLinkText + "\u2197");
```
Comment (biodranik) [inline android/src/app/organicmaps/settings/SettingsPrefsFragment.java:353]: Doesn't java support "↗" symbols in strings?

Comment (biodranik) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:353]: nit: final.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 7]
```diff
@@ -344,24 +346,24 @@ else if (preference.getKey() != null && preference.getKey().equals(getString(R.s
...
+    // Set link color.
+    link.setSpan(new ForegroundColorSpan(ContextCompat.getColor(requireContext(),
+                                                                UiUtils.getStyledResourceId(requireContext(), R.attr.colorAccent))),
+                 0, ttsLinkText.length(), 0);
+    ttsLangInfoLink.setSummary(link);
+
+    final String ttsInfoUrl = requireActivity().getString(R.string.tts_info_link);
+    ttsLangInfoLink.setOnPreferenceClickListener(preference -> {
```
Comment (biodranik) [inline android/src/app/organicmaps/settings/SettingsPrefsFragment.java:361]: nit: is there a way to mark the lambda variable as unused in Java? Maybe use _ ?

**Review by biodranik — COMMENTED** [review]
nit: add "[android]" in each commit's title.

**Review by biodranik — APPROVED** [review]
It's ok to merge IMO.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java (hunk 4 above)
Comment (strump) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:156]: Added a comment to `updateTts()` and `initTtsLangInfoLink()` methods

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 8]
```diff
@@ -241,38 +232,47 @@ public void onViewCreated(View view, @Nullable Bundle savedInstanceState)
...
+      initLargeFontSizePrefsCallbacks();
+      initTransliterationPrefsCallbacks();
+      init3dModePrefsCallbacks();
+      initPerspectivePrefsCallbacks();
+      initAutoZoomPrefsCallbacks();
+      initLoggingEnabledPrefsCallbacks();
+      initEmulationBadStorage();
+      initUseMobileDataPrefsCallbacks();
+      initPowerManagementPrefsCallbacks();
+      boolean playServices = initPlayServicesPrefsCallbacks();
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java]: Added `final` keyword

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java [hunk 9]
```diff
@@ -344,24 +346,24 @@ else if (preference.getKey() != null && preference.getKey().equals(getString(R.s
...
-      String TTS_INFO_LINK = requireActivity().getString(R.string.tts_info_link);
-      mLangInfoLink.setOnPreferenceClickListener(preference -> {
-        final Intent intent = new Intent(Intent.ACTION_VIEW);
-        intent.setData(Uri.parse(TTS_INFO_LINK));
-        requireContext().startActivity(intent);
-        return false;
-      });
-      removePreference(getString(R.string.pref_navigation), mLangInfoLink);
-    }
+    Preference ttsLangInfoLink = getPreference(getString(R.string.pref_tts_info_link));
```
[the remark this answers is not in the document]
Comment (strump) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java]: Added `final` keyword

**Review by biodranik — APPROVED** [review]
@strump please rebase and squash relevant commits (I would leave the crash fix separately).

And also add [android] to all commits (you can do it during `git rebase -i master` by inserting `r` (reword) to commits.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java (hunk 7 above)
Comment (strump) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java:363]: Java doesn't support `_` as an argument name. Let's keep it as `preference`.

File: android/src/app/organicmaps/settings/SettingsPrefsFragment.java (hunk 6 above)
Comment (biodranik) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java]: Interesting, what editors do not support UTF-8 text?

Comment (biodranik) [reply android/src/app/organicmaps/settings/SettingsPrefsFragment.java]: Using \U*** makes code reviewing harder...

**Review by biodranik — APPROVED** [review]
It would be better to have the crash fix commit separately from the refactoring, but let's move on for now.
LGTM

@rtsisyk merge?

**Review by vng — APPROVED** [review]
