### PR TITLE
[ios] Fix: New bookmark list placement

### LINKED ISSUE #9205: [ios] Adding new bookmark list puts it at the bottom of all lists
But lists should be sorted by "recently used", the last modified list should be at the top.

That leads to a visual bug that new lists are added at the bottom, but after closing and opening the dialog again, the newly added list is at the top.

CC @organicmaps/ios

### PR DESCRIPTION
**Pull request by narwalayush4**
* Fixes #9205 

Description:
- New row was being inserted at the end of the section, Should be on the top
- `getCategories()` function sorts the categories to update the table data source

| Before | After |
|--------|--------|
| https://github.com/user-attachments/assets/5454116e-ffbe-47dc-a808-7dd009fc7375 | https://github.com/user-attachments/assets/9a01b65d-22a9-4e64-930a-60d7795692a9 |

### CODE REVIEW

**Comment by zyphlar** [comment]
The before/after videos appear to be opposite of the fix you describe, can you check them for accuracy? The new "after" behavior is that entries will be added to the top, correct?

**Comment by narwalayush4** [comment]
Yep, "after" behaviour is when entries are added to the top.

Had uploaded the videos in the wrong order. Have fixed it now.

File: iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift [hunk 1]
```diff
@@ -129,7 +129,8 @@ extension BMCDefaultViewModel {
     }
 
     categories.append(manager.category(withId: manager.createCategory(withName: name)))
-    view?.insert(at: [IndexPath(row: categories.count - 1, section: section)])
+    categories = getCategories()
```
Comment (kirylkaveryn) [inline iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift:132]: This line is redundant because you append the new item to the `categories` and then reassing the whole property.
You can insert the new category as a first element both in the `category` and the `tableView`:
```swift
    categories.insert(manager.category(withId: manager.createCategory(withName: name)), at: 0)
    view?.insert(at: [IndexPath(row: 0, section: section)])
```

Comment (narwalayush4) [reply iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift:132]: Yep, better to insert at the desired postion. Saves unnecessary sorting.

**Review by kirylkaveryn — APPROVED** [review]

**Comment by narwalayush4** [comment]
@kirylkaveryn Hi, I am new here. What are the next steps to get this PR merged? Do I have to ask for a second review? If yes, then are there specific reviewers for different sectors, like ios and android?

**Review by vng — APPROVED** [review]
