### PR TITLE
Fix Estonia and Germany road shields

### LINKED ISSUE #873: All road ref numbers are displayed.
Tallinn is littered with road ref numbers, map is hard to use.
They should be displayed only for important roads or there should be an option to turn them off.

изображение

### PR DESCRIPTION
**Pull request by pastk**
Closes #873

Fixes shields' colors also (there was no orange previously).

Partly reverts https://github.com/organicmaps/organicmaps/commit/17b97eed76fea9e617ad5b0ccc4c535784c2a956 which demoted tertiary/residential shields from z12- to z15-/z18- to help with Tallinn case.
This PR brings tertiary/residential shields to z13-/z15-.
(ideally shields' visibility and priority should be determined by the route importance (national/regional/etc.) and not by a road class its being displayed on)

estonia-shields

### CODE REVIEW

File: indexer/road_shields_parser.cpp [hunk 1]
```diff
@@ -126,7 +136,17 @@ class RoadShieldParser
       else
       {
         shield = ParseRoadShield(rawText.substr(slashPos + 1));
-        shield.m_type = FindNetworkShield(std::string(rawText.substr(0, slashPos)));
+        // TODO: use a network-based shield type override only if a parser couldn't make it
+        // more specific than country's default shield type.
+        // E.g. "94" is set to Generic_Orange by Estonia parser, but then
+        // is overriden by "ee:national" => Generic_Red.
+        // (can't override just RoadShieldType::Default, as e.g. Russia parser uses Generic_Blue as country default).
+        if (shield.m_type != RoadShieldType::Hidden)
```
Comment (vng) [inline indexer/road_shields_parser.cpp:144]: Please, add/update unit tests for this Estonian logic.

File: indexer/road_shields_parser.cpp [hunk 2]
```diff
@@ -487,7 +507,7 @@ class FinlandRoadShieldParser : public NumericRoadShieldParser
                                                {40, 99, RoadShieldType::Generic_Orange},
                                                {100, 999, RoadShieldType::Generic_White},
                                                {1000, 9999, RoadShieldType::Generic_Blue},
-                                               {10000, 60000, RoadShieldType::Hidden}})
+                                               {10000, std::numeric_limits<uint16_t>::max(), RoadShieldType::Hidden}})
```
Comment (vng) [inline indexer/road_shields_parser.cpp:510]: Add kHighRoadNumber constant near NumericRoadShieldParser instead of boring std::numeric_limits<uint16_t>::max()?

Comment (pastk) [reply indexer/road_shields_parser.cpp:510]: done

File: indexer/road_shields_parser.cpp (hunk 1 above)
Comment (pastk) [reply indexer/road_shields_parser.cpp:144]: done

**Comment by pastk** [comment]
Also fixes #4881 

PTAL!

**Review by vng — APPROVED** [review]

**Comment by chereskata** [comment]
Looks promising to me. Unfortunately i have not setup an devenv for organic maps.

Could someone verify these locations?

Colour of  `A 45` and `B 54` road shields at 51.443575, 7.485097 as well as `B 236` colors at 51.578206, 7.494359

All these shields are currently white (which is obviously wrong)

Thanks :)

**Comment by pastk** [comment]
Sorry I'm on a very limited internet traffic allowance ATM, so I hesitate to download this map..
But its Germany also (I've tested on Munich already) and the code for the whole Germany is the same, so it should work fine there too.

Of course, it won't hurt if someone would double-check in those locations! Thanks in advance!

**Comment by dvdmrtnz** [comment]
> Looks promising to me. Unfortunately i have not setup a devenv for organic maps.
> 
> Could someone verify these locations?
> 
> Colour of `A 45` and `B 54` road shields at 51.443575, 7.485097 as well as `B 236` colors at 51.578206, 7.494359
> 
> All these shields are currently white (which is obviously wrong)
> 
> Thanks :)

**Comment by pastk** [comment]
Thanks for testing!

Rebased, ready to merge IMO
@vng @biodranik
