### PR TITLE
KMB import fix

### LINKED ISSUE #5718: [android] Import Bookmarks and Tracks button does not import Maps.Me bookmarks anymore
Maps.Me changed the internal KMB bookmarks format, and without knowing what exactly has changed (Maps.Me is a closed-source app), Organic Maps can't import bookmarks. See also #5638

A possible import workaround is to manually export each bookmark list from Maps.Me (select Share in the menu when you press ... on the left from the list's title), and immediately open it in Organic Maps.

From Android perspective, it's better to properly notify users about the failed import and suggest a workaround.

One of the possible solutions is to reverse-engineer what bytes have changed in KMB and ignore them in our code. For that, an older version of the same bookmark KMB file can be compared with a newer one.

```
08-13 20:54:52.080 (main) D/BookmarkCategoriesFragment: onActivityResult(): Importing bookmarks from content://com.android.externalstorage.documents/tree/primary%3AMapsWithMe%2Fbookmarks
08-13 20:54:52.083 (main) D/AppBackgroundTracker: onActivityStarted(): onActivityStarted activity = app.organicmaps.bookmarks.BookmarkCategoriesActivity@6ce6b20
08-13 20:54:52.088 (main) I/BaseActivityDelegate: logLifecycleMethod(): BookmarkCategoriesActivity: onStart() activity: app.organicmaps.bookmarks.BookmarkCategoriesActivity@6ce6b20
08-13 20:54:52.089 (main) D/AppBackgroundTracker: onActivityResumed(): onActivityResumed activity = app.organicmaps.bookmarks.BookmarkCategoriesActivity@6ce6b20
08-13 20:54:52.091 (main) I/BaseActivityDelegate: logLifecycleMethod(): BookmarkCategoriesActivity: onResume() activity: app.organicmaps.bookmarks.BookmarkCategoriesActivity@6ce6b20
08-13 20:54:52.092 (main) I/BaseActivityDelegate: logLifecycleMethod(): BookmarkCategoriesActivity: onPostResume() activity: app.organicmaps.bookmarks.BookmarkCategoriesActivity@6ce6b20
08-13 20:54:52.095 (pool-3-thread-1) D/StorageUtils: listContentProviderFilesRecursively(): docId: primary:MapsWithMe/bookmarks/New list.kmb, name: New list.kmb, mime: application/octet-stream
08-13 20:54:52.113 (pool-3-thread-1) W/BookmarkManager: importBookmarksFile(): Downloading bookmarks file content://com.android.externalstorage.documents/tree/primary%3AMapsWithMe%2Fbookmarks/document/primary%3AMapsWithMe%2Fbookmarks%2FNew%20list.kmb with file name New list.kmb
08-13 20:54:52.144 (pool-3-thread-1) D/StorageUtils: listContentProviderFilesRecursively(): docId: primary:MapsWithMe/bookmarks/doc.kmb, name: doc.kmb, mime: application/octet-stream
08-13 20:54:52.161 (pool-3-thread-1) W/BookmarkManager: importBookmarksFile(): Downloading bookmarks file content://com.android.externalstorage.documents/tree/primary%3AMapsWithMe%2Fbookmarks/document/primary%3AMapsWithMe%2Fbookmarks%2Fdoc.kmb with file name doc.kmb
08-13 20:54:52.179 (pool-3-thread-1) D/StorageUtils: listContentProviderFilesRecursively(): docId: primary:MapsWithMe/bookmarks/My Places.kmb, name: My Places.kmb, mime: application/octet-stream
08-13 20:54:52.191 (pool-3-thread-1) W/BookmarkManager: importBookmarksFile(): Downloading bookmarks file content://com.android.externalstorage.documents/tree/primary%3AMapsWithMe%2Fbookmarks/document/primary%3AMapsWithMe%2Fbookmarks%2FMy%20Places.kmb with file name My Places.kmb
08-13 20:54:52.194 (main) D/BookmarkManager: loadBookmarksFile(): Loading bookmarks file from: /data/user/0/app.organicmaps/cache/New list.kmb
08-13 20:54:52.195 (main) D/BookmarkManager: loadBookmarksFile(): Loading bookmarks file from: /data/user/0/app.organicmaps/cache/doc.kmb
08-13 20:54:52.219 (pool-3-thread-1) D/StorageUtils: listContentProviderFilesRecursively(): docId: primary:MapsWithMe/bookmarks/bm.order, name: bm.order, mime: application/octet-stream
08-13 20:54:52.224 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:426 LoadKmlData(): KML Binary deserialization failure: DeserializeException /home/runner/work/organicmaps/organicmaps/kml/serdes_binary.hpp:160, "Incorrect file version."
08-13 20:54:52.225 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:332 LoadKmlFile(): Loading bookmarks failed, file /data/user/0/app.organicmaps/files/bookmarks/New list.kmb1.kml
08-13 20:54:52.232 (main) D/BookmarkManager: loadBookmarksFile(): Loading bookmarks file from: /data/user/0/app.organicmaps/cache/My Places.kmb
08-13 20:54:52.260 (pool-3-thread-1) D/StorageUtils: listContentProviderFilesRecursively(): docId: primary:MapsWithMe/bookmarks/doc1.kmb, name: doc1.kmb, mime: application/octet-stream
08-13 20:54:52.576 (pool-3-thread-1) W/BookmarkManager: importBookmarksFile(): Downloading bookmarks file content://com.android.externalstorage.documents/tree/primary%3AMapsWithMe%2Fbookmarks/document/primary%3AMapsWithMe%2Fbookmarks%2Fdoc1.kmb with file name doc1.kmb
08-13 20:54:52.601 (main) D/BookmarkManager: loadBookmarksFile(): Loading bookmarks file from: /data/user/0/app.organicmaps/cache/doc1.kmb
08-13 20:54:52.611 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:426 LoadKmlData(): KML Binary deserialization failure: DeserializeException /home/runner/work/organicmaps/organicmaps/kml/serdes_binary.hpp:160, "Incorrect file version."
08-13 20:54:52.614 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:332 LoadKmlFile(): Loading bookmarks failed, file /data/user/0/app.organicmaps/files/bookmarks/doc.kmb1.kml
08-13 20:54:52.617 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:421 LoadKmlData(): KML Binary reading failure: Reader::SizeException /home/runner/work/organicmaps/organicmaps/coding/file_reader.cpp:127, "313 1 313"
08-13 20:54:52.619 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:332 LoadKmlFile(): Loading bookmarks failed, file /data/user/0/app.organicmaps/cache/My Places.kmb
08-13 20:54:52.742 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:426 LoadKmlData(): KML Binary deserialization failure: DeserializeException /home/runner/work/organicmaps/organicmaps/kml/serdes_binary.hpp:160, "Incorrect file version."
08-13 20:54:52.743 (Thread-3) W/OMcore: map/bookmark_helpers.cpp:332 LoadKmlFile(): Loading bookmarks failed, file /data/user/0/app.organicmaps/files/bookmarks/doc1.kmb1.kml
```

### PR DESCRIPTION
**Pull request by strump**
The main problem with updated KMB format that version ID is not changed. KMB file is generated with version `V8` while internal changes are incompatible with `V8`. Introduced new version `V8MM` for new KMB files format.

KBM v8MM files don't have compilations. I removed compilations from the code. Tracks data has extra 3 bytes with unknown purpose. Also timestamp is now stored as milliseconds instead of seconds.

Updated unit tests.

### Changes in `kml_to_kmb` tool

`kml_to_kmb` now accepts optional version parameter. It can generate not only files in V9 (latest) format but with V8.
This was needed to generate test data in V8 format.

Fixes #5718

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Is it possible to create a subtype for version81 and incorporate all fixes there?

File: kml/types_v8.hpp [hunk 1]
```diff
@@ -21,7 +21,7 @@ struct BookmarkDataV8
                                   visitor(m_visible, "visible"),
                                   visitor(m_nearestToponym, "nearestToponym"),
                                   visitor(m_properties, "properties"),
-                                  visitor(m_compilations, "compilations"),
+                                  //visitor(m_compilations, "compilations"),
```
Comment (vng) [inline kml/types_v8.hpp:24]: So the HasCompilationsSection() should be enough, no?
Why comment here? Let's keep as-is.

File: kml/types.hpp [hunk 2]
```diff
@@ -388,7 +388,7 @@ struct TrackData
 struct CategoryData
 {
   DECLARE_VISITOR_AND_DEBUG_PRINT(CategoryData, visitor(m_id, "id"),
-                                  visitor(m_compilationId, "compilationId"),
+                                  //visitor(m_compilationId, "compilationId"),
```
Comment (vng) [inline kml/types.hpp:391]: So the HasCompilationsSection() should be enough, no?
Why comment here? Let's keep as-is.

File: kml/types_v8.hpp (hunk 1 above)
Comment (strump) [reply kml/types_v8.hpp:24]: Not only compilations section is disabled but also Bookmark and Category fields list should be updated. If I enable back "compilations" field parsing would fail.

**Comment by biodranik** [comment]
@strump was you able to decompile the new format? What exactly changed there?

It would be great to make a proper kmb support before Monday, we likely push the release for the review.

File: kml/kml_to_kmb/kml_to_kmb.cpp [hunk 3]
```diff
@@ -11,11 +12,25 @@
...
     std::cout << "Converts kml file to kmb\n";
-    std::cout << "Usage: " << argv[0] << " path_to_kml_file\n";
+    std::cout << "Usage: " << argv[0] << " path_to_kml_file [KBM_FORMAT_VERSION]\n";
+    std::cout << "KBM_FORMAT_VERSION could be V8, V9, or Latest (default)\n";
     return 1;
   }
+  kml::binary::Version outVersion = kml::binary::Version::Latest;
+  if (argc >= 3)
+  {
+    std::string versionStr = argv[2];
```
Comment (biodranik) [inline kml/kml_to_kmb/kml_to_kmb.cpp:25]:
```suggestion
    std::string const versionStr = argv[2];
```

File: kml/types_v8.hpp [hunk 4]
```diff
@@ -46,6 +46,33 @@ struct BookmarkDataV8
 
   bool operator!=(BookmarkDataV8 const & data) const { return !operator==(data); }
 
+  BookmarkDataV8()
+  {
+
+  }
```
Comment (biodranik) [inline kml/types_v8.hpp:52]: Is it really needed?
```suggestion
  BookmarkDataV8() = default;
```

File: kml/types_v8.hpp [hunk 5]
```diff
@@ -46,6 +46,33 @@ struct BookmarkDataV8
...
+
+  // Initialize using latest version of BookmarkData
+  BookmarkDataV8(BookmarkData src)
```
Comment (biodranik) [inline kml/types_v8.hpp:55]:
```suggestion
  BookmarkDataV8(BookmarkData const & src)
```

**Review by biodranik — APPROVED** [review]
LGTM with minor comments.

**Comment by biodranik** [comment]
@strump some KML tests are failing.

File: kml/types.hpp [hunk 6]
```diff
@@ -503,4 +502,10 @@ inline std::string DebugPrint(BookmarkIcon icon)
 {
   return ToString(icon);
 }
+
+inline std::string DebugPrint(TimestampMillis const & ts)
+{
+  return DebugPrint(static_cast<Timestamp>(ts));
```
Comment (strump) [inline kml/types.hpp:508]: Compiler shows warning: `all paths through this function will call itself` because types `Timestamp` and `TimestampMillis` could be converted to one another. Is there any way to force use `DebugPrint(Timestamp)` function from `base/internal/message.hpp` ?

File: kml/types_v8.hpp (hunk 5 above)
Comment (strump) [reply kml/types_v8.hpp]: Fixed

File: kml/types_v8.hpp (hunk 4 above)
Comment (strump) [reply kml/types_v8.hpp]: Fixed.
We need default constructor to initialize `std::vector<BookmarkDataV8> m_bookmarksData;` field in FileDataV8

File: kml/kml_to_kmb/kml_to_kmb.cpp (hunk 3 above)
Comment (strump) [reply kml/kml_to_kmb/kml_to_kmb.cpp]: Fixed

**Comment by biodranik** [comment]
@strump fixed, force-pushed (delete your local branch and get this one again).

Why visibility=0 in kml created from kmb files? Is it a bug?

**Comment by biodranik** [comment]
@strump rebased PR, please check remaining comments.

File: kml/serdes_binary_v8.hpp [hunk 7]
```diff
@@ -0,0 +1,93 @@
...
+{
+// This class generates KMB files in format V8.
+// The only difference between V8 and V9 (Latest) is bookmarks structure.
+class SerializerKmlV8 : public SerializerKml
+{
+public:
+  explicit SerializerKmlV8(FileData & data) : SerializerKml(data) {};
+
+  template <typename Sink>
+  void Serialize(Sink & sink)
```
[the remark this answers is not in the document]
Comment (biodranik) [reply kml/serdes_binary_v8.hpp:25]: That's ok.

**Comment by biodranik** [comment]
@strump are tracks imported properly? What are the example values of these 3 unknown bytes for different tracks?

File: map/bookmark_manager.cpp [hunk 8]
```diff
@@ -1867,7 +1867,7 @@ void BookmarkManager::LoadBookmarkRoutine(std::string const & filePath, bool isT
     std::string fileSavePath = GetKMLPath(filePath);
     if (!fileSavePath.empty())
     {
-      auto const ext = GetLowercaseFileExt(filePath);
+      auto const ext = GetLowercaseFileExt(fileSavePath);
```
Comment (strump) [inline map/bookmark_manager.cpp:1870]: When you import KMB file it is converted to KML first in `GetKMLPath(...)` function and then KML is imported.
In such case `filePath = "some_file.kmb` and `fileSavePath = "some_file.kmb2.kml"`. Because we parse `fileSavePath` we should get extension correctly here.

File: map/bookmark_manager.cpp [hunk 9]
```diff
@@ -1893,6 +1893,8 @@ void BookmarkManager::LoadBookmarkRoutine(std::string const & filePath, bool isT
         else
           collection->emplace_back(std::move(fileSavePath), std::move(kmlData));
       }
+      else
+        base::DeleteFileX(fileSavePath);
```
Comment (strump) [inline map/bookmark_manager.cpp:1897]: In my cases there was a problem with `fileSavePath` parsing and temp files were not cleaned up.

File: kml/types_v8mm.hpp [hunk 10]
```diff
@@ -0,0 +1,314 @@
...
+    data.m_properties = m_properties;
+    return data;
+  }
+
+  bool operator!=(CategoryDataV8MM const & data) const { return !operator==(data); }
+
+  // Unique id (it will not be serialized in text files).
+  MarkGroupId m_id = kInvalidMarkGroupId;
+  // Compilation's type
+  CompilationType m_type = CompilationType::Category;
```
Comment (strump) [inline kml/types_v8mm.hpp:235]: Appeared that V8MM format doesn't have `m_type` field. Because of that we had `m_visibility = false`. Using default `m_type` for all V8MM.

File: map/bookmark_manager.cpp (hunk 8 above)
Comment (biodranik) [reply map/bookmark_manager.cpp:1870]: It would be even better to see these comments in the code instead of the PR ;-)

File: kml/types_v8mm.hpp (hunk 10 above)
Comment (biodranik) [reply kml/types_v8mm.hpp:235]: IT also make sense to mention in the code.

File: map/bookmark_manager.cpp (hunk 9 above)
Comment (biodranik) [reply map/bookmark_manager.cpp:1897]: Both if and else branches have this line. Put it before the if.

Comment (biodranik) [reply map/bookmark_manager.cpp:1897]: What kind of problem did you have with parsing? Should it be fixed/handled properly?

File: kml/serdes_binary_v8.hpp [hunk 11]
```diff
@@ -0,0 +1,93 @@
+#pragma once
+
+#include "kml/serdes_binary.hpp"
+#include "kml/types_v8.hpp"
+#include "kml/types.hpp"
+#include "kml/visitors.hpp"
+
+
```
Comment (biodranik) [inline kml/serdes_binary_v8.hpp:8]: nit: remove unnecessary newline

File: kml/serdes_binary_v8.hpp [hunk 12]
```diff
@@ -0,0 +1,93 @@
...
+#include <string>
+#include <vector>
+
+
```
Comment (biodranik) [inline kml/serdes_binary_v8.hpp:12]: nit: remove unnecessary newline

File: kml/serdes_binary_v8.hpp [hunk 13]
```diff
@@ -0,0 +1,93 @@
...
+namespace kml
+{
+namespace binary
```
Comment (biodranik) [inline kml/serdes_binary_v8.hpp:15]: namespace kml::binary

File: kml/types_v8mm.hpp [hunk 14]
```diff
@@ -0,0 +1,314 @@
+#pragma once
+
+#include "kml/types.hpp"
+
+namespace kml
+{
+// BookmarkDataV8MM contains the same fields as BookmarkDataV8 but with no compilations
```
Comment (biodranik) [inline kml/types_v8mm.hpp:7]:
```suggestion
// BookmarkDataV8MM contains the same fields as BookmarkDataV8 but without compilations.
```
nit: Have dots at the end of sentences.

File: map/bookmark_manager.cpp (hunk 8 above)
Comment (strump) [reply map/bookmark_manager.cpp]: Reviewed this part of code because `ext` is always `"kml"`.

File: map/bookmark_manager.cpp (hunk 9 above)
Comment (strump) [reply map/bookmark_manager.cpp]: If input KML/KMZ file has invalid format we get `kmlData == nullptr`.

File: kml/types_v8mm.hpp (hunk 10 above)
Comment (strump) [reply kml/types_v8mm.hpp]: Removed this field completly. Added comment.

File: kml/serdes_binary_v8.hpp (hunk 11 above)
Comment (strump) [reply kml/serdes_binary_v8.hpp]: Fixed.

File: kml/serdes_binary_v8.hpp (hunk 12 above)
Comment (strump) [reply kml/serdes_binary_v8.hpp]: Fixed.

File: kml/serdes_binary_v8.hpp (hunk 13 above)
Comment (strump) [reply kml/serdes_binary_v8.hpp]: Fixed

File: kml/types_v8mm.hpp (hunk 14 above)
Comment (strump) [reply kml/types_v8mm.hpp]: Fixed.

File: map/bookmark_manager.cpp (hunk 8 above)
Comment (biodranik) [reply map/bookmark_manager.cpp]: Did you add a comment in the code? Btw, why is it always kml there?

File: map/bookmark_manager.cpp [hunk 15]
```diff
@@ -1864,28 +1864,19 @@ void BookmarkManager::LoadBookmarkRoutine(std::string const & filePath, bool isT
 
     auto collection = std::make_shared<KMLDataCollection>();
 
+    // Convert KML/KMZ/KMB files to temp KML file.
     std::string fileSavePath = GetKMLPath(filePath);
     if (!fileSavePath.empty())
     {
-      auto const ext = GetLowercaseFileExt(filePath);
       std::unique_ptr<kml::FileData> kmlData;
-      if (ext == ".kml" || ext == ".kmz")
```
Comment (biodranik) [inline map/bookmark_manager.cpp:1872]: Are you 100% sure that this code should be removed? Did you test it with other file types? Is it guaranteed that this code is called only for kml/kmz files?

Comment (strump) [reply map/bookmark_manager.cpp:1872]: I tested with KML, KMZ, KMB, and GPX files.
Found an issue with GPX and fixed. Current implementation imports all formats successfully.

One questionable part: KMB is first converted to temp KML and then KML is converted to final KML. Maybe we can skip temporary step.

Nice to have: unit tests 🙂

Comment (biodranik) [reply map/bookmark_manager.cpp:1872]: Converting kml to kml doesn't look necessary ) Is it easy to fix?

File: map/bookmark_helpers.cpp [hunk 16]
```diff
@@ -336,18 +345,27 @@ std::unique_ptr<kml::FileData> LoadKmlFile(std::string const & file, KmlFileType
...
+  if (fileExt == kKmlExtension)
   {
+    // Copy input file to temp output KML with unique name.
     fileSavePath = GenerateValidAndUniqueFilePathForKML(base::FileNameFromFullPath(filePath));
     if (!base::CopyFileX(filePath, fileSavePath))
       return {};
   }
+  else if (fileExt == kGpxExtension)
+  {
+    // Copy input file to temp GPX with unique name.
```
Comment (biodranik) [inline map/bookmark_helpers.cpp:361]: Why is this copying necessary?

File: map/bookmark_manager.cpp [hunk 17]
```diff
@@ -1806,13 +1806,13 @@ BookmarkManager::KMLDataCollectionPtr BookmarkManager::LoadBookmarks(
...
-    if (kmlData == nullptr)
+    if (!kmlData)
       continue;
-    if (checker && !checker(*kmlData))
+    if (checker && !checker(kmlData.value()))
       continue;
     if (m_needTeardown)
       break;
-    collection->emplace_back(filePath, std::move(kmlData));
+    collection->emplace_back(filePath, std::unique_ptr<kml::FileData>(&kmlData.value()));
```
Comment (strump) [inline map/bookmark_manager.cpp:1815]: `collection` has type `std::vector<std::pair<std::string, std::unique_ptr<kml::FileData>>>`
I converted `std::optional<kml::FileData>` to `std::unique_ptr<kml::FileData>` here.

Comment (biodranik) [reply map/bookmark_manager.cpp:1815]: Good question, likely yes, if the collection is not moved often. Moving unique_ptr is cheaper than moving FileData.

Otherwise:
```suggestion
    collection->emplace_back(filePath, std::make_unique<kml::FileData>(std::move(kmlData)));
```

Comment (strump) [reply map/bookmark_manager.cpp:1815]: Your suggested code doesn't work. Compilation error:
`error: no matching constructor for initialization of 'kml::FileData'`

Replaced with:
`std::make_unique<kml::FileData>(std::move(kmlData.value()))`

File: kml/type_utils.hpp [hunk 18]
```diff
@@ -16,6 +16,17 @@ namespace kml
 {
 using TimestampClock = std::chrono::system_clock;
 using Timestamp = std::chrono::time_point<TimestampClock>;
+class TimestampMillis : public Timestamp {
+public:
+  TimestampMillis() = default;
+  explicit TimestampMillis(Timestamp const & ts) : Timestamp{ts} {}
+  TimestampMillis & operator=(Timestamp const & ts)
```
Comment (vng) [inline kml/type_utils.hpp:23]: I suspect it is not needed.

**Review by vng — COMMENTED** [review]
So you what was the reason to modify existing code with optional,
and then writing 
```
std::make_unique<kml::FileData>(std::move(kmlData.value())))
```

File: kml/kml_tests/tests_data.hpp [hunk 19]
```diff
@@ -1523,3 +1523,124 @@ std::vector<uint8_t> const kBinKmlV7 = {
   0xCB, 0x2D, 0x8A, 0x8C, 0xC0, 0xB2, 0x02, 0x13, 0xE8, 0x9B, 0xBA, 0x48, 0xC8, 0x77, 0x91, 0x88,
   0xC7, 0x06, 0x6C, 0xE1, 0x03, 0x64, 0xBC, 0xEC, 0x43, 0x02, 0x01, 0x00, 0x29,
 };
+
+// kBinKmlV8 contains the same bookmarks and tracks as kBinKmlV7
+std::vector<uint8_t> const kBinKmlV8 = {
```
Comment (rtsisyk) [inline kml/kml_tests/tests_data.hpp:1528]: Is it possible to push an ordinary file into the repository instead of this?

File: qt/screenshoter.cpp [hunk 20]
```diff
@@ -175,20 +175,20 @@ void Screenshoter::PrepareToProcessKml()
 void Screenshoter::ProcessNextKml()
 {
   std::string const postfix = "_" + languages::GetCurrentNorm();
-  std::unique_ptr<kml::FileData> kmlData;
-  while (kmlData == nullptr && !m_filesToProcess.empty())
+  std::optional<kml::FileData> kmlData;
+  while (!kmlData && !m_filesToProcess.empty())
```
Comment (biodranik) [inline qt/screenshoter.cpp:179]: Neither external variable nor !kmlData checks are necessary.

File: map/map_tests/kmz_unarchive_test.cpp [hunk 21]
```diff
@@ -10,28 +10,30 @@
...
+  std::string const filePath = GetKMLorGPXPath(kmzFile);
 
   TEST(!filePath.empty(), ());
   SCOPE_GUARD(fileGuard, std::bind(&base::DeleteFileX, filePath));
 
   TEST(strings::EndsWith(filePath, "doc.kml"), (filePath));
 
   auto const kmlData = LoadKmlFile(filePath, KmlFileType::Text);
-  TEST(kmlData != nullptr, ());
+  TEST(kmlData.has_value(), ());
```
Comment (biodranik) [inline map/map_tests/kmz_unarchive_test.cpp:21]:
```suggestion
  TEST(kmlData, ());
```

File: map/map_tests/bookmarks_test.cpp [hunk 22]
```diff
@@ -1391,6 +1396,6 @@ UNIT_CLASS_TEST(Runner, Bookmarks_BrokenFile)
 {
   string const fileName = GetPlatform().TestsDataPathForFile("broken_bookmarks.kmb.test");
   auto kmlData = LoadKmlFile(fileName, KmlFileType::Binary);
-  TEST(kmlData == nullptr, ());
+  TEST(!kmlData.has_value(), ());
```
Comment (biodranik) [inline map/map_tests/bookmarks_test.cpp:1399]:
```suggestion
  TEST(!kmlData, ());
```

**Review by vng — APPROVED** [review]

**Review by biodranik — APPROVED** [review]
@strump let's make a follow-up issue with KML tasks/improvements mentioned in this PR.
