### PR TITLE
[Android] Minor UI fixes

### LINKED ISSUE #8520: [Android] Download progress on the map jumps after 10%
For different languages it may work differently.

https://github.com/organicmaps/organicmaps/assets/170263/d697f318-e5e1-407e-8f1c-c82055a842aa

Maybe scale the font size and make more horizontal space for the label?

### PR DESCRIPTION
**Pull request by hemanggs**
1. `RoutingErrorDialogFragment`

| Before | After |
|---------|---------|
| WhatsApp Image 2025-02-13 at 23 39 58_b8e4e7ac | WhatsApp Image 2025-02-13 at 23 39 58_b1e4ceb6  |

2.  **[Suggestion]** In Stop Track recording dialog box , this ordering of buttons more intuitive  ( Having Save button at last seemed really un-intuitive when i used it , thoughts? )

| Before | After |
|---------|---------|
| WhatsApp Image 2025-02-13 at 18 39 26_c329f576 |WhatsApp Image 2025-02-13 at 19 19 56_70e6637e | 

3.  Fixes #8520
- Although i only got this issue when using really large Font size , not normally as described in the issue.

Before: 

https://github.com/user-attachments/assets/16da8983-021b-4cdb-a3b2-4a13ab037f04

After: 

https://github.com/user-attachments/assets/bcd08a45-d608-40a2-b712-87219b90a78a

4. Reverted Opening hours icon tint .

### CODE REVIEW

**Comment by patepelo** [comment]
Hey @hemanggs You're on fire 🔥 Most of the suggested changes look good at first glance. Can we separate style changes into a different PR?

**Comment by hemanggs** [comment]
Sure ,Thanks!

**Comment by Jean-BaptisteC** [comment]
For `RoutingErrorDialogFragment` maybe try to find a short sentence?

**Comment by hemanggs** [comment]
> For `RoutingErrorDialogFragment` maybe try to find a short sentence? `Download map to create optimal route?`

Yeah sure we can use a shorter message , but still even with a shorter message , for larger UI's (large font & display size in accessibility settings ) , the whole message is not visible , since it was limited to 2 lines only .

**Comment by hemanggs** [comment]
how about these 

This region's map isn’t downloaded. Download now?

or

Download the map to navigate this area?

or 

You need to download this map to proceed.

File: android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java [hunk 1]
```diff
@@ -35,7 +38,15 @@ void beforeDialogCreated(AlertDialog.Builder builder)
         ResultCodesHelper.getDialogTitleSubtitle(requireContext(), mResultCode, mMissingMaps.size());
     Pair<String, String> titleMessage = resHolder.getTitleMessage();
 
-    builder.setTitle(titleMessage.first);
+    TextView titleView = new TextView(requireContext());
+    titleView.setText(titleMessage.first);
+    titleView.setTextSize(18);
```
Comment (pastk) [inline android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java:43]: is it possible to not to force a fixed font size?

its better to have it adaptable according to system's settings

**Review by pastk — COMMENTED** [review]
Please separate the changes into separate commits.
No need to be shy and save on extra commits :)
Its much better when logically unrelated changes go to their own commits - the history is more clear and easier to browse, easier to revert if needed, etc.

File: android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java (hunk 1 above)
Comment (hemanggs) [reply android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java:43]: Yeah thats better  ,thanks.

**Comment by hemanggs** [comment]
> its better to have it adaptable according to system's settings


- Setting it to a  this `titleView.setTextSize(18);` does scale automatically according to system settings  , and its the closest to the dialog it is replacing   , what do you think ? 

| font = standard | font = large |
|---------|---------|
| aa38530d-e5d9-404b-a2d3-9341edb904d9|7630a1ea-1118-4e79-9136-7e6ccc4dca16|



- Although Removing the `titleView.setTextSize(18);` reverts to  [default](https://developer.android.com/develop/ui/views/text-and-emoji/autosizing-textview#default) auto scaling  ,but tbh its too small 

e97048d4-44b4-424d-9870-52b8d08363ab

File: android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java (hunk 1 above)
Comment (hemanggs) [reply android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java:44]: i did try using [setAutoSizeTextTypeUniformWithConfiguration](https://developer.android.com/reference/androidx/core/widget/TextViewCompat#setAutoSizeTextTypeUniformWithConfiguration(android.widget.TextView,int,int,int,int)) , but it has word wrapping issues :
2f29febe-07a1-4b4e-9465-757e0a9ed19e


  `titleView.setTextSize(18);` does seem to  perform  auto  scaling  if im not wrong , is that the what is required  ? i did'nt get what is intended here .

**Comment by hemanggs** [comment]
hearing_aids icon color change :


before ; 
image


after : 
image

shop color : 
image

**Comment by pastk** [comment]
Icon colors are somewhat different for dark and light versions.

Looks like you updated both to be "dark". Please re-check.

**Comment by pastk** [comment]
Also please run `generate_symbols.sh` afterwards. Don't worry about the big diff.

**Comment by hemanggs** [comment]
> Icon colors are somewhat different for dark and light versions.
> 
> Looks like you updated both to be "dark". Please re-check.

All the shop icons seem to have the same color for dark and light , #8C5F93  ,  i have set both to this color  for consistency


image

**Review by rtsisyk — APPROVED** [review]
