### PR TITLE
Qt 6.7 fix

### LINKED ISSUE #7838: [desktop][drape] Black screen with new Qt 6.7
After updating on Qt 6.7.
Qt 6.6.3 works fine.
Part of the init log, see "GLError: 1286"

```
LOG TID(1) INFO      1.12232 drape_frontend/visual_params.cpp:52 Init(): Visual scale = 2 ; Tile size = 1024 ; Resources = xhdpi
LOG TID(3) INFO      1.12317 drape_frontend/backend_renderer.cpp:724 Do(): Start routine.
LOG TID(3) INFO      1.12318 drape_frontend/backend_renderer.cpp:692 OnContextCreate(): On context create.
LOG TID(4) INFO      1.12402 drape_frontend/frontend_renderer.cpp:2401 Do(): Start routine.
LOG TID(4) INFO      1.12412 drape_frontend/frontend_renderer.cpp:2318 OnContextCreate(): On context create.
LOG TID(3) INFO      1.12845 drape/support_manager.cpp:35 Init(): Renderer = Apple M1 Pro | Api = OpenGLES3 | Version = 4.1 Metal - 88
LOG TID(4) INFO      1.12847 drape/gl_functions.cpp:1150 CheckGLError(): SrcPoint  drape/gl_functions.cpp:442 glClear():  GLError: 1286
LOG TID(3) INFO      1.12847 drape/support_manager.cpp:79 Init(): Max line width = 1 | Max texture size = 16384
LOG TID(4) INFO      1.12855 shaders/program_manager.cpp:68 InitForOpenGL(): VTF enabled
LOG TID(3) INFO      1.12864 platform/platform.cpp:215 GetFontNames(): Available font files: [10: 00_NotoNaskhArabic-Regular.ttf 00_NotoSansThai-Regular.ttf 00_NotoSerifDevanagari-Regular.ttf 01_dejavusans.ttf 02_droidsans-fallback.ttf 03_jomolhari-id-a3d.ttf 04_padauk.ttf 05_khmeros.ttf 06_code2000.ttf 07_roboto_medium.ttf ]
LOG TID(4) INFO      1.13033 drape/gl_functions.cpp:1150 CheckGLError(): SrcPoint  drape/gl_functions.cpp:442 glClear():  GLError: 1286
LOG TID(4) INFO      1.13041 drape/gl_functions.cpp:1150 CheckGLError(): SrcPoint  drape/gl_functions.cpp:442 glClear():  GLError: 1286
LOG TID(3) DEBUG     1.18301 drape/texture_manager.cpp:463 Init(): Patterns texture size = 512 512
LOG TID(3) DEBUG     1.18396 drape/texture_manager.cpp:480 Init(): Colors texture size = 64 64
```

@Ferenc- @renderexpert Maybe you have any ideas.

### PR DESCRIPTION
**Pull request by strump**
Closes #7838 

**Symptoms:** after call `glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)` in [map_widget.cpp](https://github.com/organicmaps/organicmaps/blob/master/qt/qt_common/map_widget.cpp#L429) we get error: `glGetError()` returns code 1282.

I searched for possible solutions and on Stackoverflow someone supposed this could be vertex buffer issue ([Stackoverflow answer 1](https://stackoverflow.com/a/49304885) and [Stackoverflow answer 2](https://stackoverflow.com/a/32527554)). Shaders in `gl_150.vsh.glsl`, `gles_200.vsh.glsl`, and `gles_300.vsh.glsl` read QVector4D from `"a_position"` input attribute.

I changed `a_position` assignment for OpenGL vertex shader using `glVertexAttribPointer(...)` which I saw in official Qt example https://doc.qt.io/qt-6/qtopengl-hellogles3-example.html

It works on my Mac M2 and Qt 6.7.2 from Brew. Please verify on Linux too.

### CODE REVIEW

File: qt/qt_common/map_widget.cpp [hunk 1]
```diff
@@ -420,10 +424,7 @@ void MapWidget::paintGL()
     int const samplerSizeLocation = m_program->uniformLocation("u_samplerSize");
     m_program->setUniformValue(samplerSizeLocation, samplerSize);
 
-    m_program->enableAttributeArray("a_position");
-    m_program->setAttributeBuffer("a_position", GL_FLOAT, 0, 4, 0);
-
-    funcs->glClearColor(0.0, 0.0, 0.0, 1.0);
+    funcs->glClearColor(0.5, 0.5, 0.5, 1.0);
```
Comment (vng) [inline qt/qt_common/map_widget.cpp:427]: Is changing clear colors necessary?

**Comment by vng** [comment]
@strump Could you please provide a SOF link here?
CC @renderexpert

File: qt/qt_common/map_widget.cpp (hunk 1 above)
Comment (strump) [reply qt/qt_common/map_widget.cpp:427]: Color change is optional. I just got bored of black 😉

**Comment by strump** [comment]
@vng  Stackoverflow answers I used (added also to the PR description):

* https://stackoverflow.com/a/49304885
* https://stackoverflow.com/a/32527554

Those answers doesn't give direct answer but hint to take a look at `glEnableVertexAttribArray(...)`.

**Comment by pastk** [comment]
> Please verify on Linux too.

No regressions on QT 6.4.2 Ubuntu 24.04 `Renderer = Mesa Intel(R) UHD Graphics 620 (WHL GT2) | Api = OpenGLES3 | Version = OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.2`

**Comment by strump** [comment]
@vng  AFAIK, you get `GLError: 1286` only on start when OpenGL context is not fully initialized. After drape engine and QtOpenGLWidget are fully initialized those errors are gone. If it's really important we can introduce some flag and don't call `glClear()` untill Qt app is initialized.

**Comment by Zverik** [comment]
Idk what exactly to test, but I should say, on Fedora 40 with Qt 6.7.2 the `master` branch build displays a black screen, while this one shows a map.

File: qt/qt_common/map_widget.cpp [hunk 2]
```diff
@@ -267,6 +267,10 @@ void MapWidget::Build()
                            QVector4D(-1.0, -1.0, 0.0, 0.0),
                            QVector4D(1.0, -1.0, 1.0, 0.0)};
   m_vbo->allocate(static_cast<void*>(vertices), sizeof(vertices));
+  QOpenGLFunctions *f = QOpenGLContext::currentContext()->functions();
+  f->glEnableVertexAttribArray(0);
+  f->glVertexAttribPointer(0, 4, GL_FLOAT, GL_FALSE, 4 * sizeof(GLfloat), nullptr);
+  m_vbo->release();
```
Comment (vng) [inline qt/qt_common/map_widget.cpp:273]: I'm not an expert, but is m_vbo->release() needed here and why it was absent before? Is it somehow connected with a bug?

- add a comment that 0-index is "a_position"
- add a reference to this PR in the code.
- add a reference to the issue in PR's description

Comment (strump) [reply qt/qt_common/map_widget.cpp:275]: Added comment about "a_position" binding. But as a novice in OpenGL it's possible that wording should be improved.

Added cross references.

Comment (strump) [reply qt/qt_common/map_widget.cpp:275]: By the way `m_vbo->release()` call could be immited. Don't know if we need it. OpenGL experts required.

Comment (strump) [reply qt/qt_common/map_widget.cpp]: Removed.

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
@Ferenc- Need your test and approve.

**Review by biodranik — APPROVED** [review]

**Comment by Osyotr** [comment]
It looks like these changes also fix OpenGL-related crashes that were observable on windows even before Qt 6.7 update.
Many thanks!

**Comment by vng** [comment]
squash would be better :)

**Comment by gerion0** [comment]
Can also confirm that it works for Gentoo Linux with Qt 6.7.2. Many thanks for the fix!

**Comment by Osyotr** [comment]
> squash would be better :)

IMHO squash should be the default option for this repo.

**Comment by strump** [comment]
Finally submitted a but to Qt bugtracker: https://bugreports.qt.io/browse/QTBUG-133382 (new link https://qt-project.atlassian.net/browse/QTBUG-133382)

I'm quirious what was the breaking change. But don't have much hope.
