### PR TITLE
Fix social contacts parsing on edits loading

### LINKED ISSUE #5509: Problem with the editor's handling of facebook URLs
**Describe the issue**

I don't know why, but facebook data is often duplicated when I edit a trade. I think this is the fourth time I've corrected this one. A Subdomain "people" seems to be responsible.

**Steps to reproduce**

1.  Insert a Facebook profile including "people" (https://facebook.com/people/...) in the editor's Facebook tab
2. Validate changes
3. See error

**Screenshots**

Screenshot_20230710_172906_Organic Maps
**System information:**

 - Operating system and its version: Android 13, One Ui, F-Droid
 - Organic Maps version: 2023.06.04-13-FDroid
 - Device Model: Samsung A23

**Additional context**

https://www.openstreetmap.org/changeset/138318657

### PR DESCRIPTION
**Pull request by strump**
The issue #5509 is caused by edits save/load. When POI is modified it's saved on device in OSM XML format using `editor::ToXML(...)` method with explicit social contacts processing. Function `editor::ApplyPatch(...)` loads OSM XML but skips social contacts normalization.

Method `EditableMapObject::UpdateMetadataValue` is used only within `xml_feature.cpp` so this fix should not affect OM functionality.

Closes #5509.

### CODE REVIEW

File: editor/editor_tests/xml_feature_test.cpp [hunk 1]
```diff
@@ -499,18 +499,6 @@ UNIT_TEST(XMLFeature_SocialContactsProcessing)
     osm::EditableMapObject emo;
     editor::FromXML(xmlFeature, emo);
 
-    // Read and write "contact:facebook" to apply normalization.
```
Comment (biodranik) [inline editor/editor_tests/xml_feature_test.cpp:502]: Why these tests are not needed?

Comment (strump) [reply editor/editor_tests/xml_feature_test.cpp:502]: Originally I wrote this test with steps:

1. Convert XML into EditableMapObject
2. Normalize social contacts to get shorter values
3. Convert EditableMapObject to XML
4. Verify XML content.

But after this PR step 2 is not needed.

**Review by biodranik — APPROVED** [review]
