### PR TITLE
[ios] Allow location update when app is in background

### LINKED ISSUE #6940: Background voice directions do not work on iOS
A follow-up of the #573

### PR DESCRIPTION
**Pull request by fabwu**
The app is configured to update the GPS location in the background but this information is not passed to the framework. 

With this commit the GPS location is passed to the framework even when the app is in background. This results in a higher battery usage if there is an active route but the battery usage will remain the same if no route is active because the GPS location is not updated.
    
Close #6940

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
How the Recent Track feature is working now without this change? Is updateFrameworkInfo needed for bg location to work? Where CPU cycles go?

**Comment by fabwu** [comment]
> How the Recent Track feature is working now without this change? 

I think the Recent Track's location is updated [here](https://github.com/organicmaps/organicmaps/blob/master/iphone/Maps/Core/Location/MWMLocationManager.mm#L308) and not in the framework update method. That's why the Recent Track is working but navigation is not.

> Is updateFrameworkInfo needed for bg location to work? 

Yes, the method updates the framework location by calling `f.OnLocationUpdate(gpsInfo);`. Without the location update the navigation just stops when the app is in the background.

> Where CPU cycles go?

If a navigation is active the CPU still calculates the current route in the background, so you'll have some CPU usage. If no navigation is active, iOS doesn't issue GPS updates and there's no CPU usage. I checked the CPU usage with the debugger.

**Comment by biodranik** [comment]
Thanks! Can the current route's location be updated at the same place where the recent track is updated?

File: iphone/Maps/Core/Location/MWMLocationManager.mm [hunk 1]
```diff
@@ -528,8 +527,6 @@ - (void)stop
 - (void)updateFrameworkInfo
 {
   auto app = UIApplication.sharedApplication;
-  if (app.applicationState != UIApplicationStateActive)
-    return;
   auto delegate = static_cast<MapsAppDelegate *>(app.delegate);
   if (delegate.isDrapeEngineCreated)
```
Comment (biodranik) [inline iphone/Maps/Core/Location/MWMLocationManager.mm:531]: The problem with this approach is that it calls itself without any delay, while in reality GPS locations come every second. @fabwu did you measure how many times is this method called before actually updating a location? A hundred times or more?

I suggest to properly move this code into https://github.com/organicmaps/organicmaps/blob/master/iphone/Maps/Core/Location/MWMLocationManager.mm#L305

Comment (fabwu) [reply iphone/Maps/Core/Location/MWMLocationManager.mm:531]: > @fabwu did you measure how many times is this method called before actually updating a location? A hundred times or more?

I put a log statement and it looks like it doesn't recurse.

If you want a proper refactoring, I would move the framework update to a separate observer and register that observer with `[MWMLocationManager addObserver]`. Then the framework gets location updates like the rest of the app (e.g. `MWMRouter`). We could do the same for the GPS tracker.

Comment (biodranik) [reply iphone/Maps/Core/Location/MWMLocationManager.mm:531]: @fabwu you're right, framework update is called only once, it recurses only if drape engine wasn't created yet for any reason (that should never happen).

What are the pros and cons of using observer pattern instead of a simpler direct call of `f.OnLocationUpdate` and friends where necessary?

I see in the profiler on the simulator that most of the CPU in the background is spent in onNavigationInfoUpdated. As the dashboard is not visible, it shouldn't be updated every time in the background, right? Maybe make a separate issue about it?

**Review by biodranik — APPROVED** [review]
LGTM, let's check it in alfa.

Looks like `setFrameworkUpdateMode` is not used anywhere. Can you please check why it was added and if it can be safely removed?

**Comment by biodranik** [comment]
@fabwu beta version works, so this can be merged, right?

**Review by vng — APPROVED** [review]

**Comment by fabwu** [comment]
> Looks like setFrameworkUpdateMode is not used anywhere. Can you please check why it was added and if it can be safely removed?

I'll do this in a separate PR.

> beta version works, so this can be merged, right?

Yes sure :)
