### PR TITLE
[android] Dismiss spinner when user aborts downloading area

### LINKED ISSUE #6126: Routing infinite spinner when target area isn't downloaded
**Describe the issue**

Targetting non-downloaded area and rejecting download make the routing spinner spin forever.

**Steps to reproduce**
1. Have source area downloaded (I start from Hungary)
2. Select Car navigation
3. Target something on a not downloaded area (I went into St. Johann in Tirol, but tastes vary)
4. "Do you want to download area?" "Later"
5. Car navigation spinner (contour spinner) spins forever
6. Clicking on the spinner make it flash, keeps spinning.

**Expected behavior**
- Either stop route planning (no local data),
- Or if you plan to do online planning then that.

**System information:**
 - Android 12, LineageOS
 - Organic Maps version: 2023-08-18-8-google
 - Device Model: xiomi 10Tpro

### PR DESCRIPTION
**Pull request by walterjwhite**
Fixes #6126

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Did you test all other (normal) cases too?
CC @Jean-BaptisteC

File: android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java [hunk 1]
```diff
@@ -55,8 +55,10 @@ private View addMessage(View frame)
   @Override
   public void onDismiss(DialogInterface dialog)
   {
-    if (mNeedMoreMaps && mCancelled)
+    if (mNeedMoreMaps && mCancelled) {
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java:58]:
```suggestion
    if (mNeedMoreMaps && mCancelled)
    {
```

**Comment by Jean-BaptisteC** [comment]
I don't see difference when I close downloader pop-up, spinner is always moving.

**Comment by walterjwhite** [comment]
FYI, I am waiting to get access to my Apple account to reinstall XCode which appears it will be after November 14.

**Comment by rtsisyk** [comment]
> FYI, I am waiting to get access to my Apple account to reinstall XCode which appears it will be after November 14.

This Android change, isn't it? Please attach a screen recording for before/after behavior. I don't understand what has changed from the code.

**Comment by rtsisyk** [comment]
+ update the git commit title and description, like in the PR (git commit --amend).

File: android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java (hunk 1 above)
Comment (walterjwhite) [reply android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java:58]: I have fixed this.

File: android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java [hunk 2]
```diff
@@ -55,8 +55,10 @@ private View addMessage(View frame)
...
       mCancelled = false;
+      RoutingController.get().cancel();
```
Comment (walterjwhite) [inline android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java:60]: This closes the Routing menu altogether.  It is simple, yet effective.  Perhaps it would be better to add another dialog to warn the user navigation would be cancelled.

**Comment by walterjwhite** [comment]
> > FYI, I am waiting to get access to my Apple account to reinstall XCode which appears it will be after November 14.
> 
> This Android change, isn't it? Please attach a screen recording for before/after behavior. I don't understand what has changed from the code.

I have a working fix now, please test and let me know if this works as you'd like.  It closes the menu altogether.

**Comment by biodranik** [comment]
> I have a working fix now, please test and let me know if this works as you'd like. It closes the menu altogether.

As our time is extremely limited, and changing some lines of code is easy, we expect that our contributors test their changes thoroughly, describe which scenarios were tested, and share screenshots/videos with their changes.

**Comment by walterjwhite** [comment]
Please see attached:

https://github.com/organicmaps/organicmaps/assets/469680/bedd3f92-429c-4105-8531-a0ee180763e4

**Comment by rtsisyk** [comment]
Let it be. Congratulations with the first contribution. Happy Thanksgiving!

**Comment by biodranik** [comment]
@rtsisyk that fix completely hides the route planning UI and deselects/loses the selected destination point. A proper fix should just stop the spinner from rotating and display the "route failed" message at the bottom, like it's done on iOS.
