### PR TITLE
Fix deprecated edge to edge code on Android

### LINKED ISSUE #11424: [android] Rewrite deprecated code for edge-to-edge
Google Play shows the following warning:

Your app uses deprecated APIs or parameters for edge-to-edge

One or more of the APIs that you use or parameters that you set for edge-to-edge and window display have been deprecated in Android 15. Your app uses the following deprecated APIs or parameters:
```
    android.view.Window.setStatusBarColor
    android.view.Window.setNavigationBarColor
```
These start in the following places:
```
    androidx.activity.EdgeToEdgeApi23.setUp
    androidx.activity.EdgeToEdgeApi26.setUp
    androidx.activity.EdgeToEdgeApi29.setUp
    app.organicmaps.MwmActivity.makeNavigationBarTransparentInLightMode
    com.google.android.material.bottomsheet.BottomSheetDialog.onCreate
    com.google.android.material.internal.EdgeToEdgeUtils.applyEdgeToEdge
```
To fix this, migrate away from these APIs or parameters.

### PR DESCRIPTION
**Pull request by Roniscend**
Migrated navigation bar logic to the modern AndroidX Edge to Edge API. This fixes API 35 deprecation warnings while maintaining correct transparency and layout. After making the changes, I rebuilt the project locally and tested the UI, everything works as expected.
Fixes #11424

Closes https://github.com/organicmaps/organicmaps/pull/11607

### CODE REVIEW

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 1]
```diff
@@ -2379,22 +2382,14 @@ public void onTrimMemory(int level)
...
-      flags |= View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION;
-
-      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1)
-        flags |= View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
-
-      window.getDecorView().setSystemUiVisibility(flags);
-
-      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
-        window.setNavigationBarContrastEnforced(false);
+    boolean isLightMode = (nightMask == Configuration.UI_MODE_NIGHT_NO);
```
Comment (AndrewShkrob) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java]: https://github.com/organicmaps/organicmaps/blob/d1c932fed48208fd43371b88d6e622d0a05741a9/android/sdk/src/main/java/app/organicmaps/sdk/util/Utils.java#L351-L355

File: android/app/build.gradle [hunk 2]
```diff
@@ -288,6 +288,7 @@ dependencies {
   // https://github.com/organicmaps/organicmaps/issues/6106
   implementation 'com.google.guava:guava:33.5.0-android'
   implementation 'com.github.devnullorthrow:MPAndroidChart:3.2.0-alpha'
+    implementation 'androidx.activity:activity-ktx:1.9.3'
```
Comment (AndrewShkrob) [inline android/app/build.gradle]: Why is it needed?

Comment (Roniscend) [reply android/app/build.gradle]: You are right,its not needed.I added it for EdgeToEdge.enable(), but I realized the parent activity already covers that configuration. I will remove this dependency to clean it up.

**Review by biodranik — COMMENTED** [review]
Thanks! Does it work correctly in Android 5/6 and other versions of Android?

**Comment by Roniscend** [comment]
> Thanks! Does it work correctly in Android 5/6 and other versions of Android?

Yes, the layout attributes have been standard since Android 1.0, and WindowInsetsControllerCompat handles the backward compatibility for the code

**Comment by Roniscend** [comment]
@biodranik Please review this PR and let me know if you have any suggestions or if further changes are required

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 3]
```diff
@@ -2378,23 +2379,14 @@ public void onTrimMemory(int level)
 
   private void makeNavigationBarTransparentInLightMode()
   {
-    int nightMask = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
-    if (nightMask == Configuration.UI_MODE_NIGHT_NO) // if light mode
+    boolean isLightMode = !app.organicmaps.sdk.util.Utils.isDarkMode(this);
```
Comment (AndrewShkrob) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java]:
```suggestion
    final boolean isLightMode = !app.organicmaps.sdk.util.Utils.isDarkMode(this);
```

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 4]
```diff
@@ -2378,23 +2379,14 @@ public void onTrimMemory(int level)
...
+    Window window = getWindow();
```
Comment (AndrewShkrob) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java]:
```suggestion
    final Window window = getWindow();
```

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 5]
```diff
@@ -2378,23 +2379,14 @@ public void onTrimMemory(int level)
...
+    window.setNavigationBarColor(Color.TRANSPARENT);
+    WindowInsetsControllerCompat controller = new WindowInsetsControllerCompat(window, window.getDecorView());
```
Comment (AndrewShkrob) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java]:
```suggestion
    final WindowInsetsControllerCompat controller = new WindowInsetsControllerCompat(window, window.getDecorView());
```

Where is this `controller` used?

Comment (Roniscend) [reply android/app/src/main/java/app/organicmaps/MwmActivity.java]: It was used only in the next line, so I inlined the call to remove the variable

**Comment by Roniscend** [comment]
I have addressed all the feedback and updated the pull request accordingly, please review the changes at your convenience.

**Comment by Roniscend** [comment]
@biodranik please can you re review the pr and suggest changes if any

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 6]
```diff
@@ -2385,23 +2379,13 @@ public void onTrimMemory(int level)
...
   private void makeNavigationBarTransparentInLightMode()
   {
-    int nightMask = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
-    if (nightMask == Configuration.UI_MODE_NIGHT_NO) // if light mode
+    final boolean isLightMode = !app.organicmaps.sdk.util.Utils.isDarkMode(this);
+    final Window window = getWindow();
+    window.setNavigationBarColor(Color.TRANSPARENT);
+    new WindowInsetsControllerCompat(window, window.getDecorView()).setAppearanceLightNavigationBars(isLightMode);
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
     {
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java]:
```suggestion
```

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 7]
```diff
@@ -2385,23 +2379,13 @@ public void onTrimMemory(int level)
...
-
-      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1)
-        flags |= View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
-
-      window.getDecorView().setSystemUiVisibility(flags);
-
-      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
-        window.setNavigationBarContrastEnforced(false);
+      window.setNavigationBarContrastEnforced(false);
     }
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java]:
```suggestion
```

**Review by biodranik — APPROVED** [review]
Thanks, LGTM


On Android 5 (maybe on other versions too), there is a likely unrelated insets bug, maybe you can also take a look in a different PR?

1. Open settings
2. Change Appearance theme (light to dark, or dark to light)
3. Return back to the main map screen
4. Observe that bottom buttons are behind system buttons.

grafik

**Comment by Roniscend** [comment]
> Thanks, LGTM
> 
> On Android 5 (maybe on other versions too), there is a likely unrelated insets bug, maybe you can also take a look in a different PR?
> 
> 1. Open settings
> 2. Change Appearance theme (light to dark, or dark to light)
> 3. Return back to the main map screen
> 4. Observe that bottom buttons are behind system buttons.
> 
> grafik

Sure, I will look into it

Also I have implemented all the changes as requested as well
