### PR TITLE
[android] Implements Address Bold in Search Suggestion

### LINKED ISSUE #6932: Highlight matched part of the address in search results
Now only matched names are highlighted with bold. The address part in the top first result is not highlighted, and it looks like it's not the exact match but some wrong result from the first sight. 

image

### PR DESCRIPTION
**Pull request by kavikhalique**
Fixed #6932
Closes #7114

Implemented Bold feature in search suggestion address section

fix2

fix1

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Does it properly work with non-ASCII characters, RTL texts and accented letters?

**Comment by biodranik** [comment]
Did you test it with different languages?

**Comment by kavikhalique** [comment]
Have checked roughly but will update after checking thoroughly.

Will try to cover all possible cases

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java [hunk 1]
```diff
@@ -141,4 +142,37 @@ public Spannable getFormattedTitle(@NonNull Context context)
...
+
+      if (highlightRanges != null)
+      {
+        final int size = highlightRanges.length / 2;
+        int index = 0;
+
+        for (int i = 0; i < size; i++)
+        {
+          final int start = highlightRanges[index++];
+          final int len = highlightRanges[index++];
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/search/SearchResult.java:166]: Is it possible to avoid using index variable?

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java [hunk 2]
```diff
@@ -141,4 +142,37 @@ public Spannable getFormattedTitle(@NonNull Context context)
 
     return builder;
   }
+
+  public String getAddress(@NonNull Context context)
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/search/SearchResult.java:146]: Why is this function needed?

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java [hunk 3]
```diff
@@ -141,4 +142,37 @@ public Spannable getFormattedTitle(@NonNull Context context)
...
+  }
+
+  public Spannable getFormattedAddress(@NonNull Context context)
+  {
+      final String address = getAddress(context);
+      final String addr = address.toLowerCase();
+      String title = getTitle(context);
+      final SpannableStringBuilder builder = new SpannableStringBuilder(address);
+
+      if (highlightRanges != null)
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/search/SearchResult.java:158]: What is encoded/stored in highlightRanges?

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java [hunk 4]
```diff
@@ -141,4 +142,37 @@ public Spannable getFormattedTitle(@NonNull Context context)
...
+        int index = 0;
+
+        for (int i = 0; i < size; i++)
+        {
+          final int start = highlightRanges[index++];
+          final int len = highlightRanges[index++];
+
+          final String toFind = title.substring(start,start+len).toLowerCase();
+          int start2 = addr.indexOf(toFind);
+          if(start2<0 || start2+len>=address.length()) continue;
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/search/SearchResult.java:170]: Formatting

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 2 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:146]: There is no necessity but to make it look good i did that 
Can remove it.

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 3 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:158]: Actually highlighted ranges is coming from cpp files which have two consecutive pairs of integers first represents start index and second represents length of the substring to highlight in title string. 

Please see the function getFormattedTitle which is used to highlight the title.

I basically took those substrings from titles which are being highlighted and searched in the address and if it finds any match it highlights them.

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 1 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:166]: We have locally defined index variable to iterate over the array so we need that index.

Please check the function getFormattedTitle which is used to highlight titles, I took reference from there.

There also index variable was used so i used it in similar fashion.

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 4 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:170]: Could you please guide me how should i format it?

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 3 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:158]: Shouldn't you search/match the tokens from a user's search query instead?

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:158]: No, this change only highlights the address if there is a highlight already existing in title otherwise it do not highlights anything even if text is present in query.

I am working on matching through query but unable to find the exact implementation. Should i close this pr and raise another one after dealing with query? Or do changes in this pr after some times?

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 4 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:170]: Check how other code is formatted:
```suggestion
          if (start2 < 0 || start2 + len >= address.length())
            continue;
```

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 1 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:166]: That reference function is not the best possible example )

Can `i` be used instead of `index`?

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 2 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:146]: If you want a clearer code, it can be done without using a function, for example:
```
final String address = description.region;
```

But I don't see much value in it.

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 3 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:158]: The same feature/issue should be worked in the same PR. You can apply your changes on top to be able to compare them with an older implementation.

When the PR is approved, either you can rebase/squash commits (usually if there is more than one final logical commit), or we can squash everything into one commit during the merge.

**Review by biodranik — COMMENTED** [review]
Please make sure it properly highlights RTL matches too.

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 4 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java]: Thankyou, will follow proper formatting next time.

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 3 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:158]: Sure

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java (hunk 1 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/search/SearchResult.java:166]: Yes, "i" can be used.

**Comment by kavikhalique** [comment]
> Please make sure it properly highlights RTL matches too.

Sure

**Comment by kavikhalique** [comment]
- Used query from searchFragment 
Sent it to searchAdapter 
- where it got separated into tokens and stored into string array
- Then sent this string array to searchResults class to perform searching and formatting the address according to query tokens and then bold it
@biodranik

**Comment by Jean-BaptisteC** [comment]
Can you add in first comment `closes #7114`

**Review by vng — CHANGES_REQUESTED** [review]
Well, I have doubts here.
All SearchResult <-> Strings <-> Tokens manipulation should happen in C++ core. Furthermore, string matching logic is not a simple String.indexOf.

We have a complicated matching logic (which will be improved), so highlight ranges should be calculated in core like for the regular names.

**Comment by kavikhalique** [comment]
> Well, I have doubts here.
> 
> All SearchResult <-> Strings <-> Tokens manipulation should happen in C++ core. 

Yes, technically its a kind of hack. Where i used query made tokens and utilized it.

>Furthermore, string matching logic is not a simple String.indexOf.

I agree there are a lot of algorithms present to match the strings efficiently.

The reason of why i felt indexOf will work is that, in worst case the size of address string can reach upto 200-300 chars and the size of token could reach at max 50-60. So overall overhead not that much and indexOf will not put much load on system.

> We have a complicated matching logic (which will be improved), so highlight ranges should be calculated in core like for the regular names.

Yes, i am still exploring the whole codebase its vast. Mainly the cpp files.

I thought of changing cpp files and sending the data in searchResult object together with other informations but since i am not aware of whole code base i thought of not interrupting the cpp files.
 
Please guide me which IDE i should use to properly understand the cpp codebase. 
Currently using VS code.

**Review by kavikhalique — COMMENTED** [review]
i have done changes in cpp files and reverted changes in java of algorithm part.
In cpp i used the predefined methods for highlighting the titles.

**Comment by kavikhalique** [comment]
Changes in cpp

1. Created a new function to highlight address string similar to previous highlight function for title.(just replaced the title string with address string)

2. Created one more array in result class to store the returned  highlight array result into it similar to title highlight array.

3. Sending the created array to search result class of java through jni.

Changes In java

1. Created one more array similar to the one for title highlighting

2. Included the highlight array (returned from cpp) into constructor of searchResult.java class

3. Utilized the returned array for highlighting address and highlighted the address string by calling getFormattedAddress

File: android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp [hunk 5]
```diff
@@ -90,7 +101,7 @@ jobject ToJavaResult(Result const & result, search::ProductInfo const & productI
   {
     jni::TScopedLocalRef name(env, jni::ToJavaString(env, result.GetString()));
     jni::TScopedLocalRef suggest(env, jni::ToJavaString(env, result.GetSuggestionString()));
-    return env->NewObject(g_resultClass, g_suggestConstructor, name.get(), suggest.get(), ll.m_lat, ll.m_lon, ranges.get());
+    return env->NewObject(g_resultClass, g_suggestConstructor, name.get(), suggest.get(), ll.m_lat, ll.m_lon, ranges.get(),ranges2.get());
```
Comment (biodranik) [inline android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp:104]: @vng WDYT about the approach?

Comment (kavikhalique) [reply android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp:104]: please sir review it once @vng :)

**Comment by kavikhalique** [comment]
@vng Sir please review my changes once and if there is something which needs to be improved or changed please instruct me.

**Comment by Jean-BaptisteC** [comment]
@kavikhalique can you rebase your branch?

File: search/ranker.cpp [hunk 6]
```diff
@@ -741,10 +741,13 @@ Result Ranker::MakeResult(RankerResult const & rankerResult, bool needAddress, b
       if (item.GetReadableName(city))
         res.PrependCity(city);
     });
-  }
+  } 
 
   if (needHighlighting)
+  {
     HighlightResult(m_params.m_query.m_tokens, m_params.m_query.m_prefix, res);
+    HighlightResult2(m_params.m_query.m_tokens, m_params.m_query.m_prefix, res);
```
[the remark this answers is not in the document]
Comment (kavikhalique) [reply search/ranker.cpp:749]: I guess there is some redundancy. I will rework on pr then will update.

[the remark this answers is not in the document]
Comment (kavikhalique) [reply search/ranker.cpp]: I have removed unnecessary methods and refactored codes little bit for better understanding.
Please have a look @rtsisyk

**Comment by kavikhalique** [comment]
This one is ready for review. @rtsisyk @biodranik

**Review by vng — APPROVED** [review]

File: android/app/src/main/java/app/organicmaps/search/SearchAdapter.java [hunk 7]
```diff
@@ -23,6 +23,8 @@ class SearchAdapter extends RecyclerView.Adapter<SearchAdapter.SearchDataViewHol
   @Nullable
   private SearchResult[] mResults;
 
+  private String[] queryTokens;
```
Comment (vng) [inline android/app/src/main/java/app/organicmaps/search/SearchAdapter.java:26]: Remove as unused.

File: android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp [hunk 8]
```diff
@@ -81,6 +81,17 @@ jobject ToJavaResult(Result const & result, search::ProductInfo const & productI
   }
   env->ReleaseIntArrayElements(ranges.get(), rawArr, 0);
 
+  jni::TScopedLocalIntArrayRef descRanges(
+      env, env->NewIntArray(static_cast<jsize>(result.GetDescHighlightRangesCount() * 2)));
```
Comment (vng) [inline android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp:85]: nit: One line is ok here.

File: android/app/src/main/java/app/organicmaps/search/SearchResult.java [hunk 9]
```diff
@@ -141,4 +144,27 @@ public Spannable getFormattedTitle(@NonNull Context context)
...
+      {
+        final int start = descHighlightRanges[itr++];
+        final int len = descHighlightRanges[itr++];
+
+        builder.setSpan(new StyleSpan(Typeface.BOLD), start, start + len, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
+      }
+    }
+
+    return builder;
+  }
```
Comment (vng) [inline android/app/src/main/java/app/organicmaps/search/SearchResult.java:168]: Can avoid copy-paste in getFormattedTitle and getFormattedAddress with adding helper fucntion.

File: search/highlighting.cpp [hunk 10]
```diff
@@ -56,5 +56,13 @@ void HighlightResult(QueryTokens const & tokens, strings::UniString const & pref
...
 
   SearchStringTokensIntersectionRanges(res.GetString(), beg, end, assignHighlightRange);
+
+  // Highlight description.
+  auto assignDescHighlightRange = [&](pair<uint16_t, uint16_t> const & range)
+  {
+    res.AddDescHighlightRange(range);
+  };
+
+  SearchStringTokensIntersectionRanges(res.GetAddress(), beg, end, assignDescHighlightRange);
```
Comment (vng) [inline search/highlighting.cpp:66]: nit here and above:
```
SearchStringTokensIntersectionRanges(res.GetAddress(), beg, end, [&](pair<uint16_t, uint16_t> const & range)
{
  res.AddDescHighlightRange(range);
});
```

File: search/ranker.cpp [hunk 11]
```diff
@@ -761,7 +761,9 @@ Result Ranker::MakeResult(RankerResult const & rankerResult, bool needAddress, b
   }
 
   if (needHighlighting)
+  {
     HighlightResult(m_params.m_query.m_tokens, m_params.m_query.m_prefix, res);
+  }
```
Comment (vng) [inline search/ranker.cpp:766]: Revert as before without braces.

**Review by vng — COMMENTED** [review]
Thanks! LGTM with some minor comments.

**Comment by kavikhalique** [comment]
> Thanks! LGTM with some minor comments.

I have done all required changes but my laptop is running out in huge problem due to which i am unable to contribute. As soon as i get my new laptop and setup the whole environment i will commit my changes, it will take around one week. I hope it will not affect the flow so much. Sorry for delays

**Review by vng — APPROVED** [review]
