### PR TITLE
[ios] Improve TTS voice selection

### LINKED ISSUE #2178: Make Voice Guidance Sound More Natural
Would it be possible to make the navigation voice guidance sound more natural?

### LINKED ISSUE #3222: TTS Bug
By default, installing OM in the US will have the English TTS with a US accent. However, if you go into settings and select English TTS (unchecked prior to this point), you will receive voice directions in a different accent. The only way to get back the US TTS is by reinstalling the app.

### LINKED ISSUE #6840: pronounce speech on ios
Organic Maps does not respect the system choice of the voice and always uses a default TTS voice for the language. The user's system choice of voice should be respected by Organic Maps.

выява

### LINKED ISSUE #7604: [ios] Doubled English language in the TTS Settings
Sometimes the English is doubled in the TTS Settings on iOS.
It is usually reproduced on Simulator when a new one is created. I don't find a way how to reproduce it on a device.
This doubling will continue until a user changes a preferred language.

Possible reason: simulators en_UK (or AU) current locale which differs from the en_US.

image

### PR DESCRIPTION
**Pull request by fabwu**
This commit allows a user to select more voices (e.g. English (United States), English (India)). Currently, it's only possible to select a subset of the available voices on iOS. For example, if a user selects English as TTS language, an Australian voice is selected because en_AU comes before en_US in the voice list of iOS.

Fixes #6840
Fixes #3222
Fixes #2178
Fixes #7604

### CODE REVIEW

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm [hunk 1]
```diff
@@ -286,16 +288,12 @@ + (void)removeObserver:(id<MWMTextToSpeechObserver>)observer {
...
-      find_if(list.begin(), list.end(),
-              [&twine](std::pair<std::string, std::string> const & pair) { return pair.first == twine; });
-
-  if (it != list.end())
-    return it->second;
-  else
-    return "";
+  NSString *nsLocaleString = [NSString stringWithUTF8String: localeString.c_str()];
+  NSLocale *locale = [[NSLocale alloc] initWithLocaleIdentifier: nsLocaleString];
+  NSString *localizedName = [locale localizedStringForLocaleIdentifier:nsLocaleString];
```
Comment (kirylkaveryn) [inline iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:295]:
```suggestion
  NSString * localizedName = [locale localizedStringForLocaleIdentifier:nsLocaleString];
```

File: iphone/Maps/UI/Settings/MWMTTSSettingsViewController.mm [hunk 2]
```diff
@@ -242,8 +241,7 @@ - (void)viewDidLoad
     string const savedLanguage = nsSavedLanguage.UTF8String;
     if (savedLanguage != currentBcp47Str && savedLanguage != standart.first &&
         !savedLanguage.empty())
-      m_languages.emplace_back(
-          make_pair(savedLanguage, translatedTwine(bcp47ToTwineLanguage(nsSavedLanguage))));
+      m_languages.emplace_back(make_pair(savedLanguage, translateLocale(savedLanguage)));
```
Comment (biodranik) [inline iphone/Maps/UI/Settings/MWMTTSSettingsViewController.mm:244]:
```suggestion
      m_languages.emplace_back(savedLanguage, translateLocale(savedLanguage));
```

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm [hunk 3]
```diff
@@ -286,16 +288,12 @@ + (void)removeObserver:(id<MWMTextToSpeechObserver>)observer {
...
+  localizedName = [localizedName capitalizedString];
+  return std::string([localizedName UTF8String]);
```
Comment (biodranik) [inline iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:297]: ObjC getters without parameters are easier to read as properties.
```suggestion
  return std::string(localizedName.UTF8String);
```

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm [hunk 4]
```diff
@@ -33,8 +33,10 @@
       if (lang.first == p.first)
       {
         // Twine names are equal. Make a pair: bcp47 name, localized name.
-        result.emplace_back(make_pair(lang.second, p.second));
-        break;
+        auto pair = make_pair(lang.second, tts::translateLocale(lang.second));
+        if(std::find(result.begin(), result.end(), pair) == result.end()) {
+          result.emplace_back(pair);
+        }
```
Comment (biodranik) [inline iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:39]: Change above:
```
for (auto const & p : kLanguageList)
// to
for (auto const & [twineCode, languageName] : kLanguageList)
```

```suggestion
        auto pair = std::make_pair(lang.second, tts::translateLocale(lang.second));
        if (std::find(result.begin(), result.end(), pair) == result.end())
          result.emplace_back(std::move(pair));
```

**Review by biodranik — COMMENTED** [review]
Cool, thanks!

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 1 above)
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:295]: Mmh I never get used to Objective-C syntax ^^ but I stick to the convention.

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech+CPP.h [hunk 5]
```diff
@@ -14,5 +14,5 @@
 
 namespace tts
 {
-std::string translatedTwine(std::string const & twine);
+std::string translateLocale(std::string const & twine);
```
[the remark this answers is not in the document]
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech+CPP.h:17]: Thanks good catch!

File: iphone/Maps/UI/Settings/MWMTTSSettingsViewController.mm (hunk 2 above)
Comment (fabwu) [reply iphone/Maps/UI/Settings/MWMTTSSettingsViewController.mm:244]: I really have to look into modern C++. Thanks!

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 3 above)
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:297]: Thanks!

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 4 above)
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:39]: Thanks didn't know the `std::move`

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 1 above)
[the remark this answers is not in the document]
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm]: I'd love to write a test but is there a way to call this method from Swift oder do you suggest a test in Objective-C?

**Comment by fabwu** [comment]
I've changed two more things:

1. I removed the hard-coded Alex voice for `en-US` because I wasn't able to select another voice if the Alex voice is installed.

2. The first entry of the voice list was `English (Australian)` (see screenshot). I changed it to `English (United States)`. Now the order is `English (United States)`, default voice language depending on the iOS settings and then the selected language.

<image width="40%" src="https://github.com/organicmaps/organicmaps/assets/6050639/2ca98106-4eef-443e-b020-6e1ddd9faeac">

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 1 above)
[the remark this answers is not in the document]
Comment (kirylkaveryn) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm]: Swift will not be working with the cpp (until we upgrade to the latest xcode and up the target to ios 15 because there will no way back to the xcode 14 - https://www.swift.org/documentation/cxx-interop/#enabling-c-interoperability).
So the only way to write tests for this method is objc.

[the remark this answers is not in the document]
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm]: Ok I wrote some tests in Objective-C. It was easier than expected...

I also moved the test classes to the same group as their respective classes in the project. The Tests group basically mimics the project folder structure:

image

I do this in my large projects to organize my test files but I don't know if you like it?

File: iphone/Maps/Maps.xcodeproj/project.pbxproj [hunk 6]
```diff
@@ -3759,6 +3794,9 @@
 							};
 						};
 					};
+					ED097E752BB80C320006ED01 = {
+						LastSwiftMigration = 1530;
+					};
 				};
```
Comment (kirylkaveryn) [inline iphone/Maps/Maps.xcodeproj/project.pbxproj:3800]: I think this autogenerated code can be removed.

File: iphone/Maps/Maps.xcodeproj/project.pbxproj [hunk 7]
```diff
@@ -4689,12 +4728,15 @@
 			baseConfigurationReference = 347526FA1DC0B00F00918CF5 /* common-debug.xcconfig */;
 			buildSettings = {
 				BUNDLE_LOADER = "$(TEST_HOST)";
+				CLANG_ENABLE_MODULES = YES;
```
Comment (kirylkaveryn) [inline iphone/Maps/Maps.xcodeproj/project.pbxproj:4731]: Please try to remove all this autogenerated code from the `buildSettings` and run tests.
It should be OK.

File: iphone/Maps/Maps.xcodeproj/project.pbxproj [hunk 8]
```diff
@@ -4689,12 +4728,15 @@
...
 				CODE_SIGN_STYLE = Manual;
 				DEVELOPMENT_TEAM = "";
 				"DEVELOPMENT_TEAM[sdk=iphoneos*]" = 9Z6432XD7L;
 				"DEVELOPMENT_TEAM[sdk=macosx*]" = 9Z6432XD7L;
 				PRODUCT_BUNDLE_IDENTIFIER = app.organicmaps.debug.tests;
 				PROVISIONING_PROFILE_SPECIFIER = "";
+				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
+				SWIFT_VERSION = 5.0;
```
Comment (kirylkaveryn) [inline iphone/Maps/Maps.xcodeproj/project.pbxproj:4739]: Same

File: iphone/Maps/Maps.xcodeproj/project.pbxproj [hunk 9]
```diff
@@ -4704,11 +4746,13 @@
 			baseConfigurationReference = 347526FB1DC0B00F00918CF5 /* common-release.xcconfig */;
 			buildSettings = {
 				BUNDLE_LOADER = "$(TEST_HOST)";
+				CLANG_ENABLE_MODULES = YES;
 				CODE_SIGN_STYLE = Manual;
 				"DEVELOPMENT_TEAM[sdk=iphoneos*]" = 9Z6432XD7L;
 				"DEVELOPMENT_TEAM[sdk=macosx*]" = 9Z6432XD7L;
 				PRODUCT_BUNDLE_IDENTIFIER = app.organicmaps.release.tests;
 				PROVISIONING_PROFILE_SPECIFIER = "";
+				SWIFT_VERSION = 5.0;
```
Comment (kirylkaveryn) [inline iphone/Maps/Maps.xcodeproj/project.pbxproj:4755]: Here too

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm [hunk 10]
```diff
@@ -26,15 +26,15 @@
...
+    for (auto const & [twineVoice, bcp47Voice] : native)
     {
-      if (lang.first == p.first)
+      if (twineVoice == twineRouting)
       {
-        // Twine names are equal. Make a pair: bcp47 name, localized name.
-        result.emplace_back(make_pair(lang.second, p.second));
-        break;
+        auto pair = make_pair(bcp47Voice, tts::translateLocale(bcp47Voice));
+        if(std::find(result.begin(), result.end(), pair) == result.end())
```
Comment (biodranik) [inline iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:36]:
```suggestion
        if (std::find(result.begin(), result.end(), pair) == result.end())
```

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm [hunk 11]
```diff
@@ -118,6 +118,9 @@ - (void)dealloc {
   self.speechSynthesizer.delegate = nil;
 }
 - (std::vector<std::pair<std::string, std::string>>)availableLanguages { return _availableLanguages; }
+- (std::pair<std::string, std::string>)standardLanguage {
+  return make_pair(kDefaultLanguage.UTF8String, tts::translateLocale(kDefaultLanguage.UTF8String));
```
Comment (biodranik) [inline iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:122]:
```suggestion
  return std::make_pair(kDefaultLanguage.UTF8String, tts::translateLocale(kDefaultLanguage.UTF8String));
```

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm [hunk 12]
```diff
@@ -26,15 +26,15 @@
...
-    for (std::pair<std::string, std::string> const & lang : native)
+    for (auto const & [twineVoice, bcp47Voice] : native)
     {
-      if (lang.first == p.first)
+      if (twineVoice == twineRouting)
       {
-        // Twine names are equal. Make a pair: bcp47 name, localized name.
-        result.emplace_back(make_pair(lang.second, p.second));
-        break;
+        auto pair = make_pair(bcp47Voice, tts::translateLocale(bcp47Voice));
```
Comment (biodranik) [inline iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:35]:
```suggestion
        auto pair = std::make_pair(bcp47Voice, tts::translateLocale(bcp47Voice));
```

File: iphone/Maps/Maps.xcodeproj/project.pbxproj (hunk 7 above)
Comment (biodranik) [reply iphone/Maps/Maps.xcodeproj/project.pbxproj:4731]: +1, this is not needed. We don't use modules.

File: iphone/Maps/Maps.xcodeproj/project.pbxproj [hunk 13]
```diff
@@ -4704,11 +4746,13 @@
 			baseConfigurationReference = 347526FB1DC0B00F00918CF5 /* common-release.xcconfig */;
 			buildSettings = {
 				BUNDLE_LOADER = "$(TEST_HOST)";
+				CLANG_ENABLE_MODULES = YES;
```
Comment (biodranik) [inline iphone/Maps/Maps.xcodeproj/project.pbxproj:4749]: It should be easy to remove some lines when amending the commit using Fork, Github App or other Git app with UI.

**Review by biodranik — COMMENTED** [review]
Good, thanks!

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 10 above)
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:36]: Ah sorry I missed that

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 11 above)
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:122]: done

File: iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm (hunk 12 above)
Comment (fabwu) [reply iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm:35]: done

File: iphone/Maps/Maps.xcodeproj/project.pbxproj (hunk 6 above)
Comment (fabwu) [reply iphone/Maps/Maps.xcodeproj/project.pbxproj]: Ah sorry I don't know how this got generated. I removed all lines.

**Review by biodranik — COMMENTED** [review]
A bit of final minor nitpicking )

File: iphone/Maps/UI/Settings/MWMTTSSettingsViewController.mm [hunk 14]
```diff
@@ -219,16 +219,15 @@ - (void)viewDidLoad
   m_languages.reserve(3);
   auto const & v = tts.availableLanguages;
   NSAssert(!v.empty(), @"Vector can't be empty!");
-  pair<string, string> const standart = v.front();
+  pair<string, string> const standart = tts.standardLanguage;
   m_languages.push_back(standart);
```
[the remark this answers is not in the document]
Comment (fabwu) [reply iphone/Maps/UI/Settings/MWMTTSSettingsViewController.mm:223]: That doesn't work because the variable is used below. I changed it to `standard` though.

File: iphone/Maps/Tests/Core/TextToSpeech/MWMTextToSpeechTests.mm [hunk 15]
```diff
@@ -0,0 +1,28 @@
...
+@interface MWMTextToSpeechTest : XCTestCase
+
+@end
+
+@implementation MWMTextToSpeechTest
+
+- (void)testAvailableLanguages {
+  MWMTextToSpeech * tts = [MWMTextToSpeech tts];
+  std::vector<std::pair<std::string, std::string>> langs = tts.availableLanguages;
+  auto defaultLang = std::make_pair("en-US", "English (United States)");
```
[the remark this answers is not in the document]
Comment (fabwu) [reply iphone/Maps/Tests/Core/TextToSpeech/MWMTextToSpeechTests.mm]: Ok I fixed everything as suggested :)

**Review by biodranik — APPROVED** [review]
LGTM, thanks!

@kirylkaveryn @vng any comments?
