### PR TITLE
[ios][drape] Fix crosshair alignment when "Add Place" is pressed from search results

### LINKED ISSUE #12237: [ios] Editor crosshair doesn't point to the same selected place when "Add Place" is pressed
1. Select any empty place on the map.
2. Copy its coordinates.
3. Open search and insert coordinates.
4. Tap at the found result with coordinates.
5. Expand Place Page and press Add Place

Observe that crosshair is not centered at the same coordinates, but shifted instead.

In other scenarios crosshair points correctly at the recently selected place.

### PR DESCRIPTION
**Pull request by jmegaraujo**
### Description
This PR fixes an issue where the editor crosshair does not point to the correct selected place when "Add Place" is triggered from a search result. 

When a specific coordinate (`pt`) is provided via the search result, the map was incorrectly tracking the visible viewport center (which is offset by the bottom UI panel) instead of the geometric screen center where the `WIDGET_CHOOSE_POSITION_MARK` crosshair is drawn. 

**Changes made:**
* **`frontend_renderer.cpp`**: Updated the `SetCenterEvent` creation inside `AcceptMessage` (for `SetAddNewPlaceMode`). It now passes `!pt` instead of a hardcoded `true` for the `trackVisibleViewport` argument. This ensures that when an explicit coordinate is provided, it correctly toggles tracking off to ignore UI panel offsets.
* **`user_event_stream.cpp`**: Modified `OnSetCenter` so that screen matching (`MatchGandP3d`) and scaling (`ApplyScale`) no longer hardcode `m_visibleViewport.Center()`. Instead, it introduces a `pixelTarget` that respects the `trackViewport` flag using the visible viewport center when tracking is enabled, and dynamically calculating the geometric screen center when it is disabled.
* **`user_event_stream_tests.cpp`**: Added three new unit tests to verify the asymmetric viewport logic.

Fixes #12237

### Testing
* [x] **Unit Tests:** All `drape_frontend_tests` (specifically `UserEventStream*`) pass locally.
* [x] **Manual Testing:** Tested on the iOS Simulator. Verified that tapping "Add Place" from a specific search result accurately aligns the crosshair with the intended coordinate, even when the bottom UI panel is present. 

| Device | OS | Modes |
| :--- | :--- | :--- |
| iPhone 17 | iOS 26.2 | Portrait / Landscape |

### Screenshots / Video
Before; Showcasing both "Add place" situations:
https://github.com/user-attachments/assets/cfd076c4-8f57-4a5a-af80-470545e29754

After; Showcasing both "Add place" situations:
https://github.com/user-attachments/assets/f7541966-67a2-49f5-8802-ef0062f2c54e

---
*Note: AI tools (Google Gemini) were used to assist in debugging the drape tests*

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! WDYT about these LLM comments? 3D perspective mode is now used during navigation only, but we may enable it also in the normal map browsing mode.

## Bug:  `PixelRect()`  vs  `PixelRectIn3d()`  coordinate space mismatch

**Severity: Medium**  — causes crosshair misalignment when 3D perspective is active

In  user_event_stream.cpp:419-421, the PR introduces:

```cpp
m2::PointD const pixelTarget = trackViewport ? m_visibleViewport.Center()
                                             : m2::PointD(GetCurrentScreen().PixelRect().SizeX() * 0.5,
                                                          GetCurrentScreen().PixelRect().SizeY() * 0.5);

```

This  `pixelTarget`  is passed to  `MatchGandP3d(center, pixelTarget)`  and  `ApplyScale(pixelTarget, ...)`. Both functions expect coordinates in the  **`PixelRectIn3d`**  coordinate space (actual screen pixels), not the  `PixelRect`  space (which is scaled up when 3D perspective is active).

**Evidence that  `MatchGandP3d`  expects  `PixelRectIn3d`  coordinates:**

1.  `MatchGandP3d`  internally calls  `P3dtoP(p3d)`  which normalizes using  `PixelRectIn3d().SizeX/Y()`  —  screenbase.cpp:469-470
2.  All other callers pass  `PixelRectIn3d`  coordinates, e.g.  `SetRect()`  defaults to  `tmp.PixelRectIn3d()`  —  user_event_stream.cpp:533-537
3.  Navigator touch handling passes touch pixel coords (which are in viewport/PixelRectIn3d space) —  navigator.cpp:165-167

**When 3D perspective is active:**

-   `PixelRect()`  =  `m_ViewportRect`  scaled by  `scale3d`  (> 1.0) —  screenbase.cpp:333-340
-   `PixelRectIn3d()`  =  `m_ViewportRect`  (actual viewport) —  screenbase.hpp:97
-   Their centers diverge:  `PixelRect().Center()`  =  `(W*s/2, H*s/2)`  vs  `PixelRectIn3d().Center()`  =  `(W/2, H/2)`

**The crosshair is drawn at  `PixelRectIn3d().Center()`**  —  choose_position_mark.cpp:42:

```cpp
SetPivot(glsl::ToVec2(m2::PointF(screen.PixelRectIn3d().Center())));

```

So in 3D mode, the map would be centered at the wrong pixel position, causing the same type of misalignment this PR aims to fix.

**Suggested fix:**

```cpp
m2::PointD const pixelTarget = trackViewport ? m_visibleViewport.Center()
                                             : GetCurrentScreen().PixelRectIn3d().Center();

```

**Note:**  In 2D mode (no perspective),  `PixelRect() == PixelRectIn3d()`, so this only manifests in 3D. The author likely tested only in 2D.

----------

## Minor issues

### Tests don't cover 3D perspective mode

All three new tests use default  `ScreenBase`  (2D, no perspective), so they can't catch the  `PixelRect`  vs  `PixelRectIn3d`  divergence. A test calling  `ApplyPerspective()`  on the screen before  `AddSetCenter`  would cover this.

### Test style: raw fabs instead of TEST_NEAR (nit)

The tests use  `std::fabs(a - b) < kEps`  with  `TEST()`. This is functional but less idiomatic than a  `TEST_NEAR`-style macro if one exists in the project's test framework. Minor style nit.

File: libs/drape_frontend/user_event_stream.cpp [hunk 1]
```diff
@@ -414,7 +414,13 @@ bool UserEventStream::OnSetCenter(ref_ptr<SetCenterEvent> centerEvent)
   auto const zoom = centerEvent->GetZoom();
   auto const scaleFactor = centerEvent->GetScaleFactor();
 
-  if (centerEvent->TrackVisibleViewport())
+  bool const trackViewport = centerEvent->TrackVisibleViewport();
+
+  m2::PointD const pixelTarget = trackViewport ? m_visibleViewport.Center()
+                                               : m2::PointD(GetCurrentScreen().PixelRect().SizeX() * 0.5,
+                                                            GetCurrentScreen().PixelRect().SizeY() * 0.5);
```
Comment (vng) [inline libs/drape_frontend/user_event_stream.cpp]: GetCurrentScreen().PixelRect().Center() ?

File: libs/drape_frontend/frontend_renderer.cpp [hunk 2]
```diff
@@ -772,7 +772,7 @@ void FrontendRenderer::AcceptMessage(ref_ptr<Message> message)
           zoom = scales::GetAddNewPlaceScale();
         AddUserEvent(make_unique_dp<SetCenterEvent>(
             pt ? *pt : m_userEventStream.GetCurrentScreen().GlobalRect().Center(), zoom, true /* isAnim */,
-            true /* trackVisibleViewport */, nullptr /* parallelAnimCreator */));
+            !pt /* trackVisibleViewport */, nullptr /* parallelAnimCreator */));
```
Comment (vng) [inline libs/drape_frontend/frontend_renderer.cpp:775]: AFAIR, I already played here with Android.
Will test your PR manually.

**Comment by jmegaraujo** [comment]
Thanks for your review. I updated the code to use the built-in .Center() method as you suggested. I specifically went with PixelRectIn3d().Center() to ensure the crosshair remains perfectly aligned with the physical screen even when 3D perspective mode is active.

**Comment by vng** [comment]
Updated PR (was a failed code style).
