### PR TITLE
[android] Fix bookmark edits not updating in place page on screen rotation

### LINKED ISSUE #2418: [android] Bookmark edits are not updated in PP if there were screen rotations
To reproduce:
1. Enter edit screen of any bookmark
2. Change bookmark's title
3. Rotate the screen e.g. from portrait to landscape and back
4. Tap "Save" the edit
5. Edited bookmark's title is not updated in the Place Page (bottom sheet)
unless the bookmark is re-selected on the map (i.e. the edits are saved actually)

Reproducible for sure on Android 5 and 9.

### PR DESCRIPTION
**Pull request by savsch**
Fixes #2418

The callback listener supposed to be invoked after bookmark edits (`mListener` in `EditBookmarkFragment`) was made null on configuration changes. This change fixes the issue by leveraging the fact that the parent fragment (for cases when the issue occurs, i.e. `PlacePageBookmarkFragment`) itself implements the listener.

### On master branch

https://github.com/user-attachments/assets/74f786e1-fbed-4bab-9efe-fae4d45985fc

### On this branch

https://github.com/user-attachments/assets/77a27cd3-341c-4cbb-840d-7cec117c84a5

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Thanks for fix
DYT correction is similar for this issue #2419?

**Comment by savsch** [comment]
> DYT correction is similar for this issue #2419?

Not exactly the same, as the variables lost in that issue are primitives or parcelables, so simply saving them would do. Just opened a PR for the same.

File: android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java [hunk 1]
```diff
@@ -181,6 +181,14 @@ public void onStart()
     }
   }
 
+  @Override
+  public void onAttach(@NonNull Context context)
+  {
+    super.onAttach(context);
+    if (mListener == null && getParentFragment() instanceof EditBookmarkListener)
```
Comment (pastk) [inline android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java:188]: Could you please add a comment explaining why this is necessary.

Also I wonder there is no issue with "lost" listener when a parent is BookmarksListFragment

Comment (savsch) [reply android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java:188]: Sorry to keep you waiting; been very busy the last few days.

---

> why there is no issue with "lost" listener when a parent is BookmarksListFragment

`BookmarkListActivity` has a `configChanges="orientation|..."` unlike `MwmActivity` where the issue occurs.

---

Also, now that I think about it a bit more, I shouldn't have resorted to the `onAttach` workaround.

There's an arguably cleaner way to fix this:
```diff
PlacePageBookmarkFragment.java
@@ -19,6 +19,7 @@ import androidx.annotation.NonNull;
 import androidx.annotation.Nullable;
 import androidx.fragment.app.Fragment;
 import androidx.fragment.app.FragmentActivity;
+import androidx.fragment.app.FragmentFactory;
 import androidx.lifecycle.Observer;
 import androidx.lifecycle.ViewModelProvider;
 import app.organicmaps.R;
@@ -120,6 +121,25 @@ public class PlacePageBookmarkFragment extends Fragment implements View.OnClickL
     }
   }
 
+  @Override
+  public void onCreate(@Nullable Bundle savedInstanceState)
+  {
+    // Custom FragmentFactory to prevent EditBookmarkFragment's mListener
+    // from becoming null on configuration changes
+    getChildFragmentManager().setFragmentFactory(new FragmentFactory()
+    {
+      @NonNull
+      @Override
+      public Fragment instantiate(@NonNull ClassLoader classLoader, @NonNull String className)
+      {
+        Class<? extends Fragment> fragmentClass = loadFragmentClass(classLoader, className);
+        Fragment fragment = super.instantiate(classLoader, className);
+        if (fragmentClass == EditBookmarkFragment.class)
+          ((EditBookmarkFragment) fragment).setEditBookmarkListener(PlacePageBookmarkFragment.this);
+        return fragment;
+      }
+    });
+    super.onCreate(savedInstanceState);
+  }
+
   @Override
   public void onClick(View v)
   {
@@ -127,7 +147,7 @@ public class PlacePageBookmarkFragment extends Fragment implements View.OnClickL
     EditBookmarkFragment.editBookmark(currentBookmark.getCategoryId(),
                                       currentBookmark.getBookmarkId(),
                                       activity,
-                                      activity.getSupportFragmentManager(),
+                                      getChildFragmentManager(),
                                       PlacePageBookmarkFragment.this);
   }
 

```

Should I push this instead?

Comment (pastk) [reply android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java:188]: IDK, it looks more complex for sure :)

It'd be great for more knowledgeable @organicmaps/android folks to have a look

**Review by vng — APPROVED** [review]

File: android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java (hunk 1 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java:188]: @savsch what are pros/cons of both approaches? Fixing the root cause looks like a better way, right?

Comment (savsch) [reply android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java:188]: @biodranik 
The root cause: `EditBookmarkFragment` is created in the code by one of its two static methods, both of which call `setEditBookmarkListener` on the Fragment after instantiating it. However, the Android framework obviously doesn't call `setEditBookmarkListener` when recreating `EditBookmarkFragment` for whichever reason (config changes in this case).

The listener can't be stored in a bundle either, so its "persistence" must be taken care of by means external to the fragment's own state.

I am not actually sure if the approach that got merged (checking if the parent fragment implements said listener) introduces coupling. OTOH, using a FragmentFactory (the other approach) doesn't introduce any more coupling than is already present, but is arguably more complex. I don't have an approach better than these two.
