### PR TITLE
[routing] Support maxspeed:conditional tags

### LINKED ISSUE #9016: Speed limits with time bounds are incorrect
This happends with the latest pre-release I'm testing right now.

When navigating on Android, the speed limits are now displayed on the lower-left hand side.  This is very nice.

In some countries the speed limit changes during different times of the day.  For example the Netherlands has a limit of 100kmh during the day, which increases to 120/130 after 19:00.  See example: https://www.openstreetmap.org/way/7048574#map=14/52.24543/4.97166

This is often tagged as:
"maxspeed"="100"
"maxspeed:conditional"="130 @ (19:00-06:00)"

At the moment Organic Maps seems to ignore the conditional limits, which shows an incorrect speed limit value.

### LINKED ISSUE #11918: App doesn't respect maxspeed:conditional in navigation mode
**Describe the issue**
Hello. Faced with issue with speed limit in navigation mode. Both parameters were set in this place (maxspeed and maxspeed:conditional) and condition met now. But I see only maxspeed limit. 

Place: https://www.openstreetmap.org/#map=18/54.688931/25.046468

Maxspeed: 130
maxspeed:conditional: 110 @ (Nov - Mar) - now is december.

**Steps to reproduce**
1. Ride in a place with maxspeed and maxspeed:conditional
2. Check speed limit

**Expected behaviour**
To show conditional speed limit if it set

**Screenshots**
Image

**System information:**
 - Operating system and its version: [Android 15 (HyperOS 2.0.211)]
 - Organic Maps version: [2025.12.11-22-Google-beta]
 - Device Model: [Xiaomi Redmi Note 14 Pro 5G]

### PR DESCRIPTION
**Pull request by Abdelhadi-Wael**
Generator: Parse maxspeed:conditional tags and update the collector and builder to handle conditional speed and string columns.

Serialization: Update Serializer to store conditional data when present.

Runtime: Use osmoh::OpeningHours to apply the conditional speed when the condition is true.

Tests: Add unit tests to test parsing and different CSV formats handling.
Besides the unit tests i tested manually by generating the Lithuania map and testing routing max speed on Android.

Closes #11918, Closes #9016

### CODE REVIEW

**Comment by Abdelhadi-Wael** [comment]
@biodranik Can you please review?

File: libs/routing/maxspeeds_serialization.hpp [hunk 1]
```diff
@@ -59,11 +60,15 @@ class MaxspeedsSerializer
...
-    bool IsBidirectional() const { return m_backward != SpeedMacro::Undefined; }
+    // A feature is Complex if it has Backward OR Conditional data.
+    bool IsComplex() const { return m_backward != SpeedMacro::Undefined || m_conditional != SpeedMacro::Undefined; }
 
     uint32_t m_featureID;
     SpeedMacro m_forward;
     SpeedMacro m_backward;
+
+    SpeedMacro m_conditional = SpeedMacro::Undefined;
+    std::string m_conditionalString;
```
Comment (vng) [inline libs/routing/maxspeeds_serialization.hpp]: Store ```osmoh::OpeningHours``` and use ```OpeningHoursSerDes``` here instead of raw string.

File: libs/routing/maxspeeds_serialization.hpp [hunk 2]
```diff
@@ -202,7 +215,35 @@ class MaxspeedsSerializer
...
+        backwardSpeed = converter.MacroToSpeed(static_cast<SpeedMacro>(backwardIdx));
+        CHECK(backwardSpeed.IsValid(), (i));
+      }
+      else
+        backwardSpeed = forwardSpeed;  // No backward.
+
+      SpeedInUnits conditionalSpeed;
+      std::string conditionalString;
+
+      auto const condIdx = ReadPrimitiveFromSource<uint8_t>(src);
```
Comment (vng) [inline libs/routing/maxspeeds_serialization.hpp]: MWM versioning should be included here.

**Comment by Abdelhadi-Wael** [comment]
> I can continue working on this PR if you don't mind.

Sure, I don't mind if you continue working on it :)

File: libs/routing/maxspeeds_serialization.hpp [hunk 3]
```diff
@@ -202,7 +230,34 @@ class MaxspeedsSerializer
...
+
+      auto const backwardIdx = ReadPrimitiveFromSource<uint8_t>(src);
+      SpeedInUnits backwardSpeed;
+      if (static_cast<SpeedMacro>(backwardIdx) != SpeedMacro::Undefined)
+      {
+        backwardSpeed = converter.MacroToSpeed(static_cast<SpeedMacro>(backwardIdx));
+        CHECK(backwardSpeed.IsValid(), (i));
+      }
+      else
+        backwardSpeed = forwardSpeed;  // No backward.
```
Comment (vng) [inline libs/routing/maxspeeds_serialization.hpp]: Well, I understand the point here since you have changed IsBidirectional -> IsComplex, but have doubts still ...

File: libs/routing/maxspeeds.cpp [hunk 4]
```diff
@@ -40,7 +49,13 @@ Maxspeed Maxspeeds::GetMaxspeed(uint32_t fid) const
     return Maxspeed();  // No maxspeed for |fid| is set. Returns an invalid Maxspeed instance.
 
   CHECK_EQUAL(range.second - range.first, 1, ());
-  return range.first->GetMaxspeed();
+
+  Maxspeed result = range.first->GetMaxspeed();
+
+  if (result.HasConditional() && IsConditionalActive(result.GetConditionalTime()))
+    result.SetForward(result.GetConditionalSpeed());
```
Comment (vng) [inline libs/routing/maxspeeds.cpp]: This will not work as expected because we should check the condition not with the current time(nullptr), but with the time when a vehicle is expected to be arrived to that point (way with conditional speed).

You can see how it is made in RoadAccess (with a condition) check.

This is the most non-obvious part.
I am already thinking about client speed check refactoring. Your thoughts are welcome.

**Comment by vng** [comment]
@Abdelhadi-Wael I've added a commit with minor refactoring and more tests.

At this point, the code is ok to generate and save a conditional speed.

Should refactor the client code with proper time->condition check.

File: generator/maxspeeds_collector.cpp [hunk 5]
```diff
@@ -49,66 +42,86 @@ void MaxspeedsCollector::CollectFeature(feature::FeatureBuilder const & ft, OsmE
...
+
+  if (!maxspeed.IsValid() && !maxspeedCond.IsValid())
+  {
+    if (recalcIndicator)
+      maxspeed.SetSpeed(routing::kCommonMaxSpeedValue);
+    else
+      return;
+  }
+
+  m_stream << p.m_id << "," << UnitsToString(maxspeed.IsValid() ? maxspeed.GetUnits() : maxspeedCond.GetUnits()) << ","
```
Comment (biodranik) [inline generator/maxspeeds_collector.cpp:122]: nit: std::format or std::format_to are 3x-5x faster than ostringstream.

File: generator/maxspeeds_parser.cpp [hunk 6]
```diff
@@ -201,6 +201,39 @@ bool ParseMaxspeedTag(std::string const & maxspeedValue, routing::SpeedInUnits &
   return false;
 }
 
+bool ParseMaxspeedConditionalTag(std::string const & maxspeedConditional, routing::SpeedInUnits & speed,
```
Comment (biodranik) [inline generator/maxspeeds_parser.cpp]: nit: bool + ref_buffer are faster mostly when ref_buffer is reused e.g. in a loop. std::optional is more readable and is usually as fast as bool+ref

File: generator/maxspeeds_parser.cpp [hunk 7]
```diff
@@ -201,6 +201,39 @@ bool ParseMaxspeedTag(std::string const & maxspeedValue, routing::SpeedInUnits &
...
+                                 std::string & condition)
+{
+  // Example: "110 @ (Nov - Mar)"
+  auto const atPos = maxspeedConditional.find('@');
+  if (atPos == std::string::npos)
+    return false;
+
+  std::string speedStr = maxspeedConditional.substr(0, atPos);
```
Comment (biodranik) [inline generator/maxspeeds_parser.cpp]: nit: use std::string_view here and below?

**Comment by vng** [comment]
Well, good try, but not what I was supposed to see.

- Remove the last commit ("[generator]: minor fixes]"). It produces only bigger number of lines without any actual meaning. 
```std::optional<std::pair<SpeedInUnits, string>>``` - this is ugly :)
- ```RoadGeometry``` class should store (cache)```Maxspeed``` instead of current ```SpeedKMpH m_forwardSpeed, m_backwardSpeed```. And should provide the speed with time check from here:
```
// time == 0 means no checks
SpeedKMpH GetSpeed(bool forward, time_t time = 0) const;
```
- So no need to store ```Maxspeeds``` in ```IndexGraph```
- Other things like tests and ```EdgeEstimator```look ok (at first glance).

**Comment by Abdelhadi-Wael** [comment]
> * Remove the last commit ("[generator]: minor fixes]"). It produces only bigger number of lines without any actual meaning.
>   `std::optional<std::pair<SpeedInUnits, string>>` - this is ugly :)

Done.



> * `RoadGeometry` class should store (cache)`Maxspeed` instead of current `SpeedKMpH m_forwardSpeed, m_backwardSpeed`. And should provide the speed with time check from here:

We need ```SpeedKMpH m_forwardSpeed, m_backwardSpeed``` to store ```m_eta, m_weight``` am i wrong ?

```  
double m_weight =
      0.0;  // KMpH - speed in km/h adjusted for desirability
            // cycling on very large road may be fast but speed used for route finding will be treated as much lower
  double m_eta = 0.0;  // KMpH - actual expected speed in km/h, used to display expected arrival time
  ```
  
  Please check out my last commit when you have the time (91d164408f20381177dec72916cbd342d1b88ced)

**Comment by vng** [comment]
@Abdelhadi-Wael Please, check my last commit.

**Comment by vng** [comment]
Checked on real (newly generated) data - works as expected.

File: generator/maxspeeds_builder.cpp [hunk 8]
```diff
@@ -352,49 +338,57 @@ bool ParseMaxspeeds(string const & filePath, OsmIdToMaxspeed & osmIdToMaxspeed)
...
+    if (++iter && conditional != kInvalidSpeed)
+    {
+      std::string conditionalStr(*iter);
+      while (++iter)
+        conditionalStr.append(",").append(*iter);
 
-      if (iter)
-        return false;
+      osmoh::OpeningHours oh(conditionalStr);
+      if (oh.IsValid())
```
Comment (biodranik) [inline generator/maxspeeds_builder.cpp:380]: Warn if invalid to see which cases should be supported/fixed?

File: generator/maxspeeds_collector.hpp [hunk 9]
```diff
@@ -34,25 +34,20 @@ class MaxspeedsCollector : public CollectorInterface
...
-  // 45432423,Metric,60,65534
-  // 53445423,Metric,60,65533
+  // |m_stream| contains strings with maxspeed tags value for corresponding features:
+  // OSM id,units (Metric/Imperial),maxspeed(forward),maxspeed:backward,maxspeed:conditional,string condition
   //
-  // Note 1. 65534 means kNoneMaxSpeed and 65533 means kWalkMaxSpeed. They are constants for
-  // maxspeed tag value "none" and "walk" correspondingly.
-  // Note 2. Saying osm id means osm id of features with OsmElement::EntityType::Way type without
+  // There are possible examples of strings contained in the list |m_stream|:
+  // 2343313,Metric,60,,,
```
Comment (biodranik) [inline generator/maxspeeds_collector.hpp:41]: Can speed limits in OpenStreetMap.org data contain commas?

File: generator/maxspeeds_parser.cpp [hunk 10]
```diff
@@ -201,6 +201,42 @@ bool ParseMaxspeedTag(std::string const & maxspeedValue, routing::SpeedInUnits &
...
+  strings::Trim(str);
+
+  condition.clear();
+  for (auto c : str)
+    if (c != '(' && c != ')')
+      condition.push_back(std::tolower(c));
+
+  strings::Trim(condition);
+
+  if (condition == "winter")
```
Comment (biodranik) [inline generator/maxspeeds_parser.cpp:228]: - There are 109K tags
- 2816 unique values, 508 with `PH off` that is not yet supported properly by OH AFAIR
- There are sunset-sunrise and sunrise-sunset
- There are dusk-dawn and down-dusk
- Many conditions depend on weather (wet, snow, lighting)
- "When children present", "school", "flashing"
- There are maxweight and vehicle type-related conditions we can use later

[maxspeed_conditional_raw.txt.zip](https://github.com/user-attachments/files/25457622/maxspeed_conditional_raw.txt.zip)
[maxspeed_conditional_unique.txt.zip](https://github.com/user-attachments/files/25457623/maxspeed_conditional_unique.txt.zip)

File: libs/routing/geometry.cpp [hunk 11]
```diff
@@ -93,8 +93,15 @@ class GeometryLoaderImpl final : public GeometryLoader
...
   {
-    auto const speed = m_attrsGetter.m_maxSpeeds.GetMaxspeed(featureId);
-    return {speed.GetSpeedInUnits(forward), speed.GetUnits()};
+    auto const maxspeed = m_attrsGetter.m_maxSpeeds.GetMaxspeed(featureId);
+
+    MaxspeedType speed = kInvalidSpeed;
+    if (!forward)
+      speed = maxspeed.GetBackward();
+    if (speed == kInvalidSpeed)
+      speed = maxspeed.GetForward();
```
Comment (biodranik) [inline libs/routing/geometry.cpp:102]: nit: feels like std::option in such cases could be cleaner and more explicit.

**Comment by dmitrygribenchuk** [comment]
> LGTM with beta testing. Maybe check and add to OpenStreetMap.org some local conditional restrictions and see if they work properly?

I can test it on real data if I find out how to build the application

File: generator/maxspeeds_builder.cpp (hunk 8 above)
Comment (vng) [reply generator/maxspeeds_builder.cpp:380]: A huge. All of them are known for OH, no need to spam here.

File: generator/maxspeeds_collector.hpp (hunk 9 above)
Comment (vng) [reply generator/maxspeeds_collector.hpp:41]: Yes, they are processed separately in parsing.

File: libs/routing/geometry.cpp (hunk 11 above)
Comment (vng) [reply libs/routing/geometry.cpp:102]: No

**Comment by vng** [comment]
@biodranik 
Already have an integration test, will be committed with the new map data.
