### PR TITLE
[editor] Allow removing cuisines from selection

### LINKED ISSUE #1283: [Editor]: can't remove cuisines from"Cuisine" field
**OS:** LineageOS 17.1 (Android 10.0)
**App ver.:** 2021.09.01-6-Google

If you try to remove cuisines from `Cusine` field, nothing happens - all flags are returning to their initial state after you return to main editor screen, no matter if you clear all flags or just some of them. There's also no dependency on the type of object.

Here's the video:

https://user-images.githubusercontent.com/22843816/132943792-3fe9568e-06e8-473a-82d8-defb9e4931e5.mp4

### LINKED ISSUE #2842: Removing cuisine from restaurant data does not work
When I try to remove a kitchen from the data, I uncheck the list, save the changes, but the kitchen remains in the restaurant data

### PR DESCRIPTION
**Pull request by arnaudvergnet**
Instead of copying the whole feature types object before adding the cuisine selection, we copy only the types which are not cuisines.

This allows removing cuisines from the current feature.

Closes #1283, closes #2842

### CODE REVIEW

File: indexer/editable_map_object.cpp [hunk 1]
```diff
@@ -578,9 +578,16 @@ template <class T>
...
-  params.m_types.assign(m_types.begin(), m_types.end());
 
   Classificator const & cl = classif();
+  // Ignore cuisine types as these will be set from the cuisines param
+  for (auto const & type : m_types)
+  {
+    vector<std::string> const &object_path = cl.GetFullObjectNamePath(type);
+    if (!object_path.empty() && object_path.at(0) != "cuisine")
+      params.m_types.push_back(type);
+  }
```
Comment (vng) [inline indexer/editable_map_object.cpp:589]:
```
auto const & isCuisine = IsCuisineChecker::Instance();
for (uint32_t const type : m_types)
{
  if (!isCuisine(type))
    params.m_types.push_back(type);
}
```

Comment (arnaudvergnet) [reply indexer/editable_map_object.cpp:588]: A lot more elegant!

**Review by vng — APPROVED** [review]
