### PR TITLE
[android] Display list of stop points in ruler and transit mode properly in RTL

### LINKED ISSUE #7084: List of stop point in ruler mode and transport mode is not aligned at the right in RTL
**Steps to reproduce**
1. Open Organic Maps in the Arabic language
2. Select first POI and select ruler routing
3. Touch at least 2 POI
4. The list of stop points is not aligned at the right

**Expected behaviour**
The list of stop points follows the layout direction of app.

**Screenshots**

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2023.12.21-1-Google
 - Device Model: Pixel 6

CC @strump

### PR DESCRIPTION
**Pull request by beasmm**
Closes #7084
Changes made:
	- In MultilineLayoutManager.java: if called with LAYOUT_DIRECTION_RTL tag, the layout is now properly written.
	- In RoutinBottomMenuController.java: MultilineLayoutManager class is now called with the new parameter, the mTransitFrame's layout direction.
	- In DotDividerItemDecoration.java: to properly place the dots between the elements in the list, these elements are iterated from right to left when the layout direction is RTL.

**Screenshots of changes**
| Before             |  After |
:-------------------------:|:-------------------------:
|

| Ruler mode             |  Transit mode |
:-------------------------:|:-------------------------:
|

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Thanks! It looks like a hack. Is there a simpler way to fix the issue? What is the root cause of it?

**Comment by beasmm** [comment]
In LTR languages, as the MultilineLayoutManager.java and DotDividerItemDecoration.java classes were implemented, the elements of the list of points where placed one by in a for loop from left to right. My logic was that, when the app's language assumes RTL orientation, the for loop placed the from right to left. Does this make sense? Do you have any feedback? I don't understand how it is a hack.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14
@biodranik PTAL

**Review by biodranik — COMMENTED** [review]
@rtsisyk @Jean-BaptisteC does it work in beta with RTL languages? If yes, then we can merge it for the release.

**Comment by Jean-BaptisteC** [comment]
Yes it's work in beta
Go to merge

File: android/app/src/main/java/app/organicmaps/widget/recycler/MultilineLayoutManager.java [hunk 1]
```diff
@@ -25,6 +28,8 @@ public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State
   {
     detachAndScrapAttachedViews(recycler);
 
+    assertInLayoutOrScroll(null);
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/widget/recycler/MultilineLayoutManager.java:31]: Is this call really necessary?

File: android/app/src/main/java/app/organicmaps/widget/recycler/MultilineLayoutManager.java [hunk 2]
```diff
@@ -8,9 +8,12 @@
 
 public class MultilineLayoutManager extends RecyclerView.LayoutManager
 {
-  public MultilineLayoutManager()
+  private boolean reverseLayout = false;
+
+  public MultilineLayoutManager(int layoutDirection)
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/widget/recycler/MultilineLayoutManager.java:13]: Is there an alternative way to implement similar functionality using some system/androidx classes? CC @Jean-BaptisteC
