### PR TITLE
[android] Fix missing buttons after restarting the app during navigation

### LINKED ISSUE #6712: [android] Search and bookmaks buttons disappear in the nav mode after app restart
1. start navigation
2. stop the app (swipe it away, not just switch to another app)
3. restart the app, it'll restore the navigation mode
4. left-side search and bookmarks buttons disappear

Present in the current release, no idea when this bug has appeared.

CC @Jean-BaptisteC @strump

### PR DESCRIPTION
**Pull request by rtsisyk**
Swiping the app away from the recent app lists during navigation doesn't kill the app process because of the active foreground navigation service. The next start of MwmActivity should properly restore all the navigation UI if the background navigation was already in progress. This logic was moved to MwmActivity.onRenderingInitializationFinished() by fe06fc8429 #6556 "Refactor API and Intent processing" to fix weird race conditions when restoring the route without initialized drape.

The issue was that onRenderingInitializationFinished() was not called when MwmActivity was recreated with already initialized native core. Call it explicitly from MwmActivity.onSafeCreate() to initialize navigation UI and handle incoming intents.

Fixes #6712

### CODE REVIEW

File: android/app/src/main/java/app/organicmaps/MwmActivity.java [hunk 1]
```diff
@@ -513,6 +507,9 @@ protected void onSafeCreate(@Nullable Bundle savedInstanceState)
 
     if (getIntent().getBooleanExtra(EXTRA_UPDATE_THEME, false))
       ThemeSwitcher.INSTANCE.restart(isMapRendererActive());
+
+    if (Map.isEngineCreated())
+      onRenderingInitializationFinished();
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/MwmActivity.java:512]: It would be great to have a comment about why this call is needed here.

**Review by biodranik — APPROVED** [review]
