### PR TITLE
[gpx] Specify xmlns for gpx color export

### LINKED ISSUE #8332: Add support of bookmarks and tracks colors in GPX export
Sharing from Organic Maps to OpenTracks as well as using Import All button produces the same error:

OpenTracks v.4.6.1

### PR DESCRIPTION
**Pull request by cyber-toad**
Fixes #8332, #9969 
Initial PR for discussions and testing, not for merge yet

### CODE REVIEW

**Comment by cyber-toad** [comment]
Hi, @RSR3455. Could you please check with testing for #9969 and check this file (remove .txt suffix after download) - is it visible in Garmin Basemap app and does route has green color?
Thanks.
[export_test.gpx.txt](https://github.com/user-attachments/files/18461782/export_test.gpx.txt)

**Comment by cyber-toad** [comment]
@0709wiwiwi I tried to implement schema that you suggested - could you please have a look on file attached above - it is a test file stored with new schema. Is it in sync with what you suggested, is it valid in validators that you used (I tried one online tool and it was fine, not sure how strict it is) and is it displayed with proper color in apps that you checked?

**Comment by cyber-toad** [comment]
Verified with gpx studio - color is supported
image

**Comment by RSR3455** [comment]
Basecamp gave an error message when I attempted to open the file after removing the .txt suffix, so I was unable to successfully open the file into Basecamp.

FYI, Basecamp is a free application from Garmin and can be downloaded using the following link: https://www.garmin.com/en-US/software/basecamp/.  Both Mac and Windows versions are available for download.


Robert Rearden
Fort Worth, Texas
USA
________________________________________


On Jan 17, 2025, at 5:40 PM, cyber-toad ***@***.***> wrote:


Hi, @RSR3455 <https://github.com/RSR3455>. Could you please help with testing for #9969 <https://github.com/organicmaps/organicmaps/issues/9969> and check this file (remove .txt suffix after download) - is it visible in Garmin Basemap app and does route has green color?
Thanks.
export_test.gpx.txt <https://github.com/user-attachments/files/18461782/export_test.gpx.txt>

**Comment by RSR3455** [comment]
I should have added to my earlier email that I am a GPS user with limited knowledge of GPX schema structure. I am glad to be a tester, but you may prefer to download the Basecamp application to your test sandbox.


Robert Rearden
Fort Worth, Texas
USA
________________________________________


On Jan 17, 2025, at 8:11 PM, Robert Rearden ***@***.***> wrote:

Basecamp gave an error message when I attempted to open the file after removing the .txt suffix, so I was unable to successfully open the file into Basecamp.

FYI, Basecamp is a free application from Garmin and can be downloaded using the following link: https://www.garmin.com/en-US/software/basecamp/.  Both Mac and Windows versions are available for download.


Robert Rearden
Fort Worth, Texas
USA
________________________________________


On Jan 17, 2025, at 5:40 PM, cyber-toad ***@***.***> wrote:


Hi, @RSR3455 <https://github.com/RSR3455>. Could you please help with testing for #9969 <https://github.com/organicmaps/organicmaps/issues/9969> and check this file (remove .txt suffix after download) - is it visible in Garmin Basemap app and does route has green color?
Thanks.
export_test.gpx.txt <https://github.com/user-attachments/files/18461782/export_test.gpx.txt>

**Comment by cyber-toad** [comment]
Thanks, @RSR3455. I was able to install this app and check what is the issue with my latest file - some XML validity things should be fixed. But finally I was able to generate a valid GPX and it is available in Garmin Map with color applied. So once this PR is released you will be able to export compatible tracks from OM.

**Comment by cyber-toad** [comment]
@0709wiwiwi could you please check attached file with your validators/apps?
I tried to apply schemas that you suggested and was able to have a valid color in some apps.
[export_color.gpx.txt](https://github.com/user-attachments/files/18464086/export_color.gpx.txt)

**Comment by 0709wiwiwi** [comment]
The file is not valid due to the lack of <gpx version="1.1”
  creator="cyber-toad”
Once in production optimize this as follows: creator="Organic Maps version .........” 
Garmin is merciless on this point. Other apps are usually a little more tolerant ;-)

**Comment by 0709wiwiwi** [comment]
One more note.  Speech confusion in diverse gps apps often arises as follows.

In quite a few apps, the gpx waypoints are referred to as being routepoints.
So they are not that in the first place, they just indicate an individual location.
But you can promote them into route(way)points that the routing engine will then work with. 
Route(way) points are then “sentenced” to be “snapped” to a nearby street by the router.
Associated track points are so produced by each extra via or shaping added routepoint.
Routepoints with which you draw manual tracksections are NOT handled by the router engine. 
The created "beeline" section trackpoints copy the original routepoint position unchanged.

More here: https://github.com/devemux86/cruiser/discussions/250

If you asks AI some info about this item it will give you false answers. 
AI is also sometimes confused and definitely is still learning.

**Comment by cyber-toad** [comment]
> The file is not valid due to the lack of <gpx version="1.1” creator="cyber-toad” Once in production optimize this as follows: creator="Organic Maps version .........” Garmin is merciless on this point. Other apps are usually a little more tolerant ;-)

Yes, I initially uploaded a file without valid gpx header, but I removed this comment, but probably before you downloaded the file. I fixed it and not it contains a file that passes Notepad++ checks.

**Comment by cyber-toad** [comment]
@biodranik @rtsisyk could you please review c++ changes. 
I worry a bit about assignment of color string here:

```
      if (distance < min) {
        min = distance;
        color = garminName;
      }
```
will it generate a copy so better to try to switch to string_view and move map outside of this function to member class?

**Comment by RSR3455** [comment]
Thank you for your efforts to resolve this issue.

File: kml/kml_tests/gpx_tests.cpp [hunk 1]
```diff
@@ -40,6 +40,22 @@ void importExportCompare(char const * testFile)
...
 
+void importExportCompare(char const * sourceFile, char const * destinationFile)
+{
+  auto const sourceFileName = GetPlatform().TestsDataPathForFile(sourceFile);
+  std::string sourceFileText;
+  FileReader(sourceFileName).ReadAsString(sourceFileText);
+  kml::FileData const dataFromFile = loadGpxFromFile(sourceFile);
+  std::string resultBuffer;
+  MemWriter<decltype(resultBuffer)> sink(resultBuffer);
+  kml::gpx::SerializerGpx ser(dataFromFile);
```
Comment (biodranik) [inline kml/kml_tests/gpx_tests.cpp:51]: nit: copy paste.

File: kml/serdes_gpx.cpp [hunk 2]
```diff
@@ -34,8 +34,14 @@ std::string_view constexpr kCmt = "cmt";
 std::string_view constexpr kTime = "time";
 
 std::string_view constexpr kGpxHeader =
-    "<?xml version=\"1.0\"?>\n"
-    "<gpx xmlns=\"http://www.topografix.com/GPX/1/1\" version=\"1.1\">\n";
+  "<?xml version=\"1.0\"?>\n"
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:37]: nit: Using raw string literals can be more readable: https://en.cppreference.com/w/cpp/language/string_literal

File: kml/serdes_gpx.cpp [hunk 3]
```diff
@@ -133,7 +139,12 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
 
 void GpxParser::ParseColor(std::string const & value)
 {
-  auto const colorBytes = FromHex(value);
+  std::string_view colorStr = value;
+  if (colorStr.at(0) == '#')
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:143]: 1. at() throws an exception if index is invalid, so it is slower than .front() or colorStr[0].
2. Is value always non-empty here?

File: kml/serdes_gpx.cpp [hunk 4]
```diff
@@ -133,7 +139,12 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
 
 void GpxParser::ParseColor(std::string const & value)
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:140]:
```suggestion
void GpxParser::ParseColor(std::string_view value)
```

File: kml/serdes_gpx.cpp [hunk 5]
```diff
@@ -133,7 +139,12 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
 {
-  auto const colorBytes = FromHex(value);
+  std::string_view colorStr = value;
+  if (colorStr.at(0) == '#')
+    colorStr = colorStr.substr(1, colorStr.size() - 1);
+  if (colorStr.length() == 8)
+    colorStr = colorStr.substr(2, colorStr.length() - 1);
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:146]: Consistency: either always use .size() or always use .length()

File: kml/serdes_gpx.cpp [hunk 6]
```diff
@@ -133,7 +139,12 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
 
 void GpxParser::ParseColor(std::string const & value)
 {
-  auto const colorBytes = FromHex(value);
+  std::string_view colorStr = value;
+  if (colorStr.at(0) == '#')
+    colorStr = colorStr.substr(1, colorStr.size() - 1);
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:144]: Will .remove_prefix(1) work?

File: kml/serdes_gpx.cpp [hunk 7]
```diff
@@ -133,7 +139,12 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
+  if (colorStr.length() == 8)
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:145]: What is this case?

File: kml/serdes_gpx.cpp [hunk 8]
```diff
@@ -133,7 +139,12 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
+    colorStr = colorStr.substr(2, colorStr.length() - 1);
+  auto const colorBytes = FromHex(colorStr);
   if (colorBytes.size() != 3)
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:148]: Can color be transparent?

File: kml/serdes_gpx.cpp [hunk 9]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
 
+void SaveColorToARGB(Writer & writer, uint32_t rgba)
+{
+  writer << NumToHex(static_cast<uint8_t>(rgba & 0xFF))
+         << NumToHex(static_cast<uint8_t>(rgba >> 24 & 0xFF))
+         << NumToHex(static_cast<uint8_t>((rgba >> 16) & 0xFF))
+         << NumToHex(static_cast<uint8_t>((rgba >> 8) & 0xFF));
+}
+
+std::tuple<uint8_t, uint8_t, uint8_t> ExtractRGB(std::uint32_t color) {
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:505]:
```suggestion
std::tuple<uint8_t, uint8_t, uint8_t> ExtractRGB(uint32_t color)
{
```

File: kml/serdes_gpx.cpp [hunk 10]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+  return {(color >> 24) & 0xFF, (color >> 16) & 0xFF, (color >> 8) & 0xFF};
+}
+
+int ColorDistance(std::uint32_t color1, std::uint32_t color2) {
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:509]:
```suggestion
int ColorDistance(uint32_t color1, uint32_t color2)
{
```

File: kml/serdes_gpx.cpp [hunk 11]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+  auto [r1, g1, b1] = ExtractRGB(color1);
+  auto [r2, g2, b2] = ExtractRGB(color2);
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:511]: nit
```suggestion
  auto const [r1, g1, b1] = ExtractRGB(color1);
  auto const [r2, g2, b2] = ExtractRGB(color2);
```

File: kml/serdes_gpx.cpp [hunk 12]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+    {0xff00ffff, "Magenta"},
+    {0x00ffffff, "Cyan"},
+    {0xffffffff, "White"},
+    {0xff0000ff, "Transparent"}
+  };
+  auto const it = kHexToGarmin.find(rgba);
+  if (it != kHexToGarmin.end())
+  {
+    return it->second;
+  }
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:540]:
```suggestion
    return it->second;
```

File: kml/serdes_gpx.cpp [hunk 13]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+  const auto & first = kHexToGarmin.begin();
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:541]:
```suggestion
  const auto & [min, color] = *kHexToGarmin.begin();
```

File: kml/serdes_gpx.cpp [hunk 14]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+  return {(color >> 24) & 0xFF, (color >> 16) & 0xFF, (color >> 8) & 0xFF};
+}
+
+int ColorDistance(std::uint32_t color1, std::uint32_t color2) {
+  auto [r1, g1, b1] = ExtractRGB(color1);
+  auto [r2, g2, b2] = ExtractRGB(color2);
+  return (r1 - r2) * (r1 - r2) + (g1 - g2) * (g1 - g2) + (b1 - b2) * (b1 - b2);
+}
+
+std::string MapGarminColor(uint32_t rgba)
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:515]: Is there a test for this method?

File: kml/serdes_gpx.cpp [hunk 15]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+{
+  static std::unordered_map<std::uint32_t, std::string> const kHexToGarmin = {
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:517]:
```suggestion
  static std::unordered_map<std::uint32_t, std::string_view> const kHexToGarmin = {
```

File: kml/serdes_gpx.cpp [hunk 16]
```diff
@@ -483,6 +494,66 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+    {0xffffffff, "White"},
+    {0xff0000ff, "Transparent"}
+  };
+  auto const it = kHexToGarmin.find(rgba);
+  if (it != kHexToGarmin.end())
+  {
+    return it->second;
+  }
+  const auto & first = kHexToGarmin.begin();
+  u_int32_t min = first->first;
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:542]: Will the code below work properly if this min is some color from garmin table?

File: kml/serdes_gpx.cpp (hunk 14 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:515]: It is covered in Gpx_ImportExport_Test where color from hashtable is used and in Gpx_ColorMapExport_Test where 0x443344 that is not in the table is mapped to closest one (DarkGray)

File: kml/serdes_gpx.cpp (hunk 16 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:542]: yes, there is a typo there, should be `min = ColorDistance(first->first, rgba); ` I fixed it

File: kml/serdes_gpx.cpp (hunk 15 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:517]: Should I make function to return std::string_view for this change or create std::string before return? If  use string_view for color, I got a warning in IDE that address of local variable color escaped the function, I'm not confident in my cpp knowledge to get is it an issue :) (I remember we had some problems with memory in gpx parser when it was reworked to string_view).

File: kml/serdes_gpx.cpp (hunk 12 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:540]: Fixed

File: kml/serdes_gpx.cpp (hunk 11 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:511]: Fixed

File: kml/serdes_gpx.cpp (hunk 10 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:509]: Fixed

File: kml/serdes_gpx.cpp (hunk 9 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:505]: Fixed

File: kml/serdes_gpx.cpp (hunk 8 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:148]: In theory it could be in gpx.
But later we have```

  if (colorBytes.size() != 3)
  {
    LOG(LWARNING, ("Invalid color value", value));
```
so it will reject such colors, so when I saw it I added additional code to avoid issue if we have 4 components

File: kml/serdes_gpx.cpp (hunk 7 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:145]: We have something like <xsi:gpx><color>#FF00FF00</color></xsi:gpx> in gpx. It is handled by default parser (not Osmand/etc) and earlier it was not ready for such representation

File: kml/serdes_gpx.cpp (hunk 6 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:144]: Fixed

File: kml/serdes_gpx.cpp (hunk 5 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:146]: Fixed

File: kml/serdes_gpx.cpp (hunk 4 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:140]: Fixed

File: kml/serdes_gpx.cpp (hunk 3 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:143]: We could have some invalid file with empty color value, so I reworked it a bit to add a check

File: kml/serdes_gpx.cpp (hunk 2 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:37]: Fixed

File: kml/serdes_gpx.cpp (hunk 13 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:543]: This makes color const, but we assign it inside loop later

File: kml/serdes_gpx.cpp [hunk 17]
```diff
@@ -137,13 +134,18 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
   return m_tags[m_tags.size() - n - 1];
 }
 
-void GpxParser::ParseColor(std::string const & value)
+void GpxParser::ParseColor(std::string_view value)
 {
   std::string_view colorStr = value;
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:139]: Is this line needed? Why `value` (better rename it to `colorStr`) can not be used directly?

File: kml/serdes_gpx.cpp (hunk 8 above)
Comment (biodranik) [reply kml/serdes_gpx.cpp:150]: Can drape engine render semitransparent tracks? If yes, then it may be good to support additional transparent byte. Otherwise it can be ignored/forced to always opaque.

File: kml/serdes_gpx.cpp [hunk 18]
```diff
@@ -502,13 +504,15 @@ void SaveColorToARGB(Writer & writer, uint32_t rgba)
          << NumToHex(static_cast<uint8_t>((rgba >> 8) & 0xFF));
 }
 
-std::tuple<uint8_t, uint8_t, uint8_t> ExtractRGB(std::uint32_t color) {
+std::tuple<uint8_t, uint8_t, uint8_t> ExtractRGB(uint32_t color)
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:507]: Internal .cpp helper functions should be either static or in anonymous `namespace` to avoid being exported.

File: kml/serdes_gpx.cpp [hunk 19]
```diff
@@ -502,13 +504,15 @@ void SaveColorToARGB(Writer & writer, uint32_t rgba)
...
+{
   return {(color >> 24) & 0xFF, (color >> 16) & 0xFF, (color >> 8) & 0xFF};
 }
 
-int ColorDistance(std::uint32_t color1, std::uint32_t color2) {
-  auto [r1, g1, b1] = ExtractRGB(color1);
-  auto [r2, g2, b2] = ExtractRGB(color2);
+int ColorDistance(uint32_t color1, uint32_t color2)
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:512]: ditto

File: kml/serdes_gpx.cpp (hunk 13 above)
Comment (biodranik) [reply kml/serdes_gpx.cpp:543]: Make it non-const then )

File: kml/serdes_gpx.cpp [hunk 20]
```diff
@@ -535,11 +539,9 @@ std::string MapGarminColor(uint32_t rgba)
   };
   auto const it = kHexToGarmin.find(rgba);
   if (it != kHexToGarmin.end())
-  {
     return it->second;
-  }
   const auto & first = kHexToGarmin.begin();
-  u_int32_t min = first->first;
+  u_int32_t min = ColorDistance(first->first, rgba);
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:544]: What is u_int32_t?

File: kml/serdes_gpx.cpp (hunk 17 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:139]: Some leftover after multiple changes, renamed it in method signature

File: kml/serdes_gpx.cpp (hunk 20 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:544]: I made a typo, but cpp has type for it also :)  Fixed

File: kml/serdes_gpx.cpp (hunk 13 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:543]: I slightly reworked it and now deconstructor is used as suggested.

File: kml/kml_tests/gpx_tests.cpp (hunk 1 above)
Comment (cyber-toad) [reply kml/kml_tests/gpx_tests.cpp]: Fixed

File: kml/serdes_gpx.cpp (hunk 18 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:506]: I think they are already in `namespace {` - line 480?

File: kml/serdes_gpx.cpp (hunk 19 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp]: I think they are already in `namespace {` - line 480?

**Comment by cyber-toad** [comment]
> Can drape engine render semitransparent tracks? If yes, then it may be good to support additional transparent byte. Otherwise it can be ignored/forced to always opaque.

By some reason can't reply to initial comment.
I tried to set 128 to alpha instead of 255 and track was displayed as earlier, so probably it is not supported yet.

File: kml/serdes_gpx.cpp [hunk 21]
```diff
@@ -483,6 +495,63 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+    {0x00ffffff, "Cyan"},
+    {0xffffffff, "White"},
+    {0xff0000ff, "Transparent"}
+  };
+  auto const it = kHexToGarmin.find(rgba);
+  if (it != kHexToGarmin.end())
+    return it->second;
+  auto [hex, closestColor] = *kHexToGarmin.begin();
+  uint32_t minDistance = ColorDistance(hex, rgba);
+  for (const auto & [garminColor, garminName] : kHexToGarmin)
```
[the remark this answers is not in the document]
Comment (biodranik) [reply kml/serdes_gpx.cpp:544]: As a bonus, you can move this constexpr array into an anonymous namespace, and reuse it in ParseGarminColor method.

Maybe ParseOsmandColor can also be improved using string_view.

These improvements can be done in a separate PR

File: kml/kml_tests/gpx_tests.cpp [hunk 22]
```diff
@@ -11,7 +11,7 @@
 
 namespace gpx_tests
 {
-static kml::FileData loadGpxFromString(std::string_view content) {
+static kml::FileData LoadGpxFromString(std::string_view content) {
```
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/kml_tests/gpx_tests.cpp:14]: fixed formatting

File: kml/serdes_gpx.cpp [hunk 23]
```diff
@@ -483,6 +495,63 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+    {0xccccccff, "LightGray"},
+    {0x444444ff, "DarkGray"},
+    {0xff0000ff, "Red"},
+    {0x00ff00ff, "Green"},
+    {0xffff00ff, "Yellow"},
+    {0x0000ffff, "Blue"},
+    {0xff00ffff, "Magenta"},
+    {0x00ffffff, "Cyan"},
+    {0xffffffff, "White"},
+    {0xff0000ff, "Transparent"}
```
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:537]: yes, this one is not required. fixed and removed

File: kml/serdes_gpx.cpp [hunk 24]
```diff
@@ -483,6 +495,63 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
+         << NumToHex(static_cast<uint8_t>((rgba >> 16) & 0xFF))
+         << NumToHex(static_cast<uint8_t>((rgba >> 8) & 0xFF));
+}
+
+std::tuple<uint8_t, uint8_t, uint8_t> ExtractRGB(uint32_t color)
+{
+  return {(color >> 24) & 0xFF, (color >> 16) & 0xFF, (color >> 8) & 0xFF};
+}
+
+uint32_t ColorDistance(uint32_t color1, uint32_t color2)
```
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:511]: Got it, in this case I think the more important is to have 
`std::tuple<int, int, int> ExtractRGB(uint32_t color)` return tuple of ints because we subtract outputs of this function?  Result of color distance is always a positive value, so it should be safe to store and compare it as uint32_t? But I agree, better to avoid unsigned when we can.

File: kml/serdes_gpx.cpp [hunk 25]
```diff
@@ -483,6 +495,63 @@ void SaveColorToRGB(Writer & writer, uint32_t rgba)
...
 
+void SaveColorToARGB(Writer & writer, uint32_t rgba)
+{
+  writer << NumToHex(static_cast<uint8_t>(rgba & 0xFF))
+         << NumToHex(static_cast<uint8_t>(rgba >> 24 & 0xFF))
+         << NumToHex(static_cast<uint8_t>((rgba >> 16) & 0xFF))
+         << NumToHex(static_cast<uint8_t>((rgba >> 8) & 0xFF));
+}
+
+std::tuple<uint8_t, uint8_t, uint8_t> ExtractRGB(uint32_t color)
```
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:506]: Updated to signed

File: kml/serdes_gpx.cpp (hunk 24 above)
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:511]: We don't substract result of ColorDistance, but just compare it and it is always some posistive value, so should work with uint32_t also? But I agree that better to avoid unsigned when we can.

**Comment by cyber-toad** [comment]
```
    Event if drape doesn't draw such colors as transparent now, maybe we can support it later.
    If the track/gpx/kml already has some transparency defined, would it be better to store it for the future and not lose on import/export?
```
transparency is not always parsed as a part of color (http://www.topografix.com/gpx/gpx_style/0/2/#type_opacityType), so these formats need to be supported in parser and writer. but maybe we can cover some cases here.

File: kml/serdes_gpx.cpp (hunk 15 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:520]: image

Here is a clion warning for return for the version of code that you suggest here: https://github.com/organicmaps/organicmaps/pull/10089#discussion_r1921647356
But godbolt doesn't warn about it: https://godbolt.org/z/ah5q9e339

Comment (biodranik) [reply kml/serdes_gpx.cpp:520]: Looks like clang-tidy (or whatever tool is used by clion) doesn't detect that constexpr kRGBAToGarmin is also a static variable in this case. You may try to add `static` there explicitly. Btw, it generates a bit smaller code for x86 gcc.

File: kml/serdes_gpx.cpp [hunk 26]
```diff
@@ -131,12 +134,21 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
-  auto const colorBytes = FromHex(value);
+  if (colorStr.empty())
+  {
+    LOG(LWARNING, ("Invalid color value", colorStr));
+    return;
+  }
+  if (colorStr.front() == '#')
+    colorStr.remove_prefix(1);
+  if (colorStr.size() == 8)
+    colorStr = colorStr.substr(2, colorStr.size() - 1);
```
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:147]: yes, I made a mistake thinking that parameters are [from, to], so the code is wrong but worked due to termination symbol. I replaced it with remove_prefix

File: kml/serdes_gpx.cpp (hunk 15 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:520]: I tried to replace with `auto static constexpr kRGBAToGarmin` and warning is the same. based on this hhttps://youtrack.jetbrains.com/issues?q=%20%22the%20address%20of%20the%20local%20variable%20may%20escape%20the%20function%22%20 analysis is done by clion itself and they are fixing it from time to time. So if you don't see issues with it we can try to run test suite and see how it goes.

Comment (biodranik) [reply kml/serdes_gpx.cpp]: The code should work, but it is always better to write unit tests and run them on ci with different compilers.

File: kml/serdes_gpx.cpp [hunk 27]
```diff
@@ -131,12 +134,21 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
   return m_tags[m_tags.size() - n - 1];
 }
 
-void GpxParser::ParseColor(std::string const & value)
+void GpxParser::ParseColor(std::string_view colorStr)
```
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/serdes_gpx.cpp]: I changed it and added tests. But I can't test all cases because there is an assert in impl::HexDigitToRaw that terminates execution for tests data like #MMMMMM that has valid length but wrong content. In this case should I disable assertions for these tests somehow? What is the prefered way to do it - I googled #define NDEBUG but looks like OM uses some custom assertions in assert.hpp.

**Comment by cyber-toad** [comment]
> If the track/gpx/kml already has some transparency defined, would it be better to store it for the future and not lose on import/export?

Added store of opacity if it is encoded as a part of color

File: kml/serdes_gpx.cpp (hunk 15 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp]: Done

File: kml/serdes_gpx.cpp [hunk 28]
```diff
@@ -131,42 +134,44 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
+  case 4: return kml::ToRGBA(colorBytes[1], colorBytes[2], colorBytes[3], colorBytes[0]);
+  default:
+    LOG(LWARNING, ("Invalid color value", colorStr));
+    return {};
   }
+}
+
+void GpxParser::ParseColor(std::string_view colorStr)
+{
+  if (const auto parsed = ParseColorFromHexString(colorStr); parsed.has_value())
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:164]: nit: (less letters usually means a bit more readable code)
```suggestion
  if (const auto parsed = ParseColorFromHexString(colorStr); parsed)
```

File: kml/serdes_gpx.cpp [hunk 29]
```diff
@@ -131,42 +134,44 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
+    m_color = parsed.value();
+}
+
+// https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx/. Supported colors: #AARRGGBB/#RRGGBB/AARRGGBB/RRGGBB
+void GpxParser::ParseOsmandColor(std::string const & value)
+{
+  std::optional<uint32_t> parsed = ParseColorFromHexString(value);
+  if (!parsed.has_value())
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:172]: nit:
```suggestion
  auto const color = ParseColorFromHexString(value);
  if (!color)
```

Should a warning be printed if color fails to parse?

File: kml/serdes_gpx.cpp [hunk 30]
```diff
@@ -131,42 +134,44 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
+    return;
+  uint32_t color = parsed.value();
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:174]:
```suggestion
```

File: kml/serdes_gpx.cpp [hunk 31]
```diff
@@ -131,42 +134,44 @@ std::string const & GpxParser::GetTagFromEnd(size_t n) const
...
   if (m_tags.size() > 2 && GetTagFromEnd(2) == gpx::kGpx)
   {
     m_globalColor = color;
```
Comment (biodranik) [inline kml/serdes_gpx.cpp:177]:
```suggestion
    m_globalColor = *color;
```

And the same below.

File: kml/serdes_gpx.cpp (hunk 19 above)
Comment (biodranik) [reply kml/serdes_gpx.cpp:504]: Right!

**Review by biodranik — APPROVED** [review]
Thanks! LGTM with a few nits.

> transparency is not always parsed as a part of color (http://www.topografix.com/gpx/gpx_style/0/2/#type_opacityType), so these formats need to be supported in parser and writer. but maybe we can cover some cases here.

How is this style spec related to the main gpx spec? I didn't find any reference to styles from gpx 1.1.

> RE: MapGarminColor in unit tests

There are several options for how to do that with their pros and cons. The simplest one is to move the function outside of the anonymous namespace (leave it in kml::gpx), and not make it static in the cpp file. Then you can reference it in another cpp by either including a header where it is declared, or (simpler) declaring it right before using it in the cpp unit test file:
```c++
namespace kml::gpx
{
std::string_view MapGarminColor(uint32_t rgba);
}  // namespace kml::gpx 
```

A perfect approach would use a test-only time define (e.g. derived from cmake's BUILD_TESTING), and use anonymous namespace (or `static` keyword) if production binary (or dynamic library in case of Android) is built, and expose the function if libraries are built for unit tests.

File: kml/kml_tests/gpx_tests.cpp [hunk 32]
```diff
@@ -340,9 +366,25 @@ d5
...
 {
-  kml::FileData dataFromFile = loadGpxFromFile("test_data/gpx/opentracks_color.gpx");
+  kml::FileData dataFromFile = LoadGpxFromFile("test_data/gpx/opentracks_color.gpx");
   uint32_t const expected = 0xC0C0C0FF;
   TEST_EQUAL(expected, dataFromFile.m_tracksData[0].m_layers[0].m_color.m_rgba, ());
 }
 
+UNIT_TEST(ParseFromString)
+{
+  // string hex sequence #AARRGGBB, uint32 sequence RGBA
```
[the remark this answers is not in the document]
Comment (cyber-toad) [reply kml/kml_tests/gpx_tests.cpp:376]: Fixed

File: kml/serdes_gpx.cpp (hunk 28 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:164]: Fixed

File: kml/serdes_gpx.cpp (hunk 29 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:172]: There is some logging in GpxParser::ParseColorFromHexString for unexpected values, do you want to add some more logging?

File: kml/serdes_gpx.cpp (hunk 31 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:177]: Fixed

File: kml/serdes_gpx.cpp (hunk 30 above)
Comment (cyber-toad) [reply kml/serdes_gpx.cpp:174]: Fixed

**Comment by cyber-toad** [comment]
> How is this style spec related to the main gpx spec? I didn't find any reference to styles from gpx 1.1.

Yes, I mean that there are different ways how different applications exports opacity. For this ticket I added a case when it is a part of the color, but there are some schemas when it is stored separately.

**Comment by cyber-toad** [comment]
> There are several options for how to do that with their pros and cons. The simplest one is to move the function outside of the anonymous namespace (leave it in kml::gpx), and not make it static in the cpp file.

Thanks, I moved function and added a test for it, please have a look.

**Review by biodranik — APPROVED** [review]
