### PR TITLE
[ios] Fix HTML rendering for bookmarks

### LINKED ISSUE #8768: [ios] The tables aren't rendered correctly in the place page's description HTML
| Android | iOS |
|----------|----------|
| image | image |

The html table reference:
```html
<img src='https://i.imgur.com/NYZzZnR.jpg' width='500' style='margin: auto'/><br><br>
<table border="3" cellpadding="1" cellspacing="1" style="width:320px">
<tbody>
<tr>
<td colspan="2" style="text-align:center; width:310px"><span style="color:#2c3e50"><span style="font-size:14px"><big><strong>Микуцкого 3</strong></big></span></span></td>
</tr>
<tr>
<td style="text-align:center; width:127px"><span style="color:#000000"><strong>Состояние</strong></span></td>
<td style="text-align:center; width:177px"><span style="color:#000000"><strong>Дата проверки</strong></span></td>
</tr>
<tr>
<td style="text-align:center; width:127px"><strong><span style="color:#27ae60">Исправен</span></strong></td>
<td style="text-align:center; width:177px"><span style="color:#c0392b"><strong>14.06.24</strong></span></td>
</tr>
<tr>
<td colspan="2"
style="width:310px"><span style="color:#c0392b"><strong>Причина неисправности: </strong></span><span style="color:#2980b9"><strong></strong></span></td>
</tr>
<tr>
<td colspan="2"
style="width:310px"><span style="color:#000000"><strong>Расположение ПГ: </strong></span><span style="color:#2980b9"><strong>Между 1 и 2 подъездом. На дороге.</strong></span></td>
</tr>
<tr>
<td colspan="2" style="width:310px"><span style="color:#000000"><strong>Дополнительно: </strong></span><span style="color:#2980b9"><strong>Указатель есть.</strong></span></td>
</tr>
</tbody>
</table>
```

### PR DESCRIPTION
**Pull request by biodranik**
Fixes #8768

Needs testing.

### CODE REVIEW

**Comment by kirylkaveryn** [comment]
Thanks! But this implementation raises a recursion that locks the app when I add an html description with table. Somewhere inside the system code after the call of:
```
  func setExpanded(_ expanded: Bool) {
    guard expandLabel.isHidden != expanded else { return }
    UIView.animate(withDuration: kFastAnimationDuration) {
      self.containerMaximumNumberOfLines = expanded ? 0 : (self.numberOfLines > 0 ? self.numberOfLines + 1 : 0)
      self.expandLabel.isHidden = expanded ? true : false
      self.stackView.layoutIfNeeded() // <- on this line
    }
  }
```
image

**Comment by kirylkaveryn** [comment]
I have made an update to PR: 
- For HTML: limit the expandable section to a static value of 70 pt. It allows collapsing HTML that contains images and tables because the previous solution, which calculates the collapsed height based on the `number of lines`, may be incorrect for complex HTML.
- For plain text: the old 3-line limitation is preserved.
- Small gradient under the `more` button
- Animation wasnt changed.

Here is how it looks:
image image
image  image
image

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 1]
```diff
@@ -154,42 +175,94 @@ final class ExpandableLabel: UIView {
...
 
   override func layoutSubviews() {
     super.layoutSubviews()
+    guard !isMeasuring else { return }
 
-    if oldWidth != bounds.width, let attributedText = attributedText?.mutableCopy() as? NSMutableAttributedString {
-      attributedText.enumerateAttachments(estimatedWidth: bounds.width)
-      self.attributedText = attributedText
+    if oldWidth != bounds.width {
       oldWidth = bounds.width
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:210]: `buildAttributedString` fills `sourceAttributedText` asynchronously, so this width-change branch can run before the HTML attributed text exists. Updating `oldWidth` even when `sourceAttributedText` is still `nil` consumes the initial width, and when the attributed text arrives later we skip `enumerateAttachments(estimatedWidth:)`. That leaves wide HTML `` attachments unscaled until some later width change, such as rotation.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 2]
```diff
@@ -154,42 +175,94 @@ final class ExpandableLabel: UIView {
...
+
+  override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
+    super.traitCollectionDidChange(previousTraitCollection)
+    updateAppearance()
+  }
+
+  func updateAppearance() {
+    gradientLayer.startPoint = CGPoint(x: 0.5, y: 0)
+    gradientLayer.endPoint = CGPoint(x: 0.5, y: 1)
+    let color = UIColor.white()
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:257]: This fade should use the themed place-page background instead of `UIColor.white()`. In night mode `GlobalStyleSheet.background` resolves to a dark gray, so the hardcoded white gradient shows up as a bright strip over collapsed descriptions.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 3]
```diff
@@ -3,32 +3,29 @@ final class ExpandableLabel: UIView {
...
-  private var containerText: String?
-  private var containerMaximumNumberOfLines = 2 {
-    didSet {
-      textView.textContainer.maximumNumberOfLines = containerMaximumNumberOfLines
-      textView.invalidateIntrinsicContentSize()
-    }
-  }
-
+  private var textHeightConstraint: NSLayoutConstraint!
+  private var expandControlHeightConstraint: NSLayoutConstraint!
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift]: **Bug: unused property (dead code)**

`expandControlHeightConstraint` is declared but never assigned or referenced anywhere in this file. Looks like a leftover from development.

**Fix:** remove this line.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 4]
```diff
@@ -107,16 +103,17 @@ final class ExpandableLabel: UIView {
   // MARK: - Private methods
 
   private func setupView() {
+    stackView.distribution = .fillProportionally
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:80]: **Suggestion: use `.fill` instead of `.fillProportionally`**

`.fillProportionally` distributes available space proportionally based on the arranged subviews' intrinsic content sizes. Since `textView` has an explicit height constraint (overriding its intrinsic size), and `expandView` only has its label's intrinsic height, `.fillProportionally` may produce unpredictable sizing — especially when the expand view is toggled between hidden/visible.

`.fill` would be simpler and more correct here: it respects the explicit height constraint on the text view and gives the expand view exactly its intrinsic size.

```swift
stackView.distribution = .fill
```

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 5]
```diff
@@ -139,8 +139,29 @@ final class ExpandableLabel: UIView {
...
-    stackView.addArrangedSubview(expandLabel)
+    stackView.addArrangedSubview(expandView)
     stackView.alignToSuperview(contentInsets)
+
+    textHeightConstraint = textView.heightAnchor.constraint(equalToConstant: compactHeight)
+    textHeightConstraint.isActive = true
+  }
+
+  private func updateCollapsedState() {
+    let measuringWidth = bounds.width - contentInsets.left + contentInsets.right
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:122]: **Nit: confusing arithmetic due to sign convention**

This is correct given the convention that `contentInsets.right` is `-16` (negative). But it reads as "width minus left *plus* right", which is misleading since the addition actually subtracts.

A brief comment would help future readers:
```swift
// contentInsets uses negative right/bottom values (Auto Layout constant convention)
let measuringWidth = bounds.width - contentInsets.left + contentInsets.right
```

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 6]
```diff
@@ -154,42 +175,94 @@ final class ExpandableLabel: UIView {
...
+    }
+
+    isExpanded = expanded
     UIView.animate(withDuration: kFastAnimationDuration) {
-      self.containerMaximumNumberOfLines = expanded ? 0 : (self.numberOfLines > 0 ? self.numberOfLines + 1 : 0)
-      self.expandLabel.isHidden = expanded ? true : false
-      self.stackView.layoutIfNeeded()
+      self.updateCollapsedState()
+      self.superview?.layoutIfNeeded()
+      self.layoutIfNeeded()
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift]: **Suggestion: `self.layoutIfNeeded()` is redundant here**

`self.superview?.layoutIfNeeded()` on the line above already forces layout on the superview and all its descendants, including `self`. So `self.layoutIfNeeded()` is a no-op at this point and triggers a second `updateCollapsedState()` call inside `layoutSubviews()` (which includes a `sizeThatFits` measurement).

```swift
UIView.animate(withDuration: kFastAnimationDuration) {
  self.updateCollapsedState()
  self.superview?.layoutIfNeeded()
}
```

Note: if `superview` is `nil` the view isn't in the hierarchy and the animation wouldn't be visible anyway, so the nil-case is safe to ignore.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 7]
```diff
@@ -154,42 +175,94 @@ final class ExpandableLabel: UIView {
...
+
+  override func layoutSubviews() {
+    super.layoutSubviews()
+    gradientLayer.frame = CGRect(x: 0,
+                                 y: -Constants.gradientOverlapHeight,
+                                 width: bounds.width,
+                                 height: bounds.height + Constants.gradientOverlapHeight)
+  }
+
+  override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:249]: **Issue (non-blocking): `traitCollectionDidChange` is deprecated since iOS 17**

Apple recommends using `registerForTraitChanges(_:handler:)` (or the `UITraitChangeObservable` protocol) instead. Not a regression (the old code didn't have this view at all), but worth addressing if the project's minimum deployment target is iOS 17+.

```swift
// iOS 17+
registerForTraitChanges([UITraitUserInterfaceStyle.self]) { (self: Self, _) in
  self.updateAppearance()
}
```

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 2 above)
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:257]: **Issue: gradient assumes the background behind the label is always `UIColor.white()`**

`UIColor.white()` resolves to the theme-aware color (pure white in day mode, `rgb(60,64,68)` in night mode), which matches the place page background today. But if `ExpandableLabel` is ever placed on a surface with a different background, the gradient will produce a visible color mismatch.

Consider making the gradient color configurable (defaulting to `UIColor.white()`), or deriving it from the actual `backgroundColor` of the enclosing view, so the component is self-contained.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift [hunk 8]
```diff
@@ -154,42 +175,94 @@ final class ExpandableLabel: UIView {
...
+    clipsToBounds = false
+    layer.addSublayer(gradientLayer)
+    addSubview(label)
+
+    label.translatesAutoresizingMaskIntoConstraints = false
+
+    NSLayoutConstraint.activate([
+      label.leadingAnchor.constraint(equalTo: leadingAnchor),
+      label.bottomAnchor.constraint(equalTo: bottomAnchor),
+      label.topAnchor.constraint(greaterThanOrEqualTo: topAnchor),
```
Comment (biodranik) [inline iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:277]: **Issue: missing trailing constraint on label**

The label only has `leading`, `bottom`, and `top` constraints. Without a `trailing` constraint:
1. The label could extend beyond the bounds of `ExpandView` if the text is long.
2. RTL languages (Arabic, Hebrew) won't get proper alignment — the "More" button would stay pinned to the leading (right) edge without any trailing bound.

**Fix:** add a trailing constraint:
```swift
NSLayoutConstraint.activate([
  label.leadingAnchor.constraint(equalTo: leadingAnchor),
  label.trailingAnchor.constraint(lessThanOrEqualTo: trailingAnchor),
  label.bottomAnchor.constraint(equalTo: bottomAnchor),
  label.topAnchor.constraint(greaterThanOrEqualTo: topAnchor),
])
```

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 5 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:122]: Such negative values are native for iOS because they are used by the autolayout since the beginning, so IMO such comments are redundant.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 4 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:80]: fill breaks the container height fo the `more` button. So it is better to use fillProportionally - it automatically collapses the view height to its size if there are no autolayout.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 6 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift]: Fixed!

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 2 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:257]: UIColor.white() here is the Organic Maps theme-aware color, so the “bright white strip in night mode” report is not valid in the current code
image

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 8 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:277]: Fixed! Thanks

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 7 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:249]: The minimum target is iOS 12 so there are no reason to use 2 approaches at the same time in 1 class.

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 3 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift]: Fixed!

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 2 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:257]: UIColor.white() here is the Organic Maps theme-aware color, so the “bright white strip in night mode” report is not valid in the current code

File: iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift (hunk 1 above)
Comment (kirylkaveryn) [reply iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift:210]: Fixed!  In the current implementation, ExpandableLabel.swift (line 55) resets oldWidth = 0 in expandableText.didSet, and the presenter sets .html(attributedString) only after the async HTML build finishes. That means when the attributed text arrives, the next layoutSubviews() sees oldWidth != bounds.width, runs enumerateAttachments(estimatedWidth:), and scales the attachments immediately.
