### PR TITLE
[android] Fix bottom sheet lifecycle issues

### LINKED ISSUE #3369: [android] Crash when you change screen orientation
- Open app
- Open menu burger
- Switch screen orientation
- App crashed
```
09-07 17:49:21.363  7047  7047 E AndroidRuntime: FATAL EXCEPTION: main
09-07 17:49:21.363  7047  7047 E AndroidRuntime: Process: app.organicmaps, PID: 7047
09-07 17:49:21.363  7047  7047 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.organicmaps/com.mapswithme.maps.MwmActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.mapswithme.util.bottomsheet.MenuBottomSheetFragment: could not find Fragment constructor
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5791)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5682)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-07 17:49:21.363  7047  7047 E AndroidRuntime: Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.mapswithme.util.bottomsheet.MenuBottomSheetFragment: could not find Fragment constructor
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.Fragment.instantiate(Unknown Source:94)09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentContainer.instantiate(Unknown Source:0)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$2.instantiate(Unknown Source:17)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentState.instantiate(Unknown Source:2)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.<init>(Unknown Source:13)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(Unknown Source:119)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.attachController(Unknown Source:140)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentController.attachHost(Unknown Source:4)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.lambda$init$1(Unknown Source:3)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.a(Unknown Source:0)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.b.onContextAvailable(Unknown Source:2)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(Unknown Source:20)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.activity.ComponentActivity.onCreate(Unknown Source:7)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onCreate(Unknown Source:0)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at com.mapswithme.maps.base.BaseMwmFragmentActivity.onCreate(Unknown Source:33)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8290)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8269)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        ... 15 more
09-07 17:49:21.363  7047  7047 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: com.mapswithme.util.bottomsheet.MenuBottomSheetFragment.<init> []
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at java.lang.Class.getConstructor0(Class.java:2363)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at java.lang.Class.getConstructor(Class.java:1759)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.Fragment.instantiate(Unknown Source:15)09-07 17:49:21.363  7047  7047 E AndroidRuntime:        ... 33 more
```
Pixel 6 - Android 13
version 2022.08.23-5-Google

Problem is fixed on [debug version](https://github.com/organicmaps/organicmaps/actions/runs/3008434506)

But in debug version menu burger is hide when you change screen orientation and you can't expand menu.

**Before (debug version)**

**After (debug version)**

cc @arnaudvergnet

### PR DESCRIPTION
**Pull request by arnaudvergnet**
Properly handles lifecycle for all bottom sheets. Last time I refactored them I messed this up to it would crash/loose its content when rotating the screen.

With this PR, the activity or fragment showing the bottom sheet must implement either `MenuBottomSheetInterface` or `MenuBottomSheetInterfaceWithHeader`.
- When implementing the first interface, you have to create a function which receives the bottom sheet id and returns a list of `MenuBottomSheetItem` to populate the sheet.
- When implementing the second interface, you have to create the same function as before and an other which also receives the bottom sheet id and returns a custom fragment to use as a header for the list of items.

In practice the `MenuBottomSheetInterfaceWithHeader` is only implemented by the main activity as we need to display the layers menu (uses the fragment) as well as the main menu and place page menu (uses the options list). When created, each `MenuBottomSheetFragment` will try to attach to their parent fragment, or if none is present the activity. If the attached fragment/activity implement one of the previous interfaces, their interface methods will be called to get the sheet's content.

To create a bottom sheet, we now have to call the static method `newInstance` of `MenuBottomSheetFragment`, passing it an id (to detect which sheet is shown when implementing the interfaces) and an optional title.

Please help me test and confirm there are no issues anymore. These are the bottom sheets I fixed (hope I did not miss one):

- Main menu on map
- Layers menu on map
- Place page more options
- Downloads item long click
- Bookmarks categories options
- Bookmarks list item options
- Bookmarks list sort menu
- Bookmarks list track options

The only notable UI//UX change is that the downloads item long click bottom sheet now shows the name of the selected map:

Screenshot_1662710287

Closes #3369

### CODE REVIEW

File: android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java [hunk 1]
```diff
@@ -152,23 +154,35 @@ public void onDestroyView()
   protected final void showBottomMenu(@NonNull BookmarkCategory item)
   {
     mSelectedCategory = item;
-    new MenuBottomSheetFragment(item.getName(), getMenuItems(item))
-            .show(getParentFragmentManager(), "bookmarkCategoriesBottomSheet");
+    MenuBottomSheetFragment.newInstance("bookmarkCategoriesBottomSheet", item.getName())
+            .show(getChildFragmentManager(), "bookmarkCategoriesBottomSheet");
```
Comment (vng) [inline android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java:158]: Is it reasonable to keep common style and add BOOKMARK_CATEGORIES_BOTTOM_SHEET?

File: android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java [hunk 2]
```diff
@@ -260,6 +261,94 @@ void rebind()
     }
   }
 
+  private void showBottomSheet(CountryItem selectedItem)
+  {
+    mSelectedItem = selectedItem;
+    MenuBottomSheetFragment.newInstance("downloaderBottomSheet", mSelectedItem.name)
+                           .show(mFragment.getChildFragmentManager(), "downloaderBottomSheet");
```
Comment (vng) [inline android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java:268]: Is it reasonable to keep common style and add DOWNLOADER_BOTTOM_SHEET?

File: android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java [hunk 3]
```diff
@@ -11,64 +12,42 @@
...
-    this.menuBottomSheetItems = menuBottomSheetItems;
-  }
-
-  public MenuBottomSheetFragment(@NonNull String title, ArrayList<MenuBottomSheetItem> menuBottomSheetItems)
-  {
-    this.title = title;
-    this.headerFragment = null;
-    this.menuBottomSheetItems = menuBottomSheetItems;
-  }
+  private Fragment headerFragment;
```
Comment (vng) [inline android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java:28]: mHeaderFragment

File: android/src/com/mapswithme/maps/MwmActivity.java [hunk 4]
```diff
@@ -1970,9 +1933,44 @@ public void onShareLocationOptionSelected()
     shareMyLocation();
   }
 
-  public void onLayerItemClicked(@NonNull Mode mode)
+  @Override
+  public void onLayerItemClick(@NonNull Mode mode)
   {
     closeFloatingPanels();
-    mMapButtonsController.toggleMapLayer(mode);
+    if (mMapButtonsController != null)
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/MwmActivity.java:1940]: What is the situation when this variable is null?

File: android/src/com/mapswithme/maps/MwmActivity.java [hunk 5]
```diff
@@ -1970,9 +1933,44 @@ public void onShareLocationOptionSelected()
...
+      return mPlacePageController.getMenuBottomSheetItems();
+    return null;
+  }
+
+  @Override
+  public Fragment getMenuBottomSheetFragment(String id)
+  {
+    if (id.equals(LAYERS_MENU_ID))
+      return new ToggleMapLayerFragment();
+    return null;
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/MwmActivity.java:1974]: Is it normal expected behavior to return null? It would make sense to document it with a signature.

File: android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java [hunk 6]
```diff
@@ -812,4 +816,19 @@ private void updateLoadingPlaceholder(@NonNull View root, boolean isShowLoadingP
     UiUtils.showIf(!isShowLoadingPlaceholder, root, R.id.show_on_map_fab);
     UiUtils.showIf(isShowLoadingPlaceholder, loadingPlaceholder);
   }
+
+  @Override
+  public ArrayList<MenuBottomSheetItem> getMenuBottomSheetItems(String id)
+  {
+    if (id.equals(BOOKMARKS_MENU_ID))
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java:823]: Wouldn't it be better/safer (null?) to use a switch + enum?

File: android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java [hunk 7]
```diff
@@ -257,7 +258,96 @@ void bind(T item)
...
     {
       bind(mItem);
+      bind(mItem);
+    }
+  }
+
+  private void showBottomSheet(CountryItem selectedItem)
+  {
+    mSelectedItem = selectedItem;
+    MenuBottomSheetFragment.newInstance("DOWNLOADER_BOTTOM_SHEET", mSelectedItem.name)
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java:268]: It's better to make a constant instead of a copypaste.

File: android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java [hunk 8]
```diff
@@ -257,7 +258,96 @@ void bind(T item)
...
+  private MenuBottomSheetItem getExploreMenuItem()
+  {
+    return new MenuBottomSheetItem(R.string.zoom_to_country, R.drawable.ic_explore,
+                                   () -> onExploreActionSelected(mSelectedItem, DownloaderAdapter.this));
+  }
+
+  private void appendDeleteMenuItem(ArrayList<MenuBottomSheetItem> items)
+  {
+    // Do not show "Delete" option for World files.
+    // Checking name is not beautiful, but the simplest way for now ..
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java:340]:
```suggestion
    // Checking the name is not beautiful, but the simplest way for now...
```

File: android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java [hunk 9]
```diff
@@ -308,22 +310,24 @@ private void preserveRoutingButtons(@NonNull List<PlacePageButton> items, @NonNu
...
+  public ArrayList<MenuBottomSheetItem> getMenuBottomSheetItems()
   {
+    if (mMoreItems == null)
+      return null;
     ArrayList<MenuBottomSheetItem> items = new ArrayList<>();
-    for (int i = mMaxButtons; i < buttons.size(); i++)
+    for (int i = mMaxButtons; i < mMoreItems.size(); i++)
     {
-      PlacePageButton bsItem = buttons.get(i);
+      PlacePageButton bsItem = mMoreItems.get(i);
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java:320]: Please try to use the `final` keyword everywhere if the variable is not modified. It helps to read the code and understand if the variable is "const".

File: android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java [hunk 10]
```diff
@@ -308,22 +310,24 @@ private void preserveRoutingButtons(@NonNull List<PlacePageButton> items, @NonNu
...
   }
 
-  private ArrayList<MenuBottomSheetItem> getMenuItems(final List<PlacePageButton> buttons)
+  public ArrayList<MenuBottomSheetItem> getMenuBottomSheetItems()
   {
+    if (mMoreItems == null)
+      return null;
     ArrayList<MenuBottomSheetItem> items = new ArrayList<>();
-    for (int i = mMaxButtons; i < buttons.size(); i++)
+    for (int i = mMaxButtons; i < mMoreItems.size(); i++)
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java:318]: Passing buttons as an argument had a more local scope and fewer potential side effects.

File: android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java [hunk 11]
```diff
@@ -11,64 +12,42 @@
...
-
-  public MenuBottomSheetFragment(@NonNull Fragment headerFragment)
+  public MenuBottomSheetFragment()
   {
-    this.title = null;
-    this.headerFragment = headerFragment;
-    this.menuBottomSheetItems = new ArrayList<>();
   }
 
-  // https://stackoverflow.com/questions/51831053/could-not-find-fragment-constructor
```
Comment (biodranik) [inline android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java:58]: Why did you remove the comment?

**Review by biodranik — COMMENTED** [review]
Thanks! Honestly, the proposed refactoring looks a bit complicated. Is it the simplest possible implementation? Are there any ideas on how to make it even simpler (maybe not now, but later)? Or change/improve the UI/UX and make the architecture/approach simpler?

**Comment by arnaudvergnet** [comment]
> Thanks! Honestly, the proposed refactoring looks a bit complicated. Is it the simplest possible implementation? Are there any ideas on how to make it even simpler (maybe not now, but later)? Or change/improve the UI/UX and make the architecture/approach simpler?

I agree with you that is looks complicated and I hope someone can correct me and find a better way to handle this. I am no expert with Android's lifecycle and fragments, but this was the only way I found to make the bottom sheet remember their state on configuration change.

File: android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java [hunk 12]
```diff
@@ -257,7 +258,96 @@ void bind(T item)
     void rebind()
     {
       bind(mItem);
+      bind(mItem);
```
Comment (vng) [inline android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java:261]: 2 bind calls?

File: android/src/com/mapswithme/maps/MwmActivity.java (hunk 4 above)
Comment (arnaudvergnet) [reply android/src/com/mapswithme/maps/MwmActivity.java:1940]: This variable is annotated with `@Nullable` so I am doing this check to remove the warning

File: android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java (hunk 6 above)
Comment (arnaudvergnet) [reply android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java:823]: Handling string enums in Java is not the easiest and creates a lot of boiler plate code. I felt used constants was better for those 2 simple cases.

File: android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java (hunk 10 above)
Comment (arnaudvergnet) [reply android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java:318]: Yes but passing the buttons as argument means losing the state on config change.

The bottom sheet fragment will be recreated without the host activity calling the `show` method, thus the activity will not be able to pass the buttons.

The way it is now implemented, the bottom sheet fragment will be the one calling this function using the activity context. I don't really like this approach but I could not find  cleaner way to do this.

I could make the host activity/fragment retrieve a reference to the bottom sheet using its tag, but I don't know if it will be cleaner when there are multiple bottom sheets in one activity/fragment.

File: android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java (hunk 11 above)
Comment (arnaudvergnet) [reply android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java:58]: It is not relevant as the fragment has no constructor anymore.

**Review by vng — APPROVED** [review]

**Review by rtsisyk — APPROVED** [review]

**Comment by Jean-BaptisteC** [comment]
Pixel 6 - Android 13✅

**Comment by biodranik** [comment]
@arnaudvergnet great that you also see it imperfect. Usually, we refactor only if there are fewer lines of code after the refactoring, not more lines of code.
Handling orientation changes is tricky on Android, there are several different approaches to the problem, outlined here: https://medium.com/hootsuite-engineering/handling-orientation-changes-on-android-41a6b62cb43f

So far we can merge it because we have no other choice: there are some crashes/issues on the master branch that block the release. We of course have new risks of some new problems caused by these changes.
But it would be great to carefully test/improve the code without breaking the master in the future.

**Comment by arnaudvergnet** [comment]
Refactoring to get fewer lines of code was what I wanted to do when I introduced the bug, sorry about that. I was used to other mobile framework which did not need to handle orientation change as native Android does.

IMO the change is tricky mainly for the "more" placepage button. It would have been easier if the place page itself was a fragment, but as it is not the callbacks need to go all the way back to the main activity. For the other cases the change does not make the code much harder to understand (implementing an interface instead of manually setting the callback).

Ideally the UI should be split into several independent fragments as much as possible, this would make the code way easier to understand.

**Comment by biodranik** [comment]
> IMO the change is tricky mainly for the "more" placepage button. It would have been easier if the place page itself was a fragment, but as it is not the callbacks need to go all the way back to the main activity. For the other cases the change does not make the code much harder to understand (implementing an interface instead of manually setting the callback).

> Ideally the UI should be split into several independent fragments as much as possible, this would make the code way easier to understand.

@arnaudvergnet These are all right and valid points. I can suggest you the direction we were planning to go:
1. Try to avoid/remove "More" button by using (maybe) 5 buttons instead of 4, or removing unnecessary (call), or moving it lower to the Place Page. And of course to make the order of remaining buttons stable. That is very important for building routes with stops.
2. Refactor Place Page with several goals in mind:
    - Simplify the code, so it would be easy to add _any_ new info from OSM.
    - Avoid its initialization on the app startup (it slows down the app startup, and leads to crashes on devices without Chrome Web View which is used to render bookmarks descriptions and Wikipedia) and init it only when necessary (on user click).
    - Make its initialization faster (to save battery and time on slower devices)
    - Probably improve/refactor the UI/UX (how it looks like, how it appears).

Any feedback and ideas are welcome! We can start another issue for that (if we don't have it already).

**Comment by arnaudvergnet** [comment]
I had the same direction in mind perfect!

I created an issue for this: https://github.com/organicmaps/organicmaps/issues/3400

**Comment by biodranik** [comment]
@arnaudvergnet on Android 11 emulator I see in the log:
`10-08 21:57:53.824  3136  3136 W BottomSheetBehavior: Cannot set state: 5`

What is it about?
