### PR TITLE
[android] Fix search floating toolbar focus on Android 8 and lower

### LINKED ISSUE #2347: Changing to map search not possible
It's not possible to switch to map mode in search. For example, I search for "Tailor" and want to see the locations. If I press the little map button in the lower right, it just restarts search and shows the list of tailors again.

Version: 2022.03.23-4-F-Droid
Android Version 8.0.0
Huawei P8 lite 2017

### PR DESCRIPTION
**Pull request by arnaudvergnet**
Do not rely on the focus event to detect a tap on the search query when looking at results on the map. Instead this PR makes use of the onClick event as before patch #2081 but also disables focusing and long pressing the input.

Compared to the previous implementation of onClick event handling, only a single click is needed to detect a tap. Compared to the current implementation using onFocus event (introduced with #2081), it works the same across Android versions.

Tested on physical device with Android 7 and an Android 11 emulator.

I do not have the internet bandwidth or the disk space to test on all Android versions. So please test this on your device to make sure it correctly fixes the issue and does not introduce any new.

Fixes #2347

### CODE REVIEW

File: android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java [hunk 1]
```diff
@@ -27,6 +27,8 @@ public FloatingSearchToolbarController(@NonNull Activity activity,
   {
     super(activity.getWindow().getDecorView(), activity);
     mListener = listener;
+    // we only want to detect a click on the input and not allow editing
```
Comment (biodranik) [inline android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java:30]:
```suggestion
    // We only want to detect a click on the input and not allow editing.
```

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
Thank you very much for the fix! So the focus thing is tricky, right?

**Comment by arnaudvergnet** [comment]
Yes I was not able to understand why the behavior changed between Android versions so I felt using another method would be the safest option.

**Review by vng — APPROVED** [review]
