### PR TITLE
Fix race condition in SplashActivity

### LINKED ISSUE #11938: Exception java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item
Only Android 12 is affected: https://play.google.com/console/u/0/developers/8084273541548442467/app/4972992444534608608/vitals/crashes/79af68f5448b99234a14bc1274609ea0/details?days=60&versionCode=25121616
```
Exception java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item
  at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord (ActivityTransactionItem.java:85)
  at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord (ActivityTransactionItem.java:58)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:43)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2337)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:241)
  at android.os.Looper.loop (Looper.java:342)
  at android.app.ActivityThread.main (ActivityThread.java:8123)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:583)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)
```

Gemini summary:

This crash, an IllegalArgumentException with the message "Activity client record must not be null to execute transaction item," indicates that the Android system was attempting to perform a lifecycle operation on an Activity (such as creating, resuming, or destroying it), but it encountered an invalid or missing internal record for that Activity. The error specifically means that the system could not find the necessary internal data structure (ActivityClientRecord) associated with an Activity to complete a scheduled transaction (a lifecycle event). This typically happens when an application tries to interact with an Activity that is no longer valid or has been destroyed unexpectedly from the system's perspective, often due to an asynchronous operation completing after the Activity has already been disposed of.
Potential Solutions

Here are a few potential solutions that can be implemented in the application code to address this type of crash:

    Validate Activity state before UI operations: It is observed that asynchronous operations, such as network requests or background tasks, may attempt to update the UI or interact with an Activity after it has already been destroyed. This can occur, for instance, due to a configuration change (like screen rotation) or when the user navigates away from the Activity. The system then attempts to process a transaction for a non-existent ActivityClientRecord, leading to the crash. Before performing any UI-related operations or accessing an Activity's context from an asynchronous callback, the Activity's state should be explicitly checked. Methods like isFinishing() or isDestroyed() can be utilized to ensure the Activity is still valid and active.

    // Inside an AsyncTask's onPostExecute, a Handler's post, or a network callback:
    MyActivity activity = activityReference.get(); // Assuming a WeakReference is used
    if (activity != null && !activity.isFinishing() && !activity.isDestroyed()) {
        // Safely perform UI updates or interact with the Activity here.
        activity.updateMyUI();
    }

    Ensure correct Fragment transaction handling: Incorrect handling of Fragment transactions, particularly during their commitment, is a known cause that can lead to an inconsistent state. Committing a FragmentTransaction after Activity.onSaveInstanceState() has been called can result in an IllegalStateException or, in some cases, this IllegalArgumentException as the system expects a valid Activity state. Fragment transactions should ideally be committed before the onSaveInstanceState() lifecycle method is invoked. If transactions must be committed after this point, commitAllowingStateLoss() can be used, but its implications (potential loss of user interface state) should be fully understood and accepted.

    // This should ideally be called before onSaveInstanceState()
    // For example, within onCreate(), onStart(), or in response to a user action.
    getSupportFragmentManager().beginTransaction()
        .replace(R.id.fragment_container, new MyFragment())
        .commit(); // Use commit() for most cases

    Avoid strong references to Activity contexts in long-running tasks: The presence of long-running background operations or static fields holding a strong reference to an Activity context can prevent the Activity from being garbage collected even after it has been destroyed by the system. If this stale reference is later used to interact with the system's ActivityThread, it could refer to a null or invalid ActivityClientRecord, thereby causing a crash. When an Activity context is needed in an asynchronous task or a component that might outlive the Activity, a WeakReference should be used. This allows the Activity to be garbage collected when it is no longer needed, preventing memory leaks and ensuring that attempts to access a destroyed Activity are safely handled.

    // Inside a class that might outlive the Activity (e.g., an AsyncTask, a singleton):
    private final WeakReference<Context> activityContextRef;

    public MyLongRunningTask(Context context) {
        this.activityContextRef = new WeakReference<>(context);
    }

    public void performOperation() {
        Context context = activityContextRef.get();
        if (context != null) {
            // Use the context safely.
            // Further check if it's an Activity context and if it's still valid if UI ops are involved.
        }
    }

### PR DESCRIPTION
**Pull request by Roniscend**
This pull request resolves a race condition in SplashActivity that triggers a java.lang.IllegalArgumentException: Activity client record must not be null crash when processNavigation() is invoked on a destroyed activity. By implementing a guard clause that checks isFinishing() or isDestroyed() before executing navigation transactions, the application now safely aborts the initialization process if the activity context is no longer valid.
Fixes #11938

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Thanks! 
1. Can you please remove unnecessary changes to have only what is needed for the fix? Please use clang-format https://github.com/organicmaps/organicmaps/blob/master/docs/CODE_STYLE_GUIDE.md
2. Were you able to reproduce the crash?

File: android/app/src/main/java/app/organicmaps/SplashActivity.java [hunk 1]
```diff
@@ -154,41 +154,38 @@ private void init()
...
-    {
-      // Wait for the result from MwmActivity for API callers.
-      mApiRequest.launch(intent);
-      return;
-    }
-
-    Config.setFirstStartDialogSeen(this);
-    startActivity(intent);
-    finish();
+      if (isFinishing() || isDestroyed())
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/SplashActivity.java]: How can it be explained, that processNavigation is called when isFinishing() or isDestroyed() may return true?

**Comment by Roniscend** [comment]
> 1. Can you please remove unnecessary changes to have only what is needed for the fix? Please use clang-format https://github.com/organicmaps/organicmaps/blob/master/docs/CODE_STYLE_GUIDE.md

I have implemented that

**Comment by Roniscend** [comment]
> 2\. Were you able to reproduce the crash?

I am currently testing this in Android 12 (API 31) emulator , I was not able to consistently reproduce the crash locally because of the exact timing required for the race condition, The logic here is a preventive logic it basically handles the edge case where low memory or action destroys the activity before the asynchronous callback

File: android/app/src/main/java/app/organicmaps/SplashActivity.java (hunk 1 above)
Comment (Roniscend) [reply android/app/src/main/java/app/organicmaps/SplashActivity.java]: processNavigation is invoked as a callback from an asynchronous task, lets suppose user closes the app or system destroys the activity before that task is completed the callback still executes creating a race condition

File: android/app/src/main/java/app/organicmaps/SplashActivity.java [hunk 2]
```diff
@@ -154,13 +154,11 @@ private void init()
...
   {
-    if (isDestroyed())
+    if (isFinishing() || isDestroyed())
     {
-      Logger.w(TAG, "Ignore late callback from core because activity is already destroyed");
+      Logger.w(TAG, "Ignore late callback from core because activity is already finishing or destroyed");
       return;
     }
-
-    // Re-use original intent with the known safe subset of flags to retain security permissions.
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/SplashActivity.java:163]: Why was the comment removed?

File: android/app/src/main/java/app/organicmaps/SplashActivity.java [hunk 3]
```diff
@@ -181,14 +179,13 @@ public void processNavigation()
 
     if (Factory.isStartedForApiResult(intent))
     {
-      // Wait for the result from MwmActivity for API callers.
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/SplashActivity.java:184]: Why was the comment removed?

File: android/app/src/main/java/app/organicmaps/SplashActivity.java (hunk 2 above)
Comment (Roniscend) [reply android/app/src/main/java/app/organicmaps/SplashActivity.java:163]: This is a mistake from my end I will fix this

File: android/app/src/main/java/app/organicmaps/SplashActivity.java (hunk 3 above)
Comment (Roniscend) [reply android/app/src/main/java/app/organicmaps/SplashActivity.java:184]: I'lll fix this

**Review by biodranik — APPROVED** [review]
Many thanks for your contribution! Let's check it now in beta and production, and see if it really fixes the crash.

Welcome to the club!
