### PR TITLE
[android] Fixed non-working download on Android 7 and below

### LINKED ISSUE #8737: OM fails downloading maps
Hello,

I'm leaving for a trip in a couple of days. For some reason, OM fails downloading the maps I need on an old phone I use as backup.

Any idea what I could try?

Thank you.

Android 7
OM 2024.07.08-3-Google
Huawei P9 Lite

image

### PR DESCRIPTION
**Pull request by biodranik**
Fixes #8737

The issue is caused by missing root certificates on older Android devices with the following error:

javax.net.ssl.SSLHandshakeException:
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

ISRG Root X1 and GTS/Global Sign Root certificates are embedded and used for Android 7 or older devices:

- https://letsencrypt.org/certs/isrgrootx1.pem
- https://pki.goog/repository/

### CODE REVIEW

File: android/app/src/main/java/app/organicmaps/downloader/ChunkTask.java [hunk 1]
```diff
@@ -132,6 +135,11 @@ protected Integer doInBackground(Void... p)
       if (isCancelled())
         return CANCELLED;
 
+      // Fix missing root certificates for HTTPS connections on Android 7 and below:
+      // https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686
+      if (android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.N && mUrl.startsWith("https://"))
+        ((HttpsURLConnection) urlConnection).setSSLSocketFactory(MwmApplication.sslSocketFactory);
```
Comment (vng) [inline android/app/src/main/java/app/organicmaps/downloader/ChunkTask.java:141]: Is possible sslSocketFactory  == null ok here?

File: android/app/src/main/java/app/organicmaps/util/HttpClient.java [hunk 2]
```diff
@@ -71,6 +75,11 @@ public static Params run(@NonNull final Params p) throws IOException, NullPointe
     {
       connection = (HttpURLConnection) new URL(p.url).openConnection();
 
+      // Fix missing root certificates for HTTPS connections on Android 7 and below:
+      // https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686
+      if (android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.N && p.url.startsWith("https://"))
+        ((HttpsURLConnection) connection).setSSLSocketFactory(MwmApplication.sslSocketFactory);
```
Comment (vng) [inline android/app/src/main/java/app/organicmaps/util/HttpClient.java:81]: nit: Factor out a utility function to avoid copy-paste here and above?

File: android/app/src/main/java/app/organicmaps/downloader/ChunkTask.java (hunk 1 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/downloader/ChunkTask.java:141]: I would prefer to have a crash here on Android 7 and lower, so we can debug why certificates did not load properly.

File: android/app/src/main/java/app/organicmaps/util/HttpClient.java (hunk 2 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/util/HttpClient.java:81]: Introducing a utility function will add more lines of code than these 4 lines. It's a simple if, it may be harder to read in a utility function.

Comment (vng) [reply android/app/src/main/java/app/organicmaps/util/HttpClient.java:81]: It is not about lines of code, but keeping not obvious hacks in one place with comments, instead of 2-3 ...

File: android/app/src/main/java/app/organicmaps/downloader/ChunkTask.java (hunk 1 above)
Comment (vng) [reply android/app/src/main/java/app/organicmaps/downloader/ChunkTask.java:141]: Put assert in getSslSocketFactory then?

Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/downloader/ChunkTask.java]: asserts do not work on Android.

setSSLSocketFactory will throw an illegal argument exception, so we will know when it fails in the play console.

File: android/app/src/main/java/app/organicmaps/util/HttpClient.java (hunk 2 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/util/HttpClient.java]: After a second thought I agree that it can be done cleaner. Thanks for the hints! @vng PTAL

**Review by vng — APPROVED** [review]
