### PR TITLE
[android] fix "download world" systematic pause after phone rotation 

### LINKED ISSUE #4496: Rotate device stop download world map
**Steps to reproduce**
1. Start OM (cache is clean and no world map)
2. Start download world map
3. Rotate device -> download is stopped

**Expected behavior**
Like when you download regions on map, if i rotate device -> downloading continue

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: [web-debug](https://github.com/organicmaps/organicmaps/actions/runs/4156518634)
 - Device Model: Pixel 6

### PR DESCRIPTION
**Pull request by Emilevillette**
As explained in [18023cd](https://github.com/organicmaps/organicmaps/commit/18023cdb5f4c8869d4593ba1d44013e72b60e2a3), this fixes a bug that occured on the "download map" screen, typically on a first launch/after a cache reset.

The solution I found is to track a status variable between the activity destruction and its creation after the rotation.

This PR shoud fix #4496.

I look forward to your feedback regarding this matter :)

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Did you test it? @Jean-BaptisteC can you please help to test?

**Comment by Emilevillette** [comment]
> Did you test it? @Jean-BaptisteC can you please help to test?
> 
> Please also test other possible cases, when the app is moved to the background, and then killed, or the device is locked, etc.

Hi @biodranik ! Yes I did rerun the scenario mentionned in #4496 and the problem didn't occur anymore. I just ran a few other tests as you suggested here are the outcomes:

- Device rotation: works as expected. 

- App moved to the background then killed: when the app is booted back up, the user is prompted to start downloading the remaining files (i.e. if it had downloaded 8Mo out of 50Mo, it asks to download 42Mo. In my opinion this should stay this way in case the user's context has changed between the killing of the app and the startup (e.g. he went from an unmetered WiFi connection to a limited mobile broadband access).

- Device is locked: OM stays open and download works as expected.

- Device sent to background and to foreground: on the first launch, the app crashes. This is not related to this PR as I have tested the app on 27730a1 revision, and the problem occurs (I will open a separate issue). Otherwise, when it is NOT the first launch, this works as expected.

I will commit the code updated for the review soon.

File: android/src/app/organicmaps/DownloadResourcesLegacyActivity.java [hunk 1]
```diff
@@ -66,13 +66,17 @@ public class DownloadResourcesLegacyActivity extends BaseMwmFragmentActivity
...
+  private int mCurrentAction = -1;
+
   private static final int DOWNLOAD = 0;
   private static final int PAUSE = 1;
   private static final int RESUME = 2;
   private static final int TRY_AGAIN = 3;
   private static final int PROCEED_TO_MAP = 4;
   private static final int BTN_COUNT = 5;
 
+  private final static String ACTION_KEY = "action";
```
Comment (biodranik) [inline android/src/app/organicmaps/DownloadResourcesLegacyActivity.java:78]: nit:
```suggestion
  private static final String ACTION_KEY = "action";
```

**Comment by Emilevillette** [comment]
I'm struggling a bit with the signoff, however, all the commits should be signed off. Had to force push due to some shenanigans on my local machine.

**Comment by Emilevillette** [comment]
Sorry for the kerfufle. Rebased and pushed, no merge garbage now.

**Review by biodranik — CHANGES_REQUESTED** [review]
Please squash all commits into one by `git rebase -i origin/master` and force-push it here.

**Review by biodranik — COMMENTED** [review]
Almost great ) Why are there 2 commits instead of 1?

**Comment by Emilevillette** [comment]
Oh I'm sorry ! It's fixed, thanks for the guidance. Happy to contribute to the project.

**Review by biodranik — COMMENTED** [review]
I forgot to ask one question: `orientation` is absent here:
```
    <activity android:name="app.organicmaps.DownloadResourcesLegacyActivity"
        android:configChanges="screenLayout|screenSize"/>
```

So the activity is recreated on rotation. Right? Do we really need this "recreation" behavior? Wouldn't it be better to add `orientation` in the list of configChanges?

**Comment by Emilevillette** [comment]
> I forgot to ask one question: `orientation` is absent here:
> 
> ```
>     <activity android:name="app.organicmaps.DownloadResourcesLegacyActivity"
>         android:configChanges="screenLayout|screenSize"/>
> ```
> 
> So the activity is recreated on rotation. Right? Do we really need this "recreation" behavior? Wouldn't it be better to add `orientation` in the list of configChanges?

Correct. I just tested it on commit [27730a1](https://github.com/Emilevillette/organicmaps/commit/27730a1469543268a180892fc4e6af74aadd635f), and it works as expected. I'll apply the changes tomorrow.

**Review by vng — APPROVED** [review]

**Review by blo0147 — APPROVED** [review]

**Comment by vng** [comment]
@Emilevillette So, do we merge it, or will check the Activity orientation setting?

**Comment by Emilevillette** [comment]
I'm sorry I had a busy week. I will do it right now.

**Review by blo0147 — APPROVED** [review]
Let me check it out!!

**Review by biodranik — APPROVED** [review]
Thank you! Isn't the fix beautiful and simple ;-)?

Let's merge it if it works and the issue is not reproduced.

**Comment by Jean-BaptisteC** [comment]
Wrong layout after rotate screen
Landscape layout is keep when i rotate to portrait

**Comment by Emilevillette** [comment]
I did not encouter this issue during my testing, is it possible that it is device-specific?

**Comment by biodranik** [comment]
@Jean-BaptisteC am I right that you've initially launched OM in the landscape to reproduce this issue?

**Comment by Jean-BaptisteC** [comment]
I have started in portrait -> switch in landscape -> switch in portrait -> layout is incorrect

I have test on Android 8, problem doesn't appears

**Comment by biodranik** [comment]
@Jean-BaptisteC It is reproduced on Android 13, right?

**Comment by Jean-BaptisteC** [comment]
Yes :)

**Comment by biodranik** [comment]
@Emilevillette can you please take a look? How other dialogs are correctly resized on rotation without their recreation?

**Comment by Emilevillette** [comment]
I'm afraid I have other obligations atm, I will have more time in about 2 weeks.

**Review by vng — APPROVED** [review]

**Comment by Jean-BaptisteC** [comment]
I have re-tested on master, layout is good when i change screen orientation

**Comment by biodranik** [comment]
@Jean-BaptisteC can you please create an issue for the rotation bug?

**Comment by Jean-BaptisteC** [comment]
> @Jean-BaptisteC can you please create an issue for the rotation layout bug?

I have re-tested with latest changes from master, i'm not able to reproduce bug

**Comment by biodranik** [comment]
Great, thank you very much!
