### PR TITLE
[android] Fix jump of current location point

### LINKED ISSUE #9054: [android] Position arrow jumps in navigation mode
This issue has the same roots as https://github.com/organicmaps/organicmaps/issues/6270

Logs show that every second, after a precise location from GPS provider, a location with a slightly worse accuracy comes from a fused provider. A proper fix should stop retrieving updates from all other providers except GPS (and ideally enable network providers again if location from GPS doesn't come anymore, e.g. in a tunnel).

https://github.com/user-attachments/assets/68cbec96-6877-4f68-b212-fc70c1152ccb

CC @rtsisyk this causes many issues and user reports.

### LINKED ISSUE #10128: Android Auto map rotates and twitches unpredictably when stopped
⚠ Have you searched for similar, already existing issues?
Yes. 

**Describe the issue**
When I have Organic Maps on my car's screen through Android Auto, and stop near an intersection, the map frequently starts rotating, or moving in unpredictable directions (videos attached). Sometimes, the movement is quite subtle, sometimes, the entire map rotates back and forth more than 45 degrees from the direction the car is pointed in. While I was using my phone running Organic Maps to record the videos attached to this issue, the random twitches to the map view happen even when the phone is sitting in the center console and not moving. This issue has been around ever since I started using Organic Maps more than a year ago.

**Steps to reproduce**
1. Connect your phone to Android Auto, start navigation
2. Stop at an intersection
3. Watch the map rotate and twitch unpredictably 

**Expected behaviour**
When the car is not moving, the map view should not move either.

**Screenshots**

https://github.com/user-attachments/assets/3c7c9412-fddb-4267-971e-11790d087721
https://github.com/user-attachments/assets/ba0288db-c66f-46f6-ac4c-aa2d39deb12b

**System information:**
 - Operating system and its version: [GrapheneOS - Android 14, Android 15]
 - Organic Maps version: [All versions since ~January 2024 – 2024.11.27-12]
 - Device Model: [Pixel 8 Pro]

**Additional context**
I can privately send more recordings, as well as the model of my car.

### PR DESCRIPTION
**Pull request by kavikhalique**
partially fixes #10128
fixes #9054 #6270 

The current logic filters out all the location updates from all the providers except the fused location provider. Which results in a jumps in location arrow. Better solution is pass all the location updates (including fused location) through filter and the choose the precise one. 

We cannot solely rely on fused as well since some OS have issues with it. Check out this [comment](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/location/AndroidNativeProvider.java#L92)

Note - Since multiple providers are there so flickering can still be seen but it is minimized due to checks. For total removal either we have to rely on single provider of we need to improve the filter.

### CODE REVIEW

**Comment by kavikhalique** [comment]
This glitch cannot be removed totally until we are using multiple providers at the same time. We can minimizes jumps though. We can improve the filtering to avoid glitches. 

> IDEA -
> 
> we can store last two/three coords and for every next update we can calculate if the new point lies between the line of previous points. If yes we can discard that point as it's most probably a glitch. 
> 
> edge case -
> 
> 1. If user returns back and lies between that imaginary line. Co-ordinate will not be updated but since line will be very short it as soon as user will go out of that line it location will start getting updated.
> 2. On curves or turns line logic may not work so we can take a threshold distance from the line to cover that.

We may test it out this approach if it works fine or not. WDYT @biodranik

**Comment by kavikhalique** [comment]
Glitches and jumps are mostly due to different providers providing nearby points. I logged and found mostly the points has gap of 0 to 1.5 meters. So I have added one more check in filter to discard all those points which are from different providers and have distance less than 3 meters between them.

> Logs - 
>
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 1.2374158E7
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 1.2374158E7
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 0.0
>                   app.organicmaps.debug                D  distance - 1.2950028
>                   app.organicmaps.debug                D  distance - 0.0

**Comment by biodranik** [comment]
What is the difference in horizontal accuracy between these points?

**Comment by kavikhalique** [comment]
> What is the difference in horizontal accuracy between these points?

For gps provider we skip accuracy checking so for some location data we might not have accuracy data. sometimes gps provider only provides co-ordinates. It is mentioned here in [comments](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/util/LocationUtils.java#L75C5-L77C83
)

**Comment by biodranik** [comment]
That was the case on older Androids 10 years ago. The check can detect missing accuracy if needed. My question was about logging accuracy, like you've logged the distance above )

**Comment by kavikhalique** [comment]
> That was the case on older Androids 10 years ago. The check can detect missing accuracy if needed. My question was about logging accuracy, like you've logged the distance above )

This log shows the difference between two simultaneous co-ordinates from two different providers ie. fused and gps provider. 
The glitch occurs due to this difference. Whenever provider switching occurs the marker on map moves 1 meter back or forward due to this gap

**Comment by biodranik** [comment]
Right, and my question was also about displaying horizontal accuracies of positions from both providers in addition to the distance between them.

**Comment by kavikhalique** [comment]
> Right, and my question was also about displaying horizontal accuracies of positions from both providers in addition to the distance between them. 

Thanks, 
Sure!! I will attach the log with accuracy data 👍

**Comment by kavikhalique** [comment]
```
                   app.organicmaps.debug                D  last provider: network acc: 600.0
                   app.organicmaps.debug                D  curr provider: fused acc: 223.558
                   app.organicmaps.debug                D  distance gap: 1.2374158E7
                   app.organicmaps.debug                D  last provider: fused acc: 223.558
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 0.0
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 0.0
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.0590193
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2603439
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2950028
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2950028
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2950028
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2950028
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: network acc: 600.0
                   app.organicmaps.debug                D  distance gap: 1.2374156E7
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2950028
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2950028
                   app.organicmaps.debug                D  last provider: fused acc: 5.0
                   app.organicmaps.debug                D  curr provider: gps acc: 5.0
                   app.organicmaps.debug                D  distance gap: 1.2950028

```

I have attached the log of locations and their providers with accuracy data PTAL - @biodranik

File: android/app/src/main/java/app/organicmaps/util/LocationUtils.java [hunk 1]
```diff
@@ -84,6 +87,10 @@ public static boolean isAccuracySatisfied(@NonNull Location location)
 
   public static boolean isLocationBetterThanLast(@NonNull Location newLocation, @NonNull Location lastLocation)
   {
+    //if provider is changing but distance between the two co-ords are less than threshold then discard
+    if (!Objects.equals(lastLocation.getProvider(), newLocation.getProvider()) && lastLocation.distanceTo(newLocation) < THRESHOLD_DISTNACE_METERS)
+      return false;
```
Comment (vng) [inline android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: This is a very straightforward and controversial check, IMO.
For example we have an old location with bad accuracy (WiFi) and the new location with good accuracy, but will be skipped.

UPD: Probably we can make more _precise_ check: almost equal accuracy, position and timestamp.

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: The threshold value is 3 meters. If the new co-ord is closer than 3 meters to the previous co-ord provided by different provider then updating the location will not change much on map.   

And if the device is moving and previous provider fails to update location either by late update or incorrect update automatically after the range of 3 meters the new precise provider will be used. 

The check will be working for every new update. Any failure in update by previous provider will discard that and use the latest provider.

This technique does not discards any provider until they fail to provide data early and accurately. We can test this technique. This solves the glitch problem on map reported by many users.

**Comment by kavikhalique** [comment]
I did various testings and read some docs but I didn't find anything perfectly solving this problem. 

Problem - Every time the location is updated by gps provider, wifi provider or network provider then fused provider also provides the co-ordinates and the coords provided by both of them differ little bit. Since accuracy and other data are quite accurate in both the cases, they get accepted and this causes a glitch effect. 

- Method1 - I tried rejecting all the coords with same time stamps, it works,  but in we will loose updates from fused provider because it always updates after other providers. so fused will never be used.

- Method2 - I tried to reject all the coord updates which are very near to the previous location (approx. 5 meters). It doesn't seem working when device moves fast.

 [stack overflow](https://stackoverflow.com/a/58794585) suggests using only fused provider its enough for high accuracy but it is available above 31+ api and few devices (as mentioned [here](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/location/AndroidNativeProvider.java#L92C5-L100C7)) doesn't work properly with fused.

Objective - For every update if we have fused provider's update and it is correct (ie. not static as mentioned [here](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/location/AndroidNativeProvider.java#L92C5-L100C7))) then we should prefer it over other updates. And for every time stamp we should update the location only once.

- **Current best approach in my mind** - On every location update don't update it instantly instead store it until receive the fused location for the same time stamp. if receive fused location for same time stamp then update the location. If receive another time stamp that means fused haven't provided any location in that case update the previous timestamp and add this new time stamp in variable and perform like this every time. (This way we will always be choosing fused location over other if received )

Please have a look over it, any better suggestion will be helpful - @AndrewShkrob @biodranik @vng

File: android/app/src/main/java/app/organicmaps/util/LocationUtils.java (hunk 1 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: Actually this was not the major problem instead the updation of older co-ordinates after new co-ordinates  was the actual problem. I inserted a check to only accept co-ordinates which have time stamp greater equal to current time stamps. It solves most of the glitches like back and forth. 

Logged timestamp of wrong updates - 

```
2025-06-06 05:38:02.124  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3085718, new timestamp 3085716
2025-06-06 05:38:02.602  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3086192, new timestamp 3086190
2025-06-06 05:38:03.496  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3087083, new timestamp 3087082
2025-06-06 05:38:03.973  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3087566, new timestamp 3087557
2025-06-06 05:38:04.293  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3087886, new timestamp 3087885
2025-06-06 05:38:04.820  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3088409, new timestamp 3088409
2025-06-06 05:38:06.064  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3089658, new timestamp 3089657
2025-06-06 05:38:07.888  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3091483, new timestamp 3091481
2025-06-06 05:38:09.518  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3093109, new timestamp 3093106
2025-06-06 05:38:11.496  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3095082, new timestamp 3095082
2025-06-06 05:38:13.631  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3097224, new timestamp 3097219
2025-06-06 05:38:14.970  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3098558, new timestamp 3098557
2025-06-06 05:38:16.086  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3099681, new timestamp 3099679
2025-06-06 05:38:17.966  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3101557, new timestamp 3101557
2025-06-06 05:38:20.642  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3104233, new timestamp 3104233
2025-06-06 05:38:23.920  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3107513, new timestamp 3107510
2025-06-06 05:38:26.341  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3109933, new timestamp 3109932
2025-06-06 05:38:33.981  7776-7776  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 3117575, new timestamp 3117574

```

PTAL - @vng @biodranik

Comment (vng) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: Now the check looks better!
I don't remember why, but we decided to _always trust_ the"fused "before.

UPD: Could you please clarify which provider has worse timestamp: fused or gps?

**Review by vng — APPROVED** [review]

File: android/app/src/main/java/app/organicmaps/util/LocationUtils.java (hunk 1 above)
Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: It was fused most of the times probably because it performs some processing before providing the location.

Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: This check will always replace the last (correct) GPS location in favor of a new (incorrect) network/fused one.

As it was stated above, the root cause of the bug is that many providers are active at the same time. And the real fix is to avoid running many providers at the same time. To reduce the risks of breaking users' experience with changes untested on the whole zoo of Android devices, I propose to properly fix the root case instead of experimenting with filters. Using only one precise GPS (or one precise fused) provider will not only fix the issue reported by users, but also reduce the battery consumption.

One of the possible simple approaches is to implement a decision maker code that will turn off other providers as soon as the GPS provider sends any data. If it shows good results, we can tune it later.

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: Yes the main cause is use of multiple providers but we cannot strictly rely on any one if we want precision as well as availability at the same time. 

Fused location is best one but it is available over api level 31, and also in some devices (as commented in code base) it does not work properly(ie. Provides same co-ordinates repeatedly).

I have one another better suggestion. We can keep this filter and also we can store all the co-ords of same time stamp and show only fused one if available otherwise is we receive location with different time stamp we can update the previous temp location to core. This way for every timestamp we will not be using multiple providers. Though for different timestamps logic will still be similar. But most of the glitch issue will get resolve and we don't have to sacrifice wil availability and precision by remove some providers.

Also, code base has already implementation for removal of passive providers.

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: > UPD: Could you please clarify which provider has worse timestamp: fused or gps?

Below is the log of wrong timestamp and its provider its most of the time fused because its little bit delayed but is most accurate one (as suggested by google). Other providers provide early and since fused provider uses those data and analyses it gets late to update. resulting a glitch behavior. 

In my case logs say both providers provide quite similar data just time varies. but it might not be the case in every device. Since google suggests using fused provider then probably there would be some reason : )

```
2025-06-06 13:42:59.297  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4042186, new timestamp 4042183 provider: fused
2025-06-06 13:42:59.801  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4042646, new timestamp 4042644 provider: fused
2025-06-06 13:43:00.245  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4043134, new timestamp 4043134 provider: fused
2025-06-06 13:43:00.797  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4043564, new timestamp 4043458 provider: fused
2025-06-06 13:43:01.255  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4044128, new timestamp 4044119 provider: fused
2025-06-06 13:43:01.561  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4044377, new timestamp 4044375 provider: fused
2025-06-06 13:43:02.171  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4044957, new timestamp 4044922 provider: fused
2025-06-06 13:43:02.773  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4045636, new timestamp 4045587 provider: fused
2025-06-06 13:43:05.050  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4047944, new timestamp 4047935 provider: fused
2025-06-06 13:43:06.576  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4049469, new timestamp 4049458 provider: fused
2025-06-06 13:43:08.183  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4051074, new timestamp 4051057 provider: fused
2025-06-06 13:43:11.690  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4054582, new timestamp 4054562 provider: fused
2025-06-06 13:43:12.803  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4055689, new timestamp 4055683 provider: fused
2025-06-06 13:43:14.673  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4057562, new timestamp 4057559 provider: fused
2025-06-06 13:43:17.347  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4060240, new timestamp 4060233 provider: fused
2025-06-06 13:43:20.618  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4063510, new timestamp 4063506 provider: fused
2025-06-06 13:43:23.043  9316-9316  wrong update            app.organicmaps.debug                D  (main) LocationHelper.java:227 onLocationChanged():  prev timestamp - 4065939, new timestamp 4065932 provider: fused

```

Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: @kavikhalique is it hard to log every location from every provider as it works now in the master branch (without these fixes here) to see the whole timeline + details (incl. precision)?

Using fused provider as the main one can also lead to issues in some cases. So the ideal fix would choose the best provider, either GPS or fused one, based on some criteria.

The implementation may receive all providers data for some time, but emit only one, the best precision location to the consumers chosen from all existing providers. And stop unnecessary providers after that.

Something like that:

1. Keep a dictionary for each last location with a provider being the key.
2. Keep the location that was actually used last time out of the several last locations kept in a dictionary.
3. Keep the count how many times each provider was better than others (and sent to the app) and reset it if provider was switched.
4. After the count reaches some value, e.g. 3 sequential better locations, and the provider is either GPS or fused, then other providers can be disabled.

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: > @kavikhalique is it hard to log every location from every provider as it works now in the master branch (without these fixes here) to see the whole timeline + details (incl. precision)?
> 

No, even the current master shows all the logs whenever any provider provides location with all the data like accuracy and velocity co-ords etc.

> Using fused provider as the main one can also lead to issues in some cases. So the ideal fix would choose the best provider, either GPS or fused one, based on some criteria.
> 

Actually fused itself is made to updates from various providers and provides the best possible accurate locations available. It handles all the providers usage and also battery optimisations.

This is what [documetation](https://developers.google.com/location-context/fused-location-provider) says -

> The fused location provider is a location API in Google Play services that intelligently combines different signals to provide the location information that your app needs.

> The fused location provider manages the underlying location technologies, such as GPS and Wi-Fi, and provides a simple API that you can use to specify the required quality of service. For example, you can request the most accurate data available, or the best accuracy possible with no additional power consumption.

Except few devices fused location works perfectly in other devices and google docs says we can totally rely on fused api.

Even the current master implementation only shows fused updates all other updates are overrided every time because there is filter skipping condition for fused provider.

Relying totally on fused may create few problems. 

1. For apis lower than 31 we need other providers bcz fused is not there

2. There are false update issues in few devices.

What about trying to solve these two issues and relying on fused only? Since fused provider handles battery consumptions very efficiently. Like in background mode or screen off mode etc.

**Comment by vng** [comment]
From my perspective, these changes are good itself, even if they are not aimed to fix _all_ location bugs.
- "fused" locations should also be passed through the filter
- getElapsedRealtimeNanos filtering with not getting an old location after the new one is good. It was assumed as a constraint

File: android/app/src/main/java/app/organicmaps/util/LocationUtils.java (hunk 1 above)
Comment (biodranik) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: > even the current master shows all the logs whenever any provider provides location with all the data like accuracy and velocity co-ords etc.

I meant debugging logs from your device as a real example of some data )

> Actually fused itself is made to updates from various providers and provides the best possible accurate locations available. It handles all the providers usage and also battery optimisations.

I'm sharing with you our experience from many years. In theory, fused should work fine, in practice, we observed issues in some cases, esp. on ungoogled devices with microg, but also on Google-backed devices.

And as you mentioned, it wasn't present on API < 31.

What we can try as a partial workaround: enable _only_ fused provider on API 31+ and see how it goes. Then we can separately fix the issue for older devices.

**Comment by biodranik** [comment]
> From my perspective, these changes are good itself, even if they are not aimed to fix all location bugs.

It would be great to somehow test these changes on some real data from raised issues, taken from https://github.com/organicmaps/organicmaps/issues/10128 https://github.com/organicmaps/organicmaps/issues/9054 https://github.com/organicmaps/organicmaps/issues/6270 issues. And beta-test them too to avoid surprises…

File: android/app/src/main/java/app/organicmaps/util/LocationUtils.java (hunk 1 above)
Comment (zloidemon) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: > 
> I'm sharing with you our experience from many years. In theory, fused should work fine, in practice, we observed issues in some cases, esp. on ungoogled devices with microg, but also on Google-backed devices.
> 

[Alexander Borsuk](https://github.com/biodranik) What issues have you observed with fused location providers in practice?

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: > I meant debugging logs from your device as a real example of some data )
> 

Oh, sure will do it... 👍
 
> I'm sharing with you our experience from many years. In theory, fused should work fine, in practice, we observed issues in some cases, esp. on ungoogled devices with microg, but also on Google-backed devices.
> 

Yes, i read, its mentioned in comments that in some devices fused provider is available but it updates same co-ordinates for 10-15 meter changes (i feel its their optimisation technique which decreases precision and they update the same cached location for few delta meters) 

> What we can try as a partial workaround: enable _only_ fused provider on API 31+ and see how it goes. Then we can separately fix the issue for older devices.

Yes, this seems a good idea. 👍

**Comment by ekirchman** [comment]
Is there a way for a non-contributor like myself to test the build from this branch? As far as I'm aware, the default F-Droid build can't be used in AA, and you need some sort of key in order to build the Google play store version which is the only version which allows the use of OM in AA. I'd like to be able to provide logs if possible.

**Comment by biodranik** [comment]
@ekirchman There is no way to test on AA without a google play-signed build (publicly available or closed beta one). This issue should be reproducible without AA too, did you observe something strange on your device?

**Comment by biodranik** [comment]
And of course, every PR has debug versions installable separately and available to test! Check "Checks" tab, and then press "Android Check" to see zipped apks in the Artifacts section, e.g. https://github.com/organicmaps/organicmaps/actions/runs/15479411653

File: android/app/src/main/java/app/organicmaps/util/LocationUtils.java (hunk 1 above)
Comment (vng) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java:88]: We have logs for Pixel 8 (Android 15, API 35) and probably AA, where fused locations are not optimal (check hAcc). Car-GPS provider is better (seems like from the AA head unit)
```
06-03 07:26:35.150 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[Car-GPS 46.125895,12.181318 hAcc=1.0 et=+12d10h56m58s949ms alt=397.3999938964844 vel=3.8700001 bear=48.72]
06-03 07:26:35.151 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[Car-GPS 46.125895,12.181318 hAcc=1.0 et=+12d10h56m58s949ms alt=397.3999938964844 vel=3.8700001 bear=48.72]
06-03 07:26:35.151 (main) D/app.organicmaps.location: LocationHelper.java:218 onLocationChanged(): The new Location[Car-GPS 46.125895,12.181318 hAcc=1.0 et=+12d10h56m58s949ms alt=397.3999938964844 vel=3.8700001 bear=48.72] is worse than the last Location[Car-GPS 46.125895,12.181318 hAcc=1.0 et=+12d10h56m58s949ms alt=397.3999938964844 vel=3.8700001 bear=48.72]
06-03 07:26:35.152 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[Car-GPS 46.125895,12.181318 hAcc=1.0 et=+12d10h56m58s949ms alt=397.3999938964844 vel=3.8700001 bear=48.72]
06-03 07:26:35.152 (main) D/app.organicmaps.location: LocationHelper.java:218 onLocationChanged(): The new Location[Car-GPS 46.125895,12.181318 hAcc=1.0 et=+12d10h56m58s949ms alt=397.3999938964844 vel=3.8700001 bear=48.72] is worse than the last Location[Car-GPS 46.125895,12.181318 hAcc=1.0 et=+12d10h56m58s949ms alt=397.3999938964844 vel=3.8700001 bear=48.72]
06-03 07:26:35.153 (main) D/app.organicmaps.location: LocationHelper.java:98 onSatelliteStatusChanged(): total = 31 used = 27 fixed = true
06-03 07:26:35.153 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused 46.125895,12.181318 hAcc=5.67 et=+12d10h56m58s949ms alt=397.3999938964844 mslAlt=348.32068949479924 vel=3.8700001 bear=48.0]
06-03 07:26:35.952 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[gps 46.125919,12.181407 hAcc=7.142857 et=+12d10h56m59s780ms alt=445.0 vAcc=2.0 mslAlt=395.92098020154964 mslAltAcc=2.0181427 vel=3.86 sAcc=0.27 bear=49.6 bAcc=2.3 {Bundle[{satellites=27, maxCn0=38, meanCn0=29}]}]
06-03 07:26:35.995 (main) D/app.organicmaps.location: LocationHelper.java:98 onSatelliteStatusChanged(): total = 31 used = 28 fixed = true
06-03 07:26:36.123 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[Car-GPS 46.125920,12.181362 hAcc=1.0 et=+12d10h56m59s949ms alt=397.29998779296875 vel=4.6000004 bear=48.64]
06-03 07:26:36.138 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[Car-GPS 46.125920,12.181362 hAcc=1.0 et=+12d10h56m59s949ms alt=397.29998779296875 vel=4.6000004 bear=48.64]
06-03 07:26:36.139 (main) D/app.organicmaps.location: LocationHelper.java:218 onLocationChanged(): The new Location[Car-GPS 46.125920,12.181362 hAcc=1.0 et=+12d10h56m59s949ms alt=397.29998779296875 vel=4.6000004 bear=48.64] is worse than the last Location[Car-GPS 46.125920,12.181362 hAcc=1.0 et=+12d10h56m59s949ms alt=397.29998779296875 vel=4.6000004 bear=48.64]
06-03 07:26:36.139 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[Car-GPS 46.125920,12.181362 hAcc=1.0 et=+12d10h56m59s949ms alt=397.29998779296875 vel=4.6000004 bear=48.64]
06-03 07:26:36.139 (main) D/app.organicmaps.location: LocationHelper.java:218 onLocationChanged(): The new Location[Car-GPS 46.125920,12.181362 hAcc=1.0 et=+12d10h56m59s949ms alt=397.29998779296875 vel=4.6000004 bear=48.64] is worse than the last Location[Car-GPS 46.125920,12.181362 hAcc=1.0 et=+12d10h56m59s949ms alt=397.29998779296875 vel=4.6000004 bear=48.64]
06-03 07:26:36.145 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused 46.125920,12.181362 hAcc=5.67 et=+12d10h56m59s949ms alt=397.29998779296875 mslAlt=348.2206999605613 vel=4.6000004 bear=48.0]
06-03 07:26:36.605 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[network 46.129725,12.189763 hAcc=400.0 et=+12d10h56m58s101ms]
06-03 07:26:36.608 (main) D/app.organicmaps.location: LocationHelper.java:218 onLocationChanged(): The new Location[network 46.129725,12.189763 hAcc=400.0 et=+12d10h56m58s101ms] is worse than the last Location[fused 46.125920,12.181362 hAcc=5.67 et=+12d10h56m59s949ms alt=397.29998779296875 mslAlt=348.2206999605613 vel=4.6000004 bear=48.0]
06-03 07:26:36.948 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[gps 46.125936,12.181451 hAcc=6.632653 et=+12d10h57m0s773ms alt=446.0 vAcc=2.0 mslAlt=396.9210671700283 mslAltAcc=2.0181427 vel=3.9199998 sAcc=0.66 bear=55.4 bAcc=4.7 {Bundle[{satellites=28, maxCn0=38, meanCn0=29}]}]
```

**Comment by zloidemon** [comment]
> It would be great to somehow test these changes on some real data from raised issues, taken from #10128 #9054 #6270 issues. And beta-test them too to avoid surprises…

[Alexander Borsuk](https://github.com/biodranik) What steps are needed to reproduce the original issues using the collected real data?

**Comment by ekirchman** [comment]
> @ekirchman There is no way to test on AA without a google play-signed build (publicly available or closed beta one). This issue should be reproducible without AA too, did you observe something strange on your device?

I've only seemed to notice this issue when using AA. The issue is undetectable to me when not plugged into AA. It was my understanding that this was due to the same issue as listed in this thread, but specifically caused by the car's GPS. https://github.com/organicmaps/organicmaps/issues/10128#issuecomment-2689001259

**Comment by kavikhalique** [comment]
> Adding a log from a real device with jumping locations. @kavikhalique, note that there are cases when data comes from 4! providers at the same time. That is definitely not efficient and should be properly refactored.
> 
> [jumping location.txt](https://github.com/user-attachments/files/20646053/jumping.location.txt) 

 _Originally posted by @biodranik in [#9054](https://github.com/organicmaps/organicmaps/issues/9054#issuecomment-2954192363)_

Thanks for the testing and logs, I had mentioned this problem before and suggested one possible solution too. kindly check the below quoted comment.

> I have one another better suggestion. We can keep this filter and also we can store all the co-ords of same time stamp and if we receive location with different time stamp we can update the previous temp location to core. This way for every timestamp we will not be using multiple providers. Though for different timestamps logic will still be similar. But most of the glitch issue will get resolve and we don't have to sacrifice with availability and precision by removing some providers.

Actually initially I started to solve this problem only and in between I found that time stamps are not sequential. I have a commit ready where filtered locations of time stamps are stored in "temp_location" variable, and we update a location to core only when we receive new time stamp co-ords.  should I add that commit in this PR? 

My another suggestion is to add some weight logic for every provider and increase decrease weight according to accuracy and always use the provider with highest weight. This way switching between providers will decrease and most of the glitch will not occur. But it needs proper discussion. I feel currently we can go with temp_location logic for same time stamps and later add this provider weight technique to minimize switchings. WDYT @biodranik

**Comment by kavikhalique** [comment]
Although these logics with time stamps solve backward glitches but it does not solves all glitch problems totally. We need to somehow avoid sudden switchings between providers to solve this problem totally.  Attaching the screen recording of glitch after these changes.

https://github.com/user-attachments/assets/cadbafe3-5460-4c4a-adef-f38d895a0e2e

To solve this problem, I can think of three ways (if there is any better idea please suggest)

1. Totally rely on any single provider
2. Create a very strong filter which catch the glitches and avoid
3. Keep all providers but make switching difficult by putting some weight logic.

PTAL - @biodranik @vng

File: android/app/src/main/java/app/organicmaps/util/LocationUtils.java [hunk 2]
```diff
@@ -14,6 +14,8 @@
 import androidx.annotation.NonNull;
 import androidx.core.content.ContextCompat;
 
+import java.util.Objects;
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/util/LocationUtils.java]: Why is this line needed? )

Comment (kavikhalique) [reply android/app/src/main/java/app/organicmaps/util/LocationUtils.java]: this probably came from last pr. removed this. Thanks

**Comment by kavikhalique** [comment]
The root cause of this problem is not only this. I tested with single provider too and I found the glitch is still present there. 
Though this PR removes some glitches but most of the forward glitches are due to core implementation. I found probably extrapolator is causing the issue because when I disabled it glitch was totally gone. 
I think extrapolator causes the issue when device moves very fast like in car or bike and that is the reason most of the glitches are observed in AA. 

To confirm this, tomorrow i will perform a test with iOS device.

**Comment by biodranik** [comment]
Here are two interesting (real) examples:

1. Note the highest precision of CAR-gps (and its presence):
```
06-07 16:18:01.088 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused XX.YYY hAcc=5.039 et=+16d19h48m34s252ms alt=357.88386054050716 vAcc=4.8028097 mslAlt=308.51472531666246 mslAltAcc=4.810393 vel=1.3842126 sAcc=0.3079213 bear=201.48933 bAcc=10.369494]
06-07 16:18:01.590 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[gps XX.YYY hAcc=7.6530614 et=+16d19h48m34s771ms alt=348.0 vAcc=4.0 mslAlt=298.63102766716077 mslAltAcc=4.0091023 vel=1.37 sAcc=0.29 bear=214.0 bAcc=4.7 {Bundle[{satellites=29, maxCn0=43, meanCn0=30}]}]
06-07 16:18:01.598 (main) D/app.organicmaps.location: LocationHelper.java:218 onLocationChanged(): The new Location[gps XX.YYY hAcc=7.6530614 et=+16d19h48m34s771ms alt=348.0 vAcc=4.0 mslAlt=298.63102766716077 mslAltAcc=4.0091023 vel=1.37 sAcc=0.29 bear=214.0 bAcc=4.7 {Bundle[{satellites=29, maxCn0=43, meanCn0=30}]}] is worse than the last Location[fused XX.YYY hAcc=5.039 et=+16d19h48m34s252ms alt=357.88386054050716 vAcc=4.8028097 mslAlt=308.51472531666246 mslAltAcc=4.810393 vel=1.3842126 sAcc=0.3079213 bear=201.48933 bAcc=10.369494]
06-07 16:18:01.667 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused XX.YYY hAcc=5.008 et=+16d19h48m34s771ms alt=358.0935373128846 vAcc=4.8882427 mslAlt=308.72448594306655 mslAltAcc=4.895694 vel=1.4359108 sAcc=0.27422008 bear=201.66728 bAcc=10.078324]
06-07 16:18:01.679 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused XX.YYY hAcc=4.993 et=+16d19h48m34s866ms alt=358.0935373128846 vAcc=4.8882427 mslAlt=308.72450690663345 mslAltAcc=4.895694 vel=1.4376922 sAcc=0.27422008 bear=202.00912 bAcc=10.276746]
```

Note that there are 4! fused locations mixed with one GPS location in just one second:
```
06-07 16:18:02.095 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[network XX.YYY hAcc=2200.0 et=+16d19h48m32s872ms]
06-07 16:18:02.096 (main) D/app.organicmaps.location: LocationHelper.java:218 onLocationChanged(): The new Location[network XX.YYY hAcc=2200.0 et=+16d19h48m32s872ms] is worse than the last Location[fused XX.YYY hAcc=4.993 et=+16d19h48m34s866ms alt=358.0935373128846 vAcc=4.8882427 mslAlt=308.72450690663345 mslAltAcc=4.895694 vel=1.4376922 sAcc=0.27422008 bear=202.00912 bAcc=10.276746]
06-07 16:18:02.103 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused XX.YYY hAcc=4.983 et=+16d19h48m35s257ms alt=358.0935373128846 vAcc=4.8882427 mslAlt=308.72452472168027 mslAltAcc=4.895694 vel=1.4364027 sAcc=0.3155056 bear=202.94618 bAcc=9.925814]
06-07 16:18:02.175 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused XX.YYY hAcc=4.976 et=+16d19h48m35s350ms alt=358.0935373128846 vAcc=4.8882427 mslAlt=308.7246128244308 mslAltAcc=4.895694 vel=1.4323622 sAcc=0.3155056 bear=204.10124 bAcc=9.925814]
06-07 16:18:02.587 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[gps XX.YYY hAcc=6.632653 et=+16d19h48m35s768ms alt=348.0 vAcc=4.0 mslAlt=298.63110867883523 mslAltAcc=4.0091023 vel=0.95 sAcc=0.35 bear=216.4 bAcc=6.7 {Bundle[{satellites=29, maxCn0=43, meanCn0=31}]}]
06-07 16:18:02.655 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused XX.YYY hAcc=4.93 et=+16d19h48m35s768ms alt=358.11611819328704 vAcc=5.0769644 mslAlt=308.7472077771495 mslAltAcc=5.084139 vel=1.3554156 sAcc=0.26770207 bear=205.76035 bAcc=10.03716]
06-07 16:18:02.768 (main) D/app.organicmaps.location: LocationHelper.java:200 onLocationChanged(): provider = AndroidNativeProvider location = Location[fused XX.YYY hAcc=4.886 et=+16d19h48m35s947ms alt=358.11611819328704 vAcc=5.0769644 mslAlt=308.7472156205313 mslAltAcc=5.084139 vel=1.3522016 sAcc=0.26770207 bear=206.46986 bAcc=10.167365]
```

**Comment by biodranik** [comment]
I assume that interpolator's code was not designed for location updates faster than one per second, and from different providers. And when it happens, we observe glitches.

Strange that it fails with only one provider. @kavikhalique did you observe issues with one provider with one update per second or with several updates per second?

Technically, GPS cannot be updated faster than 1HZ. While >1HZ frequencies can be helpful for higher speeds, most of the real use cases don't need it.

**Comment by kavikhalique** [comment]
> Strange that it fails with only one provider. @kavikhalique did you observe issues with one provider with one update per second or with several updates per second?
> 

In android time is not set to 1 seconds thats why in a second every provider provides more than 2 updates.

> Technically, GPS cannot be updated faster than 1HZ. While >1HZ frequencies can be helpful for higher speeds, most of the real use cases don't need it. 

Yes, today i performed testing in iOS device with moving fast and i found location was not getting updated so quickly (i assume its 1 second in iOS) but in andoroid there is no such constraint on location update which might be causing issue.
