### PR TITLE
[ios] Fix distance freeze for locales with comma as decimal seperator

### LINKED ISSUE #6209: [ios] The distance to the next turn or to the final destination freezes
> After an upgrade to the latest version, in the navigation mode, the distance to the next turn or to the final destination freezes at 10 kilometers (when the countdown should switch from counting kilometers to counting hundreds of meters) and unfreezes back only when the distance gets below 1 kilometer (when it switches to counting dozens of meters).

_Originally posted by @biodranik in https://github.com/organicmaps/organicmaps/issues/4029#issuecomment-1747466003_

### LINKED ISSUE #6478: [ios] Distance in navigation panel is not updated between 10km and 1000m
There is a regression when the distance in navigation mode is not properly updated and stays at 10km without an update. Two users have reported it. Looks like it reproduces in CarPlay, I wasn't able to reproduce it on the iPhone.

> ...I‘m on the road again. Seems the problem is between 10 km and 1 km. Position and speed is not affected.
When entering 1 km and lower it‘s counting down from 10 km to 900 meters
Also when it's more than 10 km to the next exit everything is okay. Just between 10 km and 1 km

> iPhone 12, iOS 17.1
I’m using CarPlay when navigating with organic maps
The phone's language is German.
AppStore says Organic Maps is up to date, Version 2023.09.22_20
I’m not sure if I described it correctly. OrganicMaps told me, 56 km to the next exit. Then 55, 54, and so on, until 10 km is reached. Then the display was not counting down, it still says 10 km until 1 km is reached and it needs to switch to meters.
Speed is still correct and the map is moving like normal.

### PR DESCRIPTION
**Pull request by fabwu**
Use NumberFormatter to parse distance instead of Double.

Fixes #6209
Fixes #6478

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Fixed #6478?

File: iphone/Maps/Classes/CarPlay/CarPlayService.swift [hunk 1]
```diff
@@ -654,7 +654,7 @@ extension CarPlayService {
   }
 
   func createEstimates(routeInfo: RouteInfo) -> CPTravelEstimates? {
-    if let distance = Double(routeInfo.targetDistance) {
+    if let distance = NumberFormatter().number(from: routeInfo.targetDistance)?.doubleValue {
```
Comment (biodranik) [inline iphone/Maps/Classes/CarPlay/CarPlayService.swift:657]: It's ok as a quick workaround. But why the distance is passed as a string, and then converted to a double? Is it possible to store raw double in the RouteInfo?

**Review by biodranik — APPROVED** [review]

File: iphone/Maps/Classes/CarPlay/CarPlayService.swift (hunk 1 above)
Comment (fabwu) [reply iphone/Maps/Classes/CarPlay/CarPlayService.swift:657]: Yes that's much better. I'll post my changes soon.

Comment (fabwu) [reply iphone/Maps/Classes/CarPlay/CarPlayService.swift]: I did some quick tests and it worked in the simulator. I'm just confused why they used a string instead of the double. This needs maybe more testing...

**Comment by fabwu** [comment]
Maybe this fixes #6380 as well?

File: iphone/Maps/Classes/CarPlay/CarPlayService.swift (hunk 1 above)
Comment (biodranik) [reply iphone/Maps/Classes/CarPlay/CarPlayService.swift]: @fabwu is it hard to refactor this code a bit in a separate PR, to avoid this unnecessary and risky conversion?

**Comment by biodranik** [comment]
@gpesquero you never know how changes in one place may break something in another :D https://github.com/organicmaps/organicmaps/pull/4029

**Comment by biodranik** [comment]
@fabwu congrats! With just one line of code you've fixed 4 important issues! :)

**Comment by gpesquero** [comment]
> @gpesquero you never know how changes in one place may break something in another :D #4029

Yep... we should have done more follow-up on those issues reported back in October, right after we merged the decimal separator change...

Is there a way to add unit tests in the iOS/CarPlay & Android/Android Auto sides?

**Comment by biodranik** [comment]
Maybe, let's ask @kirylkaveryn @fabwu @Jean-BaptisteC @arnaudvergnet

**Comment by fabwu** [comment]
> @fabwu congrats! With just one line of code you've fixed 4 important issues! :)

It was really the insight with the decimal separator that made the difference here ;)

> Is there a way to add unit tests in the iOS/CarPlay & Android/Android Auto sides?

@gpesquero I'd love to have unit tests as well so I followed [this guide](https://medium.com/@bahalek/adding-unit-test-target-for-an-existing-xcode-project-528eac6d89ba) adding a unit test target. It looks easy for a small project but I couldn't make it work for the organic maps project so far.

**Comment by gpesquero** [comment]
> @gpesquero I'd love to have unit tests as well so I followed [this guide](https://medium.com/@bahalek/adding-unit-test-target-for-an-existing-xcode-project-528eac6d89ba) adding a unit test target. It looks easy for a small project but I couldn't make it work for the organic maps project so far.

@fabwu: I will have a look at this guide to see if I can create unit tests in iOS.

Regarding the CarPlay functionality, have you tested also if the grouping (thousands) separator works Ok with different locales? In standard iOS, this can be tested searching for far cities (Sidney for example, if you live in Europe).
