### PR TITLE
Cuisine editor filter fix

### LINKED ISSUE #285: Search in Russian doesn't work in sub-search (like kitchen type) when POI is added
If you search 'амери' than 'американская кухня' is not displayed. But it is displayed for 'ameri' (probably, as a substring for 'american').

index_1
index_2
index_3

### PR DESCRIPTION
**Pull request by strump**
Added filtering not only by english but in translated label too.

Closes #285 and #2841.

| Rus | Ukr | Hebr |
| --- | --- | ---- |
| cuisine-filter | cuisine-filter-ukr | cuisine-filter-hebr |

### CODE REVIEW

File: android/jni/com/mapswithme/util/StringUtils.cpp [hunk 1]
```diff
@@ -44,7 +44,7 @@ Java_com_mapswithme_util_StringUtils_nativeFilterContainsNormalized(JNIEnv * env
   for (int i = 0; i < length; i++)
   {
     std::string str = jni::ToNativeString(env, (jstring) env->GetObjectArrayElement(src, i));
-    if (search::ContainsNormalized(str, substr))
+    if (search::ContainsNormalized(str, substr) || search::ContainsNormalized(osm::Cuisines::Instance().Translate(str), substr))
```
Comment (vng) [inline android/jni/com/mapswithme/util/StringUtils.cpp:47]: Please, take this:
auto const & cuisines = osm::Cuisines::Instance();
out of the loop.

**Review by vng — APPROVED** [review]

File: android/jni/com/mapswithme/util/StringUtils.cpp (hunk 1 above)
Comment (strump) [reply android/jni/com/mapswithme/util/StringUtils.cpp]: Fixed
