### PR TITLE
[editor] Fixed bug overwriting existing features

### LINKED ISSUE #2298: Editor: existing object is updated instead of creation of a new one
1. Find a POI object on map, zoom to it
2. In menu choose Add new place
3. Add a new place, put a cross onto existing POI
4. Instead of a new POI, existing one is updated with tags from new one. For example, check version '3' in https://www.openstreetmap.org/node/5418889456/history  - cafe is merged with sports shop

### PR DESCRIPTION
**Pull request by map-per**
fixes #2298

This PR solves the problem that, when adding a node at a location where a different node is located already, the tags of the new feature are added to the existing node. This often leads to nonsense combinations (see #2298) and can also make address nodes unusable.

Test:
- Bug in current Play Store version: https://www.openstreetmap.org/changeset/149696066
- This PR doesn't overwrite the old node, but creates a new node: https://www.openstreetmap.org/changeset/149697572
   The existing node remains untouched: https://www.openstreetmap.org/node/11257500263

### CODE REVIEW

**Comment by biodranik** [comment]
OSM login in Debug version uses OSM dev server.

**Comment by map-per** [comment]
> OSM login in Debug version uses OSM dev server.

Ok, thanks! Didn't know that.

File: editor/osm_editor.cpp [hunk 1]
```diff
@@ -646,8 +646,9 @@ void Editor::UploadChanges(string const & oauthToken, ChangesetTags tags,
               }
               else
               {
-                LOG(LDEBUG, ("Create case: uploading patched feature", osmFeature));
-                changeset.Modify(osmFeature);
+                LOG(LDEBUG, ("Create case: uploading new feature", osmFeature));
+                // There is another node nearby, but it is saver to upload a new node (#2298).
+                changeset.Create(feature);
```
Comment (biodranik) [inline editor/osm_editor.cpp:651]: As was discussed in the issue, this implementation will always create the feature, even if it already exists. A better approach would be to try to compare features by some criteria and decide about modifying or creating based on it:

```
if (IsTheSameFeature(osmFeature, osmFeatureCopy)
{
  LOG(LDEBUG, ("Create case: uploading patched feature", osmFeature));
  changeset.Modify(osmFeature);
}
else
{
  LOG(LDEBUG, ("Create case: uploading new feature", osmFeature));
  // There is another feature node nearby, but it is safe to upload a new node (#2298).
  changeset.Create(feature);
}
```

`IsTheSameFeature` function can be implemented in different ways. It can be thoroughly tested with different combinations of tags. It would be great to debug and dump real tag values for some most popular OM types that are edited to write these tests properly.

Is there a way to calculate how many real duplicates were replaced with the existing code, and how many wrong types have been replaced?

Comment (map-per) [reply editor/osm_editor.cpp:651]: > Is there a way to calculate how many real duplicates were replaced with the existing code, and how many wrong types have been replaced?

I don't know how to prove this with numbers as this bug is very hard to spot. The changeset comments of OM "Updated ..." are very generic.

But when reviewing OM changesets I spot this bug ocasionally and I only remember one occasion where merging was a good thing to do. That was when a newly opened place got merged with a `disused:shop`. But even there the `disused:shop` tag remained in place, leading to inconsistent data.

Important to note is that the current merge decision is **nonsense**. The implementation just checks whether there is **any** feature nearby and not whether these features are **the same** before merging / overwriting. This algorithm merges a waste_basket into a fire_hydrant in case one is close by although this violates the ["one feature, one OSM element"](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element) rule of OSM.

Currently OM is trying to be smart, but it isn't. It's just damaging  OSM data. With this PR OM will always add a new place whenever the user clicks on "Add a place". If this leads to a duplicate this is an error type that is way easier to spot and fix in OSM. Moreover it is more "acceptable" to have these types of errors as OM is an offline editor, and editing based on up to two month old map data almost inevitably leads to some duplicates.

With this PR the overwhelming majority of cases will be handled correctly. An `IsTheSameFeature` check would be cool to have, but it won't prevent all duplicates and is difficult to implement. How can we tell that features are the same? If we use feature type and `name`, duplicates will be overlooked if the `name` is written slightly different. And just using feature type is not save e.g. if there are two clothes shops on top of each other (on different levels) in a shopping centre. In my opinion implementing this is not worth the effort at the moment as OM has more important issues.

This PR significantly reduces the number of wrong edits. That's why I suggest to merge this PR as a first step and open a new Issue for the merge algorithm.

Comment (biodranik) [reply editor/osm_editor.cpp:651]: 1. Thanks for the clarification! I agree that this should be an improvement. Is it possible to add some specific comment for these changesets, so we can later collect a database of all real cases and see where/how we can implement a better feature merge later?

2. Does it make sense to also create a note?

3. Btw, is there any external API/web service that can help to merge features more efficiently (and will be easier to support/extend than doing it in a client code)? Does it make sense to create such an API?

Comment (map-per) [reply editor/osm_editor.cpp:651]: > 1. 

That's a very good Idea. I added a "info:feature_close_by=yes" flag to the changeset meta data. This way one can easily filter for these changesets in e.g. OSMCha.

> 2.

No, notes are for human-human interaction only. Automatically adding them is not allowed.

> 3.

I don't know any API

**Comment by map-per** [comment]
Tested the addition of the "info:feature_close_by=yes" changeset tag. It works as intended now. (https://www.openstreetmap.org/changeset/149860708)

File: editor/changeset_wrapper.cpp [hunk 2]
```diff
@@ -247,6 +247,11 @@ void ChangesetWrapper::Delete(editor::XMLFeature node)
   m_deleted_types[GetTypeForFeature(node)]++;
 }
 
+void ChangesetWrapper::AddChangesetTag(std::string key, std::string value)
+{
+    m_changesetComments.insert({key, value});
+}
```
Comment (biodranik) [inline editor/changeset_wrapper.cpp:253]:
```suggestion
void ChangesetWrapper::AddChangesetTag(std::string key, std::string value)
{
  m_changesetComments.emplace(std::move(key), std::move(value));
}
```

File: editor/osm_editor.cpp [hunk 3]
```diff
@@ -646,8 +646,10 @@ void Editor::UploadChanges(string const & oauthToken, ChangesetTags tags,
               }
               else
               {
-                LOG(LDEBUG, ("Create case: uploading patched feature", osmFeature));
-                changeset.Modify(osmFeature);
+                LOG(LDEBUG, ("Create case: uploading new feature", feature));
+                // There is another node nearby, but it is saver to upload a new node (#2298).
+                changeset.Create(feature);
+                changeset.AddChangesetTag("info:feature_close_by", "yes");
```
Comment (biodranik) [inline editor/osm_editor.cpp:652]: This line should go _before_ the previous line to reliably send tags to the server when changeset is created, not when it's closed.

**Comment by map-per** [comment]
Thank you! I updated the PR.

**Review by biodranik — APPROVED** [review]
Thanks! Let's start monitoring potential conflicts.

**Comment by map-per** [comment]
Yes, I think `feature_close_by` doesn't happen very often. My estimate is about 50 changesets per month. 

My plan is to analyse these changesets about one month after the next release.
