### PR TITLE
[drape] Introduced new style parameters to adjust route arrow colors

### LINKED ISSUE #5044: Inconsistent arrow color for route with multiple stop points
**The issue**
Route arrow color is different on the first subroute (before the first stop) and on following subroute (after the first stop).

**Steps to reproduce**
1. Build bicycle route from two points.
2. Add intermidiate stop point.
3. Arrow color after stop point has purple color.

**Expected behavior**
Arrows color should be consistent.

**Screenshots**

**System information:**
 - Operating system: Android 13
 - Organic Maps version: 2023.04.02-7-Google
 - Device Model: Oppo 11

**Additional context**
Arrows color is configured with `RouteArrowsMaskCar-color` and `RouteArrowsMaskBicycle-color` properties from `style.mapcss` files. But according to [route_renderer.cpp](https://github.com/organicmaps/organicmaps/blob/master/drape_frontend/route_renderer.cpp#L386) these properties are not applied till the first route stop. In `RouteRenderer::GetMaskColor()` method variable `baseDistance` is 0.0 for the first subroute and non-zero for others.

This behaviour was introduced in commit [f5a85223](https://github.com/organicmaps/organicmaps/commit/553f20f7cac24f81a15b2a13c5275628f5a85223) by `r.kuznetsov`.

### PR DESCRIPTION
**Pull request by strump**
Closes #5044 .

Route from start (current position) to first stop point has default color defined by properties `Route`, `RouteBicycle`, and `RoutePedestrian`. After the first stop route color and arrow color are adjusted according to `RouteMaskCar`, `RouteMaskBicycle`, `RouteMaskPedestrian`, `RouteArrowsMaskCar`, and `RouteArrowsMaskBicycle` properties.

**🆕 Changes:** Introduced properties `RouteFirstSegmentArrowsMaskCar` and `RouteFirstSegmentArrowsMaskBicycle` to adjust route arrow colors till the first stop. **Note** currently those properties in `style.mapcss` has 0.0 opacity and do not change arrow color.

**Screenshots doesn't represent actual code! Arrow color is adjusted for demo.**
| Car route | Bicycle route|
| ------- | ------- |
|  route-arrow-car-schema | route-arrow-bicycle-schema |

### CODE REVIEW

File: drape_frontend/route_renderer.cpp [hunk 1]
```diff
@@ -383,21 +385,44 @@ CirclesPackHandle * RouteRenderer::GetPreviewHandle(size_t & index)
...
+        return GetColorConstant(kRoutePrimaryArrowsMaskBicycle);
+  }
+  else if (m_distanceFromBegin < baseDistance)
+  {
+    if (routeType == RouteType::Car)
+      return GetColorConstant(kRouteArrowsMaskCar);
+    if (routeType == RouteType::Bicycle)
+      return GetColorConstant(kRouteArrowsMaskBicycle);
+  }
+  return {0, 0, 0, 0};
```
Comment (biodranik) [inline drape_frontend/route_renderer.cpp:423]:
```suggestion
  const bool isFirstSegment = baseDistance == 0.0;
  switch (routeType)
  {
  case RouteType::Car: return GetColorConstant(isFirstSegment ? kRoutePrimaryArrowsMaskCar : kRouteArrowsMaskCar);
  case RouteType::Bicycle: return GetColorConstant(isFirstSegment ? kRoutePrimaryArrowsMaskBicycle : kRouteArrowsMaskBicycle);
  default: return Color::Transparent();
  }
```

File: drape_frontend/route_renderer.cpp [hunk 2]
```diff
@@ -383,21 +385,44 @@ CirclesPackHandle * RouteRenderer::GetPreviewHandle(size_t & index)
...
+// Arrow mask is used to adjust route arrow color. First subroute has primary arrows color
+// defined by RoutePrimaryArrowsMaskCar and RoutePrimaryArrowsMaskBicycle properties.
+dp::Color RouteRenderer::GetArrowMaskColor(RouteType routeType, double baseDistance) const
+{
+  if (baseDistance == 0.0)
+  {
+      if (routeType == RouteType::Car)
+        return GetColorConstant(kRoutePrimaryArrowsMaskCar);
+      if (routeType == RouteType::Bicycle)
+        return GetColorConstant(kRoutePrimaryArrowsMaskBicycle);
```
Comment (biodranik) [inline drape_frontend/route_renderer.cpp:414]: kRouteFirstSegmentArrowsMaskBicycle?

Primary is not clear.

**Review by biodranik — COMMENTED** [review]
Good! Did you test it in all routing modes? Does it look good?

I didn't understand the comment about screenshots. Did you manually change color there?

File: drape_frontend/route_renderer.cpp (hunk 1 above)
Comment (strump) [reply drape_frontend/route_renderer.cpp:423]: In proposed code you removed `if (m_distanceFromBegin < baseDistance)` condition. This check is present in `master` now. Not sure how it will affect route colors. Should I keep it?

File: drape_frontend/route_renderer.cpp (hunk 2 above)
Comment (strump) [reply drape_frontend/route_renderer.cpp:414]: I couldn't come up with better name. Any ideas?

**Comment by strump** [comment]
@biodranik 
> I didn't understand the comment about screenshots. Did you manually change color there?

I made custom OrganicMaps build with some bright color for `RoutePrimaryArrowsMaskCar` and `RoutePrimaryArrowsMaskBicycle` and made some screenshots. But in this PR colors are transparent. Arrow colors should be the same after merge.

File: drape_frontend/route_renderer.cpp (hunk 1 above)
Comment (biodranik) [reply drape_frontend/route_renderer.cpp:423]: Right! My bad. The you can reuse the transparent constant only.

File: drape_frontend/route_renderer.cpp (hunk 2 above)
Comment (biodranik) [reply drape_frontend/route_renderer.cpp:414]: > kRouteFirstSegmentArrowsMaskBicycle?

**Review by biodranik — APPROVED** [review]
Thanks! It would be great to fix white arrow color in the following PR :)

CC @vng

File: drape_frontend/route_renderer.cpp [hunk 3]
```diff
@@ -383,21 +385,44 @@ CirclesPackHandle * RouteRenderer::GetPreviewHandle(size_t & index)
   return nullptr;
 }
 
-dp::Color RouteRenderer::GetMaskColor(RouteType routeType, double baseDistance,
-                                      bool arrows) const
+// Arrow mask is used to adjust route color for subroutes after the first stop. So subroute to the first stop
```
Comment (vng) [inline drape_frontend/route_renderer.cpp:388]: "Route mask"

**Review by vng — APPROVED** [review]

File: drape_frontend/route_renderer.cpp [hunk 4]
```diff
@@ -383,21 +385,44 @@ CirclesPackHandle * RouteRenderer::GetPreviewHandle(size_t & index)
...
+// point has default color, while subsequent subroutes color is adjusted with RouteArrowsMaskCar,
+// RouteArrowsMaskBicycle and kRouteMaskPedestrian properties.
```
Comment (vng) [inline drape_frontend/route_renderer.cpp:390]: This comment should be for GetArrowMaskColor ?

Comment (strump) [reply drape_frontend/route_renderer.cpp]: Updated comment. Do you have ideas how to make it more clear?

File: drape_frontend/route_renderer.cpp (hunk 3 above)
Comment (strump) [reply drape_frontend/route_renderer.cpp]: Thanks. Fixed comments

File: drape_frontend/route_renderer.cpp [hunk 5]
```diff
@@ -383,19 +385,43 @@ CirclesPackHandle * RouteRenderer::GetPreviewHandle(size_t & index)
...
+// by RouteFirstSegmentArrowsMaskCar and RouteFirstSegmentArrowsMaskBicycle properties.
+// All following subroutes have arrow color defined by RouteArrowsMaskCar, RouteArrowsMaskBicycle.
+dp::Color RouteRenderer::GetArrowMaskColor(RouteType routeType, double baseDistance) const
+{
+  if (baseDistance == 0.0)
+  {
+      if (routeType == RouteType::Car)
+        return GetColorConstant(kRouteFirstSegmentArrowsMaskCar);
+      if (routeType == RouteType::Bicycle)
+        return GetColorConstant(kRouteFirstSegmentArrowsMaskBicycle);
```
Comment (biodranik) [inline drape_frontend/route_renderer.cpp:415]:
```suggestion
    if (routeType == RouteType::Car)
      return GetColorConstant(kRouteFirstSegmentArrowsMaskCar);
    if (routeType == RouteType::Bicycle)
      return GetColorConstant(kRouteFirstSegmentArrowsMaskBicycle);
```

Comment (strump) [reply drape_frontend/route_renderer.cpp]: Fixed formatting

**Comment by biodranik** [comment]
We usually split regenerated commits to avoid merge conflicts and for easier reverting/rebasing.

**Comment by strump** [comment]
Splitted into 2 commits.
