### PR TITLE
[Android] Check browser availability before showing OAuth login UI.

### LINKED ISSUE #10689: Login to OpenStreetMap failures with error message
⚠ Have you searched for similar, already existing issues?
Yes, only find similar ones, but nothing with this error message.

**Describe the issue**
Can't login into OpenStreetMap. I got the error message "Web browser is not available"

**Steps to reproduce**
1. Open Organic Maps app (needs no linked OpenStreetMap account yet)
2. Open menu
3. Click on "Settings"
4. Click on "OpenStreetMap profile"
5. Click on "Login to OpenStreetMap"

**Expected behaviour**
A login frame opens and the login with correct credentials works fine.

**Actual behaviour**
An error message appears: "Web browser is not available"

**Screenshots**
Image

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2025.05.20-5-Google
 - Device Model: Samsung Galaxy S20 Ultra 5G

**Additional context**
Needs an app with no linked OpenStreetMap account yet.

### LINKED ISSUE #10741: OSM web browser oauth2 login fails with "Web browser unavailable" error
Two users have reported this bug. @strump do you have any ideas?

 > I'm reaching out, as I have noticed a bug on the Organic Maps Android app (2025.05.20-5-Google).
 > 
 > Under settings > OpenStreetMap profile, I am not able to click the "Sign in to OpenStreetMap" blue button to link my OSM profile, as a contributor.
 > Android system displays "Web browser unavailable". The button "Sign up to OSM" though, works.
 > 
 >

### PR DESCRIPTION
**Pull request by strump**
Fixes #10741
Fixes #10689

I couldn't reproduce the issue. So I don't know why OM can't open browser. Maybe some permissions problem. Changed behaviour: if browser coulnd't be found then we fallback to login + password UI (no browser required).

## Update 2025-07-02

Unified `Utils.openUri` and `Utils.openUrl` functions.
Rebased on `master`.

## Update 2025-07-09

Replaced try-catch with if-else block for browser availability check.

### CODE REVIEW

**Comment by biodranik** [comment]
Still waiting for a user's confirmation.

**Comment by biodranik** [comment]
A user still doesn't see the login/password fields with this fix and still gets the same error with a browser login:
grafik

File: android/app/src/main/java/app/organicmaps/util/Utils.java [hunk 1]
```diff
@@ -226,6 +226,19 @@ public static void openAppInMarket(Activity activity, String url)
     }
   }
 
+  /*
+   * Check if WebBrowser intent could be opened.
+   */
+  public static boolean isBrowserAvailable(Context context)
+  {
+    final Intent intent = new Intent(Intent.ACTION_VIEW);
+    intent.setData(Uri.parse("https://osm.org"));
```
Comment (biodranik) [inline android/app/src/main/java/app/organicmaps/util/Utils.java:190]: Could it be that `Uri.parse(OsmOAuth.nativeGetOAuth2Url()` behaves differently compared to `Uri.parse("https://osm.org")`? @strump can you please modify this function to specifically check for OSM auth, so we can test it with a user?

**Comment by zloidemon** [comment]
[Alexander Borsuk](https://github.com/biodranik) To improve testability and maintainability, could we refactor the OAuth logic into a separate library with its own HTTP client and dedicated tests?

**Comment by strump** [comment]
@biodranik I see that `Utils.openUri()` and `Utils.openUrl()` do the same but in a different way:

* `openUrl()` — try + catch
* `openUri()` — if (intent.resolveActivity(..) != null) else Toast.makeText(...)

I made a change: unified those two methods. Now both methods trigger web browser with try+catch.

File: android/app/src/main/java/app/organicmaps/util/Utils.java [hunk 2]
```diff
@@ -221,28 +248,6 @@ public static void openUrl(@NonNull Context context, @Nullable String url)
...
   }
 
-  /**
-   * Attempts to open a URI in another app via the system app chooser.
-   * @param context the app context
-   * @param uri the URI to open.
-   * @param failMessage string id: message to show in a toast when the system can't find an app to open with.
-   * @param action (optional) the Intent action to use. If none is provided, defaults to Intent.ACTION_VIEW.
-   */
-  public static void openUri(@NonNull Context context, @NonNull Uri uri, Integer failMessage, @NonNull String... action)
```
Comment (strump) [inline android/app/src/main/java/app/organicmaps/util/Utils.java:231]: Optional argument `action` is never used. So I removed it.

**Review by biodranik — APPROVED** [review]
Thanks, one user confirmed that it helped.
